### ISSUE TITLE
UIconf's still broken on install

### ISSUE THREAD

**Issue by DBezemer** [kaltura/platform-install-packages#124]
The 4 default bottom uiconf files are still missing on a new install.
the url:
```
/p/101/sp/10100/embedIframeJs/uiconf_id/11601109/partner_id/101?autoembed=true&entry_id=0_tz5t3va3&playerId=kaltura_player_1400006778&cache_st=1400006778&width=460&height=290&flashvars[streamerType]=auto&flashvars[ks]=
```
Gives the error An error occurred when trying to retrieve uiConfFile

The files for 11601109 does not exist on disk either, so my suspicion is that there is something wrong in the order of the XML file generation

**Comment by comzis** [comment]
@ robp2175   I had uiconf error as well with the new install , fixed by running 
chmod -R 777 /opt/kaltura/app/cache .  I guess Jess should advise if this is in fact related

cheers

**Comment by kaltura-hooks** [comment]
Hi @DBezemer,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please
ensure that your issue includes the following (please comment with more info if you have not included all this info in
your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
	# rpm -qa "kaltura*"
	For deb based systems:
	# dpkg -l "kaltura-*"
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

**Comment by DBezemer** [comment]
UIconfs are now added to the base packages, closing this issue.
