### ISSUE TITLE
The requested URL returned error: 504

### ISSUE THREAD

**Issue by corematter** [kaltura/platform-install-packages#129]
Trying to install Kaltura. Failed to download rpm.
rpm -ihv http://installrepo.kaltura.org/releases/kaltura-release.noarch.rpm
Retrieving http://installrepo.kaltura.org/releases/kaltura-release.noarch.rpm
curl: (22) The requested URL returned error: 504
error: skipping http://installrepo.kaltura.org/releases/kaltura-release.noarch.rpm - transfer failed

Browsing http://installrepo.kaltura.org produces the following error:

An error occurred while processing your request.
Reference #97.bfa9f33f.1400123971.183a9ecd

**Comment by tomoya-saito** [comment]
Now, this issue occurs again.
