### ISSUE TITLE
can't preview & embed rtmp streaming - media not found

### ISSUE THREAD

**Issue by noamtahan** [kaltura/platform-install-packages#140]
Hi,
After install 9.16 on centos 6.5 the preview & embed Delivery Types: 

* Kaltura Auto
* HTTP Progressive Download

Working great but,

* HTTP Streaming (Akamai)
* HTTP Streaming (HDS)
* RTMP Streaming
* Secure Transport (RTMPE)

Not working.
I installed red5 and ran 
```
/opt/kaltura/bin/kaltura-red5-config.sh
```
all the symbolic links was created but why the red5 Delivery Types :5080:
* RTMP Streaming
* Secure Transport (RTMPE)

not working?
the massage is " media not found"?
Also nothing on kaltlog?
When I try the paths
```
http://vod.kal.loc:5080/oflaDemo/
http://vod.kal.loc:5080/demos/ofla_demo.html
```
everything work fine? (RTMP & RTMPT).

**Comment by renich** [comment]
The same happens to me while using Amazon's S3 and Cloudfront.

HTTP streaming works fine. RTMP doesn't. Strange thing, though. If I use ffmpeg to check out a file in /kaltura/file.mp4, RTMP works. If I try /kaltura/content/file.mp4, it fails.

I repeat, I am using 2 Cloudfront distributions: HTTP and RMTP. The former works fine while the later works only on /kaltura and not on /kaltura/content

My settings on RTMP

Delivery profile Type: RTMP
Streamer Type: RTMP
Supported Media Protocols: rtmp,rtmpe,rtmpt,rtmpte
Delivery profile URL: rtmp://s2xxxxxxxxxxx.cloudfront.net/cfx/st
Prefix: /kaltura

Followed this guide: https://github.com/kaltura/platform-install-packages/issues/61#issuecomment-38462301

**Comment by jessp01** [comment]
Closing but if you still have an issue, due let me know.

**Comment by josephwu2010** [comment]
I  can not   surf  the http://localhost.localdomain:5080  ,  or http://192.168.0.11:5080   in my network .    so  can not  config  red5 .   
 

ÔÚ 2015-03-11 16:55:44£¬"Jess Portnoy" <notifications@github.com> Ð´µÀ£º


Closing but if you still have an issue, due let me know.

¡ª

**Comment by eemirtekin** [comment]
iptables -F
service iptables stop
chkconfig iptables off

**Comment by renich** [comment]
@josephwu2010 no, no, no! Don't follow @eemirtekin! That turns off your firewall. That kind of advice is nocive and should never be followed.

Please, read https://github.com/kaltura/platform-install-packages/blob/master/doc/kaltura-required-ports.md and open those ports only.

@eemirtekin dude, don't ever tell people to turn off their firewall. Bad enought it is with SELinux off as well.

**Comment by kinglok** [comment]
Hi all,

I would like to report the issue still remain unsolved in 10.6 with the following error:

2015-03-14 19:21:03 [88341010] [KalturaClientBase->doCurl] NOTICE: curl: http://kaltura.plklsp.edu.hk:80/api_v3/index.php?service=system&action=ping&apiVersion=3.1.6&format=3&clientTag=batch%3A+kaltura.plklsp.edu.hk+KScheduleHelper+index%3A+0+sessionId%3A+88341010&ignoreNull=1&partnerId=-1&ks=ZmQ5OTE3OWRkOTQ2ZDI4MTc5YzhkMDEyZGY3ZGZkYzljZTFhZGI3MHwtMTs7MTQyODkyNDA2MzsyOzE0MjYzMzIwNjMuMzI3MjtiYXRjaFVzZXI7ZGlzYWJsZWVudGl0bGVtZW50Oy0xOw%3D%3D&kalsig=fb4ef3479646b73ddfb411208d34040d
2015-03-14 19:21:03 [88341010] [KScheduleHelper->run] ERR: exception 'Exception' with message 'System is not yet ready - ping failed' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:
#0 /opt/kaltura/app/batch/batches/KScheduleHelper.class.php(44): KalturaLog::err('System is not y...')
--
==> /opt/kaltura/log/batch/validatelivemediaservers-0-2015-03-14.err.log <==
PHP Fatal error:  Uncaught exception 'KalturaClientException' with message 'couldn't connect to host' in /opt/kaltura/app/batch/client/KalturaClientBase.php:357
Stack trace:
#0 /opt/kaltura/app/batch/client/KalturaClient.php(4172): KalturaClientBase->doQueue()
--
2015-03-14 19:21:26 [0.000819] [123.202.8.19] [1594863143] [PS2] [KalturaStatement->execute] DEBUG: Sql took - 0.00060296058654785 seconds
2015-03-14 19:21:26 [0.000359] [123.202.8.19] [1594863143] [PS2] [DeliveryProfilePeer::getDeliveryByPartner] ERR: exception 'Exception' with message 'Delivery ID can't be determined for partnerId [101] streamer type [rtmp] and media protocol [rtmp]' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:
#0 /opt/kaltura/app/alpha/lib/model/DeliveryProfilePeer.php(217): KalturaLog::err('Delivery ID can...')
--
#19 {main}
2015-03-14 19:21:26 [0.000433] [123.202.8.19] [1594863143] [PS2] [KExternalErrors::dieError] ERR: exception 'Exception' with message 'exiting on error 25 - wrong query attributes, This format is unsupported' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/KExternalErrors.class.php(117): KalturaLog::err('exiting on erro…')

**Comment by jessp01** [comment]
Hello,

There are several issues here:
2015-03-14 19:21:03 [88341010] [KScheduleHelper->run] ERR: exception 'Exception' with message 'System is not yet ready - ping failed' in /opt/kaltura/app/infra/log/KalturaLog.php:82 Stack trace:

Means batch cannot make HTTP request to service URL.
Check the /opt/kaltura/app/configurations/batch/batch.ini and make sure the serviceUrl contains a value that:
curl $SERVICE_URL_VAL -I -v

returns HTTP 200 for.

Second issue is cause you must create an RTMP delivery profile.

Since this is not a general bug, feel free to open a discussion at forum.kaltura.org if you have additional issues.

Thanks,

**Comment by renich** [comment]
@jessp01 about the curl line you posted. I hapen to have a LoadBalancing IP; provided by OVH. That curl command would return a 302. If you add -L, it will return 200. Will the batch server support redirects?

**Comment by jessp01** [comment]
Yes, redirects are not a problem. So long as the batch is able to make the 
request. You can look at the log to see the request it is making but 
basically if http://$HOSTNAM/api_v3 works you should be ok.

May the source be with you,

Jess Portnoy

**Comment by noamtahan** [comment]
Hi all,
Has anyone solved this issue of streaming broadcast integration with the red5 server?
I think we need to open this issue again so kaltura can support rtmp streaming.
What do you think?

**Comment by kinglok** [comment]
Still haven't find a way to make rtmp working...so disappointed.

I think it is great if someone would contribute the community by giving detailed how-to to achieving that.

Kinglok, Fong

**Comment by eemirtekin** [comment]
Hi All
I agree with you

**Comment by abhaygarg12493** [comment]
Yeah , we also have the same issue . Open this issue

**Comment by noamtahan** [comment]
Hi @jessp01 , 
We all want helping solve that issue,
Fisrst, I think that it is nessaccery to reopen this issue or open a new issue,
Second, like @kinglok said it will be great if someone would contribute the community by giving detailed how-to to achieving that.
@eemirtekin , @abhaygarg12493, Tjanks for your reply, hopefully, we will find solusion for this issue.
Thanks all,
