### ISSUE TITLE
Enabling Services

### ISSUE THREAD

**Issue by mortenblue** [kaltura/platform-install-packages#206]
Under Batch Process Control => Setup there are several services listed. How can I change their status from Disabled to Enabled and visa versa? I saw some several screenshots where there were dropdown menu's which would allow me to do this but after the 4th clean installation, I do not have these dropdowns.

**Comment by kjrose** [comment]
I've done this, but I have a server that has over 500 videos that need to be transferred. How do you trigger the export of existing video files?
