### ISSUE TITLE
SSL fetching issue from zzzkaltura.ssl.conf

### ISSUE THREAD

**Issue by blackyboy** [kaltura/platform-install-packages#264]
Hi @jessp01 @KalturaCommunity  back in every kaltura versions while installation time and prompting for SSL we give the SSL location as follows 

```
SSLCertificateFile /etc/ssl/certs/STAR_mydomain_com.crt
SSLCertificateKeyFile /etc/pki/tls/private/mydomain.key
SSLCertificateChainFile /etc/ssl/STAR_mydomain_com-bundle.crt
```
And it used to work perfect till the version "9.18.0".

But now in current version "Community Edition Kaltura Server 9.19.5" while installation time if we use the same method there is no error. But after that While accessing admin console and try to login  the https://mydomain.com/admin_console/ we get API error. And did a check for my SSL using ssl shopper tool we found that the certificate it using is the default one from Apache. 

After debugging found that it's fetching certificate from 

```
SSLCertificateFile /etc/pki/tls/certs/localhost.crt
SSLCertificateKeyFile /etc/pki/tls/private/localhost.key
```
which have default in /etc/httpd/conf.d/ssl.conf. It's not fetching my SSL certs from zzzkaltura.ssl.conf vhost.

I have fixed it by moving cert-files from 

```
mv -v /etc/ssl/certs/STAR_mydomain_com.crt /etc/pki/tls/certs/localhost.crt
mv -v /etc/pki/tls/private/mydomain.key /etc/pki/tls/private/localhost.key
```
Now My Kaltura working fine. Will this get fix while the installation time in future?.

Thank you.

**Comment by himbeere** [comment]
Hello.

I have the exact same issue. Kaltura 10.1. Obviousely there is something wrong with deployed apache config.

**Comment by jessp01** [comment]
Hello,

I won't say there is a problem with the Apache config. The problem is that Apache takes the first cert it sees and that when install mod_ssl it automatically puts in /etc/httpd/conf.d/ssl.conf with a self signed cert.
It would be incorrect for the Kaltura config to move this file aside since it does not belong to us so the thing to do is for you to edit the ssl.conf file and input the desired cert and then restart.

**Comment by himbeere** [comment]
Hello.

Yeah. But maybe you could add something to the troubleshooting section. It took me a while to get the server running because of this.

cheers

**Comment by jessp01** [comment]
Hi @himbeere,

You are more than welcome to submit a pull request to the guide and I'll be happy to merge it.

Thanks,
