### ISSUE TITLE
Kaltura admin console error code: API:-1

### ISSUE THREAD

**Issue by ilgatto** [kaltura/platform-install-packages#286]
Hi I noticed kaltura have some instable behaviour. 
My issue now is cannot login in admin_console due to an "Error code: API -1" instead kmc works fine.

"An error occurred
(error code: API:-1)"

i paste kaltlog output in succession post.

**Comment by sincerbex** [comment]
hi, i have installed kaltura on ubuntu 16.04 server. the installation was successful but I am unable to enter the admin. blank page with An error occurred (error code: API: -1). I installed kaltura with ssl. what can I check to find the problem? thanks for the support. best regards
