### ISSUE TITLE
New Install Failing Uncaught exception 'Zend_Config_Exception' with message 'parse_ini_file(/opt/kaltura/web/flash/kmc/v5.37.27/config.ini)

### ISSUE THREAD

**Issue by robp2175** [kaltura/platform-install-packages#293]
I am trying to perform a brand new install and it fails everytime. This is the error it seems to be failing on
==> deploy_v2.log <==
PHP Fatal error:  Uncaught exception 'Zend_Config_Exception' with message 'parse_ini_file(/opt/kaltura/web/flash/kmc/v5.37.27/config.ini): failed to open stream: No such file or directory' in /opt/kaltura/app/vendor/ZendFramework/library/Zend/Config/Ini.php:184
Stack trace:
#0 /opt/kaltura/app/vendor/ZendFramework/library/Zend/Config/Ini.php(125): Zend_Config_Ini->_loadIniFile('/opt/kaltura/we...')
#1 /opt/kaltura/app/deployment/uiconf/deploy_v2.php(302): Zend_Config_Ini->__construct('/opt/kaltura/we...')
#2 /opt/kaltura/app/deployment/uiconf/deploy_v2.php(33): uiConfDeployment::init('/opt/kaltura/we...')
#3 {main}

  thrown in /opt/kaltura/app/vendor/ZendFramework/library/Zend/Config/Ini.php on line 184

This directory exists /opt/kaltura/web/flash/kmc/v5.37.30, but not v5.37.27

**Comment by nyok92** [comment]
Hello, it seems that i've got the same problem : 

**Here is my deploy_v2.log:**

PHP Fatal error:  Uncaught exception 'Zend_Config_Exception' with message 'parse_ini_file(/opt/kaltura/web/flash/kmc/v5.43.13/config.ini): failed to open stream: No such file or directory' in /opt/kaltura/app/vendor/ZendFramework/library/Zend/Config/Ini.php:184
Stack trace:
#0 /opt/kaltura/app/vendor/ZendFramework/library/Zend/Config/Ini.php(125): Zend_Config_Ini->_loadIniFile('/opt/kaltura/we...')
#1 /opt/kaltura/app/deployment/uiconf/deploy_v2.php(301): Zend_Config_Ini->__construct('/opt/kaltura/we...')
#2 /opt/kaltura/app/deployment/uiconf/deploy_v2.php(33): uiConfDeployment::init('/opt/kaltura/we...')
#3 {main}
  thrown in /opt/kaltura/app/vendor/ZendFramework/library/Zend/Config/Ini.php on line 184


**Here is my /etc/yum.repos.d/kaltura.repo:**

# URL: http://kaltura.org/
[Kaltura]
name = Kaltura Server
baseurl = http://installrepo.origin.kaltura.org/releases/latest/$releasever/RPMS/$basearch/
gpgkey = http://installrepo.origin.kaltura.org/releases/RPM-GPG-KEY-kaltura-curr
gpgcheck = 1
enabled = 1

[Kaltura-noarch]
name = Kaltura Server arch independent
baseurl = http://installrepo.origin.kaltura.org/releases/latest/$releasever/RPMS/noarch
gpgkey = http://installrepo.origin.kaltura.org/releases/RPM-GPG-KEY-kaltura-curr
gpgcheck = 1
enabled = 1
