### ISSUE TITLE
Default players dont work (malformed XML?)

### ISSUE THREAD

**Issue by DBezemer** [kaltura/platform-install-packages#31]
From the default available players the following don't work:
- KDP3 Light
- Player with captions (String could not be parsed as XML error)
- Hovering controls player (String could not be parsed as XML error)
- Widescreen player (String could not be parsed as XML error)
- Multiple vertical playlist (String could not be parsed as XML error)
- Player with no share button (String could not be parsed as XML error)

All these players yield the following error:

```
[Tue Feb 11 21:42:15 2014] [error] [client 192.168.1.106] PHP Warning:  SimpleXMLElement::__construct(): Entity: line 1: parser error : Start tag expected, '<' not found in /opt/kaltura/web/html5/html5lib/v2.1.1/modules/KalturaSupport/UiConfResult.php on line 231
[Tue Feb 11 21:42:15 2014] [error] [client 192.168.1.106] PHP Warning:  SimpleXMLElement::__construct(): "" in /opt/kaltura/web/html5/html5lib/v2.1.1/modules/KalturaSupport/UiConfResult.php on line 231
[Tue Feb 11 21:42:15 2014] [error] [client 192.168.1.106] PHP Warning:  SimpleXMLElement::__construct(): ^ in /opt/kaltura/web/html5/html5lib/v2.1.1/modules/KalturaSupport/UiConfResult.php on line 231
```

**Comment by harshadyeola** [comment]
@jessp01 @DBezemer 
How to fix above issue. i am getting default players blank.

**Comment by KalturaCommunity** [comment]
Hello,

Which player is blank? easiest way would be to simply create a new player 
in the universal studio tab in KMC and use it.

May the source be with you,

Jess Portnoy

**Comment by harshadyeola** [comment]
Below is the list of players that are blank
```
Player with no share button
Player with captions
Multiple vertical playlist
Hovering controllers player
Widescreen player
```
While custom player is working fine.

**Comment by KalturaCommunity** [comment]
My guess would be that if you look for the ui_conf ID for this player in 
the DB:
mysql> select conf_file_path from ui_conf where id=$ID
and then look at the file system under:
/opt/kaltura/web/$conf_file_path, you will discover the file is missing.. 
Other than placing a valid UI conf file in this location, there is not 
much you can do.. however, seeing how you're able to create a new player, 
you can simply use it. No real importance to the default ones.

May the source be with you,

Jess Portnoy

**Comment by harshadyeola** [comment]
@jessp01

I am not able to figure out the solution for this. Here is the screen shot for error.
![selection_056](https://cloud.githubusercontent.com/assets/7354660/8976806/c6c5f83a-36af-11e5-96a7-83a7566097b4.jpg)

**Comment by jessp01** [comment]
Hello,

When do you get this screen? when creating a new player? when trying to edit it or..?
Thanks,
