### ISSUE TITLE
Analytics graphs not showing anymore

### ISSUE THREAD

**Issue by comzis** [kaltura/platform-install-packages#313]
perform_referential_integrity.kjb  is failing when executed through cron script below

/opt/kaltura/dwh/etlsource/execute/etl_perform_retention_policy.sh -p /opt/kaltura/dwh -k /opt/kaltura/pentaho/pdi/kitchen.sh

the error log showing:

ERROR 02-01 08:03:42,767 - Move old partitions to archive - An error occurred executing this job entry : 
Couldn't execute SQL: CALL move_innodb_to_archive()

ERROR 02-01 07:59:19,418 - Kitchen - Finished with errors
INFO  02-01 07:59:19,418 - Kitchen - Start=2015/01/02 07:59:17.248, Stop=2015/01/02 07:59:19.418
INFO  02-01 07:59:19,419 - Kitchen - Processing ended after 2 seconds.
INFO  02-01 08:03:06,869 - Kitchen - Start of run.
INFO  02-01 08:03:07,180 - perform retention policy - Start of job execution
INFO  02-01 08:03:08,082 - perform retention policy - Starting entry [Seize retention lock]
INFO  02-01 08:03:08,085 - Seize retention lock - Loading transformation from XML file [/opt/kaltura/dwh/etlsource//common/seize_lock_by_name.ktr]
INFO  02-01 08:03:08,381 - seize_lock_by_name - Dispatching started for transformation [seize_lock_by_name]
INFO  02-01 08:03:08,563 - get_retention_lock_name - Dispatching started for transformation [get_retention_lock_name]
INFO  02-01 08:03:08,601 - Generate Row - Finished processing (I=0, O=0, R=0, W=1, U=0, E=0)
INFO  02-01 08:03:08,605 - Mapping input specification - Finished processing (I=0, O=0, R=1, W=1, U=0, E=0)
INFO  02-01 08:03:08,613 - Set lock name = retention_lock - Finished processing (I=0, O=0, R=1, W=1, U=0, E=0)
INFO  02-01 08:03:08,616 - Mapping output specification - Finished processing (I=0, O=0, R=1, W=1, U=0, E=0)
INFO  02-01 08:03:08,618 - Get lock name - Finished processing (I=0, O=0, R=1, W=1, U=0, E=0)
INFO  02-01 08:03:08,622 - Create lock states - Finished processing (I=0, O=0, R=1, W=1, U=0, E=0)
INFO  02-01 08:03:08,644 - Register lock - Finished processing (I=1, O=0, R=1, W=1, U=0, E=0)
INFO  02-01 08:03:08,659 - Get free lock - Finished processing (I=1, O=0, R=1, W=1, U=0, E=0)
INFO  02-01 08:03:08,660 - Lock is free - Finished processing (I=0, O=0, R=1, W=1, U=0, E=0)
INFO  02-01 08:03:08,662 - Get Now - Finished processing (I=0, O=0, R=1, W=1, U=0, E=0)
INFO  02-01 08:03:08,667 - Seize lock - Finished processing (I=1, O=0, R=1, W=1, U=1, E=0)
INFO  02-01 08:03:08,675 - perform retention policy - Starting entry [Move old partitions to archive]
ERROR 02-01 08:03:42,767 - Move old partitions to archive - An error occurred executing this job entry : 
Couldn't execute SQL: CALL move_innodb_to_archive()

Cannot remove all partitions, use DROP TABLE instead

INFO  02-01 08:03:42,769 - perform retention policy - Finished job entry [Move old partitions to archive] (result=[false])
INFO  02-01 08:03:42,769 - perform retention policy - Finished job entry [Seize retention lock] (result=[false])
INFO  02-01 08:03:42,769 - perform retention policy - Job execution finished
INFO  02-01 08:03:43,033 - Kitchen - Finished!
ERROR 02-01 08:03:43,033 - Kitchen - Finished with errors
INFO  02-01 08:03:43,034 - Kitchen - Start=2015/01/02 08:03:06.871, Stop=2015/01/02 08:03:43.033
INFO  02-01 08:03:43,034 - Kitchen - Processing ended after 36 seconds.

**Comment by comzis** [comment]
correction , it's  perform_retention_policy.kjb

**Comment by jessp01** [comment]
Hi,

Please try calling the kalturadw.add_partitions() stored procedure.
Should fix it.

Thanks,

**Comment by comzis** [comment]
Hi Jess,

Thank you for you help. Worked like a charm:)

Regards

**Comment by jessp01** [comment]
Great, happy to:)

May the source be with you,

Jess Portnoy
