### ISSUE TITLE
Open Ports Doc

### ISSUE THREAD

**Issue by dbinoj** [kaltura/platform-install-packages#318]
https://github.com/kaltura/platform-install-packages/blob/master/doc/kaltura-required-ports.md

Why do I need to open MySQL's, LDAP's, etc's ports on Kaltura's server? These are not services that must be accessible outside of Kaltura.

**Comment by jessp01** [comment]
Hello,

As far as LDAP goes, this is only relevant if you install MediaSpace 
[which is not part of the open source core platform but rather an 
application on top of it].
As far as MySQL, if this is a standalone machine, it only needs to listen 
on 127.0.0.1 [or use a UNIX socket] but if it is a cluster, then yes, it 
must be accessible from multiple nodes.

For additional questions, please post at forum.kaltura.org.

Thanks,

May the source be with you,

Jess Portnoy
