### ISSUE TITLE
content report doesn't work on kaltura ce

### ISSUE THREAD

**Issue by mchakroun** [kaltura/platform-install-packages#319]
tail /opt/kaltura/log/batch/dbcleanup-0-2015-01-07.err.log
PHP Fatal error:  Uncaught exception 'KalturaClientException' with message 'couldn't connect to host' in /home/kaltura/app/batch/client/KalturaClientBase.php:357
Stack trace:
#0 /home/kaltura/app/batch/client/KalturaClient.php(1309): KalturaClientBase->doQueue()
#1 /home/kaltura/app/batch/batches/Cleanup/KAsyncDbCleanup.class.php(30): KalturaBatchService->cleanExclusiveJobs()
#2 /home/kaltura/app/batch/batches/Cleanup/KAsyncDbCleanupExe.php(11): KAsyncDbCleanup->run()
#3 {main}
  thrown in /home/kaltura/app/batch/client/KalturaClientBase.php on line 357

if someone could help me figure out what it could be ..

**Comment by jessp01** [comment]
Hello,

The errors pasted above do not have a direct connection with content reporting.
First, can you run kaltura-sanity.sh and see if anything fails?
Second, check for the pattern 'ERROR' under /opt/kaltura/dwh/logs

Thanks,

**Comment by mchakroun** [comment]
Hello, thank you for your answer, I ran a sanity test and here are the results:
[DWH cycle] [FAILED, RC: 255] - [5.653577306]
[Upload content kaltura_logo_animated_green.flv] [PASSED, RC: 0] - [.482504198]
[Upload bulk using CSV] [PASSED, RC: 0] - [.428732573]
[Upload bulk using XML] [PASSED, RC: 0] - [.226469715]
[Create player] [PASSED, RC: 0] - [.114639137]
[Generate thumb] [FAILED, RC: 255] - [.072746050]
[Delete parnter] [PASSED, RC: 0] - [.236461096]
[Red5 file upload] [PASSED, RC: 0] - [2.993103654]

**Comment by mchakroun** [comment]
grep  'ERROR' /opt/kaltura/dwh/logs/etl_hourly-20150108-*
/opt/kaltura/dwh/logs/etl_hourly-20150108-04.log:ERROR 08-01 04:00:07,242 - process_events - org.pentaho.di.core.exception.KettleException:
/opt/kaltura/dwh/logs/etl_hourly-20150108-04.log:ERROR 08-01 04:00:07,244 - file_processing_job - An error occurred executing this job entry :
/opt/kaltura/dwh/logs/etl_hourly-20150108-04.log:ERROR 08-01 04:00:07,244 - file_processing_job - org.pentaho.di.core.exception.KettleException:

**Comment by jessp01** [comment]
Please view the file and copy a larger chunk of the output around the error.

Thanks,

**Comment by mchakroun** [comment]
INFO  11-01 04:00:07,944 - Table input - Finished processing (I=1, O=0, R=1, W=1, U=0, E=0)
INFO  11-01 04:00:07,946 - Write to log - Finished processing (I=0, O=0, R=1, W=1, U=0, E=0)
INFO  11-01 04:00:07,947 - Copy rows to result - Finished processing (I=0, O=0, R=1, W=1, U=0, E=0)
INFO  11-01 04:00:07,949 - Process single cycle - Starting entry [file_processing_job]
INFO  11-01 04:00:07,957 - process_events - Starting entry [Process events]
INFO  11-01 04:00:07,957 - Process events - Loading transformation from XML file [/opt/kaltura/dwh/etlsource//events/process/process_file.ktr]
ERROR 11-01 04:00:07,993 - process_events - org.pentaho.di.core.exception.KettleException:
Unexpected error during transformation metadata load

Error reading object from XML file

Unable to load step info from XML step nodeorg.pentaho.di.core.exception.KettleStepLoaderException:
Unable to load class for step/plugin with id [ConcurrentSafeCombinationLookup]. Check if the plugin is available in the plugins subdirectory of the Kettle distribution.


Unable to load class for step/plugin with id [ConcurrentSafeCombinationLookup]. Check if the plugin is available in the plugins subdirectory of the Kettle distribution.




        at org.pentaho.di.job.entries.trans.JobEntryTrans.getTransMeta(JobEntryTrans.java:1195)
        at org.pentaho.di.job.entries.trans.JobEntryTrans.execute(JobEntryTrans.java:611)
        at org.pentaho.di.job.Job.execute(Job.java:503)
        at org.pentaho.di.job.Job.execute(Job.java:642)
        at org.pentaho.di.job.Job.execute(Job.java:420)
        at org.pentaho.di.job.entries.job.JobEntryJobRunner.run(JobEntryJobRunner.java:63)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.pentaho.di.core.exception.KettleXMLException:
Error reading object from XML file

Unable to load step info from XML step nodeorg.pentaho.di.core.exception.KettleStepLoaderException:
Unable to load class for step/plugin with id [ConcurrentSafeCombinationLookup]. Check if the plugin is available in the plugins subdirectory of the Kettle distribution.


Unable to load class for step/plugin with id [ConcurrentSafeCombinationLookup]. Check if the plugin is available in the plugins subdirectory of the Kettle distribution.



        at org.pentaho.di.trans.TransMeta.loadXML(TransMeta.java:2869)
        at org.pentaho.di.trans.TransMeta.<init>(TransMeta.java:2365)
        at org.pentaho.di.trans.TransMeta.<init>(TransMeta.java:2326)
        at org.pentaho.di.job.entries.trans.JobEntryTrans.getTransMeta(JobEntryTrans.java:1151)
        ... 6 more
Caused by: org.pentaho.di.core.exception.KettleXMLException:
Unable to load step info from XML step nodeorg.pentaho.di.core.exception.KettleStepLoaderException:
Unable to load class for step/plugin with id [ConcurrentSafeCombinationLookup]. Check if the plugin is available in the plugins subdirectory of the Kettle distribution.


Unable to load class for step/plugin with id [ConcurrentSafeCombinationLookup]. Check if the plugin is available in the plugins subdirectory of the Kettle distribution.


        at org.pentaho.di.trans.step.StepMeta.<init>(StepMeta.java:297)
        at org.pentaho.di.trans.TransMeta.loadXML(TransMeta.java:2521)
        ... 9 more

Thanks

**Comment by jessp01** [comment]
Has the installation gone well or did it fail at some point?
I would recommend trying to reinstall the kaltura-dwh package with yum 
reinstall

If this does not work then perhaps follow this procedure:
0. Backup all Kaltura DBs using:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.2.0/doc/rpm-cluster-deployment-instructions.md#backup-and-restore-practices

1. Drop the current DWH DBs:
PASSW=$MYSQL_SUPER_USER_PASSWD
for i in `mysql -N -p$PASSWD kalturadw -e "show tables"`;do mysql 
-p$PASSWD kalturadw -e "drop table $i";done
for i in `mysql -N -p$PASSWD kalturadw_ds -e "show tables"`;do mysql 
-p$PASSWD kalturadw_ds -e "drop table $i";done
for i in `mysql -N -p$PASSWD kalturalog -e "show tables"`;do mysql 
-p$PASSWD kalturalog -e "drop table $i";done
for i in `mysql -p$PASSWD -e "Show procedure status" |grep kalturadw|awk 
-F " " '{print $2}'`;do mysql kalturadw -p$PASSWD -e "drop procedure 
$i;";done
for i in `mysql -p$PASSWD -e "Show procedure status" |grep 
kalturadw_ds|awk -F " " '{print $2}'`;do mysql kalturadw_ds -p$PASSWD -e 
"drop procedure $i;";done

Then:
# yum reinstall kaltura-dwh
# kaltura-dwh-config.sh

Thanks,

May the source be with you,

Jess Portnoy

**Comment by mchakroun** [comment]
thank you for your fast response, the install went well and stats used to be shown. It happened since an update I can't remember which one. I found these lines of error now, it could give some more info I hope:
#4 {main}
2015-01-11 18:27:24 [0.000503] [xxx.xxx.xxx.xxx] [1561125484] [API] [KalturaFrontController->getExceptionObject] ERR: exception 'KalturaAPIException' with message 'Service "livestats" does not exists' in /home/kaltura/app/api_v3/lib/KalturaServicesMap.php:194
Stack trace:
#0 /home/kaltura/app/api_v3/lib/KalturaDispatcher.php(51): KalturaServicesMap::retrieveServiceActionItem('livestats', 'collect')

**Comment by jessp01** [comment]
Hi,

The error you posted is nothing to worry about and is also unrelated to DWH.
Have you tried following the proc. I specified above? Thanks,

**Comment by mchakroun** [comment]
yes did but nothing new, now I installed on a fresh new server and still can't get analytics working but this time i have no errors in  /opt/kaltura/dwh/logs/ ...

**Comment by KalturaCommunity** [comment]
Hello,

How long have you waited? note that analytics updates at 4 hour intervals.
Thanks,

May the source be with you,

Jess Portnoy

**Comment by mchakroun** [comment]
Thank you for fast response. It's all ok with "Live Reports" but can't find /apps/liveanalytics/v0.17/index.html on my fresh install, do I have to install it manually ?

**Comment by jessp01** [comment]
Hello,

Live reports is not yet fully functional. Please do not attempt to use it at the moment.
BTW, for general questions, as opposed to bug reports, please post at forum.kaltura.org

Thanks,

**Comment by mchakroun** [comment]
thank you for you help and time

**Comment by jessp01** [comment]
Most welcome.

May the source be with you,

Jess Portnoy
