### ISSUE TITLE
Can't get ssl to configure

### ISSUE THREAD

**Issue by verdonv** [kaltura/platform-install-packages#321]
I initially installed 9.x before I had SSL on the server. I have since installed SSL, and cannot find a way to rerun the base config or the front config that will recognize that I have SSL and allow me to configure it.

I have tried re-running /opt/kaltura/bin/kaltura-base-config.sh

I have looked for IS_SSL=N in /etc/kaltura.d/system.ini to remove it. It is not there. I have tried adding IS_SSL=Y to /etc/kaltura.d/system.ini and re-running kaltura-front-config.sh

I have upgraded to 10.2 and this forced a re-run of opt/kaltura/bin/kaltura-base-config.sh

All to no avail. In any case, when I run kaltura-front-config.sh I am presented with "It is recommended that you do work using HTTPs. Would you like to continue anyway?[N/y]". Choosing N exits the script. Choosing yes will run me through the script but with no SSL options.

I'm not sure where to go from here? I've looked at the new kaltura ssl conf file and it is quite a bit different from the one I have on a 6.x install, so I don't want to just copy it. 

Any suggestions?

**Comment by jessp01** [comment]
Hi,

I am not sure why it does not prompt you about SSL, seem to be unable to reproduce it.
Can you edit the kaltura-front-config.sh and put:
unset IS_SSL
Before:
if [ -z "$IS_SSL" ];then

And let me know if that works?

Thanks,

**Comment by verdonv** [comment]
Thanks Jess,

I can’t get at the server until tomorrow, but will let you know. To be sure, there’s absolutely nothing in the base config that could effect this? So no need to run that again?

Best regards,
v

**Comment by KalturaCommunity** [comment]
Hi,

You're welcome naturally.
If you already re-run base-config and inputted https where appropriate 
[mostly when prompted for service url] then its fine, otherwise, yes, do 
run it again.

Thanks,

May the source be with you,

Jess Portnoy

**Comment by verdonv** [comment]
Hi Jess :-)

Well, I re-ran base and front configs, which at first didn't yield the results. I was never asked for crt/key info. Then I saw that 

/etc/kaltura.d/system.ini still had

SERVICE_URL=http://mydomain.ca:80

I tried removing that file and re-running base-config. Then I had to soft link to the newly generated system.ini file and run front-config again. Then, I finally was asked for ssl information, and everything seemed to restart alright.

Unfortunately, I cannot connect to the server over https. I can connect over http, but it leads to the default apache welcome page.

There is nothing being written to /opt/kaltura/log/kaltura_apache_errors_ssl.log or /opt/kaltura/log/kaltura_apache_errors.log

If I look at /etc/httpd/conf.d it contains
-rw-r--r--. 1 root root  237 Dec 17 15:26 php5.conf
-rw-r--r--. 1 root root  990 Dec 19 00:32 php.conf
-rw-r--r--. 1 root root 1707 Jan 12 10:37 phpMyAdmin.conf
-rw-r--r--. 1 root root  392 Oct 16 10:49 README
-rw-r--r--. 1 root root  299 Aug 15 02:57 welcome.conf
lrwxrwxrwx. 1 root root   55 Jan 20 11:35 zzzkaltura.ssl.conf -> /opt/kaltura/app/configurations/apache/kaltura.ssl.conf

Should there also be a sl for zzzkaltura.conf?

I don't know how I managed to bugger things up so much, but I'm sure it's me ;-)

Any suggestions?
verdon

**Comment by jessp01** [comment]
Hello,

Please run:
\# apachectl -t -DDUMP_VHOSTS
And paste the output.
Lets see what vhosts Apache thinks are set
Also:
\# netstant -plntu |grep httpd
To see which ports apache listens on.
Finally, check the main apache log file under /var/log/httpd
See if you see errors there.

**Comment by verdonv** [comment]
> Please run:
> # apachectl -t -DDUMP_VHOSTS

[root@Kmedia conf.d]# apachectl -t -DDUMP_VHOSTS
httpd: Could not reliably determine the server's fully qualified domain name, using Kmedia.nipissingu.ca for ServerName
VirtualHost configuration:
xxx.xxx.xxx.xxx:443     kmedia.nipissingu.ca (/etc/httpd/conf.d/zzzkaltura.ssl.conf:18)
Syntax OK


> And paste the output.
> Lets see what vhosts Apache thinks are set

> Also:
> # netstant -plntu |grep httpd
> To see which ports apache listens on.

[root@Kmedia conf.d]# netstat -plntu |grep httpd
tcp        0      0 :::80                       :::*                        LISTEN      21094/httpd         


Now ^^ this is odd. It was previously working on 443, just not with kaltura.


> Finally, check the main apache log file under /var/log/httpd
> See if you see errors there.

access_log
just the stuff from me hitting the default page

error_log
[Tue Jan 20 11:35:53 2015] [notice] SELinux policy enabled; httpd running as context unconfined_u:system_r:httpd_t:s0
(note: selinux is set to permissive)
[Tue Jan 20 11:35:53 2015] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Tue Jan 20 11:35:53 2015] [notice] Digest: generating secret for digest authentication ...
[Tue Jan 20 11:35:53 2015] [notice] Digest: done
[Tue Jan 20 11:35:54 2015] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.4.36 mod_ssl/2.2.15 OpenSSL/1.0.1e-fips configured -- resuming normal operations
[Wed Jan 21 03:48:02 2015] [notice] SIGHUP received.  Attempting to restart
httpd: Could not reliably determine the server's fully qualified domain name, using Kmedia.nipissingu.ca for ServerName
[Wed Jan 21 03:48:02 2015] [notice] Digest: generating secret for digest authentication ...
[Wed Jan 21 03:48:02 2015] [notice] Digest: done
[Wed Jan 21 03:48:02 2015] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.4.36 mod_ssl/2.2.15 OpenSSL/1.0.1e-fips configured -- resuming normal operations

ssl_request_log and ssl_error_log are both empty

**Comment by jessp01** [comment]
Hi,

Is it possible you removed: /etc/httpd/conf.d/ssl.conf?
This is the default Apache SSL file which also contains:
'Listen 443'
Which is what you are missing.
I would suggest you readd it but alternatively, you can also put Listen 
443 in /opt/kaltura/app/configurations/apache/kaltura.ssl.conf

Thanks,

May the source be with you,

Jess Portnoy

**Comment by verdonv** [comment]
DOH... yes, I did remove that, thinking it might be colliding with kaltura's attempts to configure ssl.

...and just like magic, kaltura is responding on 443 ;-) Now I can properly kick the tires, and then attempt a data/content migration from a version 6.x server.

Jess, than you very much for your patience and persistence in talking me through this! 

I think ultimately, the problem in getting this to reconfigure to ssl after the fact was that /etc/kaltura.d/system.ini sill had a line in it pointing to myhost.ca:80 so no matter how many times I re-ran base or front config, I never got asked the questions to setup my ssl host. To fix that, I blew the link away, re-ran base-config, and then manually re-created the softlink to system.ini in /etc/kaltura.d/

Very best rgds,
verdon

**Comment by jessp01** [comment]
Hi @verdonv,

Happy to hear we're good.
I suggest running
\# kaltura-sanity.sh
to make sure all works properly and, as for migration, take a look at this:
https://github.com/kaltura/platform-install-packages/tree/Jupiter-10.3.0/doc/kaltura-updater

**Comment by DBezemer** [comment]
@jessp01 recommend to run yum reinstall mod_ssl to get the original conf file back :)

**Comment by KalturaCommunity** [comment]
Hi David,

The reason it is better to bring it back from backup is that the spec for 
it has:
%config(noreplace) %{_sysconfdir}/httpd/conf.d/ssl.conf

That means that an update does not replace the current copy and, a user 
may and indeed perhaps did, put additions there:)

In the event the original no longer exists, doing reinstall is good.

May the source be with you,

Jess Portnoy

**Comment by verdonv** [comment]
..some success and some failure in kaltura-sanity.sh I'll post over on the forums about that.
