### ISSUE TITLE
Not clear where to use the answer file

### ISSUE THREAD

**Issue by renich** [kaltura/platform-install-packages#322]
Hello,

I've been trying to follow the cluster installation. But it is not clear to me where should I use the answer file.

I've been using it on every script. Does that hurt?

**Comment by AquileaSFX** [comment]
Hello renich,

you have to install the front first,
and then the ans file generated shoult be used on the other nodes,

for example:
/opt/kaltura/bin/kaltura-batch-config.sh /path/to/ans-generated-by-front.ans

you have to download the ans file and upload it to your nodes
(or other methods)

the idea is that you use the same information for all,

URL SERVICE,
mysql server, same users and passwords.

**Comment by renich** [comment]
Thanks for getting back to me.

It is confusing, then, when you suggest installing the SPHINX server first.
I will use the answer file for all.

Might I suggest correcting the cluster installation howto and mentioning SPHINX after the front?

Thanks.

**Comment by AquileaSFX** [comment]
Hello Again,

you can install Sphinx first, thats OK.
what I usually do is to create a template for my ans file

using this:

https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.3.0/doc/kaltura.template.ans

then I manually fill that file and use that for all my nodes

**Comment by jessp01** [comment]
@renich,

The doc does specify you must install Sphinx first:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.3.0/doc/rpm-cluster-deployment-instructions.md

If you feel something can be better clarified, please submit a pull request.
