### ISSUE TITLE
kaltura error after update 10.2.0

### ISSUE THREAD

**Issue by eemirtekin** [kaltura/platform-install-packages#323]
Hello All;

Categories have been deleted but all entries stands

Following error constantly repeats
2015-01-13 11:06:27 [116375634] [KalturaClientBase->doQueue] NOTICE: execution time for [http://xxxx:80/api_v3/index.php?service=batch&action=getExclusiveJobs]: [0.083565950393677]
2015-01-13 11:06:27 [116375634] [KJobHandlerWorker->run] ERR: exception 'Exception' with message 'The access to service [batch->getExclusiveJobs] is forbidden' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:
#0 /opt/kaltura/app/batch/batches/KJobHandlerWorker.class.php(76): KalturaLog::err('The access to s...')

[root@kaltura ~]# kaltura-sanity.sh
[Space on /] [PASSED, RC: 0] - [.005325286]
[Space on /opt/kaltura/web] [PASSED, RC: 0] - [.005404561]
[Check httpd daemon status] [PASSED, RC: 0] - [.028550502]
Napping 1 seconds to allow the daemon httpd to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon httpd to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon httpd to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon httpd to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon httpd to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon httpd to finish its init after monit restarted it..
[Check httpd daemon is started by Monit] [PASSED, RC: 0] - [7.364050393]
[check daemon httpd init status] [PASSED, RC: 0] - [.006481550]
[Check kaltura-sphinx daemon status] [PASSED, RC: 0] - [.029649226]
Napping 1 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
[Check kaltura-sphinx daemon is started by Monit] [PASSED, RC: 0] - [8.930366432]
[check daemon kaltura-sphinx init status] [PASSED, RC: 0] - [.006238778]
[Check kaltura-batch daemon status] [PASSED, RC: 0] - [.027691585]
Napping 1 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
[Check kaltura-batch daemon is started by Monit] [PASSED, RC: 0] - [8.315788416]
[check daemon kaltura-batch init status] [PASSED, RC: 0] - [.005977809]
[Check kaltura-monit daemon status] [PASSED, RC: 0] - [.028272945]
[check daemon kaltura-monit init status] [PASSED, RC: 0] - [.007267934]
[Check memcached daemon status] [PASSED, RC: 0] - [.028164828]
Napping 1 seconds to allow the daemon memcached to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon memcached to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon memcached to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon memcached to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon memcached to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon memcached to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon memcached to finish its init after monit restarted it..
[Check memcached daemon is started by Monit] [PASSED, RC: 0] - [7.368224281]
[check daemon memcached init status] [PASSED, RC: 0] - [.005759616]
[kaltura-html5lib ver in KMC config.ini] [PASSED, RC: 0] - [.093020294]
[kaltura-kdp3 ver in KDP3 config.ini] [PASSED, RC: 0] - [.054780126]
[kaltura-kmc ver in KMC config.ini] [PASSED, RC: 0] - [.061787878]
[Get KMC SWFs] [PASSED, RC: 0] - [.170083785]
[check_testme_page] [PASSED, RC: 0] - [14.526779263]
[check_kmc_index_page] [PASSED, RC: 0] - [.046657803]
[check_admin_console_index_page] [PASSED, RC: 0] - [.331169792]
[check_studio_index_page] [PASSED, RC: 0] - [.547912616]
[Create Partner] [PASSED, RC: 0] - [1.905237130]
[Local dropfolder creation succeeded] [PASSED, RC: 0] - [10.314183559]
[Create flavor param] [PASSED, RC: 0] - [5.502270957]
[Delete flavor param] [PASSED, RC: 0] - [5.224904343]
[Upload content kaltura_logo_animated_blue.flv] [PASSED, RC: 0] - [.867095168]
Napping 10 seconds to allow entry 0_tf53ecco to digest..
Napping 10 seconds to allow entry 0_tf53ecco to digest..
Napping 10 seconds to allow entry 0_tf53ecco to digest..
Napping 10 seconds to allow entry 0_tf53ecco to digest..
Napping 10 seconds to allow entry 0_tf53ecco to digest..
Napping 10 seconds to allow entry 0_tf53ecco to digest..
Napping 10 seconds to allow entry 0_tf53ecco to digest..
Napping 10 seconds to allow entry 0_tf53ecco to digest..
Napping 10 seconds to allow entry 0_tf53ecco to digest..
[kaltura_logo_animated_blue.flv - 0_tf53ecco status] [FAILED, RC: 1] - [-.537351257]
Napping 30 seconds to allow mail to be sent out..
[Found an email sending entry for mb-xxx@kaltura.com[PID is 107] in /var/log/maillog] [PASSED, RC: 0] - [30.008882460]
Testing analytics, be patient..

Please note: if you are running this test on a clustered ENV, it will fail but this does not mean there is an actual problem.
The tech information as to why is available here:
https://github.com/kaltura/platform-install-packages/issues/106#issuecomment-42837404

[DWH cycle] [FAILED, RC: 255] - [.868509000]
[Upload content kaltura_logo_animated_green.flv] [PASSED, RC: 0] - [5.940846560]
[Upload bulk using CSV] [PASSED, RC: 0] - [.552664928]
[Upload bulk using XML] [PASSED, RC: 0] - [.520894226]
[Create player] [PASSED, RC: 0] - [.408086882]
[Generate thumb] [FAILED, RC: 255] - [5.474411981]
[Delete parnter] [PASSED, RC: 0] - [.319542626]
[Red5 file upload] [SKIPPED as OflaDemo isn't configured]
see: https://github.com/kaltura/platform-install-packages/blob/master/doc/install-kaltura-redhat-based.md#configure-red5-server

Thank you for running Kaltura! To keep Kaltura viable, stable and well tested, please join the community and help by contributing sanity tests that verify overall platform stability: http://bit.ly/kaltura-ci , and by contributing to the project roadmap by solving simple tasks and challenges: http://bit.ly/kaltura-tasks.

**Comment by jessp01** [comment]
Can you please try downloading and running this script?

https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.3.0/RPM/scripts/postinst/kaltura-sphinx-reindex.sh

Let me know if that helped, thanks,

**Comment by jessp01** [comment]
Hi, any update on this one?

**Comment by eemirtekin** [comment]
Hi Jess
Resolved. 
Thanks a lot

**Comment by eemirtekin** [comment]
@jessp01 i by the way kaltura-sanity.sh  
[Space on /] [PASSED, RC: 0] - [.005348494]
[Space on /opt/kaltura/web] [PASSED, RC: 0] - [.004560321]
[Check httpd daemon status] [PASSED, RC: 0] - [.024728906]
Napping 1 seconds to allow the daemon httpd to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon httpd to finish its init after monit restarted it..
[Check httpd daemon is started by Monit] [PASSED, RC: 0] - [3.228810391]
[check daemon httpd init status] [PASSED, RC: 0] - [.005634980]
[Check kaltura-sphinx daemon status] [PASSED, RC: 0] - [.030711695]
Napping 1 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
[Check kaltura-sphinx daemon is started by Monit] [PASSED, RC: 0] - [7.867363943]
[check daemon kaltura-sphinx init status] [PASSED, RC: 0] - [.005716413]
[Check kaltura-batch daemon status] [PASSED, RC: 0] - [.029005440]
Napping 1 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
[Check kaltura-batch daemon is started by Monit] [PASSED, RC: 0] - [8.279268241]
[check daemon kaltura-batch init status] [PASSED, RC: 0] - [.006140092]
[Check kaltura-monit daemon status] [PASSED, RC: 0] - [.030908588]
[check daemon kaltura-monit init status] [PASSED, RC: 0] - [.006215231]
[Check memcached daemon status] [PASSED, RC: 0] - [.025523618]
Napping 1 seconds to allow the daemon memcached to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon memcached to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon memcached to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon memcached to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon memcached to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon memcached to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon memcached to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon memcached to finish its init after monit restarted it..
[Check memcached daemon is started by Monit] [PASSED, RC: 0] - [8.378327412]
[check daemon memcached init status] [PASSED, RC: 0] - [.006376441]
[kaltura-html5lib ver in KMC config.ini] [PASSED, RC: 0] - [.095589391]
[kaltura-kdp3 ver in KDP3 config.ini] [PASSED, RC: 0] - [.055577005]
[kaltura-kmc ver in KMC config.ini] [PASSED, RC: 0] - [.060478299]
[Get KMC SWFs] [PASSED, RC: 0] - [.153442878]
[check_testme_page] [PASSED, RC: 0] - [.159248693]
[check_kmc_index_page] [PASSED, RC: 0] - [.050151857]
[check_admin_console_index_page] [PASSED, RC: 0] - [5.258179188]
[check_studio_index_page] [PASSED, RC: 0] - [.548254537]
[Create Partner] [PASSED, RC: 0] - [1.949001254]
[Local dropfolder creation succeeded] [PASSED, RC: 0] - [.292605504]
[Create flavor param] [PASSED, RC: 0] - [5.507687529]
[Delete flavor param] [PASSED, RC: 0] - [5.241224021]
[Upload content kaltura_logo_animated_blue.flv] [PASSED, RC: 0] - [.783985278]
Napping 10 seconds to allow entry 0_xw7wj35z to digest.. 
Napping 10 seconds to allow entry 0_xw7wj35z to digest.. 
Napping 10 seconds to allow entry 0_xw7wj35z to digest.. 
Napping 10 seconds to allow entry 0_xw7wj35z to digest.. 
[kaltura_logo_animated_blue.flv - 0_xw7wj35z status] [PASSED, RC: 0] - [55.937593476]
[Thumb for 0_xw7wj35z identical to /opt/kaltura/bin/kaltura_logo_animated_blue_1_sec.jpg] [PASSED, RC: 0] - [.756768780]
[Clipping 0_xw7wj35z Succeeded] [PASSED, RC: 0] - [.487531831]
[Trimming 0_xw7wj35z Succeeded] [PASSED, RC: 0] - [5.505652286]
[Mock playback 0_xw7wj35z succeeded] [PASSED, RC: 0] - [5.304008105]
[Entry reconversion of 0_xw7wj35z succeeded] [PASSED, RC: 0] - [.508699400]
Napping 30 seconds to allow mail to be sent out.. 
[Found an email sending entry for mb-kaltura.yasar.edu.tr@kaltura.com[PID is 109] in /var/log/maillog] [PASSED, RC: 0] - [30.008447496]
Testing analytics, be patient..

Please note: if you are running this test on a clustered ENV, it will fail but this does not mean there is an actual problem.
The tech information as to why is available here: 
https://github.com/kaltura/platform-install-packages/issues/106#issuecomment-42837404

[DWH cycle] [FAILED, RC: 255] - [33.700394865]
[Upload content kaltura_logo_animated_green.flv] [PASSED, RC: 0] - [.793585289]
[Upload bulk using CSV] [PASSED, RC: 0] - [10.413582045]
[Upload bulk using XML] [PASSED, RC: 0] - [.446023910]
[Create player] [PASSED, RC: 0] - [5.228733647]
[Generate thumb] [PASSED, RC: 0] - [.312851094]
[Delete partner] [PASSED, RC: 0] - [.524900480]
[Red5 file upload] [PASSED, RC: 0] - [3.042411298]


Thank you for running Kaltura! To keep Kaltura viable, stable and well tested, please join the community and help by contributing sanity tests that ve
