### ISSUE TITLE
How could I move kaltura web to custom directory

### ISSUE THREAD

**Issue by eemirtekin** [kaltura/platform-install-packages#325]
Hello all;
I mount nfs on kaltura single server
nfs directory is /data
how can I move /opt/kaltura/web  directory to /data

Thanks in advance!

**Comment by jessp01** [comment]
Hello,

Easiest way would be to create a symlink from /data to /opt/kaltura/web.
In the future, for general questions, please post on forum.kaltura.org.
Thanks,
