### ISSUE TITLE
Error updating UIConf

### ISSUE THREAD

**Issue by himbeere** [kaltura/platform-install-packages#326]
Hello.

I just installed kaltura 10.2. via rpm on a centos7 system. Everything works so far but i cannot update the players. See attached screen. Error in kaltlog:

==> /opt/kaltura/log/kaltura_apache_errors.log <==
[Wed Jan 14 15:18:25.035953 2015] [:error] [pid 31188] [client 151.252.43.186:53030] PHP Fatal error:  Uncaught exception 'Exception' with message 'An error occurred when trying to retrieve uiConfFile' in /opt/kaltura/web/html5/html5lib/v2.25/modules/KalturaSupport/UiConfResult.php:90\nStack trace:\n#0 /opt/kaltura/web/html5/html5lib/v2.25/modules/KalturaSupport/UiConfResult.php(43): UiConfResult->loadUiConf()\n#1 /opt/kaltura/web/html5/html5lib/v2.25/modules/KalturaSupport/KalturaCommon.php(122): UiConfResult->__construct(Object(RequestHelper), Object(KalturaClientHelper), Object(KalturaCache), Object(KalturaLogger), Object(KalturaUtils))\n#2 /opt/kaltura/web/html5/html5lib/v2.25/includes/Pimple.php(122): {closure}(Object(Pimple))\n#3 /opt/kaltura/web/html5/html5lib/v2.25/includes/Pimple.php(83): Pimple->{closure}(Object(Pimple))\n#4 /opt/kaltura/web/html5/html5lib/v2.25/modules/KalturaSupport/apiServices/mweUpgradePlayer.php(10): Pimple->offsetGet('uiconf_result')\n#5 /opt/kaltura/web/html5/html5lib/v2.25/services.php(30): mweUpgradePlayer->run()\n#6 /opt/kaltura/web/html5/html5lib/v2.25/services.php(21): mwEmbedApi in /opt/kaltura/web/html5/html5lib/v2.25/modules/KalturaSupport/UiConfResult.php on line 90, referer: http://great-domain.fishing/apps/studio/v1.9.3/index.html

Any idea on that?

thanks and cheers

![bildschirmfoto 2015-01-14 um 15 23 59](https://cloud.githubusercontent.com/assets/631865/5740205/991fe4ac-9c01-11e4-95a8-c461c58f22c7.png)

**Comment by himbeere** [comment]
After reinstalling everything works as expected. No idea what was causing this?

**Comment by jessp01** [comment]
Hi,

This sounds like this issue: https://github.com/kaltura/platform-install-packages/issues/124
Which should indeed be resolved. However, please note that you can always create new players with the exact same feature set.
