### ISSUE TITLE
RPM with Centos 7

### ISSUE THREAD

**Issue by toddleish** [kaltura/platform-install-packages#330]
I am trying to install the Kaltura CE RPM on Centos 7.  I have successfully installed RED5 on a different Centos 7 machine, but when I try to install the Kaltura RPM, I get several initial errors related to PHP extensions that are required but not installed...  Will the Kaltura RPM work with Centos 7, PHP 5.4.16, etc?

**Comment by KalturaCommunity** [comment]
Hello,

Please see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.3.0/doc/install-kaltura-redhat-based.md#note-on-rhelcentos-7

May the source be with you,

Jess Portnoy

**Comment by toddleish** [comment]
Thank you Jess.  I successfully installed Kaltura based on the link you provided.  However, there may be a bug in the config process.  After installing, the instructions say to "Configure MySQL with the required Kaltura Settings: /opt/kaltura/bin/kaltura-mysql-settings.sh."  When I run this, I get an error that says "package mysql-server is not installed".  The MariaDB service is then killed and won't restart.  I have tried this a few times with the same result.  I verified that MariaDB is running before I tried this script.  I have attached three screenshots showing the process and errors...  Also, if this is not the proper place to post this, can you direct me to the best location?
![kalturaconfig1](https://cloud.githubusercontent.com/assets/10604947/5828161/2650529c-a0be-11e4-92bd-895628cfd2ad.jpg)
![kalturaconfig2](https://cloud.githubusercontent.com/assets/10604947/5828163/2a8da468-a0be-11e4-9ba8-9f5bafebba2a.jpg)
![kalturaconfig3](https://cloud.githubusercontent.com/assets/10604947/5828165/2df003f8-a0be-11e4-86a9-70933e062a80.jpg)

**Comment by jessp01** [comment]
Hello,

Glad to here some progress was made:)
The "package mysql-server is not installed" is OK and in a newer revision 
is directed to /dev/null
if rpm -q mysql-server 2>/dev/null;then

You can ignore it.
As far as why it would not load, please check the mariadb.log for errors 
and post them.

Best would be to post at forum.kaltura.org, for general issues, for 
something you feel is a reproducible bug, the issues section here is 
correct:)

May the source be with you,

Jess Portnoy

**Comment by toddleish** [comment]
I tried to post this to forum.kaltura.org, but it says new users are not allowed to upload images... not sure how to get past that.  Hopefully this is something you can reproduce there...

I am installing Kaltura CE on Centos 7 based on the instructions here:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.3.0/doc/install-kaltura-redhat-based.md#note-on-rhelcentos-7.

Kaltura seems to install fine, but when I move to the next step following installation, "Configure MySQL with the required Kaltura Settings" and run /opt/kaltura/bin/kaltura-mysql-settings.sh, MariaDB crashes and will not recover.  Below are two screenshots showing the MariaDB log.  The first log is the normal log.  The second log is the log after running the Kaltura script.  I don't see from this why MariaDB is crashing.  Please let me know what I can do to move past this.
Thanks!
![mariadb-log-normal](https://cloud.githubusercontent.com/assets/10604947/5841345/682c01ac-a159-11e4-9fce-f5fc2f55d3e2.jpg)

![mariadb-log-aftercrash](https://cloud.githubusercontent.com/assets/10604947/5841348/6c768f7a-a159-11e4-8bdc-3fcaa3dcd907.jpg)

**Comment by KalturaCommunity** [comment]
Hello,

Please try removing /var/lib/mysql/ib_logfile* and restart MariaDB.

No need to post screenshots, just strings from the log is fine:)

Thanks,

May the source be with you,

Jess Portnoy

**Comment by toddleish** [comment]
Yes, that worked!  Thank you for your expertise.

**Comment by jessp01** [comment]
Happy to assist.
