### ISSUE TITLE
install Kaltura on CentOS 7 64bit - dependency issues

### ISSUE THREAD

**Issue by jonasyuandotcom** [kaltura/platform-install-packages#331]
I tried to install Kaltura on CentOS 7 64bit according to this guide https://github.com/kaltura/platform-install-packages/blob/master/doc/install-kaltura-redhat-based.md , but I got these errors when running yum install kaltura-server:

--> Finished Dependency Resolution
Error: Package: kaltura-librtmp-2.3-2.x86_64 (Kaltura)
           Requires: libgnutls.so.26()(64bit)
Error: Package: kaltura-ffmpeg-aux-0.6-2.x86_64 (Kaltura)
           Requires: libopenjpeg.so.2()(64bit)
Error: Package: kaltura-sphinx-2.2.1-16.x86_64 (Kaltura)
           Requires: libmysqlclient.so.16()(64bit)
Error: Package: kaltura-ffmpeg-2.1.3-1.x86_64 (Kaltura)
           Requires: libopenjpeg.so.2()(64bit)
Error: Package: kaltura-librtmp-2.3-2.x86_64 (Kaltura)
           Requires: libgnutls.so.26(GNUTLS_1_4)(64bit)
Error: Package: kaltura-sphinx-2.2.1-16.x86_64 (Kaltura)
           Requires: libmysqlclient.so.16(libmysqlclient_16)(64bit)

**Comment by jessp01** [comment]
Hello, 
Please see here:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.3.0/doc/install-kaltura-redhat-based.md#note-on-rhelcentos-7

I believe you did not setup the rhel7 repo..
