### ISSUE TITLE
/opt/kaltura/bin/kaltura-functions.rc: line 73: [: : integer expression expected

### ISSUE THREAD

**Issue by harshadyeola** [kaltura/platform-install-packages#332]
Got this error While installing Kaltura  with guide on 
https://github.com/kaltura/platform-install-packages/blob/master/doc/install-kaltura-redhat-based.md
stucked at this step
`/opt/kaltura/bin/kaltura-config-all.sh`
![selection_003](https://cloud.githubusercontent.com/assets/7354660/5852134/de0114ce-a237-11e4-9b3d-81f928765bee.png)

**Comment by jessp01** [comment]
Hello,

The error you see was fixed but it is not the real problem.
Can you paste the contents of /opt/kaltura/log/insertContent.log?

**Comment by jessp01** [comment]
Closing due to lack of feedback, please reopen if still relevant.
