### ISSUE TITLE
Suggested tweak to SSL install instructions text

### ISSUE THREAD

**Issue by verdonv** [kaltura/platform-install-packages#336]
Hi,

In the instructions for an SSL install here <https://github.com/kaltura/platform-install-packages/blob/master/doc/install-kaltura-redhat-based.md>, the text in the sample question answer format is slightly misleading. On the 4th line, it says
<pre>Which port will this Vhost listen on [80]?: "&lt;80&gt;"</pre>
If you actually enter 80 there, and not 443, you will never be asked later on if you're apache is working with SSL and you will not be offered to configure the paths to your cert/etc.

**Comment by jessp01** [comment]
Hello @verdonv,

This was recently corrected:
https://github.com/kaltura/platform-install-packages/commit/6b24d26ef139bb6b3bd6518a7da6b5cf585e9541

If you still find it not clear enough, would love to get a pull req with additional suggestions.

Thanks,
