### ISSUE TITLE
cloudfront and RTMP streaming 404 Error

### ISSUE THREAD

**Issue by blackyboy** [kaltura/platform-install-packages#338]
Hi @jessp01 @KalturaCommunity 
 
Now i have installed Kaltura Current version ( 10.03) with S3 storage profile and cloudfront web and rtmp distributions. The HTTP progressive download is working fine with Cloudfront web distribution, But in rtmp we getting Error GET http://s1cxxxxxxxx6.cloudfront.net/fcs/ident/ 404 (Not Found). Please also see the attached screenshot for more detail. 

![selection_001](https://cloud.githubusercontent.com/assets/4866182/5996910/1f5c840e-aad9-11e4-9c74-8cff80527640.png)

**Comment by renich** [comment]
I tweaked the file: /opt/kaltura/app/alpha/lib/model/DeliveryProfileRtmp.php

On line 49, change:

```php
$url .= "/name/a." . $this->NON_FLV_FILE_EXTENSION;
```

to
```php
$url .= "." . $this->NON_FLV_FILE_EXTENSION;
```

And that makes RTMP work. It is an ugly hack, but it helps.

Thanks to jeroslaw for that one.

**Comment by renich** [comment]
@blackyboy btw, dude; a thousand thanks for your howto. It helped me configure my instance.

**Comment by blackyboy** [comment]
@renich Awesome work's great :+1: , Thanks for your hack buddy...  :octocat:
