### ISSUE TITLE
Installation error in scripts

### ISSUE THREAD

**Issue by renich** [kaltura/platform-install-packages#340]
Every time I reinstall kaltura, which is often, I get:

```bash
...
Checking MySQL version..
Ver 5.1.73 found compatible
ERROR 1193 (HY000) at line 1: Unknown system variable 'innodb_log_file_size'
/opt/kaltura/bin/kaltura-functions.rc: line 73: [: : integer expression expected

CREATE USER kaltura;
...
```

I must say I run kaltura-drop-db.sh before I do this.

**Comment by renich** [comment]
Forgot to mention:

- CentOS 6.6
- Kaltura 10.3.0
- Cluster setup (only for DB really, for now).

**Comment by jessp01** [comment]
Hello,

What ver of MySQL is this? Also, what does:
select @@innodb_log_file_size; return?

**Comment by renich** [comment]
mysql version:
```bash
# rpm -q mysql-server
mysql-server-5.1.73-3.el6_5.x86_64
```

result of select @@innodb_log_file_size
```bash
mysql -e 'select @@innodb_log_file_size;'
ERROR 1193 (HY000) at line 1: Unknown system variable 'innodb_log_file_size'
```

**Comment by renich** [comment]
Also, the mysql config file (before you ask).
```ini
[mysqld]
max_allowed_packet = 16M

open_files_limit = 20000

innodb_log_file_size=32M

innodb_file_per_table

lower_case_table_names = 1



innodb_log_file_size=32M

innodb_file_per_table


datadir=/var/lib/mysql
socket=/var/lib/mysql/mysql.sock
user=mysql
# Disabling symbolic-links is recommended to prevent assorted security risks
symbolic-links=0

[mysqld_safe]
log-error=/var/log/mysqld.log
pid-file=/var/run/mysqld/mysqld.pid
```

I must add that the mysql server is independent. It is not local; it is another server (separate from the kaltura installation). But it has been configured with the mysql script.

**Comment by renich** [comment]
Ok, it seems that my server's DB had faulty ib_logfile{1,2}. I removed those and now innodb is showing. Should I reinstall because of this?

**Comment by jessp01** [comment]
Did the DB phase pass correctly creating all tables and populating data?


May the source be with you,

Jess Portnoy



-------- Original message --------

**Comment by renich** [comment]
I don't really know and it's hard to determine. KMC and KAC work but I dunno if I have one of those strange bugs that hit you because some record didn't get in.

You know the script and the procedure much better than I do. What would you think? Is it merely a test or does it affect me in some way? Should I reinstall?

**Comment by jessp01** [comment]
If the install phase passed with no errors then you should be fine.
If you wish to repopulate the DB, you do not have to reinstall everything anew.
You can just drop the DB with:
\# kaltura-drop-db.sh
and then repopulate with:
\# kaltura-db-config.sh

Closing for now, please reopen if you have more issues.

**Comment by renich** [comment]
Ok, repopulated with drop and config-all and it worked fine; no errors. Thanks.
