### ISSUE TITLE
can't upgrade to 10.3

### ISSUE THREAD

**Issue by kinglok** [kaltura/platform-install-packages#341]
Currently, I am using 9.18 and can't perform upgrade.  Here is the response in console.

[root@kaltura kinglok]# yum clean all
Loaded plugins: fastestmirror
Cleaning repos: Kaltura Kaltura-noarch base extras updates
Cleaning up Everything
Cleaning up list of fastest mirrors
[root@kaltura kinglok]# yum update kaltura-release
Loaded plugins: fastestmirror
Setting up Update Process
Determining fastest mirrors
 * base: ftp.cuhk.edu.hk
 * extras: ftp.cuhk.edu.hk
 * updates: ftp.cuhk.edu.hk
Kaltura                                                  | 2.9 kB     00:00     
Kaltura/primary_db                                       | 182 kB     00:01     
Kaltura-noarch                                           | 2.9 kB     00:00     
Kaltura-noarch/primary_db                                |  33 kB     00:00     
base                                                     | 3.7 kB     00:00     
base/primary_db                                          | 4.6 MB     00:00     
extras                                                   | 3.4 kB     00:00     
extras/primary_db                                        |  30 kB     00:00     
updates                                                  | 3.4 kB     00:00     
updates/primary_db                                       | 2.1 MB     00:00     
No Packages marked for Update
[root@kaltura kinglok]# yum clean all
Loaded plugins: fastestmirror
Cleaning repos: Kaltura Kaltura-noarch base extras updates
Cleaning up Everything
Cleaning up list of fastest mirrors
[root@kaltura kinglok]# yum update "*kaltura*"
Loaded plugins: fastestmirror
Setting up Update Process
Determining fastest mirrors
 * base: ftp.cuhk.edu.hk
 * extras: ftp.cuhk.edu.hk
 * updates: ftp.cuhk.edu.hk
Kaltura                                                  | 2.9 kB     00:00     
Kaltura/primary_db                                       | 182 kB     00:01     
Kaltura-noarch                                           | 2.9 kB     00:00     
Kaltura-noarch/primary_db                                |  33 kB     00:00     
base                                                     | 3.7 kB     00:00     
base/primary_db                                          | 4.6 MB     00:00     
extras                                                   | 3.4 kB     00:00     
extras/primary_db                                        |  30 kB     00:00     
updates                                                  | 3.4 kB     00:00     
updates/primary_db                                       | 2.1 MB     00:00     
No Packages marked for Update
[root@kaltura kinglok]#

**Comment by jessp01** [comment]
Hello,

What does /etc/yum.repos.d/kaltura.repo contain?


May the source be with you,

Jess Portnoy



-------- Original message --------

**Comment by kinglok** [comment]
I should be using 9.19.5...

the file content:

# URL: http://kaltura.org/
[Kaltura]
name = Kaltura Server
baseurl = http://installrepo.kaltura.org/releases/9.19.5/RPMS/$basearch/
gpgkey = http://installrepo.kaltura.org/releases/RPM-GPG-KEY-kaltura
gpgcheck = 1
enabled = 1

[Kaltura-noarch]
name = Kaltura Server arch independent
baseurl = http://installrepo.kaltura.org/releases/9.19.5/RPMS/noarch
gpgkey = http://installrepo.kaltura.org/releases/RPM-GPG-KEY-kaltura
gpgcheck = 1
enabled = 1

# we currently do not have the nightly so commented. We do have plans to add that.
#[Kaltura-testing]
#name = Kaltura Server arch independent
#baseurl = http://installrepo.kaltura.org/releases/nightly/RPMS/$basearch/
#gpgkey = http://installrepo.kaltura.org/releases/RPM-GPG-KEY-kaltura
#gpgcheck = 1 
#enabled = 0

#[Kaltura-testing-noarch]
#name = Kaltura Server arch independent
#baseurl = http://installrepo.kaltura.org/releases/nightly/RPMS/noarch
#gpgkey = http://installrepo.kaltura.org/releases/RPM-GPG-KEY-kaltura
#gpgcheck = 1
#enabled = 0

**Comment by jessp01** [comment]
Change '9.19.5' to 'latest' and yum clean all.


May the source be with you,

Jess Portnoy



-------- Original message --------
