### ISSUE TITLE
kaltura admin_console an error occurred API:-1

### ISSUE THREAD

**Issue by youcheng1** [kaltura/platform-install-packages#342]
kaltura admin_console an error occurred API:-1

kaltura_admin.log:
ERR: exception 'Exception' with message 'Class [KalturaInternalToolsPluginSystemHelperAction] requires permissions [Array
(
    [0] => SYSTEM_INTERNAL
)
]' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:
#0 /opt/kaltura/app/ui_infra/InfraBootstrapper.php(113): KalturaLog::err('Class [KalturaI...')
#1 /opt/kaltura/app/vendor/ZendFramework/library/Zend/Application/Bootstrap/BootstrapAbstract.php(662): InfraBootstrapper->_initNavigation()
#2 /opt/kaltura/app/vendor/ZendFramework/library/Zend/Application/Bootstrap/BootstrapAbstract.php(615): Zend_Application_Bootstrap_BootstrapAbstract->_executeResource('navigation')
#3 /opt/kaltura/app/vendor/ZendFramework/library/Zend/Application/Bootstrap/BootstrapAbstract.php(579): Zend_Application_Bootstrap_BootstrapAbstract->_bootstrap(NULL)
#4 /opt/kaltura/app/vendor/ZendFramework/library/Zend/Application.php(347): Zend_Application_Bootstrap_BootstrapAbstract->bootstrap(NULL)
#5 /opt/kaltura/app/admin_console/web/index.php(37): Zend_Application->bootstrap()
#6 {main}
2015-02-04 20:38:56 [662900335] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [VirusScanListAction] requires permissions [Array
(
    [0] => SYSTEM_ADMIN_VIRUS_SCAN
)
]' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:
#0 /opt/kaltura/app/ui_infra/InfraBootstrapper.php(113):

kaltura-apache-error.log
[Wed Feb 04 07:39:13 2015] [error] [client 127.0.0.1] File does not exist: /opt/kaltura/app/alpha/web/opt, referer: http://localhost/admin_console/index.php/user/login
[Wed Feb 04 07:39:29 2015] [error] [client 127.0.0.1] File does not exist: /opt/kaltura/app/alpha/web/opt, referer: http://localhost/admin_console/index.php/user/login
[Wed Feb 04 07:40:11 2015] [error] [client 127.0.0.1] File does not exist: /opt/kaltura/app/alpha/web/lib/images/kmc/null.png, referer: http://localhost/kmc
[Wed Feb 04 07:42:13 2015] [error] [client 192.168.164.1] PHP Notice:  The language 'zh_CN' has to be added before it can be used. in /opt/kaltura/app/vendor/ZendFramework/library/Zend/Translate/Adapter.php on line 322, referer: http://192.168.164.128/start/index.php
[Wed Feb 04 07:42:13 2015] [error] [client 192.168.164.1] PHP Notice:  No translation for the language 'zh' available. in ...

**Comment by DBezemer** [comment]
These messages are normal and can be ignored. Basically it tries to use your system language, and falls back on english when this language cannot be found.

The other messages occur when you are not logged in yet as there is a permissions check before you're logged in.
