### ISSUE TITLE
Couldn't connect with mysql

### ISSUE THREAD

**Issue by petechua** [kaltura/platform-install-packages#343]
Hi,

Installing on Centos 6.6, encountered below error during /opt/kaltura/bin/kaltura-config-all.sh:
CREATE USER kaltura;
CREATE USER etl;
CREATE DATABASE kaltura;
CREATE DATABASE kaltura_sphinx_log;
CREATE DATABASE kalturadw;
CREATE DATABASE kalturadw_ds;
CREATE DATABASE kalturadw_bisources;
CREATE DATABASE kalturalog;
Checking connectivity to needed daemons...
ERROR: Couldn't connect with mysql -ukaltura -pvfPZIiCY55AvWBR -h127.0.0.1 -P3306.
Please check your setup and then run /opt/kaltura/bin/kaltura-db-config.sh again.

Remove the databases and re-run /opt/kaltura/bin/kaltura-db-config.sh throws back the same error.

mysqld is started and accessible:
[root@mytube ~]# mysql -u root -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 36
Server version: 5.1.73 Source distribution

Any ideas please?

**Comment by petechua** [comment]
Looking further up installation history, apparently there are error observed:

Non-fatal POSTIN scriptlet failure in rpm package kaltura-nginx-1.6.2-6.x86_64
----------------------------------------------------------------------

Thanks for using nginx!

Please find the official documentation for nginx here:
* http://nginx.org/en/docs/

Commercial subscriptions for nginx are available on:
* http://nginx.com/products/

----------------------------------------------------------------------
/bin/chown: invalid user: `kaltura:adm'
/bin/chown: invalid user: `kaltura:adm'
warning: %post(kaltura-nginx-1.6.2-6.x86_64) scriptlet failed, exit status 1

**Comment by jessp01** [comment]
Hello,

About Nginx, this was fixed a while back. Are you using the latest repo?
As far as MySQL - what is the output for:
mysql> select host,user from mysql.user;

**Comment by petechua** [comment]
Hi,

The Kaltura repo on my system:

[root@a ~]# more /etc/yum.repos.d/kaltura.repo 
# URL: http://kaltura.org/
[Kaltura]
name = Kaltura Server
baseurl = http://installrepo.kaltura.org/releases/latest/RPMS/$basearch/
gpgkey = http://installrepo.kaltura.org/releases/RPM-GPG-KEY-kaltura
gpgcheck = 1 
enabled = 1

[Kaltura-noarch]
name = Kaltura Server arch independent
baseurl = http://installrepo.kaltura.org/releases/latest/RPMS/noarch
gpgkey = http://installrepo.kaltura.org/releases/RPM-GPG-KEY-kaltura
gpgcheck = 1
enabled = 1

# we currently do not have the nightly so commented. We do have plans to add that.
#[Kaltura-testing]
#name = Kaltura Server arch independent
#baseurl = http://installrepo.kaltura.org/releases/nightly/RPMS/$basearch/
#gpgkey = http://installrepo.kaltura.org/releases/RPM-GPG-KEY-kaltura
#gpgcheck = 1 
#enabled = 0

#[Kaltura-testing-noarch]
#name = Kaltura Server arch independent
#baseurl = http://installrepo.kaltura.org/releases/nightly/RPMS/noarch
#gpgkey = http://installrepo.kaltura.org/releases/RPM-GPG-KEY-kaltura
#gpgcheck = 1
#enabled = 0
[root@a ~]# 

Output of mysql:
mysql> select host,user from mysql.user;
+---------------------+---------+
| host                | user    |
+---------------------+---------+
| %                   | etl     |
| %                   | kaltura |
| 127.0.0.1           | root    |
| localhost           |         |
| localhost           | root    |
| a.mydomain.com |         |
+---------------------+---------+
6 rows in set (0.00 sec)

mysql>

**Comment by jessp01** [comment]
Yes, so this is your problem. Did you run mysql_secure_installation? it usually drops the
| localhost without user and passwd..
Anyhow, you can delete this line manually and then it should work.

**Comment by vadimtar** [comment]
I've got the Non-fatal POSTIN scriptlet failure in rpm package kaltura-nginx-1.6.2-6.x86_64 error today, installed stand alone server

**Comment by jessp01** [comment]
Hi @vadimtar,

What was the error? also, does not seem related to this closed issue.
Please post it at forum.kaltura.org.

Thanks,
