### ISSUE TITLE
kaltura 9.19.8 - Problem scheduled batch when change hostname

### ISSUE THREAD

**Issue by angober** [kaltura/platform-install-packages#344]
I changed the hostname and run kaltura-batch-config.sh in the DB instead of changing the name of the tasks you do is recreate all tasks with the new name. By doing this I get the following error:

PHP Fatal error: Uncaught exception 'KalturaException' with message 'Scheduler id "88983" conflicts Between hosts: "dsacgvkalt01.srv.gva.es" and "rhelcnlgvkaltura.srv.gva.es'' in / srv_apl / Kaltura / app / batch /client/KalturaClientBase.php:734
Stack trace:
# 0 /srv_apl/kaltura/app/batch/client/KalturaClient.php(644): KalturaClientBase-> throwExceptionIfError (Array)

How I can make only one name kept on tasks and not duplicated each time?

**Comment by jessp01** [comment]
Hello,

Please truncate:
| scheduler                            |
| scheduler_config                     |
| scheduler_status                     |
| scheduler_worker

And then restart batch, should be fine.

May the source be with you,

Jess Portnoy

**Comment by angober** [comment]
Ok, thanks...
