### ISSUE TITLE
skip/bypass PRE_CONSENT message during chef runs?

### ISSUE THREAD

**Issue by nukepuppy** [kaltura/platform-install-packages#353]
Is there some sort of attribute that should be bypassing the PRE_CONSENT message?
after some tests ran an strace on the process after it ran for a very very long time

```
write(1, "Please input a valid mail addres"..., 42) = 42
ioctl(0, SNDCTL_TMR_TIMEBASE or TCGETS, 0x7fff70a90c00) = -1 EINVAL (Invalid argument)
lseek(0, 0, SEEK_CUR)                   = -1 ESPIPE (Illegal seek)
read(0, "", 1)                          = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
write(1, "Please input a valid mail addres"..., 42) = 42
ioctl(0, SNDCTL_TMR_TIMEBASE or TCGETS, 0x7fff70a90c00) = -1 EINVAL (Invalid argument)
lseek(0, 0, SEEK_CUR)                   = -1 ESPIPE (Illegal seek)
read(0, "", 1)                          = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
```

obviously this ran until I killed it manually... what is supposed to handle this?

**Comment by jessp01** [comment]
Hello,

for none interactive installs, just use an answer file, with this template:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.6.0/doc/kaltura.template.ans

**Comment by jessp01** [comment]
You may also be interested in using Chef in case you are planning on a cluster:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.6.0/doc/rpm-chef-cluster-deployment.md

**Comment by nukepuppy** [comment]
jess,
this WAS using chef.... and it was stuck on that component when doing sphinx in the sphinx recipe it got stuck there for half an hour before I killed it manually
what values in here:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.6.0/doc/kaltura.template.ans

would go from the attributes in: https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.6.0/chef-repo/cookbooks/kaltura/templates/default/kaltura.ans.erb

to skip the question successfully?

default[:kaltura][:USER_CONSENT] = 0  

Really not understanding why my generated answer file from chef would still prompt for a password....

**Comment by KalturaCommunity** [comment]
Yes. Like you wrote should work. Otherwise its a bug which you can bypass with echo NO | kaltura-config-script-name.sh

If so please submit a report.


May the source be with you,

Jess Portnoy



-------- Original message --------
