### ISSUE TITLE
When using chef other issues are critical

### ISSUE THREAD

**Issue by nukepuppy** [kaltura/platform-install-packages#354]
looking at this issue https://github.com/kaltura/platform-install-packages/issues/337

when CHEF encounters this issue it 'fails' ...    what would work around for this be? I'm growing concerned the chef recipes are not really usable right now?

My ideas to tackle this is to provide my own template file to overwrite /opt/kaltura/bin/kaltura-functions.rc with BEFORE It runs ? since the command that fails doesn't exist as a system variable

```
mysql> select @@innodb_log_file_size;
ERROR 1193 (HY000): Unknown system variable 'innodb_log_file_size'
```

**Comment by nukepuppy** [comment]
Ok I think the issue is really the fact the advice right now is to use the opscode community cookbook for mysql - and well there has been some major changes there...

we should consider maybe importing this cookbook as a dependency into the platform chef - repo and then writing a wrapper to leverage it with the appropriate kaltura values / depdencies

there are some out of band things such as the mysql-settings.rb recipe that assumes it would be run on the same server as 'mysql' but that wont be true too often... if ever except the all in one server maybe.

anyhow i'm going to close this out as there is no immediate fix atm.. would be good to know if maybe we can move the project ahead some more with maybe using berkshelf / manage dependencies from other cookbooks easier.. the moving target of mysql is going to be an issue.

**Comment by jessp01** [comment]
Hello @nukepuppy,

I agree we should look into berkshelf and would love to get contributions and pull requests from you [or others] on that front.

Thanks,
