### ISSUE TITLE
Overly nested repository

### ISSUE THREAD

**Issue by renich** [kaltura/platform-install-packages#355]
Hello,

Check this out:
http://cdn.installrepo.kaltura.org/releases/latest/RPMS/x86_64/x86_64/x86_64/x86_64/x86_64/x86_64/x86_64/x86_64/x86_64/kaltura-pentaho-4.2.1-1.x86_64.rpm

You have an error somewhere and it's nesting x86_64's in your repo; it makes mirroring awkward...

**Comment by renich** [comment]
Also, it would be nicer, cheaper and faster to have an rsync daemon running. It would take a lot of pain from your server.

**Comment by jessp01** [comment]
Hi,

Thanks for the report, I removed the releases/latest/RPMS/x86_64/x86_64 and its sub dirs which indeed should not be there.
rsync - not quite sure what you mean? the repos are hosted on our CDN. where and for which purpose do you need rsync running?

**Comment by renich** [comment]
Well, rsync is made for this. It enables a server to get only what's new; with a lot of really cool features. All major linux distributions offer rsync servers. They're easy to enable. I could help if you like.

https://en.wikipedia.org/wiki/Rsync
https://mirrors.fedoraproject.org/publiclist/ (look for rsync)

It's the best way to sync mirrors. Wget will take ages and will not be able to mirror (in sync; as in locally delete what it's not in the remote location). While rsync will just get the differences and fast as hell. It will save you bandwidth and processor time.

Here's a neat howto: http://www.server-world.info/en/note?os=CentOS_6&p=rsync

The only difference is that you want to allow everybody and use it read-only. It can co-exist with your current apache server.

**Comment by jessp01** [comment]
oh, it would be quite shameful for me not to know what rsync is!
that was not what i was asking.. i was trying to understand what you want to do exactly, which I now understand but again, since we have no control over the CDN nodes you are reaching, I cannot set this up. As you mentioned, we do support Apache indexing so doing this with wget is possible but yes, it will take longer.
