### ISSUE TITLE
standalone batch running apache but not using it

### ISSUE THREAD

**Issue by doubleshot** [kaltura/platform-install-packages#359]
Kaltura-batch gets installed with apache and starts it, yet in a cluster scenario, the batch.ini uses the api service url, which is not the batch server.  
It's also doesnt install the kaltura apache config, if the intention was to have batch point at itself. 

Before I make a pull request to fix this by removing the apache start, what is your intention? 
1. Batch to run Apache so that API calls are localhost, or
2. Batch to not run apache and point at API LB

I'd vote for # 2, however, with the new RPM ability to easily update kaltura-base, it may be better to have batches point at themselves for performance/debugging reasons and not tie up the primary APIs. 

Thanks

**Comment by jessp01** [comment]
Hi,

What should happen is option #1. I will make sure the Apache configuration enabling batch requests onto itself is in place. 
As you mentioned, you can always reconfigure it any way you wish but this will be the default.

Thanks,

**Comment by jessp01** [comment]
pushed and distributed as kaltura-postinst-1.0.24-8.noarch
