### ISSUE TITLE
unable to update to 10.6.0 because of missing file in repo

### ISSUE THREAD

**Issue by himbeere** [kaltura/platform-install-packages#360]
Hello.

I did a "yum clean all" before trying to update but i still get this issue:

```
Kaltura-noarch/primary_db      FAILED                                                                   ] 2.5 MB/s | 5.7 MB  00:00:04 ETA 
http://installrepo.kaltura.org/releases/latest/RPMS/noarch/repodata/84492ebd8af1b229aebcd31e6abd83331575095add8586c2cea793ccd1c2391d-primary.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found
```

Here the content of /etc/yum.repos.d/kaltura.repo
```
[root@videos ~]# cat /etc/yum.repos.d/kaltura.repo
# URL: http://kaltura.org/
[Kaltura]
name = Kaltura Server
baseurl = http://installrepo.kaltura.org/releases/rhel7/RPMS/$basearch/
gpgkey = http://installrepo.kaltura.org/releases/RPM-GPG-KEY-kaltura
gpgcheck = 1 
enabled = 1

[Kaltura-noarch]
name = Kaltura Server arch independent
baseurl = http://installrepo.kaltura.org/releases/latest/RPMS/noarch
gpgkey = http://installrepo.kaltura.org/releases/RPM-GPG-KEY-kaltura
gpgcheck = 1
enabled = 1

# we currently do not have the nightly so commented. We do have plans to add that.
#[Kaltura-testing]
#name = Kaltura Server arch independent
#baseurl = http://installrepo.kaltura.org/releases/nightly/RPMS/$basearch/
#gpgkey = http://installrepo.kaltura.org/releases/RPM-GPG-KEY-kaltura
#gpgcheck = 1 
#enabled = 0

#[Kaltura-testing-noarch]
#name = Kaltura Server arch independent
#baseurl = http://installrepo.kaltura.org/releases/nightly/RPMS/noarch
#gpgkey = http://installrepo.kaltura.org/releases/RPM-GPG-KEY-kaltura
#gpgcheck = 1
#enabled = 0
[root@videos ~]#
```

(as for the suggestion to use the forum, i always get a white page after login in to the forums page)
![bildschirmfoto 2015-03-18 um 13 15 06](https://cloud.githubusercontent.com/assets/631865/6708471/e58656be-cd70-11e4-8b9d-6c198ceba922.png)

cheers

**Comment by jessp01** [comment]
Hello,

Our repo is using CDN, which might mean your particular edge is not fully synced.
Can you try changing the string 'latest' to 10.6.0 and see if this makes any diff? it seem to have solved the issue for another user in the past.
Of course, in the next upgrade, which will occur on Sun. you will need to change it again to 'latest' so you will continue to get updates when you run "yum update "*kaltura*"

About the forum, can you please provide your user name?

Thank you,

**Comment by himbeere** [comment]
Hello.

Thanks for your answer. My user name for the forum is "himbeere".

Changing "latest" to "10.6.0" works indeed. Thanks again.

**Comment by KalturaCommunity** [comment]
Hi,

Glad it works but please be sure to change it later.
I could not find this username, can you please send me your email?
Also, lets move the discussion to private mails, please write to 
jess.portnoy@kaltura.com

Thanks,

May the source be with you,

Jess Portnoy
