### ISSUE TITLE
User list is not working on Admin console (for partner -2)

### ISSUE THREAD

**Issue by Ronileco** [kaltura/platform-install-packages#362]
Hi,
On the latest release we can't see the user list in the admin console.

I tried calling the user service list action after creating an admin KS for publisher -2, and it didn't work (from testme console)

**Comment by jessp01** [comment]
Hi Roni,

This is not a generic bug as the ENVs we have with 10.7.0 work well.
So, please open a post at forum.kaltura.org.

Before doing so, I would make sure the DB is intact, i.e partner table looks OK, then that Sphinx is running and then run kaltlog while making the request.

If you still can't track the issue, please post.

**Comment by Ronileco** [comment]
Thanks for the quick reply I'll check that.
BTW I was able to find the user credentials on the DB and we can use the users.

I'll check the Sphinx got those changes as well
