### ISSUE TITLE
Kmc not working after install ce 10

### ISSUE THREAD

**Issue by jaiswal41** [kaltura/platform-install-packages#363]
its showing Loading status.

**Comment by jessp01** [comment]
Hello,

Start by looking here:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.8.0/doc/kaltura-packages-faq.md#troubleshooting-help

Also, use an HTTP sniffer to detect the failing request.
and, run:
# kaltura-sanity.sh
if you still have issues, please post to forum.kaltura.org.

**Comment by jaiswal41** [comment]
[Space on /] [PASSED, RC: 0] - [.008265890]

[Space on /opt/kaltura/web] [PASSED, RC: 0] - [.008315013]
[Check httpd daemon status] [PASSED, RC: 0] - [.022479214]
Napping 1 seconds to allow the daemon httpd to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon httpd to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon httpd to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon httpd to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon httpd to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon httpd to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon httpd to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon httpd to finish its init after monit restarted it..
[Check httpd daemon is started by Monit] [PASSED, RC: 0] - [9.370780252]
[check daemon httpd init status] [PASSED, RC: 0] - [.007093272]
[Check kaltura-sphinx daemon status] [PASSED, RC: 0] - [.031920141]
Napping 1 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
[Check kaltura-sphinx daemon is started by Monit] [PASSED, RC: 0] - [7.821743335]
[check daemon kaltura-sphinx init status] [PASSED, RC: 0] - [.007136674]
[Check kaltura-batch daemon status] [PASSED, RC: 0] - [.028862421]
Napping 1 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
[Check kaltura-batch daemon is started by Monit] [PASSED, RC: 0] - [9.325663464]
[check daemon kaltura-batch init status] [PASSED, RC: 0] - [.007018612]
[Check kaltura-monit daemon status] [PASSED, RC: 0] - [.023908476]
[check daemon kaltura-monit init status] [PASSED, RC: 0] - [.006996297]
[Check memcached daemon status] [PASSED, RC: 0] - [.022336398]
Napping 1 seconds to allow the daemon memcached to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon memcached to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon memcached to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon memcached to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon memcached to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon memcached to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon memcached to finish its init after monit restarted it..
Napping 1 seconds to allow the daemon memcached to finish its init after monit restarted it..
[Check memcached daemon is started by Monit] [PASSED, RC: 0] - [8.328799333]
[check daemon memcached init status] [PASSED, RC: 0] - [.006968581]
[kaltura-html5lib ver in KMC config.ini] [PASSED, RC: 0] - [.081705779]
[kaltura-kdp3 ver in KDP3 config.ini] [PASSED, RC: 0] - [.032452415]
[kaltura-kmc ver in KMC config.ini] [PASSED, RC: 0] - [.039253552]
[Get KMC SWFs] [PASSED, RC: 0] - [.120336496]
[check_testme_page] [PASSED, RC: 0] - [.091232447]
[check_kmc_index_page] [PASSED, RC: 0] - [.023356390]
[check_admin_console_index_page] [PASSED, RC: 0] - [.166808566]
[check_studio_index_page] [PASSED, RC: 0] - [.370784552]
[check_clipapp_index_page] [FAILED, RC: 1] - [.363844580]
[Create Partner] [PASSED, RC: 0] - [1.596627332]
[Local dropfolder creation succeeded] [PASSED, RC: 0] - [.283978722]
[Create flavor param] [PASSED, RC: 0] - [.390663430]
[Delete flavor param] [PASSED, RC: 0] - [.164383299]
[Upload content kaltura_logo_animated_blue.flv] [PASSED, RC: 0] - [.581333430]
Napping 10 seconds to allow entry 0_h6s5hptn to digest..
Napping 10 seconds to allow entry 0_h6s5hptn to digest..
Napping 10 seconds to allow entry 0_h6s5hptn to digest..
Napping 10 seconds to allow entry 0_h6s5hptn to digest..
Napping 10 seconds to allow entry 0_h6s5hptn to digest..
Napping 10 seconds to allow entry 0_h6s5hptn to digest..
[kaltura_logo_animated_blue.flv - 0_h6s5hptn status] [PASSED, RC: 0] - [61.185524248]
[Thumb for 0_h6s5hptn identical to /opt/kaltura/bin/kaltura_logo_animated_blue_1_sec.jpg] [PASSED, RC: 0] - [.564899541]
[Clipping 0_h6s5hptn Succeeded] [PASSED, RC: 0] - [.364663188]
[Trimming 0_h6s5hptn Succeeded] [PASSED, RC: 0] - [.330999848]
[Mock playback 0_h6s5hptn succeeded] [PASSED, RC: 0] - [.237675780]
[Entry reconversion of 0_h6s5hptn succeeded] [PASSED, RC: 0] - [.289169896]
Napping 30 seconds to allow mail to be sent out..
send-mail: Cannot open mail:25
[Could not find an email sending entry for mb-kalturaaws.wddemo.net@kaltura.com [PID is 103] in /var/log/maillog] [FAILED, RC: 1] - [30.012229390]
Testing analytics, be patient..

Please note: if you are running this test on a clustered ENV, it will fail but this does not mean there is an actual problem.
The tech information as to why is available here:
https://github.com/kaltura/platform-install-packages/issues/106#issuecomment-42837404
