### ISSUE TITLE
Kaltura repository is broken

### ISSUE THREAD

**Issue by ivanxx** [kaltura/platform-install-packages#366]
HI there!,

I was trying to make a new installation on a Centos7 server and, after downloading some of the packages, I'm getting this message everytime I try to contact the repos:

`http://installrepo.kaltura.org/releases/latest/RPMS/noarch/repodata/51d24c0881c03ccb6a3f961e099ed003327c15892e6c291a0bbf2eb6281d1e3d-primary.sqlite.bz2: [Errno 14] HTTP Error 301 - Moved Permanently`

And samge goes for the rhel7 installations:

`http://installrepo.kaltura.org/releases/rhel7/RPMS/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 301 - Moved Permanently`

Trying to access directly from a web browser to http://installrepo.kaltura.org/releases also crashes with a ERR_TOO_MANY_REDIRECTS error.

**Comment by jessp01** [comment]
Hello,

I am unable to reproduce it.
Can you please try to yum clean all and rerun? if it still fails, 
please provide the output for:
# curl -I -v http://installrepo.kaltura.org/releases/

Thanks,

May the source be with you,

Jess Portnoy

Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
connect.kaltura.com

**Comment by ivanxx** [comment]
Hi Jess,

it's working again now!
Looks like some downtime on the CDN. I even tried to access from different countries (I'm installing from Spain over a server in France) with same results, hence the posting of the issue. But now it's working OK and I've just installed the missing packages (kaltura-front among them, go figure!)

Thanks a lot for the prompt response!

-Iván.

**Comment by KalturaCommunity** [comment]
Great, Ivan. Indeed the quirks of CDN:) Thanks for the update.


May the source be with you,

Jess Portnoy



-------- Original message --------
