### ISSUE TITLE
How can I install Kaltura CE on Ubuntu?

### ISSUE THREAD

**Issue by onurgu** [kaltura/platform-install-packages#377]
The title says it all. I saw question tag so thought it was OK to ask here.

**Comment by jessp01** [comment]
Hello,

Its actually work in progress at the moment. There are a few issues to resolve, one being the Sphinx crashing on 14.04 and another is some specific issues with our API and PHP 5_5 which is what the LTS for Ubuntu has in its repos. I am closing this issue but can ping you when it is released.
For now, you can install on RHEL/CentOS 6/7.

**Comment by jessp01** [comment]
Hello,

As promised, an initial version is ready for inspection:)
Note that this is an early beta and should not be installed on Prod. machines.
To install, follow:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.9.0/doc/install-kaltura-deb-based.md

Bug reports are welcomed, naturally.
