### ISSUE TITLE
SSL installation symlinks to zzzkaltura.conf after completion of base-config

### ISSUE THREAD

**Issue by acheckley** [kaltura/platform-install-packages#378]
Hi Everyone, 

I'm running the SSL installation after returning from my Easter holiday. The last changes to the double port work brilliantly but now I am encountering an error on a fresh SSL installation.

After the base-config has completed successfully, apache fails to restart due to a configuration error:

base-config completed successfully, if you ever want to re-configure your system (e.g. change DB hostname) run the following script:
# rm /opt/kaltura/app/base-config.lock
# /opt/kaltura/bin/kaltura-base-config.sh

Reloading httpd: not reloading due to configuration syntax error

The last part of the installation script is symlinking to the non ssl apache configuration file zzzkaltura.conf containing empty @variables@.

I'm going to investigate. I suspect I know why this is happening.

**Comment by acheckley** [comment]
I'm going to start by checking:

Line 79 
ln -sf $APP_DIR/configurations/apache/kaltura.conf /etc/httpd/conf.d/zzzkaltura.conf

**Comment by acheckley** [comment]
Commenting out line 79 has solved the apache problem for me via SSL. I think there needs to be an if condition. 

If not SSL then ln -sf $APP_DIR/configurations/apache/kaltura.conf /etc/httpd/conf.d/zzzkaltura.conf otherwise do nothing.

However, this could be because I'm following the installation instructions from the read me where I change "Vhost port to listen on [80]: 443".

**Comment by acheckley** [comment]
After a successful installation, I obtain the:

--------------------------
An error occurred

(error code: API:-1)
--------------------------

when logging into:
http://mediaserver.co.uk/admin_console/index.php/user/login

running the kaltura-sanity.sh check passes up until:

PHP Warning:  file_get_contents(https://mediaserver.ac.uk:443/kmc): failed to open stream: Connection refused in /opt/kaltura/bin/get_kmc_swfs.php on line 9
[Get KMC SWFs] [FAILED, RC: 255] - [.164249444]
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
[check_testme_page] [FAILED, RC: 1] - [.016340358]
[check_kmc_index_page] [FAILED, RC: 1] - [.008974517]
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
[check_admin_console_index_page] [FAILED, RC: 1] - [.015705345]
[check_studio_index_page] [FAILED, RC: 1] - [.462074817]
[check_clipapp_index_page] [FAILED, RC: 1] - [.506988951]
[Create Partner] [FAILED, RC: 255] - [.140009449]
Partner creation failed. I will skip all tests that require it.

Nano /opt/kaltura/bin/get_kmc_swfs.php

Line 9

$kmcHtmlContent = file_get_contents($kmcUrl);

In context:

$kmcUrl = $clientConfig->serviceUrl . 'kmc';
$kmcHtmlContent = file_get_contents($kmcUrl);
if(!$kmcHtmlContent)
{
        echo "Fetching URL [$kmcUrl] failed\n";
        exit(-1);
}

I'm going to check the value contained in $kmcUrl. I cannot access over https:// after this full installation so it maybe something else resulting from a quite installation and setup in my Virtual box. If it is a new error, I'll start a new bug post.

**Comment by jessp01** [comment]
Hi,

Can you please provide the full answer file generated? it will be under /tmp/kaltura_.ans
mask passwords and sensitive data beforehand of course:)

**Comment by acheckley** [comment]
TIME_ZONE="Europe/London"
KALTURA_FULL_VIRTUAL_HOST_NAME="mediaserver.ac.uk:443"
KALTURA_VIRTUAL_HOST_NAME="mediaserver.ac.uk"
DB1_HOST="127.0.0.1"
DB1_PORT="3306"
DB1_PASS="password"
DB1_NAME="kaltura"
DB1_USER="kaltura"
SERVICE_URL="https://mediaserver.ac.uk:443"
SPHINX_SERVER1="127.0.0.1"
SPHINX_SERVER2=" "
DWH_HOST="127.0.0.1"
DWH_PORT="3306"
SPHINX_DB_HOST="127.0.0.1"
SPHINX_DB_PORT="3306"
ADMIN_CONSOLE_ADMIN_MAIL="andrew@email.ac.uk"
ADMIN_CONSOLE_PASSWORD="password"
CDN_HOST="mediaserver.ac.uk"
KALTURA_VIRTUAL_HOST_PORT="443"
SUPER_USER="root"
SUPER_USER_PASSWD="password"
ENVIRONMENT_NAME="Kaltura Video Platform"
DWH_PASS="password"
PROTOCOL="https"
RED5_HOST="mediaserver.ac.uk"
USER_CONSENT="0"
CONTACT_MAIL="NO"
VOD_PACKAGER_HOST="mediaserver.ac.uk"
VOD_PACKAGER_PORT="88"
IP_RANGE="0.0.0.0-255.255.255.255"



CONFIG_CHOICE="0"
IS_SSL="y"
CRT_FILE="/etc/ssl/certs/server.crt"
KEY_FILE="/etc/pki/tls/private/server.key"
CHAIN_FILE="NO_CHAIN"
CA_FILE="NO_CA"

**Comment by jessp01** [comment]
Hello,

Your config seems perfectly fine. What version is this?

**Comment by acheckley** [comment]
Hi Jess,

I'm working on 10.7 at the moment.

**Comment by jessp01** [comment]
That might explain it. Please upgrade to 10.8.0.
I believe it was your bug report that made me make changes:)

May the source be with you,

Jess Portnoy

Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
connect.kaltura.com

**Comment by acheckley** [comment]
Thanks, I'll give that a go. I had a few other problems with 10.8 so rolled back to 10.7. I'm more familiar with the Kaltura code now though so may have better luck.

**Comment by jessp01** [comment]
Great. Please let me know if you have any issues and open a new bug report 
if you do. I am closing this one for now.

May the source be with you,

Jess Portnoy

Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
connect.kaltura.com
