### ISSUE TITLE
Admin Console not working after update 10.6 to 10.8

### ISSUE THREAD

**Issue by eemirtekin** [kaltura/platform-install-packages#379]
Hello All,

I updated kaltura, but there are some problems,
I can't login admin console blank screen.

PHP Fatal error:  Call to undefined method KalturaClient::setPartnerId() in /opt/kaltura/app/batch/batches/KBatchBase.class.php on line 258

My allkaltlog below
http://kaltura.yasar.edu.tr/start/kaltura.log
Thanks in advance.

**Comment by jessp01** [comment]
Hi,

Looks as though you did not run the kaltura-config-all.sh script post upgrading.
Please do so and if you still have issues post at forum.kaltura.org

**Comment by nzimas** [comment]
Hi Jess,

I have actually ran kaltura-config-all.sh twice and still get the error.

==> /opt/kaltura/log/batch/validatelivemediaservers-0-2015-04-28.err.log <==
PHP Fatal error:  Call to undefined method KalturaClient::setPartnerId() in /opt/kaltura/app/batch/batches/KBatchBase.class.php on line 258
PHP Fatal error:  Call to undefined method KalturaClient::setPartnerId() in /opt/kaltura/app/batch/batches/KBatchBase.class.php on line 258
PHP Fatal error:  Call to undefined method KalturaClient::setPartnerId() in /opt/kaltura/app/batch/batches/KBatchBase.class.php on line 258
PHP Fatal error:  Call to undefined method KalturaClient::setPartnerId() in /opt/kaltura/app/batch/batches/KBatchBase.class.php on line 258
PHP Fatal error:  Call to undefined method KalturaClient::setPartnerId() in /opt/kaltura/app/batch/batches/KBatchBase.class.php on line 258
PHP Fatal error:  Call to undefined method KalturaClient::setPartnerId() in /opt/kaltura/app/batch/batches/KBatchBase.class.php on line 258
PHP Fatal error:  Call to undefined method KalturaClient::setPartnerId() in /opt/kaltura/app/batch/batches/KBatchBase.class.php on line 258
PHP Fatal error:  Call to undefined method KalturaClient::setPartnerId() in /opt/kaltura/app/batch/batches/KBatchBase.class.php on line 258
PHP Fatal error:  Call to undefined method KalturaClient::setPartnerId() in /opt/kaltura/app/batch/batches/KBatchBase.class.php on line 258
PHP Fatal error:  Call to undefined method KalturaClient::setPartnerId() in /opt/kaltura/app/batch/batches/KBatchBase.class.php on line 258

**Comment by tan-tan-kanarek** [comment]
You'll have to regenerate the admin console client library.
#cd @APP_DIR@
#php generator/generate.php php5ZendClientAdminConsole
