### ISSUE TITLE
SSL @KALTURA_FULL_VIRTUAL_HOST_NAME@ not populated in enabled.kaltura.conf

### ISSUE THREAD

**Issue by acheckley** [kaltura/platform-install-packages#380]
Hi Everyone,

I noticed that @KALTURA_FULL_VIRTUAL_HOST_NAME@ was not being populated in 

opt/kaltura/app/configurations/apache/conf.d/enabled.kaltura.conf

Line 62

I'll re-run the installer and check to see if I have the same issue again.

**Comment by jessp01** [comment]
See https://github.com/kaltura/platform-install-packages/issues/406
