### ISSUE TITLE
Gaps in documentation / functionality

### ISSUE THREAD

**Issue by nukepuppy** [kaltura/platform-install-packages#382]
short list of a few big(ish?) issues
if you're looking to distribute the installation over various role specific nodes

---issue1---  DWH wont install on amazon RDS (really if we dont want to manage a mysql cluster the package shouldn't force us to do so) Requires SUPER for specific stored procedures it seems.  ( not sure if my solution is viable but I removed all the `DEFINER` values... there were maybe 5 places that needed this done....  I DONT KNOW if this is viable or if it will even work properly doing this.. (i dont even know why we need a dedicated db for analytics in the end)
similar to this:
```
-CREATE DEFINER=`etl`@`localhost` PROCEDURE `calc_updated_batch_job`(p_start_date INT(11), p_end_date INT(11))
+CREATE PROCEDURE `calc_updated_batch_job`(p_start_date INT(11), p_end_date INT(11))
```

---issue2--- VOD packager using chef - if you make a standalone 'vod' server as the run list/recipe order the document suggests.. you don't have ANY thing in /opt/kaltura/  after installing 'kaltura-nginx'    which means you cannot complete the installation at all  ( solution for this was: yum install kaltura-postinst - this should be in the recipe/ cookbooks / docs)

---issue3---. lastly.. the chef cookbooks don't seem to care if you have more than 1 SPHINX server
because even though there are attributes for it:
```
default[:kaltura][:SPHINX_SERVER1] = "#{node['fqdn']}"
default[:kaltura][:SPHINX_SERVER2] = "#{node['fqdn']}"
```
the template for the answer file is always writing nothing statically
```
SPHINX_SERVER2=" "
```
SOLUTION (MAYBE): I dont want to fork the entire project for this but if it was using berkshelf and one repository for cookbook it would be a bit easier to submit a fix.. but the fix is in templates/default/kaltura.ans.erb  ...  though i don't know what will then READ that answer file and 'do something' with the sphinx_server2 value if at all?
```
SPHINX_SERVER1="<%= node[:kaltura][:SPHINX_SERVER1]%>"
SPHINX_SERVER2=""<%= node[:kaltura][:SPHINX_SERVER2]%> "
```

seems like there is a lot of gaps in functionality and in the documentation

**Comment by jessp01** [comment]
Hi @nukepuppy,

I would very much appreciate it if you do fork and make a pull request. It shouldn't take too long to fork and this way, I can attribute credit to you.

As far as analytics, I will let the relevant devs know and as for kaltura-nginx, I just fixed it by declaring a dep on kaltura-postinst in the RPM spec, thank you for reporting that.
You can install kaltura-nginx-1.6.2-10.x86_64.rpm, which also includes a new tag of the vod-nginx-module.

**Comment by nukepuppy** [comment]
I know this is now closed... Any ideas about the DWH on RDS(mysql) from amazon? since SUPER privileges aren't allowed..  is there anyone who can speak to whether dropping the DEFINER=`etl`@`localhost`  values are viable for prod?
