### ISSUE TITLE
Ssl Offloading and mixed https content 

### ISSUE THREAD

**Issue by fxpz** [kaltura/platform-install-packages#383]
Hi,

I've configured my KalturaCE in a single machine with external mysql and SSL Offloading on load balancer.
I ran:
- kaltura-base-config with ssl confguration and 443 port
- kaltura-front-config setting http_port on 80

Everthings seems ok.

When I try to login to kmc console, lib/js/jquery-1.8.3.min.js and lib/js/swfobject_v2.2.js are loaded through http and not https, so the browser block this requests and I see the "flash not instaleld" error.
I seen that in the app code, to retrieve protol, php variable $_SERVER['HTTPS'] is used but with ssl offloading this variable is not set.

I used this workaround:

created /etc/php.d/zz-kaltura-ssl.ini
`auto_prepend_file='/opt/kaltura/ssl.php'`

in /opt/kaltura/ssl.php
`<?php
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && ($_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https')) {
        $_SERVER['HTTPS']='on';
}
?>`

It works fine, but, is there any other solution insted of this workaround?

**Comment by DBezemer** [comment]
Add the following line to kaltura.conf (apache file, above the Include line)

```
SetEnvIf X-Forwarded-Proto https HTTPS=on
```

**Comment by jessp01** [comment]
Hi David,

Please pull on the server/configurations/apache repo.
We take it from there.

May the source be with you,

Jess Portnoy

Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
connect.kaltura.com

**Comment by fxpz** [comment]
Thanks a lot, it works fine!
