### ISSUE TITLE
videos not playing after upgrading to 10.8 / player not loading

### ISSUE THREAD

**Issue by nzimas** [kaltura/platform-install-packages#387]
All clips we had published under the 9.x series stopped working under 10.8.
The clips load fine in the KMC's thumbnail generator, however.

Furthermore, the preview and embed window is not showing the player either.

kaltura_api_v3.log does not offer any debugging clues at all.

**Comment by nzimas** [comment]
Looks like I've stumbled upon a possible culprit.

==> /opt/kaltura/log/kaltura_apache_errors.log <==
[Mon Apr 27 15:09:12 2015] [error] [client 37.187.150.22] PHP Warning:  file_get_contents(/opt/kaltura/web//flash/kdp3wrapper/v34.0/kdp3wrapper.swf): failed to open stream: No such file or directory in /opt/kaltura/app/alpha/apps/kaltura/modules/extwidget/actions/kwidgetAction.class.php on line 329, referer: http://www.rapidtvnews.com/rtvn-videos.html?tmpl=component&view=video&videoid=63


How can this be remedied?

**Comment by nzimas** [comment]
And some more informative verbose that is thrown when accessing the standalone player.

==> /opt/kaltura/log/kaltura_apache_errors.log <==
[Mon Apr 27 15:15:09 2015] [error] [client 37.187.150.22] Cannot find [html5lib_host] in config, referer: http://streamer.eurotvguild.com/index.php/extwidget/preview/partner_id/101/uiconf_id/11601473/entry_id/0_3g601dxz/embed/auto?

**Comment by jessp01** [comment]
Did you run kaltura-config-all.sh, post upgrade?

If not, please run it. It should set it in 
/opt/kaltura/app/configurations/local.ini

May the source be with you,

Jess Portnoy

Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
connect.kaltura.com

**Comment by nzimas** [comment]
Won't it mess up my current settings?
Will it preserve data?

**Comment by jessp01** [comment]
Yes, that is the normal upgrade proc:
https://github.com/kaltura/platform-install-packages/blob/master/doc/install-kaltura-redhat-based.md#upgrade-kaltura

May the source be with you,

Jess Portnoy

Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
connect.kaltura.com

**Comment by nzimas** [comment]
Thanks for the prompt reply. 
Your suggestions solved the issue.
