### ISSUE TITLE
several post upgrade errors

### ISSUE THREAD

**Issue by nzimas** [kaltura/platform-install-packages#388]
1. The Kaltura Admin Console is not accessible and a blank page is shown instead (nothing com)

2015-04-28 11:02:09 [192193414] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [EventNotificationTemplateUpdateStatusActi
on] requires permissions [Array
(
    [0] => eventNotification.SYSTEM_ADMIN_EVENT_NOTIFICATION_MODIFY
)
]' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:
#0 /opt/kaltura/app/ui_infra/InfraBootstrapper.php(113): KalturaLog::err('Class [EventNot...')
#1 /opt/kaltura/app/vendor/ZendFramework/library/Zend/Application/Bootstrap/BootstrapAbstract.php(662): InfraBootstrapper->_initNavigation()
#2 /opt/kaltura/app/vendor/ZendFramework/library/Zend/Application/Bootstrap/BootstrapAbstract.php(615): Zend_Application_Bootstrap_BootstrapAbstract->_executeResource('navigation')
#3 /opt/kaltura/app/vendor/ZendFramework/library/Zend/Application/Bootstrap/BootstrapAbstract.php(579): Zend_Application_Bootstrap_BootstrapAbstract->_bootstr
#4 /opt/kaltura/app/vendor/ZendFramework/library/Zend/Application.php(347): Zend_Application_Bootstrap_BootstrapAbstract->bootstrap(NULL)
#5 /opt/kaltura/app/admin_console/web/index.php(37): Zend_Application->bootstrap()
#6 {main}
2015-04-28 11:02:09 [192193414] [Infra_TranslateAdapter->_loadTranslationData] DEBUG: locale [en]
2015-04-28 11:02:09 [192193414] [Infra_TranslateAdapter->_loadTranslationData] DEBUG: locale [he]

2. Videos are not being processed

==> /opt/kaltura/log/batch/distributeupdatecloser-0-2015-04-28.err.log <==
PHP Fatal error:  Call to undefined method KalturaClient::setPartnerId() in /opt/kaltura/app/batch/batches/KBatchBase.class.php on line 258

**Comment by nzimas** [comment]
Just to clarify, error 1 happens upon logging in. That is to say, right after the login screen.

**Comment by nzimas** [comment]
Error 1 has disappeared after running kaltura-config-all.sh for a second time-
Error 2 persists, however.

==> /opt/kaltura/log/batch/validatelivemediaservers-0-2015-04-28.err.log <==
PHP Fatal error:  Call to undefined method KalturaClient::setPartnerId() in /opt/kaltura/app/batch/batches/KBatchBase.class.php on line 258
PHP Fatal error:  Call to undefined method KalturaClient::setPartnerId() in /opt/kaltura/app/batch/batches/KBatchBase.class.php on line 258
PHP Fatal error:  Call to undefined method KalturaClient::setPartnerId() in /opt/kaltura/app/batch/batches/KBatchBase.class.php on line 258
PHP Fatal error:  Call to undefined method KalturaClient::setPartnerId() in /opt/kaltura/app/batch/batches/KBatchBase.class.php on line 258
PHP Fatal error:  Call to undefined method KalturaClient::setPartnerId() in /opt/kaltura/app/batch/batches/KBatchBase.class.php on line 258
PHP Fatal error:  Call to undefined method KalturaClient::setPartnerId() in /opt/kaltura/app/batch/batches/KBatchBase.class.php on line 258
PHP Fatal error:  Call to undefined method KalturaClient::setPartnerId() in /opt/kaltura/app/batch/batches/KBatchBase.class.php on line 258
PHP Fatal error:  Call to undefined method KalturaClient::setPartnerId() in /opt/kaltura/app/batch/batches/KBatchBase.class.php on line 258
PHP Fatal error:  Call to undefined method KalturaClient::setPartnerId() in /opt/kaltura/app/batch/batches/KBatchBase.class.php on line 258
PHP Fatal error:  Call to undefined method KalturaClient::setPartnerId() in /opt/kaltura/app/batch/batches/KBatchBase.class.php on line 258

**Comment by jessp01** [comment]
try this:
\# /etc/init.d/kaltura-monit stop
\# /etc/init.d/httpd stop
\# rm -fr /opt/kaltura/app/cache/*
\# php /opt/kaltura/app/generator/generate.php
\# /etc/init.d/httpd start
\# /etc/init.d/kaltura-monit start

**Comment by nzimas** [comment]
done that, then re-ran kaltura-config-all.sh.
same result, unfortunately.

if i do not run kaltura-config-all.sh, then the clips won’t play.

Kind of a catch-22 here.

**Comment by jessp01** [comment]
What is the output for rpm -qa "*kaltura*"?
Also, when you stopped apache, did you ensure all children really went 
down?

May the source be with you,

Jess Portnoy

Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
connect.kaltura.com

**Comment by nzimas** [comment]
Apache has been killed and no children left alive to tell the tale :)

Here’s the list of packages kaltura:
kaltura-libfaac-1.26-1.x86_64
kaltura-libmcrypt-2.5.7-5.x86_64
kaltura-sshpass-1.05-1.x86_64
kaltura-fdk-acc-0.1.3-1.x86_64
kaltura-ffmpeg-aux-0.6-2.x86_64
kaltura-kupload-1.0.0-1.noarch
kaltura-kdp3wrapper-v37.0-1.noarch
kaltura-kdp-v2.7.0-1.noarch
kaltura-mencoder-3.4.6-9.x86_64
kaltura-ffmpeg-2.1.3-1.x86_64
kaltura-batch-10.8.0-1.noarch
kaltura-kdp3-v3.9.9-2.noarch
kaltura-release-10.8.0-1.noarch
kaltura-libass-0.9.11-2.x86_64
kaltura-libmemcached-1.0.16-2.x86_64
kaltura-widgets-1.0.0-8.noarch
kaltura-segmenter-1.0-1.x86_64
kaltura-ksr-v1.0.44-1.noarch
kaltura-kvpm-v1.0.6-1.noarch
kaltura-postinst-1.0.25-1.noarch
kaltura-pentaho-4.2.1-1.x86_64
kaltura-base-10.8.0-14.noarch
kaltura-kmc-v5.38.11-1.noarch
kaltura-red5-1.0.4-1.x86_64
kaltura-x264-0.140-2.20140104.x86_64
kaltura-a52dec-0.7.4-11.x86_64
kaltura-libopencore-amr-0.1.2-2.x86_64
kaltura-lame-3.99.5-3.x86_64
kaltura-kclip-v1.1.2.1-2.noarch
kaltura-kdpwrapper-v11.0-1.noarch
kaltura-flexwrapper-v1.2-1.noarch
kaltura-server-10.8.0-1.noarch
kaltura-dwh-9.4.0-2.noarch
kaltura-libmcrypt-devel-2.5.7-5.x86_64
kaltura-monit-5.6-15.x86_64
kaltura-librtmp-2.3-2.x86_64
kaltura-krecord-1.0.0-1.noarch
kaltura-sphinx-2.2.1-16.x86_64
kaltura-kcw-1.0.0-6.noarch
kaltura-html5-studio-v1.9.6-1.noarch
kaltura-html5lib-v2.29-1.noarch
kaltura-nginx-1.6.2-6.x86_64
kaltura-front-10.8.0-1.noarch
kaltura-clipapp-1.3-2.noarch


--
Nuno Zimas
Systems Administrator & Web Developer
T:  +44 (0) 20 3575 1337

**Comment by nzimas** [comment]
I have reinstalled all the Kaltura RPMs and now get a different error message when the CSV file is uploaded:

None of the uploaded items were processed succsessfuly.

2015-04-28 19:35:23 [1064704938] [KJobHandlerWorker->closeJob] ERR: exception 'Exception' with message 'Error: None of the uploaded items were processed succsessfuly' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:
#0 /opt/kaltura/app/batch/batches/KJobHandlerWorker.class.php(366): KalturaLog::err('Error: None of ...')

**Comment by nzimas** [comment]
And immediately before the door reported in the above comment, this comes up kaltlog:

PHP Fatal error:  Uncaught exception 'KalturaClientException' with message 'Empty reply from server' in /opt/kaltura/app/batch/client/KalturaClientBase.php:362
Stack trace:
#0 /opt/kaltura/app/batch/client/KalturaClient.php(4172): KalturaClientBase->doQueue()
--
            [tmp_name] => /opt/kaltura/web/tmp/php5eS9Ry
            [error] => 0
            [size] => 337
--
            [tmp_name] => /opt/kaltura/web/tmp/php5eS9Ry
            [error] => 0
            [size] => 337

It must be noted that 

PHP Fatal error:  Call to undefined method KalturaClient::setPartnerId() in /opt/kaltura/app/batch/batches/KBatchBase.class.php on line 258

still happens.

**Comment by tan-tan-kanarek** [comment]
You'll have to generate the batch client library as well.

**Comment by nzimas** [comment]
What should go after
php generator/generate.php?

**Comment by tan-tan-kanarek** [comment]
Run it with no params, it will generate all needed libs.

T.

Sent with AquaMail for Android
http://www.aqua-mail.com

On April 28, 2015 11:29:09 PM nzimas <notifications@github.com> wrote:

What should go after
php generator/generate.php?

> On 28 Apr 2015, at 17:22, Tan-Tan <notifications@github.com> wrote:
>
> You'll have to generate the batch client library as well.
>
> -
> Reply to this email directly or view it on GitHub <https://github.com/kaltura/platform-install-packages/issues/388#issuecomment-97197120>.
>


-

**Comment by nzimas** [comment]
Same result.

Besides the recommendations in this thread, I have already ran kaltura-config-all.sh about a dozen times and reinstalled all Kaltura packages to no avail.

**Comment by nzimas** [comment]
This showstopper is all the most disturbing if one takes into account that everything worked normally yesterday, right after upgrading Kaltura.

**Comment by jessp01** [comment]
Closing. Please upgrade to latest and submit an issue should you have any problems.
