### ISSUE TITLE
Ubuntu update error, after adding Kaltura Repository, due to no i386 build

### ISSUE THREAD

**Issue by rohithmeethal** [kaltura/platform-install-packages#389]
Installation script will fail at update process by giving this error 

W: Failed to fetch http://installrepo.kaltura.org/repo/apt/debian/dists/jupiter/InRelease  Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)

After bit of searching I found the issue due to the fact that there is no i386 build in your repo making ubuntu update to throw warning and exit.

to fix this you need explicitly mention only 64 bit build is available like this 

deb [arch=amd64] http://installrepo.kaltura.org/repo/apt/debian jupiter main

**Comment by jessp01** [comment]
Fair point and thank you for reporting. I will update the script and doc accordingly.
Please note that this is not an error, just a warning though:)

**Comment by rohithmeethal** [comment]
Cool, thank you :)
