### ISSUE TITLE
please add a vagrant box for easy development

### ISSUE THREAD

**Issue by rohithmeethal** [kaltura/platform-install-packages#390]
No matter how much I try, something goes wrong at the end for setting up kaltura on debian, considering total amount of time I have spent already, a fully working version of Kaltura Ubuntu vagrant box will be a blessing, I would have done it myself, but I am still long way from getting it done, since my installation kmc wont work throwing some php errors, regarding ui conf. If any one have a working vagrant box setup, my life would be a lot easier :) . I am writing this after 2 days of installation pain.

**Comment by jessp01** [comment]
Hello,

Since we release a new version every other week, creating a ready made one is less sensible. That said, I will be happy to help you with the install and, if needed, fix bugs you came across. Please start a thread on forum.kaltura.org so we can discuss and advance.

Thanks,
