### ISSUE TITLE
kaltura-ffmpeg.spec violates the gpl

### ISSUE THREAD

**Issue by kierank** [kaltura/platform-install-packages#392]
--enable-nonfree clearly makes the build not gpl any more...

**Comment by jessp01** [comment]
Thank you, you are most correct. Will fix it ASAP.

May the source be with you,

Jess Portnoy

Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
connect.kaltura.com

**Comment by jessp01** [comment]
Looking here:
https://www.ffmpeg.org/legal.html

FFmpeg is licensed under the GNU Lesser General Public License (LGPL) 
version 2.1 or later. However, FFmpeg incorporates several optional parts 
and optimizations that are covered by the GNU General Public License (GPL) 
version 2 or later. If those parts get used the GPL applies to all of 
FFmpeg.

So, not quite sure what it should be licensed under when using 
--enable-nonfree, any suggestions?

May the source be with you,

Jess Portnoy

Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
connect.kaltura.com

**Comment by kierank** [comment]
Nonfree is used when you link in a component (e.g fdk-aac) that isn't (L)GPL compatible. This means the resulting binary is not redistributable whatsoever.

**Comment by KalturaCommunity** [comment]
Yes, I realize that. Will consult our legal. Thanks,


May the source be with you,

Jess Portnoy



-------- Original message --------

**Comment by jessp01** [comment]
Just to keep you posted, we are discussing our options from both a tech and legal perspectives on this one. Thank you again for calling our attention to it.

**Comment by kierank** [comment]
So it's been a while and you're still in violation afaik. Do you plan to change this or should I add it to the ffmpeg bugtracker as a violation?

**Comment by jessp01** [comment]
Hello @kierank,

We are in the process of attempting to utilise ffmpeg's internal implementation of AAC, mentioned here:
https://trac.ffmpeg.org/wiki/Encode/HighQualityAudio

That would mean we can eliminate use of FDK_AAC and libfaac and therefore will no longer require the nonfree compilation flag.

I will keep you posted shortly.

Once again, thank you for bringing this to our attention,

**Comment by kierank** [comment]
Thanks - on discussion with other FFmpeg developers this discussion should be tracked at https://trac.ffmpeg.org/ticket/4735
