### ISSUE TITLE
Can´t Configure Red5 Server - could not find kaltura-functions.rc

### ISSUE THREAD

**Issue by Senger** [kaltura/platform-install-packages#393]
After proceed with guide "Installing Kaltura on a Single Server (deb)" in an Ubuntu 14.04 64bits, I can´t Configure Red5 server:

root@zjxugymiv5:/home# aptitude install kaltura-red5
The following partially installed packages will be configured:
  kaltura-red5
No packages will be installed, upgraded, or removed.
0 packages upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B of archives. After unpacking 0 B will be used.
Setting up kaltura-red5 (1.0.0-1) ...
ERROR:could not find /var/lib/dpkg/info/kaltura-functions.rc so, exiting..dpkg: error processing package kaltura-red5 (--configure):
 subprocess installed post-installation script returned error exit status 3
Errors were encountered while processing:
 kaltura-red5
E: Sub-process /usr/bin/dpkg returned an error code (1)
A package failed to install.  Trying to recover:
Setting up kaltura-red5 (1.0.0-1) ...
ERROR:could not find /var/lib/dpkg/info/kaltura-functions.rc so, exiting..dpkg: error processing package kaltura-red5 (--configure):
 subprocess installed post-installation script returned error exit status 3
Errors were encountered while processing:
 kaltura-red5

Any Idea? Tks!

**Comment by jessp01** [comment]
Fixed. Please upgrade to 1.0.0-1+b2
