### ISSUE TITLE
It seems rpm file doesn't exist

### ISSUE THREAD

**Issue by nalekberov** [kaltura/platform-install-packages#397]
Hi,

I have tried to install

rpm -ihv http://installrepo.kaltura.org/releases/kaltura-release.noarch.rpm

but seems there is no rpm file.

**Comment by jessp01** [comment]
It works correctly for me.
What is the output in your case?

$ curl -I -v http://installrepo.kaltura.org/releases/kaltura-release.noarch.rpm
* Hostname was NOT found in DNS cache
*   Trying 38.74.192.73...
* Connected to installrepo.kaltura.org (38.74.192.73) port 80 (#0)
> HEAD /releases/kaltura-release.noarch.rpm HTTP/1.1
> User-Agent: curl/7.35.0
> Host: installrepo.kaltura.org
> Accept: */*
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Date: Tue, 19 May 2015 12:57:26 GMT
Date: Tue, 19 May 2015 12:57:26 GMT
* Server Apache/2.2.15 (CentOS) is not blacklisted
< Server: Apache/2.2.15 (CentOS)
Server: Apache/2.2.15 (CentOS)
< Last-Modified: Mon, 04 May 2015 23:00:27 GMT
Last-Modified: Mon, 04 May 2015 23:00:27 GMT
< ETag: "3a02da-1a34-51549872151a1"
ETag: "3a02da-1a34-51549872151a1"
< Accept-Ranges: bytes
Accept-Ranges: bytes
< Content-Length: 6708
Content-Length: 6708
< Connection: close
Connection: close
< Content-Type: application/x-rpm
Content-Type: application/x-rpm

< 
* Closing connection 0

**Comment by nalekberov** [comment]
Yes, now it works.
