### ISSUE TITLE
kaltura-red5 dependency issues

### ISSUE THREAD

**Issue by kuya1284** [kaltura/platform-install-packages#402]
While trying to install kaltura-red5, aptitude is reporting the following.  I'm not sure how to proceed because it looks like kaltura-red5 is trying to install *tomcat6*, but *mina2* apparently depends on *tomcat7*.  I'm trying to install this on Ubuntu Server 14.04.2 64-bit.

> The following packages have unmet dependencies:
>  libtomcat7-java : Conflicts: libtomcat6-java but 6.0.39-1 is to be installed.
> The following actions will resolve these dependencies:
> 
>    Remove the following packages:
> 1)     libtomcat7-java
> 
>    Leave the following dependencies unresolved:
> 2)     libmina2-java recommends libtomcat7-java

Thanks in advance for your help.

**Comment by kuya1284** [comment]
After I proceed with and finish installing kaltura-red5, it appeared that everything went through smoothly. However, when I check the status:

> service red5-server status

it appears to have failed

> * Checking status of Flash streaming server red5-server [fail]

I suspect this could be due to the dependency issue requiring tomcat7. When I try to install *libtomcat7-java*, aptitude reports back the following:

> The following NEW packages will be installed:
>   libtomcat7-java{b}
> 0 packages upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
> Need to get 0 B/3,649 kB of archives. After unpacking 4,269 kB will be used.
> The following packages have unmet dependencies:
>  libtomcat7-java : Conflicts: libtomcat6-java but 6.0.39-1 is installed.
> The following actions will resolve these dependencies:
> 
>      Remove the following packages:
> 1)     kaltura-red5
> 2)     libtomcat6-java
> 3)     red5-server
> 
>      Leave the following dependencies unresolved:
> 4)     libspring-context-java recommends libtomcat6-java

I'm guessing that this is a Red5 issue and that I should be opening a ticket with them. Is this a correct assumption? If so, my apologies.

**Comment by jessp01** [comment]
Hello,

No need to apologize:) but indeed, the red5-server package is maintained by the distro and not by us and so, you should indeed report to the package maintainer.

Note that Kaltura can function properly without Red5, however, you will not be able to use the cam recording functionality.

Thanks,

**Comment by kuya1284** [comment]
Thanks very much. :)
