### ISSUE TITLE
/opt/kaltura/bin/kaltura-config-all.sh fails @ populating DB

### ISSUE THREAD

**Issue by strumpfonja** [kaltura/platform-install-packages#405]
Heya,
I am having issue with reinstalling kaltura on Centos 7 (worked fine before upgrade).
after upgrade I couldn't login into KAC, so i went to reinstall kaltura (currently I am using it for testing purposes so no big deal for some small data loss)
I am following instructions from https://github.com/kaltura/platform-install-packages/blob/master/doc/install-kaltura-redhat-based.md#ssl-step-by-step-installation

i removed kaltura, and started new install, when i run /opt/kaltura/bin/kaltura-config-all.sh I get error, here is the log:
***
Configuring your Kaltura DB...
Checking MySQL version..
Ver 5.5.41-MariaDB found compatible

CREATE USER kaltura;
CREATE USER etl;
CREATE DATABASE kaltura;
CREATE DATABASE kaltura_sphinx_log;
CREATE DATABASE kalturadw;
CREATE DATABASE kalturadw_ds;
CREATE DATABASE kalturadw_bisources;
CREATE DATABASE kalturalog;
Checking connectivity to needed daemons...
Connectivity test passed:)
Cleaning cache..
Populating DB with data.. please wait..
Output for /opt/kaltura/app/deployment/base/scripts/installPlugins.php being logged into /opt/kaltura/log/installPlugins.log
Output for /opt/kaltura/app/deployment/base/scripts/insertDefaults.php being logged into /opt/kaltura/log/insertDefaults.log

                Archving logs to /opt/kaltura/log/log_25_05_15_09_37.tar.gz...
ERROR: we failed on something else..

/opt/kaltura/log/insertDefaults.log says:

PHP Fatal error:  Call-time pass-by-reference has been removed in /opt/kaltura/app/plugins/metadata/lib/kMetadataManager.php on line 555

if i rerun /opt/kaltura/bin/kaltura-config-all.sh, it finishes without error, but i can login to KAC, and sanity test fails at user creation.

can some1 help me with this error ?

**Comment by jessp01** [comment]
Hello,

Issue is resolved here:
https://github.com/kaltura/server/pull/2574

I backported it to the 10.11.0 branch and you can update kaltura-base to 
kaltura-base-10.11.0-8 and then use kaltura-drop-db.sh and rerun the 
config script.

Thanks,

May the source be with you,

Jess Portnoy

Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
connect.kaltura.com

**Comment by strumpfonja** [comment]
thanks jessp01 for a quick response, 

after  updating an reruning config script i get flowing error: 

Redirecting to /bin/systemctl restart  httpd.service
Note: Forwarding request to 'systemctl enable httpd.service'.
Restarting kaltura-monit (via systemctl):                  [  OK  ]
Running Sphinx config...


kaltura-sphinx-2.2.1-16.x86_64
base-config completed successfully, if you ever want to re-configure your system (e.g. change DB hostname) run the following script:
# rm /opt/kaltura/app/base-config.lock
# /opt/kaltura/bin/kaltura-base-config.sh


searchd (pid 10416 10415) is running...
Stopping searchd: Sphinx 2.2.1-id64-dev (r4097)
Copyright (c) 2001-2013, Andrew Aksyonoff
Copyright (c) 2008-2013, Sphinx Technologies Inc (http://sphinxsearch.com)

using config file '/opt/kaltura/app/configurations/sphinx/kaltura.conf'...
stop: successfully sent SIGTERM to pid 10416

Backing up files to /opt/kaltura/sphinx.bck.1432543989. Once the upgrade is done and tested, please remove this directory to save space
Starting searchd: Sphinx 2.2.1-id64-dev (r4097)
Copyright (c) 2001-2013, Andrew Aksyonoff
Copyright (c) 2008-2013, Sphinx Technologies Inc (http://sphinxsearch.com)

using config file '/opt/kaltura/app/configurations/sphinx/kaltura.conf'...
listening on all interfaces, port=9312
WARNING: index 'kaltura_base': no fields configured (use rt_field directive) - NOT SERVING
WARNING: index 'kaltura_kuser_base': no fields configured (use rt_field directive) - NOT SERVING
precaching index 'kaltura_entry'
precaching index 'kaltura_category'
precaching index 'kaltura_kuser'
precaching index 'kaltura_category_kuser'
precaching index 'kaltura_cue_point'
precaching index 'kaltura_entry_distribution'
precaching index 'kaltura_caption_item'
precaching index 'kaltura_tag'
precaching index 'kaltura_metadata'
precached 9 indexes in 0.028 sec

PHP Fatal error:  Uncaught exception 'PropelException' with message 'Could not connect to any database server' in /opt/kaltura/app/alpha/apps/kaltura/lib/myDbHelper.class.php:36
Stack trace:
#0 /opt/kaltura/app/deployment/base/scripts/populateSphinxEntries.php(21): myDbHelper::getConnection('propel2')
#1 {main}
  thrown in /opt/kaltura/app/alpha/apps/kaltura/lib/myDbHelper.class.php on line 36
Failed to run /opt/kaltura/app/deployment/base/scripts/populateSphinxEntries.php.
        Please try to run it manually and look at the logs
ERROR: /opt/kaltura/bin/kaltura-sphinx-config.sh failed:( You can re-run it when the issue is fixed.

any idea how to fix this ?

**Comment by jessp01** [comment]
Welcome and thanks for reporting.
Run:
kaltura-drop-db.sh again, then run kaltura-db-config.sh and then re-run 
kaltura-config-all.sh and you should be good to go:)

May the source be with you,

Jess Portnoy

Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
connect.kaltura.com

**Comment by strumpfonja** [comment]
quick info, so far so good, still deploying analytics warehouse db...

**Comment by KalturaCommunity** [comment]
Great, please close the issue.


May the source be with you,

Jess Portnoy



-------- Original message --------

**Comment by strumpfonja** [comment]
Kaltura is configured without errors.
it seems everything  is working fine, but monit reports error

![crop](https://cloud.githubusercontent.com/assets/12005400/7796280/edc0bd18-02dd-11e5-8573-18100658468a.png)

and sanity test results fails at:
Napping 75 seconds to allow the daemon httpd to finish its init after monit restarted it..
[Check httpd daemon is started by Monit] [FAILED, RC: 1] - [77.525053107]

Napping 75 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
[Check kaltura-batch daemon is started by Monit] [FAILED, RC: 1] - [77.295587093]

Napping 75 seconds to allow the daemon memcached to finish its init after monit restarted it..
[Check memcached daemon is started by Monit] [FAILED, RC: 1] - [76.509281853]

[DWH cycle] [FAILED, RC: 255] - [7.152056423]

**Comment by jessp01** [comment]
Try
# killall -9 httpd
# /etc/init.d/httpd start

May the source be with you,

Jess Portnoy

Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
connect.kaltura.com

**Comment by strumpfonja** [comment]
[root@vl-cent7 ~]# killall -9 httpd
[root@vl-cent7 ~]# /etc/init.d/httpd start
-bash: /etc/init.d/httpd: No such file or directory

**Comment by KalturaCommunity** [comment]
Try
# service httpd start

May the source be with you,

Jess Portnoy

Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
connect.kaltura.com

**Comment by strumpfonja** [comment]
[root@vl-cent7 ~]# service httpd status
Redirecting to /bin/systemctl status  httpd.service

monit reports apache is running,

memchace and mysql status is still the same

**Comment by jessp01** [comment]
For MySQL, most probably cause you are using MariaDB and perhaps need to adjust paths under:
/opt/kaltura/app/configurations/monit/monit.d/enabled.mysqld.rc

please take a look and change PID path, executable path, etc, according to your ENV.

For memcached, please check the same in:
/opt/kaltura/app/configurations/monit/monit.d/enabled.mysqld.rc

**Comment by jessp01** [comment]
Closing this one since the original problem is solved. Do let me know if you have additional questions.
And also, if you do end up changing monit configs, since we might want to integrate them.
Thanks,
