### ISSUE TITLE
SLL Installation Error on Centos 6.6

### ISSUE THREAD

**Issue by acheckley** [kaltura/platform-install-packages#406]
Hi Everyone,

After a short break, I've attempted to install Kaltura (latest) via the SSL installer. I've encountered the following error:

Reloading httpd: not reloading due to configuration syntax error
                                                           [FAILED]

		Archving logs to /opt/kaltura/log/log_02_06_15_11_28.tar.gz...
ERROR: /opt/kaltura/bin/kaltura-batch-config.sh failed:( You can re-run it when the issue is fixed.

In preparation for the installation, I have a fully working SSL Apache in order to check my certificate files and to rule this out as a problem.

I'm going to explore.

**Comment by acheckley** [comment]
Okay, I've found the problem:

nano /etc/httpd/conf.d/zzzkaltura.conf


<VirtualHost *:@KALTURA_VIRTUAL_HOST_PORT@>
        ErrorLog "@LOG_DIR@/kaltura_apache_errors.log"
        CustomLog @LOG_DIR@/kaltura_apache_access.log vhost_kalt

        Include "@APP_DIR@/configurations/apache/conf.d/enabled.*.conf"
</VirtualHost>


My paths have not been populated. I will investigate.

**Comment by acheckley** [comment]
I've prepopulated the Kaltura zzzkaltura.conf template (manually filling in the @tokens@)

nano /opt/kaltura/app/configurations/apache/kaltura.conf.template

and the error has been solved. Something isn't working correctly in the SSL installer because it's not pulling through the tokens or overwriting with the template at the end.

**Comment by acheckley** [comment]
This installation has now completed. I can access Kaltura over https:// but am unable to log into the Administrator console:

An error occurred

(error code: API:-1)

and cannot see any content in the Publisher KMC.

I'm going to run the sanity check.

**Comment by acheckley** [comment]
[Create Partner] [FAILED, RC: 255] - [.250818833]
Partner creation failed. I will skip all tests that require it.

**Comment by jessp01** [comment]
Is your certificate in order? what do you see in the Apache error log?

**Comment by acheckley** [comment]
Hi Jess,

It turned out to be the certificate. I'm not sure why but it replaced my server certificate with a self signed certificate in the ssl.conf file.

**Comment by acheckley** [comment]
The good news is that everything is up and running.

It does show that there is a bug in the installation script though (with the tokens not being populated) and the overwriting of the certificate files via the ssl.conf. The ssl.conf is taking priority over the certificate files in the zzzkaltura.ssl.conf file.

**Comment by jessp01** [comment]
Hello,

It prompts for the certificate location. As a default opt, it has the self 
signed one that was auto generated with the mod_ssl package.
Perhaps you just hit enter instead of providing your own?

May the source be with you,

Jess Portnoy

Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
virtualconnect.kaltura.com

**Comment by acheckley** [comment]
Hi Jess, I've tested the installer over a few times over with the same results in the certificate. I'm happy to give it another run but I think it's a bug.

**Comment by jessp01** [comment]
Hello @acheckley,

Is this still an issue or can we close it? Thanks,
