### ISSUE TITLE
sanity check returns few errors

### ISSUE THREAD

**Issue by hsafe** [kaltura/platform-install-packages#407]
Hi there
Following the first failed attempt to get kaltura running, I did a clean install. All went through except had a minor issue on the /etc/hosts with error at the db checking step it read as:
ERROR: Couldn't make an API request to http://red5:80/api_v3/index.php?service=system&action=ping.
Please check your setup and then run /opt/kaltura/bin/kaltura-db-config.sh again.
I fixed the issue and added the name to the hosts file and did a:
/opt/kaltura/bin/kaltura-db-config.sh <mysql-hostname> <mysql-super-user> <mysql-super-user-passwd> <mysql-port> [upgrade]
The db was removed and recreated successfully. Then I did a successful kaltura-red5 install and in the end ran the script:
/opt/kaltura/bin/kaltura-sanity.sh
Here is the return result, primarily complaining regarding the batch and logo animation:

[root@red5 ~]# /opt/kaltura/bin/kaltura-sanity.sh
[Space on /] [PASSED, RC: 0] - [.036062839]
[Space on /opt/kaltura/web] [PASSED, RC: 0] - [.029355478]
[Check httpd daemon status] [PASSED, RC: 0] - [.059326256]
Napping 1 seconds to allow the daemon httpd to finish its init after monit restarted it..
Napping 2 seconds to allow the daemon httpd to finish its init after monit restarted it..
Napping 3 seconds to allow the daemon httpd to finish its init after monit restarted it..
Napping 4 seconds to allow the daemon httpd to finish its init after monit restarted it..
Napping 5 seconds to allow the daemon httpd to finish its init after monit restarted it..
Napping 6 seconds to allow the daemon httpd to finish its init after monit restarted it..
Napping 7 seconds to allow the daemon httpd to finish its init after monit restarted it..
Napping 8 seconds to allow the daemon httpd to finish its init after monit restarted it..
Napping 9 seconds to allow the daemon httpd to finish its init after monit restarted it..
[Check httpd daemon is started by Monit] [PASSED, RC: 0] - [9.540317915]
[check daemon httpd init status] [PASSED, RC: 0] - [.006128202]
[Check kaltura-sphinx daemon status] [PASSED, RC: 0] - [.035539475]
Napping 1 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
Napping 2 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
Napping 3 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
Napping 4 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
Napping 5 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
.
.
.
Napping 75 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
[Check kaltura-batch daemon is started by Monit] [FAILED, RC: 1] - [77.354949421]
[check daemon kaltura-batch init status] [PASSED, RC: 0] - [.005547839]
[Check kaltura-monit daemon status] [PASSED, RC: 0] - [.022372359]
[check daemon kaltura-monit init status] [PASSED, RC: 0] - [.004978547]
[Check memcached daemon status] [PASSED, RC: 0] - [.021500267]
Napping 1 seconds to allow the daemon memcached to finish its init after monit restarted it..
Napping 2 seconds to allow the daemon memcached to finish its init after monit restarted it..
Napping 3 seconds to allow the daemon memcached to finish its init after monit restarted it..
Napping 4 seconds to allow the daemon memcached to finish its init after monit restarted it..
Napping 5 seconds to allow the daemon memcached to finish its init after monit restarted it..
Napping 6 seconds to allow the daemon memcached to finish its init after monit restarted it..
Napping 7 seconds to allow the daemon memcached to finish its init after monit restarted it..
Napping 8 seconds to allow the daemon memcached to finish its init after monit restarted it..
[Check memcached daemon is started by Monit] [PASSED, RC: 0] - [8.367812348]
[check daemon memcached init status] [PASSED, RC: 0] - [.005066742]
[kaltura-html5lib ver in KMC config.ini] [PASSED, RC: 0] - [.085284871]
[kaltura-kdp3 ver in KDP3 config.ini] [PASSED, RC: 0] - [.042173534]
[kaltura-kmc ver in KMC config.ini] [PASSED, RC: 0] - [.047133604]
[Get KMC SWFs] [PASSED, RC: 0] - [1.296648987]
[check_testme_page] [PASSED, RC: 0] - [10.824321654]
[check_kmc_index_page] [PASSED, RC: 0] - [.036169910]
[check_admin_console_index_page] [PASSED, RC: 0] - [.461125035]
[check_studio_index_page] [PASSED, RC: 0] - [.012535182]
[check_clipapp_index_page] [PASSED, RC: 0] - [.472437540]
[Create Partner] [PASSED, RC: 0] - [1.971734783]
[Local dropfolder creation succeeded] [PASSED, RC: 0] - [.348726260]
[Create flavor param] [PASSED, RC: 0] - [.395226183]
[Delete flavor param] [PASSED, RC: 0] - [.181218720]
[Upload content kaltura_logo_animated_blue.flv] [PASSED, RC: 0] - [5.824659951]
Napping 10 seconds to allow entry 0_ta02u0nv to digest.. 
Napping 10 seconds to allow entry 0_ta02u0nv to digest.. 
Napping 10 seconds to allow entry 0_ta02u0nv to digest.. 
Napping 10 seconds to allow entry 0_ta02u0nv to digest.. 
Napping 10 seconds to allow entry 0_ta02u0nv to digest.. 
Napping 10 seconds to allow entry 0_ta02u0nv to digest.. 
Napping 10 seconds to allow entry 0_ta02u0nv to digest.. 
Napping 10 seconds to allow entry 0_ta02u0nv to digest.. 
Napping 10 seconds to allow entry 0_ta02u0nv to digest.. 
[kaltura_logo_animated_blue.flv - 0_ta02u0nv status] [FAILED, RC: 1] - [-.468045453]
Napping 30 seconds to allow mail to be sent out.. 
[Found an email sending entry for mb-red5@kaltura.com[PID is 101] in /var/log/maillog] [PASSED, RC: 0] - [30.048072711]
Testing analytics, be patient..

Please note: if you are running this test on a clustered ENV, it will fail but this does not mean there is an actual problem.
The tech information as to why is available here: 
https://github.com/kaltura/platform-install-packages/issues/106#issuecomment-42837404

[DWH cycle] [FAILED, RC: 255] - [.496481675]
[Upload content kaltura_logo_animated_green.flv] [PASSED, RC: 0] - [.530314344]
[Upload bulk using CSV] [PASSED, RC: 0] - [.328237351]
[Upload bulk using XML] [PASSED, RC: 0] - [.297624584]
[Create player] [PASSED, RC: 0] - [.185705094]
[Generate thumb] [FAILED, RC: 255] - [.141691343]
[Delete partner] [PASSED, RC: 0] - [.139678207]
[Red5 file upload] [SKIPPED as OflaDemo isn't configured]
see: https://github.com/kaltura/platform-install-packages/blob/master/doc/install-kaltura-redhat-based.md#configure-red5-server

Thank you for running Kaltura! To keep Kaltura viable, stable and well tested, please join the community and help by contributing sanity tests that verify overall platform stability: http://bit.ly/kaltura-ci , and by contributing to the project roadmap by solving simple tasks and challenges: http://bit.ly/kaltura-tasks.

You have new mail in /var/spool/mail/root

Now there is the batch and i ran it individually as:
[root@red5 ~]# /opt/kaltura/bin/kaltura-batch-config.sh 
kaltura-batch-10.12.0-1.noarch
base-config completed successfully, if you ever want to re-configure your system (e.g. change DB hostname) run the following script:
# rm /opt/kaltura/app/base-config.lock
# /opt/kaltura/bin/kaltura-base-config.sh

Reloading httpd: 
Starting monit: Starting Monit 5.13 daemon with http interface at [*]:2812
                                                           [  OK  ]

Is it serious and how can I troubleshoot, the steps are so many that I would like to await your final verdict on it ....appreciate your prompt response(as previous :)). Thanks

**Comment by jessp01** [comment]
Hello,

Is your batch server running? 
\# /etc/init.d/kaltura-batch

Also check /opt/kaltura/log/kaltura_batch.log and run kaltlog as well to see additional errors.

**Comment by hsafe** [comment]
Hello Jess
After a batch rerun kaltura-batch-config, the status of the batch says 
running. The log is quite heavily gernerating stuffs. I did a grep on 
the error and got this only:
[root@red5 ~]# cat /opt/kaltura/log/kaltura_batch.log |grep error
PHP Fatal error: Uncaught exception 'Zend_Config_Exception' with message 
'Section 'red5' cannot be found in 
/opt/kaltura/app/cache//batch/config.ini' in 
/opt/kaltura/app/vendor/ZendFramework/library/Zend/Config/Ini.php:150

[root@red5 ~]# cat /opt/kaltura/log/kaltura_batch.log |wc
2966 34576 1868876
What can I assume here?


On 6/7/2015 2:54 PM, Jess Portnoy wrote:
>
> Hello,
>
> Is your batch server running?
> # /etc/init.d/kaltura-batch
>
> Also check /opt/kaltura/log/kaltura_batch.log and run kaltlog as well 
> to see additional errors.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/kaltura/platform-install-packages/issues/407#issuecomment-109732928>.
>

-- 
Hamid Safe
Borhancid.com

**Comment by KalturaCommunity** [comment]
run kaltlog from the shell, its an alias to easily find errors in logs.

May the source be with you,

Jess Portnoy

Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
virtualconnect.kaltura.com

**Comment by hsafe** [comment]
Hmmm
well non-existant
[root@red5 bin]# kaltlog
-bash: kaltlog: command not found
[root@red5 bin]# which kaltlog
/usr/bin/which: no kaltlog in 
(/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin)
[root@red5 bin]# whereis kaltlog
kaltlog:

On 6/7/2015 3:28 PM, KalturaCommunity wrote:
> run kaltlog from the shell, its an alias to easily find errors in logs.
>
> May the source be with you,
>
> Jess Portnoy
>
> Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
> virtualconnect.kaltura.com
>
>
>
> On Sun, 7 Jun 2015, hsafe wrote:
>
> > Hello Jess
> > After a batch rerun kaltura-batch-config, the status of the batch says
> > running. The log is quite heavily gernerating stuffs. I did a grep on
> > the error and got this only:
> > [root@red5 ~]# cat /opt/kaltura/log/kaltura_batch.log |grep error
> > PHP Fatal error: Uncaught exception 'Zend_Config_Exception' with message
> > 'Section 'red5' cannot be found in
> > /opt/kaltura/app/cache//batch/config.ini' in
> > /opt/kaltura/app/vendor/ZendFramework/library/Zend/Config/Ini.php:150
> >
> > [root@red5 ~]# cat /opt/kaltura/log/kaltura_batch.log |wc
> > 2966 34576 1868876
> > What can I assume here?
> >
> >
> > On 6/7/2015 2:54 PM, Jess Portnoy wrote:
> > >
> > > Hello,
> > >
> > > Is your batch server running?
> > > # /etc/init.d/kaltura-batch
> > >
> > > Also check /opt/kaltura/log/kaltura_batch.log and run kaltlog as well
> > > to see additional errors.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > 
> <https://github.com/kaltura/platform-install-packages/issues/407#issuecomment-109732928>.
> > >
> >
> > --
> > Hamid Safe
> > Borhancid.com
> >
> > —
> > Reply to this email directly or view it on 
> GitHub.[ACH7XiYPhHcpY0RthY8G9vQHl6vbf1Fcks5oRBp6gaJpZM4E6vsc.gif]
> >
> >
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/kaltura/platform-install-packages/issues/407#issuecomment-109736868>.
>

-- 
Hamid Safe
Borhancid.com

**Comment by KalturaCommunity** [comment]
# . /etc/profile.d/kaltura_base.sh
and then run kaltlog.

Its an alias defined in that file.
May the source be with you,

Jess Portnoy

Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
virtualconnect.kaltura.com

**Comment by hsafe** [comment]
No luck...

[root@red5 profile.d]# ./kaltura_base.sh
bash: ./kaltura_base.sh: Permission denied
[root@red5 profile.d]# ls -la
total 80
drwxr-xr-x. 2 root root 4096 Jun 7 13:30 .
drwxr-xr-x. 84 root root 4096 Jun 7 13:43 ..
-rw-r--r--. 1 root root 1127 Jul 16 2014 colorls.csh
-rw-r--r--. 1 root root 1143 Jul 16 2014 colorls.sh
-rw-r--r--. 1 root root 92 Nov 22 2013 cvs.csh
-rw-r--r--. 1 root root 78 Nov 22 2013 cvs.sh
-rw-r--r--. 1 root root 192 Sep 9 2014 glib2.csh
-rw-r--r--. 1 root root 192 Sep 9 2014 glib2.sh
-rw-r--r--. 1 root root 370 May 31 16:27 kaltura_base.sh
-rw-r--r--. 1 root root 53 Mar 25 2014 kaltura_ffmpeg.sh
-rw-r--r--. 1 root root 40 Jan 27 2014 kaltura_lame.sh
-rw-r--r--. 1 root root 49 Jan 27 2014 kaltura_mencoder.sh
-rw-r--r--. 1 root root 47 Feb 4 2014 kaltura_sphinx.sh
-rw-r--r--. 1 root root 1741 Nov 4 2014 lang.csh
-rw-r--r--. 1 root root 2706 Nov 4 2014 lang.sh
-rw-r--r--. 1 root root 123 Jun 4 2014 less.csh
-rw-r--r--. 1 root root 121 Jun 4 2014 less.sh
-rw-r--r--. 1 root root 97 Apr 5 2012 vim.csh
-rw-r--r--. 1 root root 269 Apr 5 2012 vim.sh
-rw-r--r--. 1 root root 169 May 20 2009 which2.sh
[root@red5 profile.d]# bash -x kaltura_base.sh
+ 
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/opt/kaltura/bin
+ export PATH
+ alias 'allkaltlog=grep --color "ERR:\|PHP\|trace\|CRIT\|\[error\]" 
/opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log'
+ alias 'kaltlog=tail -f /opt/kaltura/log/*.log 
/opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color 
"ERR:\|PHP\|trace\|CRIT\|\[error\]"'
+ '[' -r /etc/kaltura.d/system.ini ']'
+ . /etc/kaltura.d/system.ini
++ WEB_DIR=/opt/kaltura/web
++ LOG_DIR=/opt/kaltura/log
++ APP_DIR=/opt/kaltura/app
++ BASE_DIR=/opt/kaltura
++ PHP_BIN=/usr/bin/php
++ OS_KALTURA_USER=kaltura
++ MAILTO=h.safe@borhancid.com <mailto:MAILTO=h.safe@borhancid.com>
++ ADMIN_CONSOLE_ADMIN_MAIL=h.safe@borhancid.com 
<mailto:ADMIN_CONSOLE_ADMIN_MAIL=h.safe@borhancid.com>
++ DB1_HOST=127.0.0.1
++ DB1_NAME=kaltura
++ DB1_USER=kaltura
++ DB1_PASS=wKkJJc9CNbmxGLs
++ DWH_HOST=127.0.0.1
++ DWH_PORT=3306
++ DWH_USER=etl
++ DWH_PASS=wKkJJc9CNbmxGLs
++ SERVICE_URL=http://red5:80
++ SPHINX_HOST=127.0.0.1
++ DB1_PORT=3306
++ SUPER_USER=root
++ SUPER_USER_PASSWD=root@123
++ KALTURA_VIRTUAL_HOST_NAME=red5
++ RED5_HOST=red5
[root@red5 profile.d]# kaltlog
-bash: kaltlog: command not found


[root@red5 profile.d]# cat kaltura_base.sh
PATH=$PATH:/opt/kaltura/bin
export PATH
alias allkaltlog='grep --color "ERR:\|PHP\|trace\|CRIT\|\[error\]" 
/opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log'
alias kaltlog='tail -f /opt/kaltura/log/*.log 
/opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color 
"ERR:\|PHP\|trace\|CRIT\|\[error\]"'
if [ -r /etc/kaltura.d/system.ini ];then
. /etc/kaltura.d/system.ini
fi


On 6/7/2015 3:39 PM, KalturaCommunity wrote:
> # . /etc/profile.d/kaltura_base.sh
> and then run kaltlog.
>
> Its an alias defined in that file.
> May the source be with you,
>
> Jess Portnoy
>
> Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
> virtualconnect.kaltura.com
>
>
>
> On Sun, 7 Jun 2015, hsafe wrote:
>
> > Hmmm
> > well non-existant
> > [root@red5 bin]# kaltlog
> > -bash: kaltlog: command not found
> > [root@red5 bin]# which kaltlog
> > /usr/bin/which: no kaltlog in
> > (/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin)
> > [root@red5 bin]# whereis kaltlog
> > kaltlog:
> >
> > On 6/7/2015 3:28 PM, KalturaCommunity wrote:
> > > run kaltlog from the shell, its an alias to easily find errors in 
> logs.
> > >
> > > May the source be with you,
> > >
> > > Jess Portnoy
> > >
> > > Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
> > > virtualconnect.kaltura.com
> > >
> > >
> > >
> > > On Sun, 7 Jun 2015, hsafe wrote:
> > >
> > > > Hello Jess
> > > > After a batch rerun kaltura-batch-config, the status of the 
> batch says
> > > > running. The log is quite heavily gernerating stuffs. I did a 
> grep on
> > > > the error and got this only:
> > > > [root@red5 ~]# cat /opt/kaltura/log/kaltura_batch.log |grep error
> > > > PHP Fatal error: Uncaught exception 'Zend_Config_Exception' with 
> message
> > > > 'Section 'red5' cannot be found in
> > > > /opt/kaltura/app/cache//batch/config.ini' in
> > > > 
> /opt/kaltura/app/vendor/ZendFramework/library/Zend/Config/Ini.php:150
> > > >
> > > > [root@red5 ~]# cat /opt/kaltura/log/kaltura_batch.log |wc
> > > > 2966 34576 1868876
> > > > What can I assume here?
> > > >
> > > >
> > > > On 6/7/2015 2:54 PM, Jess Portnoy wrote:
> > > > >
> > > > > Hello,
> > > > >
> > > > > Is your batch server running?
> > > > > # /etc/init.d/kaltura-batch
> > > > >
> > > > > Also check /opt/kaltura/log/kaltura_batch.log and run kaltlog 
> as well
> > > > > to see additional errors.
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > >
> > > 
> <https://github.com/kaltura/platform-install-packages/issues/407#issuecomment-109732928>.
> > > > >
> > > >
> > > > --
> > > > Hamid Safe
> > > > Borhancid.com
> > > >
> > > > —
> > > > Reply to this email directly or view it on
> > > GitHub.[ACH7XiYPhHcpY0RthY8G9vQHl6vbf1Fcks5oRBp6gaJpZM4E6vsc.gif]
> > > >
> > > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > 
> <https://github.com/kaltura/platform-install-packages/issues/407#issuecomment-109736868>.
> > >
> >
> > --
> > Hamid Safe
> > Borhancid.com
> >
> > —
> > Reply to this email directly or view it on 
> GitHub.[ACH7XrgiUi6aWkwo-gzdMPNTlKGbP6UYks5oRB0CgaJpZM4E6vsc.gif]
> >
> >
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/kaltura/platform-install-packages/issues/407#issuecomment-109738060>.
>

-- 
Hamid Safe
Borhancid.com

**Comment by jessp01** [comment]
No, don;t run it. Source it.

\# . /etc/profile.d/kaltura_base.sh
there is a space between '.' and /etc/profile.d/kaltura_base.sh

May the source be with you,

Jess Portnoy

Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
virtualconnect.kaltura.com

**Comment by hsafe** [comment]
errr...sorry my mistake...here is what is the outcome:
[root@red5 profile.d]# kaltlog
==> /opt/kaltura/log/kaltura_apache_errors.log <==
[Sun Jun 07 14:58:40 2015] [error] [client 192.168.2.112] File does not exist: /opt/kaltura/app/alpha/web/currentsetting.htm
[Sun Jun 07 15:09:07 2015] [error] [client 192.168.2.112] File does not exist: /opt/kaltura/app/alpha/web/currentsetting.htm
[Sun Jun 07 15:25:56 2015] [error] [client 192.168.2.112] File does not exist: /opt/kaltura/app/alpha/web/currentsetting.htm
[Sun Jun 07 15:43:41 2015] [error] [client 192.168.2.112] File does not exist: /opt/kaltura/app/alpha/web/currentsetting.htm

--
[2015-06-07 13:41:50]failed to connect [1] [0.0078179836273193] mysql:host=127.0.0.1;port=3306;dbname=kaltura_sphinx_log;
PHP Fatal error:  Uncaught exception 'PropelException' with message 'Unable to open PDO connection dsn[mysql:host=127.0.0.1;port=3306;dbname=kaltura_sphinx_log;] user[kaltura] password[wKkJJc9CNbmxGLs] [wrapped: SQLSTATE[42000] [1044] Access denied for user 'kaltura'@'localhost' to database 'kaltura_sphinx_log']' in /opt/kaltura/app/vendor/propel/Propel.php:649
Stack trace:
#0 /opt/kaltura/app/vendor/propel/Propel.php(532): Propel::initConnection(Array, 'sphinx_log')
--
2015-06-07 13:47:57 [647213052] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [BATCH_BASE] for partner [0] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64
Stack trace:
#0 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(280): KalturaLog::alert('ERROR - Permiss...')
--
==> /opt/kaltura/log/batch/bulkupload-0-2015-06-07.err.log <==
PHP Notice:  Use of undefined constant DUPLICATE_CATEGORY - assumed 'DUPLICATE_CATEGORY' in /opt/kaltura/app/plugins/bulk_upload/xml/batch/BulkUploadEngineXml.php on line 1251

--
==> /opt/kaltura/log/batch/import-1-2015-06-07.err.log <==
PHP Notice:  Undefined index: content-type in /opt/kaltura/app/plugins/webex/WebexPlugin.php on line 24

--
==> /opt/kaltura/log/batch/import-3-2015-06-07.err.log <==
PHP Notice:  Undefined index: content-type in /opt/kaltura/app/plugins/webex/WebexPlugin.php on line 24

--
==> /opt/kaltura/log/kaltura_apache_errors.log <==
[Sun Jun 07 16:00:36 2015] [error] [client 192.168.2.112] File does not exist: /opt/kaltura/app/alpha/web/currentsetting.htm

--
==> /opt/kaltura/log/kaltura_apache_errors.log <==
[Sun Jun 07 16:19:28 2015] [error] [client 192.168.2.77] File does not exist: /opt/kaltura/app/alpha/web/currentsetting.htm

**Comment by hsafe** [comment]
Hello all
Wanted to update this thread maybe useful for novices like myself. After several tries and failures and troubleshooting with the kaltura tech teams. I managed to pull it off. Now here is my observations/hints for the tech teams and also the interested:
a. One thing is really missing in the top of instruction is the verification of the /etc/hosts and avaiability of a FQDN host which is the same as the http server since later on the scripts pick this to curl and run the checks and fail there if it does not exist.

b. In any stage screw up there is no really reverting back...trust me I have tested it in various failed step and primarily it is due to a lot of packages handled by kaltura installation and auto-config generated files will screw you. So remember to start afresh...till this is really handled by the team

c. Third is the permissions, there seems to be a bit of issues related to that I faced and seems that a sanity check for all the dirs under /opt/kaltura/ creating and run must be made. An example along the installation was  /opt/kaltura/dwh/logs/dwh_setup.log where the process staled indefinitely and checking on the file found the root owner on it. I did not wait more and opening another window chowned it back to kaltura:root . 

d. One other plausible case is the config of your server, my case was a VM probably all other guys out there are the same shoes ...my try and errors proved me that you need to consider minimal of the below for a successful install
cores:2
RAM: 2048
HDD: 10GB
anything less is prune to either time out fail or later warn you that you have run out of space(my case twice from 6GB to 8GB and now have to extend my VM to 10 GB for the installation of kaltura-Red5).
Hope above will be useful and I have no complains from the tech teams as they were really helpful and promptly all the time :)

**Comment by jessp01** [comment]
Hello @hsafe,

Thank you for your feedback.

As per A, we do state that here:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.15.0/doc/install-kaltura-redhat-based.md#pre-install-notes

"When installing, you will be prompted for each server's resolvable hostname. Note that it is crucial that all host names will be resolvable by other servers in the cluster (and outside the cluster for front machines). Before installing, verify that your /etc/hosts file is properly configured and that all Kaltura server hostnames are resolvable in your network."

RE b: can you explain exactly what failed for you? I rerun specific steps of the install constantly and have not run into issues. Indeed if there are any, I'd be more than happy to correct them.

RE c: /opt/kaltura/dwh/logs/dwh_setup.log is where the output of the DWH population is logged to, since the install runs as root, it is fine for it to be owned by it. Why did this pose an issue to you?

RE d: one core for a small testing machine should be fine. RAM and space really depend on the volume you intend to use, both as far as how many entries you plan on storing and how much traffic and transcoding you plan on doing.

Thanks again,

**Comment by jessp01** [comment]
Closing the issue due to lack of feedback but please feel free to comment with replies to my questions at any time so we can fix whatever needs fixing.
