### ISSUE TITLE
Installation issue: Error [Get KMC SWFs] [FAILED, RC: 255] - [.040684749]

### ISSUE THREAD

**Issue by hhermann** [kaltura/platform-install-packages#415]
Hello,

I tried to install the latest kaltura on RHEL7 now for hours but can not get it to pass the kaltura-sanity.sh successfully. Could you please help?

Best regards,

Harald

ERROR
Redirecting to /bin/systemctl status  memcached.service
[Check memcached daemon is started by Monit] [PASSED, RC: 0] - [48.485834209]
Note: Forwarding request to 'systemctl is-enabled memcached.service'.
enabled
[check daemon memcached init status] [PASSED, RC: 0] - [.002262349]
[kaltura-html5lib ver in KMC config.ini] [PASSED, RC: 0] - [.042560969]
[kaltura-kdp3 ver in KDP3 config.ini] [PASSED, RC: 0] - [.020578188]
[kaltura-kmc ver in KMC config.ini] [PASSED, RC: 0] - [.022886727]
/kmc): failed to open stream: No such file or directory in /opt/kaltura/bin/get_kmc_swfs.php on line 9
[Get KMC SWFs] [FAILED, RC: 255] - [.040684749]
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
[check_testme_page] [FAILED, RC: 1] - [.005156905]
[check_kmc_index_page] [FAILED, RC: 1] - [.003100951]
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
[check_admin_console_index_page] [FAILED, RC: 1] - [.005211866]
[check_studio_index_page] [FAILED, RC: 1] - [.005340857]
[check_clipapp_index_page] [FAILED, RC: 1] - [.703780390]
' (0) 2005 (HY000): Unknown MySQL server host 'localhost
[Create Partner] [FAILED, RC: 255] - [.063881759]
Partner creation failed. I will skip all tests that require it.
[Red5 file upload] [SKIPPED as OflaDemo isn't configured]
see: https://github.com/kaltura/platform-install-packages/blob/master/doc/install-kaltura-redhat-based.md#configure-red5-server

**Comment by kaltura-hooks** [comment]
Hi @hhermann,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by hhermann** [comment]
/opt/kaltura/bin# rpm -qa "kaltura*"
kaltura-monit-5.6-15.x86_64
kaltura-kcw-1.0.0-6.noarch
kaltura-a52dec-0.7.4-11.x86_64
kaltura-ffmpeg-2.1.3-2.x86_64
kaltura-widgets-1.0.0-8.noarch
kaltura-html5-studio-v1.9.8-1.noarch
kaltura-kdp3wrapper-v37.0-1.noarch
kaltura-postinst-1.0.26-6.noarch
kaltura-lame-3.99.5-3.x86_64
kaltura-libmcrypt-2.5.8-2.x86_64
kaltura-kclip-v1.1.2.1-2.noarch
kaltura-pentaho-4.2.1-1.x86_64
kaltura-batch-10.13.0-1.noarch
kaltura-kmc-v5.39.3-2.noarch
kaltura-front-10.13.0-1.noarch
kaltura-libfaac-1.28-1.x86_64
kaltura-libopencore-amr-0.1.3-1.x86_64
kaltura-flexwrapper-v1.2-1.noarch
kaltura-html5lib-v2.31-2.noarch
kaltura-kdp-v2.7.0-1.noarch
kaltura-kdpwrapper-v11.0-1.noarch
kaltura-libass-0.9.11-2.x86_64
kaltura-kupload-1.0.0-1.noarch
kaltura-krecord-1.0.0-1.noarch
kaltura-dwh-9.4.0-2.noarch
kaltura-red5-1.0.3-3.x86_64
kaltura-server-10.13.0-1.noarch
kaltura-sshpass-1.05-1.x86_64
kaltura-fdk-aac-0.1.3-1.x86_64
kaltura-segmenter-1.0-1.x86_64
kaltura-clipapp-1.3-2.noarch
kaltura-release-10.13.0-1.noarch
kaltura-ffmpeg-aux-0.6-2.x86_64
kaltura-kvpm-v1.0.6-1.noarch
kaltura-mencoder-3.4.6-9.x86_64
kaltura-base-10.13.0-7.noarch
kaltura-x264-0.140-2.20140104.x86_64
kaltura-nginx-1.8.0-1.x86_64
kaltura-kdp3-v3.9.9-2.noarch
kaltura-sphinx-2.2.1-16.x86_64




 tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
tail: cannot open '/opt/kaltura/log/batch/*.log' for reading: No such file or directory
curl: http://socbm264:80/api_v3/index.php?service=multirequest&format=3&ignoreNull=1&clientTag=php5%3A15-06-15&apiVersion=3.2.0&1%3Aservice=userrole&1%3Aaction=add&1%3AuserRole%3AobjectType=KalturaUserRole&1%3AuserRole%3Aname=System+Administrator&1%3AuserRole%3AsystemName=System+Administrator&1%3AuserRole%3Adescription=System+Administrator&1%3AuserRole%3Astatus=1&1%3AuserRole%3ApermissionNames=%2A&1%3AuserRole%3Atags=admin_console&1%3Aks=N2YwYWRhMDRmMzk4MmE1ZWJlZjJlMjQ3N2VkYzkwYTI4YzI1NDIzNnwtMjstMjsxNDM0NDU1NjcwOzI7MzQ5OTs7&2%3Aservice=user&2%3Aaction=add&2%3Auser%3AobjectType=KalturaUser&2%3Auser%3Aid=harald.hermann%40advantest.com&2%3Auser%3AscreenName=harald.hermann%40advantest.com&2%3Auser%3AfullName=Kaltura+Administrator&2%3Auser%3Aemail=harald.hermann%40advantest.com&2%3Auser%3Astatus=1&2%3Auser%3Apassword=anhe2107&2%3Auser%3AisAdmin=1&2%3Auser%3AroleIds=%7B1%3Aresult%3Aid%7D&2%3Auser%3AallowedPartnerIds=%2A&2%3Aks=N2YwYWRhMDRmMzk4MmE1ZWJlZjJlMjQ3N2VkYzkwYTI4YzI1NDIzNnwtMjstMjsxNDM0NDU1NjcwOzI7MzQ5OTs7&kalsig=d1cddcf9578a87629fa2ec225fab5aa7
PHP Fatal error:  Uncaught exception 'KalturaClientException' with message 'Empty reply from server' in /opt/kaltura/app/tests/lib/KalturaClientBase.php:362
Stack trace:
#0 /opt/kaltura/app/tests/lib/KalturaClientBase.php(817): KalturaClientBase->doQueue()
--
==> /opt/kaltura/log/kalt_up.log <==
PHP Warning:  mysqli_query() expects parameter 1 to be mysqli, boolean given in /opt/kaltura/app/deployment/updates/update.php on line 237
' (0)]' in /opt/kaltura/app/vendor/propel/Propel.php:649_DB_PASS@] [wrapped: SQLSTATE[HY000] [2005] Unknown MySQL server host 'localhost
Stack trace:
#0 /opt/kaltura/app/vendor/propel/Propel.php(532): Propel::initConnection(Array, 'propel')
--
2015-06-26 14:36:27 [988633008] [KSchedulerConfig->load] NOTICE: loading configuration /opt/kaltura/app/configurations/batch at 1435322021
PHP Fatal error:  Uncaught exception 'Zend_Config_Exception' with message 'Section 'socbm264' cannot be found in /opt/kaltura/app/cache//batch/config.ini' in /opt/kaltura/app/vendor/ZendFramework/library/Zend/Config/Ini.php:150
Stack trace:
#0 /opt/kaltura/app/batch/scheduler/KSchedulerConfig.class.php(59): Zend_Config_Ini->__construct('/opt/kaltura/ap...', 'socbm264', true)
--
[2015-06-15 11:13:27]failed to connect [1] [0.0011129379272461] mysql:host=127.0.0.1;port=3306;dbname=kaltura_sphinx_log;
PHP Fatal error:  Uncaught exception 'PropelException' with message 'Unable to open PDO connection dsn[mysql:host=127.0.0.1;port=3306;dbname=kaltura_sphinx_log;] user[kaltura] password[9IsqnmeVqSvkmDU] [wrapped: SQLSTATE[28000] [1045] Access denied for user 'kaltura'@'localhost' (using password: YES)]' in /opt/kaltura/app/vendor/propel/Propel.php:649
Stack trace:
#0 /opt/kaltura/app/vendor/propel/Propel.php(532): Propel::initConnection(Array, 'sphinx_log')

**Comment by jessp01** [comment]
Hello,

Does this problem still persist? I seem to recall another issue where you reported all is in working order..

Thanks,

**Comment by hhermann** [comment]
Thanks for catching up on this. Yes the issue is still there. I used kaltura the first time but could not find a similar issue that solved my issue.

**Comment by hhermann** [comment]
Sorry hit the wrong button issue is not solved yet.

**Comment by jessp01** [comment]
Can you try to update to latest? and when you run kaltura-config-all.sh, please make sure nothing fails and, if it does, please paste full output.

**Comment by jessp01** [comment]
Closing for now. If the issue persists, please reopen.

**Comment by hhermann** [comment]
Hello, sorry for the delayed answer. I have updated to the latest. The installation went fine and I got an mail confirming the installation. Then I run http://<hostname>:8080/admin_console/ on the host where kaltura is installed but got page not found error. Then I ran kaltura-sanity.sh and got this error.

[check daemon memcached init status] [PASSED, RC: 0] - [.002181849]
[kaltura-html5lib ver in KMC config.ini] [PASSED, RC: 0] - [.044281513]
[kaltura-kdp3 ver in KDP3 config.ini] [PASSED, RC: 0] - [.020672669]
[kaltura-kmc ver in KMC config.ini] [PASSED, RC: 0] - [.023164164]
PHP Warning:  file_get_contents(http://<hostname>:8080/kmc): failed to open stream: Connection refused in /opt/kaltura/bin/get_kmc_swfs.php on line 9
[Get KMC SWFs] [FAILED, RC: 255] - [.042898443]
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
[check_testme_page] [FAILED, RC: 1] - [.156160317]
[check_kmc_index_page] [FAILED, RC: 1] - [.153690850]
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
[check_admin_console_index_page] [FAILED, RC: 1] - [.156074111]
[check_studio_index_page] [FAILED, RC: 1] - [.155518768]
[check_clipapp_index_page] [FAILED, RC: 1] - [.904245712]
[Create Partner] [FAILED, RC: 255] - [.213601388]
Partner creation failed. I will skip all tests that require it.
[Red5 file upload] [SKIPPED as OflaDemo isn't configured]
see: https://github.com/kaltura/platform-install-packages/blob/master/doc/install-kaltura-redhat-based.md#configure-red5-server


Thank you for running Kaltura! To keep Kaltura viable, stable and well tested, please join the community and help by contributing sanity tests that verify overall platform stability: http://bit.ly/kaltura-ci , and by contributing to the project roadmap by solving simple tasks and challenges: http://bit.ly/kaltura-tasks.

**Comment by hhermann** [comment]
Could you please re-open this issue? Seems I am not allowed to do this.

**Comment by itsnando** [comment]
Were you able to solve this issue? I'm having the same problem.

**Comment by hhermann** [comment]
Sorry for the late reply not yet, I will try it again and let you know if I got further.

**Comment by itsnando** [comment]
No problem. I was able to get it. I ran kaltura-front-config.sh again and I selected Yes because I will be using HTTPs. After doing this sanity passed with no problem.

**Comment by jessp01** [comment]
@itsnando - just to make sure I understand, are we all good now or is there still an issue? Thanks.

**Comment by itsnando** [comment]
I'm good. I was letting hhermann know what I did to solve the issue hopefully it works for hhermann.

**Comment by jessp01** [comment]
Thanks @itsnando:) @hhermann - if you still have an issue, please post at forum.kaltura.org. We'd rather keep the issues section on GitHub for bug reports and not troubleshooting assistance.

**Comment by itsnando** [comment]
Ok no problem. :+1:
