### ISSUE TITLE
Installation error with kaltura-dwh

### ISSUE THREAD

**Issue by jdwolfe** [kaltura/platform-install-packages#420]
I get an error when running the install_kaltura_all_in_1.sh script.

dpkg: error processing package kaltura-dwh (--configure):
 subprocess installed post-installation script returned error exit status 11

In the log file everything looks good until ...
[2015-07-06 22:20:09]exception 'Exception' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'kaltura_sphinx_log.sphinx_log' doesn't exist' in /opt/kaltura/app/infra/log/KalturaLog.php:82

I can confirm that the table does exist:
+------------------------------+
| Tables_in_kaltura_sphinx_log |
+------------------------------+
| sphinx_log                   |
| sphinx_log_server            |
+------------------------------+

I remove and reinstalled kaltura-db.
Any one know what I can do to fix this?

**Comment by kaltura-hooks** [comment]
Hi @jdwolfe,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by jdwolfe** [comment]
I have only attempted on one platform, Ubuntu 14.04.2 LTS on an AWS instance. Self-hosted.
`mysql  Ver 14.14 Distrib 5.5.43, for debian-linux-gnu (x86_64) using readline 6.3`

```
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                  Version                 Architecture            Description
+++-=====================================-=======================-=======================-===============================================================================
ii  kaltura-base                          10.14.0-1+b4            all                     Kaltura Open Source Video Platform
ii  kaltura-clipapp                       1.3-1+b2                all                     Kaltura Video Presentations Manager
ii  kaltura-db                            10.10.0+b3              all                     Kaltura Open Source Video Platform - batch server
rc  kaltura-dwh                           10.10.0-1+b14           amd64                   Kaltura Open Source Video Platform - Analytics
ii  kaltura-html5-studio                  1.9.9-1                 all                     Kaltura Open Source Video Platform - frontend server
ii  kaltura-html5lib                      2.32-1                  all                     Kaltura Open Source Video Platform - HTML5 player
ii  kaltura-kclip                         1.1.2.1-1               all                     Kaltura Video Presentations Manager
ii  kaltura-kcw                           2.2.4-1+b3              all                     Kalture Contribution Wizard
ii  kaltura-kdp                           2.7.0-1                 all                     Kaltura Dynamic Player
ii  kaltura-kdp3                          3.9.9-1+b3              amd64                   Kaltura Dynamic Player
ii  kaltura-kdp3wrapper                   37-1                    all                     KDP3 Wrapper
ii  kaltura-kdpwrapper                    11-1                    all                     KDP Wrapper
ii  kaltura-kmc                           5.39.3-1                all                     Kaltura Management Console
ii  kaltura-krecord                       1.7-1                   all                     Kaltura kRecord - used for recording from web cam
ii  kaltura-kupload                       1.2.16-1                all                     Kaltura kupload widget
un  kaltura-pentaho                       <none>                  <none>                  (no description available)
ii  kaltura-postinst                      1.0.27                  all                     Kaltura Open Source Video Platform
ii  kaltura-sphinx                        2.2.1-3+b1              amd64                   Sphinx full-text search server - for Kaltura
ii  kaltura-widgets                       10.9.0-1+b4             all                     Kaltura Open Source Video Platform - widgets meta package
```


2015-07-06 21:13:37 [244152819] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [PARTNER_-1_GROUP_*_PE                                  RMISSION] for partner [0] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64
Stack trace:
#0 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(280): KalturaLog::alert('ERROR - Permiss...')
--
2015-07-06 21:13:37 [244152819] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [PARTNER_-1_GROUP_*_PE                                  RMISSION] for partner [0] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64
Stack trace:
#0 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(280): KalturaLog::alert('ERROR - Permiss...')
--
2015-07-06 21:13:46 [2020521252] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [MEDIA_SERVER_BASE] f                                  or partner [-1] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64
Stack trace:
#0 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(280): KalturaLog::alert('ERROR - Permiss...')
--
2015-07-06 21:14:11 [703073461] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [BATCH_BASE] for partn                                  er [0] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64
Stack trace:
#0 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(280): KalturaLog::alert('ERROR - Permiss...')
--
2015-07-06 21:14:19 [789238477] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [BATCH_BASE] for partn                                  er [0] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64
Stack trace:
#0 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(280): KalturaLog::alert('ERROR - Permiss...')
--
2015-07-06 21:14:24 [372088392] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [] for partner [0] not                                   found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64
Stack trace:
#0 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(280): KalturaLog::alert('ERROR - Permiss...')
--
2015-07-06 22:20:23 [1860596599] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [PARTNER_-1_GROUP_*_P                                  ERMISSION] for partner [0] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64
Stack trace:
#0 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(280): KalturaLog::alert('ERROR - Permiss...')
--
2015-07-06 22:20:23 [1860596599] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [PARTNER_-1_GROUP_*_P                                  ERMISSION] for partner [0] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64
Stack trace:
#0 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(280): KalturaLog::alert('ERROR - Permiss...')
--
2015-07-06 22:20:23 [1860596599] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [PARTNER_-1_GROUP_*_P                                  ERMISSION] for partner [0] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64
Stack trace:
#0 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(280): KalturaLog::alert('ERROR - Permiss...')
--
2015-07-06 22:20:32 [1394185659] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [MEDIA_SERVER_BASE] f                                  or partner [-1] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64
Stack trace:
#0 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(280): KalturaLog::alert('ERROR - Permiss...')
--
2015-07-06 22:20:56 [1510433181] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [BATCH_BASE] for part                                  ner [0] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64
Stack trace:
#0 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(280): KalturaLog::alert('ERROR - Permiss...')
--
2015-07-06 22:21:04 [134925571] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [BATCH_BASE] for partn                                  er [0] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64
Stack trace:
#0 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(280): KalturaLog::alert('ERROR - Permiss...')
--
2015-07-06 22:21:09 [831738184] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [] for partner [0] not                                   found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64
Stack trace:
#0 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(280): KalturaLog::alert('ERROR - Permiss...')

**Comment by jessp01** [comment]
Looks like the DB deployment did not fully complete.
Can you try to do:
\# dpkg-reconfigure kaltura-db
?

It will prompt you about removing the DB, select yes and let the postinst recreate it.
When done, make sure to also:
\# dpkg-reconfigure kaltura-base
\# dpkg-reconfigure kaltura-batch

Also, before doing all that, make sure that:
\# curl -I -v $SERVICE_URL/api_v3/
returns correctly.
It is possible that you have other vhosts configured making the request go to a diff docroot than the one defined for Kaltura. Take a look at:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.15.0/doc/install-kaltura-deb-based.md#setup-the-kaltura-deb-repository

There is a note about vhosts there..

**Comment by jdwolfe** [comment]
I had uninstalled and reinstalled kaltura-db several times and it failed every time. `dpkg-reconfigure kaltura-db` worked this time for some reason. So kaltura-db is installed correctly. But kaltura-dwh is still failing when installing.

Last few lines of the log file:
```
2015-07-10 15:13:38 [KalturaStatement->execute] DEBUG: /* k.pgoamedia.com[159817852][propel] */ SELECT permission_to_permission_item.ID, permission_to_permission_item.PERMISSION_ID, permission_to_permission_item.PERMISSION_ITEM_ID, permission_to_permission_item.CREATED_AT, permission_to_permission_item.UPDATED_AT FROM `permission_to_permission_item` WHERE permission_to_permission_item.PERMISSION_ID='236'
2015-07-10 15:13:38 [KalturaStatement->execute] DEBUG: Sql took - 8.2969665527344E-5 seconds
2015-07-10 15:13:38 [KalturaStatement->execute] DEBUG: /* k.pgoamedia.com[159817852][propel] */ INSERT INTO permission_to_permission_item (`ID`,`PERMISSION_ID`,`PERMISSION_ITEM_ID`,`CREATED_AT`,`UPDATED_AT`) VALUES (NULL,'236','959','2015-07-10 15:13:38','2015-07-10 15:13:38')
2015-07-10 15:13:38 [KalturaStatement->execute] DEBUG: Sql took - 0.0022749900817871 seconds
2015-07-10 15:13:38 [kObjectCreatedEvent->__construct] DEBUG: Event [kObjectCreatedEvent] object type [PermissionToPermissionItem] id [2338]
2015-07-10 15:13:38 [kObjectCreatedEvent->doConsume] DEBUG: consumer [kPermissionManager] started handling [kObjectCreatedEvent] object type [PermissionToPermissionItem] id [2338]
2015-07-10 15:13:38 [kObjectCreatedEvent->doConsume] DEBUG: consumer [kPermissionManager] finished handling [kObjectCreatedEvent] object type [PermissionToPermissionItem] id [2338]
2015-07-10 15:13:38 [kObjectSavedEvent->__construct] DEBUG: Event [kObjectSavedEvent] object type [PermissionToPermissionItem] id [2338]
2015-07-10 15:13:38 [kObjectSavedEvent->__construct] DEBUG: Event [kObjectSavedEvent] object type [Permission] id [236]
2015-07-10 15:13:38 [global] NOTICE: Done
installPlugins.log0000644000000000000000000000000012547761174013273 0ustar  rootrootkaltura_deploy.log0000644000000000000000000000000012547761174013302 0ustar  rootrootkaltura_populate.log0000644000000000000000000000000012547761174013637 0ustar  rootrootkaltura_scripts.log0000644000000000000000000001145112547761174013511 0ustar  rootroot2015-07-10 15:12:10 [2076494635] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [PARTNER_-1_GROUP_*_PERMISSION] for partner [0] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64
Stack trace:
#0 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(280): KalturaLog::alert('ERROR - Permiss...')
#1 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(197): addItemToPermissions(Object(kApiActionPermissionItem), Array, '0')
#2 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(40): addActionPermissionItem(Object(Zend_Config))
#3 {main}
2015-07-10 15:12:10 [2076494635] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [PARTNER_-1_GROUP_*_PERMISSION] for partner [0] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64
Stack trace:
#0 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(280): KalturaLog::alert('ERROR - Permiss...')
#1 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(197): addItemToPermissions(Object(kApiActionPermissionItem), Array, '0')
#2 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(40): addActionPermissionItem(Object(Zend_Config))
#3 {main}
2015-07-10 15:12:10 [2076494635] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [PARTNER_-1_GROUP_*_PERMISSION] for partner [0] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64
Stack trace:
#0 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(280): KalturaLog::alert('ERROR - Permiss...')
#1 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(197): addItemToPermissions(Object(kApiActionPermissionItem), Array, '0')
#2 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(40): addActionPermissionItem(Object(Zend_Config))
#3 {main}
2015-07-10 15:12:20 [388584542] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [MEDIA_SERVER_BASE] for partner [-1] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64
Stack trace:
#0 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(280): KalturaLog::alert('ERROR - Permiss...')
#1 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(197): addItemToPermissions(Object(kApiActionPermissionItem), Array, '-1')
#2 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(40): addActionPermissionItem(Object(Zend_Config))
#3 {main}
```

What should `$SERVICE_URL` be?

There are no vhosts installed. This is a blank AWS instance.

**Comment by jessp01** [comment]
SERVICE_URL is the domain/hostname your Kaltura instance is installed on.
for example, for our SaaS, that would be www.kaltura.com. For your ec2 
test server, you can either use the IP or the public DNS which looks like 
ec2-000-000-00-00.compute-1.amazonaws.com where these 0s are the IP 
address of the instance separated with '-' instead of '.'. It should state 
the public DNS in the EC2 console.

As far as DWH - how exactly does it fail? i.e, what is the 
output? Also, what MySQL server version are you using?

May the source be with you,

Jess Portnoy

**Comment by jdwolfe** [comment]
It fails in the log snippet I posted.
`LERT: exception 'Exception' with message 'ERROR - Permission name [PARTNER_-1_GROUP_*_PERMISSION] for partner [0] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64`
`2015-07-10 15:12:10 [2076494635] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [PARTNER_-1_GROUP_*_PERMISSION] for partner [0] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64`
`2015-07-10 15:12:10 [2076494635] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [PARTNER_-1_GROUP_*_PERMISSION] for partner [0] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64`
`2015-07-10 15:12:20 [388584542] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [MEDIA_SERVER_BASE] for partner [-1] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64`

```
dpkg: error processing package kaltura-dwh (--configure):
 subprocess installed post-installation script returned error exit status 11
Errors were encountered while processing:
 kaltura-dwh
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
`mysql  Ver 14.14 Distrib 5.5.43, for debian-linux-gnu (x86_64) using readline 6.3`

The curl statement returns a 404 since there in nothing in /var/www/html (except the default Apache page)

**Comment by jessp01** [comment]
The document root should be /opt/kaltura/app/alpha/web and defined by 
/etc/apache2/sites-enabled/zzzkaltura.conf:1

This is done when installing the kaltura-front package.

If you do not have this vhost configured, all will fail, including the 
kaltura-db final phase, which will go a long way to explain the error 
lines you posted which BTW do not have anything to do with dwh, only with 
the operational DB which is populated in kaltura-db's postinst.

Do you not have this vhost set up?
did you run the install script as per instructions here?
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.15.0/doc/install-kaltura-deb-based.md

May the source be with you,

Jess Portnoy

**Comment by KalturaCommunity** [comment]
It is quite possible you forgot to enable the multiverse report which caused kaltura - front to be skipped.

May the source be with you,

Jess Portnoy



On Fri, Jul 10, 2015 at 8:47 AM -0700, "Jess Portnoy" <notifications@github.com<mailto:notifications@github.com>> wrote:

The document root should be /opt/kaltura/app/alpha/web and defined by
/etc/apache2/sites-enabled/zzzkaltura.conf:1

This is done when installing the kaltura-front package.

If you do not have this vhost configured, all will fail, including the
kaltura-db final phase, which will go a long way to explain the error
lines you posted which BTW do not have anything to do with dwh, only with
the operational DB which is populated in kaltura-db's postinst.

Do you not have this vhost set up?
did you run the install script as per instructions here?
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.15.0/doc/install-kaltura-deb-based.md

May the source be with you,

Jess Portnoy



On Fri, 10 Jul 2015, Jeff Wolfe wrote:

>
> It fails in the log snippet I posted.
> LERT: exception 'Exception' with message 'ERROR - Permission name [PARTNER_-1_GROUP_*_PERMISSION] for partner [0] not found in
> database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64
> 2015-07-10 15:12:10 [2076494635] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message
> 'ERROR - Permission name [PARTNER_-1_GROUP_*_PERMISSION] for partner [0] not found in database - skipping!' in
> /opt/kaltura/app/infra/log/KalturaLog.php:64
> 2015-07-10 15:12:10 [2076494635] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message
> 'ERROR - Permission name [PARTNER_-1_GROUP_*_PERMISSION] for partner [0] not found in database - skipping!' in
> /opt/kaltura/app/infra/log/KalturaLog.php:64
> 2015-07-10 15:12:20 [388584542] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message
> 'ERROR - Permission name [MEDIA_SERVER_BASE] for partner [-1] not found in database - skipping!' in
> /opt/kaltura/app/infra/log/KalturaLog.php:64
>
> dpkg: error processing package kaltura-dwh (--configure):
> subprocess installed post-installation script returned error exit status 11
> Errors were encountered while processing:
> kaltura-dwh
> E: Sub-process /usr/bin/dpkg returned an error code (1)
>
> mysql Ver 14.14 Distrib 5.5.43, for debian-linux-gnu (x86_64) using readline 6.3
>
> The curl statement returns a 404 since there in nothing in /var/www/html (except the default Apache page)
>
> -
> Reply to this email directly or view it on GitHub.[AFBqvck1_XhSl5RYgwZSncg2OZlR8htNks5ob99JgaJpZM4FTHDI.gif]
>
>
>

-

**Comment by jdwolfe** [comment]
It looks like kaltura-front wasn't installed when I ran `install_kaltura_all_in_1.sh`

```
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                              Version               Architecture          Description
+++-=================================-=====================-=====================-=======================================================================
ii  kaltura-base                      10.14.0-1+b4          all                   Kaltura Open Source Video Platform
ii  kaltura-clipapp                   1.3-1+b2              all                   Kaltura Video Presentations Manager
ii  kaltura-db                        10.10.0+b3            all                   Kaltura Open Source Video Platform - batch server
iF  kaltura-dwh                       10.10.0-1+b14         amd64                 Kaltura Open Source Video Platform - Analytics
ii  kaltura-html5-studio              1.9.9-1               all                   Kaltura Open Source Video Platform - frontend server
ii  kaltura-html5lib                  2.32-1                all                   Kaltura Open Source Video Platform - HTML5 player
ii  kaltura-kclip                     1.1.2.1-1             all                   Kaltura Video Presentations Manager
ii  kaltura-kcw                       2.2.4-1+b3            all                   Kalture Contribution Wizard
ii  kaltura-kdp                       2.7.0-1               all                   Kaltura Dynamic Player
ii  kaltura-kdp3                      3.9.9-1+b3            amd64                 Kaltura Dynamic Player
ii  kaltura-kdp3wrapper               37-1                  all                   KDP3 Wrapper
ii  kaltura-kdpwrapper                11-1                  all                   KDP Wrapper
ii  kaltura-kmc                       5.39.3-1              all                   Kaltura Management Console
ii  kaltura-krecord                   1.7-1                 all                   Kaltura kRecord - used for recording from web cam
ii  kaltura-kupload                   1.2.16-1              all                   Kaltura kupload widget
ii  kaltura-pentaho                   4.2.1                 amd64                 Pentaho Open Source Data Integration Community Edition (CE).
ii  kaltura-postinst                  1.0.27                all                   Kaltura Open Source Video Platform
ii  kaltura-sphinx                    2.2.1-3+b1            amd64                 Sphinx full-text search server - for Kaltura
ii  kaltura-widgets                   10.9.0-1+b4           all                   Kaltura Open Source Video Platform - widgets meta package
```

I'm just going to scrap this instance and start over from the beginning.

**Comment by jessp01** [comment]
No need to scratch it.. I think you simply forgot to enable the multiverse 
repo. There is a note about this in the doc:
Ubuntu NOTE: You must also make sure the multiverse repo is enabled in 
/etc/apt/sources.list

May the source be with you,

Jess Portnoy

**Comment by jessp01** [comment]
Also, just pushed a new version of the script:
https://github.com/kaltura/platform-install-packages/commit/aa203e75ff7522106c51990ba684594d71eefde9
Will now auto detects distro and codename and adds repos as needed.

I am closing this but feel free to update should you still have issues.

**Comment by jdwolfe** [comment]
Thanks for your patience and helping with this. I still can't get kaltura-dwh to install and it seems to be related to database problems.
I enabled the multiverse in /etc/apt/sources.list and fixed the issue with the Virtualhost
I did a `dpkg-reconfigure` for all the items in `install_kaltura_all_in_1.sh`. Everything works perfect until I get to kaltura-dwh.
Then I still get these errors:
```
kaltura_scripts.log:2015-07-10 20:01:01 [921954012] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [PARTNER_-1_GROUP_*_PERMISSION] for partner [0] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64
kaltura_scripts.log:2015-07-10 20:01:01 [921954012] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [PARTNER_-1_GROUP_*_PERMISSION] for partner [0] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64
kaltura_scripts.log:2015-07-10 20:01:01 [921954012] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [PARTNER_-1_GROUP_*_PERMISSION] for partner [0] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64
kaltura_scripts.log:2015-07-10 20:01:15 [1444110671] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [MEDIA_SERVER_BASE] for partner [-1] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64
kaltura_scripts.log:2015-07-10 20:01:58 [837391650] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [BATCH_BASE] for partner [0] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64
kaltura_scripts.log:2015-07-10 20:02:12 [281145854] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [BATCH_BASE] for partner [0] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64
kaltura_scripts.log:2015-07-10 20:02:22 [316256689] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [] for partner [0] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64
```
I'm assuming that `[PARTNER_-1_GROUP_*_PERMISSION] for partner [0]` means that it is looking in the kaltura.permissions table where name="PARTNER_-1_GROUP_*_PERMISSION" and partner_id=0
But I only see one entry with "PARTNER_-1_GROUP_*_PERMISSION" and its partner_id is -1

Same for `[MEDIA_SERVER_BASE] for partner [-1]`, I only see one entry with that name and the partner_id is -5
Same for `[BATCH_BASE] for partner [0]` the only partner_id is -1
I don't know what `[] for partner [0]` is trying to match 

Is this bad data in the DB or did some other repo not get installed correctly?
