### ISSUE TITLE
Why does Kaltura Clusters require sticky session?

### ISSUE THREAD

**Issue by matsuu** [kaltura/platform-install-packages#427]
In [How to Crete a Kaltura Session](http://knowledge.kaltura.com/faq/how-create-kaltura-session):
> The Kaltura API is REST based and stateless.

But [Apache configuration example](https://github.com/kaltura/platform-install-packages/blob/master/doc/apache_balancer.conf) and [HAProxy configuration example](https://github.com/kaltura/platform-install-packages/blob/master/doc/haproxy.cfg) use cookie for sticky session.

**Comment by jessp01** [comment]
Hello Matsuu,

The API is indeed stateless. However, one also needs to make use of the Admin console, KMC, KMS and other such web fronts, this is the reason. 
For additional general questions, please post at forum.kaltura.org instead.
We'd like to keep the issue tracking for bugs and pull requests only.

Thanks,
