### ISSUE TITLE
install of kaltura-base asks for a password.

### ISSUE THREAD

**Issue by krischik** [kaltura/platform-install-packages#432]
When installing kaltura-base it asks for *a password* without indication which one.

```
>sudo aptitude install kaltura-base
The following NEW packages will be installed:
  kaltura-base libmcrypt4{a} monit{a} php5-curl{a} php5-mcrypt{a}
0 packages upgraded, 5 newly installed, 0 to remove and 1 not upgraded.
Need to get 0 B/79,9 MB of archives. After unpacking 192 MB will be used.
Do you want to continue? [Y/n/?] y
Preconfiguring packages ...
Selecting previously unselected package libmcrypt4.
(Reading database ... 60701 files and directories currently installed.)
Preparing to unpack .../libmcrypt4_2.5.8-3.3_amd64.deb ...
Unpacking libmcrypt4 (2.5.8-3.3) ...
Selecting previously unselected package monit.
Preparing to unpack .../monit_1%3a5.9-1_amd64.deb ...
Unpacking monit (1:5.9-1) ...
Selecting previously unselected package php5-curl.
Preparing to unpack .../php5-curl_5.6.9+dfsg-0+deb8u1_amd64.deb ...
Unpacking php5-curl (5.6.9+dfsg-0+deb8u1) ...
Selecting previously unselected package php5-mcrypt.
Preparing to unpack .../php5-mcrypt_5.6.9+dfsg-0+deb8u1_amd64.deb ...
Unpacking php5-mcrypt (5.6.9+dfsg-0+deb8u1) ...
Selecting previously unselected package kaltura-base.
Preparing to unpack .../kaltura-base_10.16.0-2+b2_all.deb ...
Unpacking kaltura-base (10.16.0-2+b2) ...
Processing triggers for man-db (2.7.0.2-5) ...
Processing triggers for systemd (215-17+deb8u1) ...
Processing triggers for libapache2-mod-php5 (5.6.9+dfsg-0+deb8u1) ...
Setting up libmcrypt4 (2.5.8-3.3) ...
Setting up monit (1:5.9-1) ...
Setting up php5-curl (5.6.9+dfsg-0+deb8u1) ...
php5_invoke: Enable module curl for cli SAPI
php5_invoke: Enable module curl for apache2 SAPI
Setting up php5-mcrypt (5.6.9+dfsg-0+deb8u1) ...
php5_invoke: Enable module mcrypt for cli SAPI
php5_invoke: Enable module mcrypt for apache2 SAPI
Setting up kaltura-base (10.16.0-2+b2) ...
Enter password:
```

My guess it is the database password. But it is not very user friendly. And soon after it fails with Issue #431

**Comment by jessp01** [comment]
the kaltura-base postinst script should prompt you with several dialogues, as can be seen here:
/var/lib/dpkg/info/kaltura-base.postinst
/var/lib/dpkg/info/kaltura-base.templates

If it does not, it is possible you have:
DEBIAN_FRONTEND=noninteractive
set. In that case, you need to create a response file as per:
https://github.com/kaltura/platform-install-packages/blob/master/doc/install-kaltura-deb-based.md#unattended-installation

If that is not the case, I suggest you edit /var/lib/dpkg/info/kaltura-base.postinst and change:
#!/bin/bash
to:
\#!/bin/bash -x
run:
\# dpkg-reconfigure kaltura-base
and see what exactly is the flow you reach.

**Comment by krischik** [comment]
Thanks. I saw the installation dialogues the first time around. But I messed the initial installation up with the wrong mysql password.

So I tries a de-install, re-install and this is not going well :-(

Not giving up yet.

**Comment by KalturaCommunity** [comment]
No reason why you should give up:)
You can ALWAYS run dpkg-reconfigure kaltura-base to fix previous errs. No 
need for a reinstall.

Please describe the exact current situation and I'll be happy to help you.

May the source be with you,

Jess Portnoy

**Comment by krischik** [comment]
Well I was able to reinstall after returning the VM to a previous shapshot. What I noticed was that some questions where asked multiple times.

**Comment by jessp01** [comment]
Hello,

The only questions that should repeat themselves in an all in one install are the DB creds and passwd. This is because one might install a cluster, in which case, not all packages need to be installed on all nodes.
