### ISSUE TITLE
What does "The original flavor asset is missing" stand for?

### ISSUE THREAD

**Issue by krischik** [kaltura/platform-install-packages#433]
What does the error message "The original flavor asset is missing" mean.

I get the error message when I open the details on an freshly uploaded video, then to flavours and select the convert action on any missing flavour.

The reason I went there in the first place is that the uploaded videos are stuck in converting for quite a while now. Which makes me wonder if there is a problem with the freshly installed system.

I Could not find it in the documentation and if you google it all you find are the references in the source code.

**Comment by krischik** [comment]
Also I noted a waiting wheel which does not go away:

![katura-flavor-1](https://cloud.githubusercontent.com/assets/685853/9131645/d2acb7c6-3ced-11e5-8f70-23e6e9172293.PNG)

**Comment by jessp01** [comment]
Hello,

Is your batch daemon running?
run:
\# /opt/kaltura/bin/kaltura-sanity.sh
It should run many sanity tests that can help diagnose the problem.

**Comment by krischik** [comment]
No, It is not even installed:

```
[Check kaltura-batch daemon status] [SKIPPED as kaltura-batch is not installed]
[Check kaltura-batch daemon init] [SKIPPED as kaltura-batch is not installed]
```

And if I try to install it the kaltura-nginx.service fails

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
libdvdnav4 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [J/n] j
Setting up kaltura-nginx (1.8.0-2+b2) ...
Job for kaltura-nginx.service failed. See 'systemctl status kaltura-nginx.service' and 'journalctl -xn' for details.



                Archving logs to /opt/kaltura/log/log_07_08_15_12_57.tar.gz...
dpkg: error processing package kaltura-nginx (--configure):
 subprocess installed post-installation script returned error exit status 11
Processing triggers for libc-bin (2.19-18) ...
Errors were encountered while processing:
 kaltura-nginx
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Because the server is missing in it's configuration:

```
Aug 07 10:55:07 testbsits kaltura-nginx[6024]: Starting nginx: nginx.
Aug 07 12:53:00 testbsits kaltura-nginx[8787]: Reloading nginx configuration: nginx: [emerg] invalid number of arguments in "server" directive in /opt/kaltura/nginx/conf/nginx.conf:17
Aug 07 12:53:00 testbsits kaltura-nginx[8787]: nginx: configuration file /opt/kaltura/nginx/conf/nginx.conf test failed
```

And if I add the server to the name file it disappears again. Next try `dpkg-reconfigure kaltura-base` - did not help.

And, as suggested in another issue `aptitude install -f` - did not help as well. 

And last a de-install and re-install of kaltura-nginx. But that failed as well.

**Comment by jessp01** [comment]
What distribution are you using? I suspect you are missing some repositories which is why kaltura-batch did not install. try:
\# aptitude install kaltura-batch

to see what deps are missing.

As for kaltura-nginx, I suggest you edit /var/lib/dpkg/info/kaltura-nginx.postinst
and add -x to the !#/bin/bash line so that you'll get debug info and see why the postinst fails.

**Comment by krischik** [comment]
Debian 8 and you are right there is a problem around mplayer libdvdnav4 mencoder:

```
sudo apt-get upgrade mencoder
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libdvdnav4 : Breaks: mencoder (< 2:1.0) but 2:1.0~rc4.dfsg1+svn34540-1+deb7u1 is to be installed
              Breaks: mplayer (< 2:1.0)
E: Broken packages
```

After googeling a bit I found:

https://www.vimp.com/de/web/faq-installation/items/how-to-install-the-transcoding-tools-on-debian-8-jessie.html

which helped installing kaltura-batch.

**Comment by krischik** [comment]
The problem with kaltura-nginx is that the server is missing in the `/opt/kaltura/nginx/conf/nginx.conf` file:

```
http {
        upstream kalapi {
                server ;
        }
 
```

My guess it that it is copied from another configuration file. Just could not figure out which one.

**Comment by jessp01** [comment]
The server is prompted about here:
/var/lib/dpkg/info/kaltura-nginx.postinst
        db_input critical 'kaltura-nginx/nginx_hostname' || true
        db_go || true
        db_get 'kaltura-nginx/nginx_hostname'
        VOD_PACKAGER_HOST=$RET

What happens if you do:
\# dpkg-reconfigure kaltura-nginx
?

**Comment by jessp01** [comment]
For Debian 8, there is this note:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.17.0/doc/install-kaltura-deb-based.md#setup-the-kaltura-deb-repository

Debian Jessie [8] NOTE: You must also make sure the following Wheezy repos are enabled in /etc/apt/sources.list

deb http://ftp.debian.org/debian/ wheezy main
deb http://security.debian.org/ wheezy/updates main


Also, the http://installrepo.origin.kaltura.org/repo/apt/debian/install_kaltura_all_in_1.sh script tries to auto enable it

**Comment by jessp01** [comment]
I am closing this one for now as it seems everything is in order. But if you are able to reproduce the problem you had with kaltura-nginx when using dpkg-reconfigure, please open a separate issue with the output of bash -x.

Thanks,
