### ISSUE TITLE
Can't get SSL to work on Debian

### ISSUE THREAD

**Issue by krischik** [kaltura/platform-install-packages#436]
I  have a working non SSL system and want and what to change it to use SSL as well. For this I use:

```
sudo dpkg-reconfigure kaltura-base

```

The first error (warning) message I notice is 

```
Aug 17 09:59:49 ch-thl-vm-024 apache2[6057]: AH02559: The SSLCertificateChainFile directive (/etc/apache2/sites-enabled/zzzkaltura.ssl.conf:16) is deprecated, SSLCertificateFile should be used instead
```

and next one is:

```
Aug 17 09:56:22 ch-thl-vm-024 apache2[3486]: AH00526: Syntax error on line 11 of /etc/apache2/sites-enabled/zzzkaltura.ssl.conf:
Aug 17 09:56:22 ch-thl-vm-024 apache2[3486]: Invalid command 'SSLMutex', perhaps misspelled or defined by a module not included in the server configuration
```
and lastly 

```
Aug 17 09:59:49 ch-thl-vm-024 apache2[6057]: AH00526: Syntax error on line 2 of /opt/kaltura/app/configurations/apache/conf.d/enabled.kaltura.conf:
Aug 17 09:59:49 ch-thl-vm-024 apache2[6057]: ServerName takes one argument, The hostname and port of the server
```

After commenting out the `SSLMutex` in the `zzzkaltura.ssl.conf` file and fixing the `enabled.kaltura.conf` coping the last backup file I can start apache again.

I can also access the admin_console. However when I want to start KCM I get the attached error message:

![kcm-1](https://cloud.githubusercontent.com/assets/685853/9302432/c875dec2-44d6-11e5-9f69-68bdd2435aef.PNG)

Any ideas?

**Comment by krischik** [comment]
After clicking OK a couple of times I get this more telling error message:

![kmc-2](https://cloud.githubusercontent.com/assets/685853/9302498/4f84f27c-44d7-11e5-877c-c404c7e751f2.PNG)

**Comment by jessp01** [comment]
Hello,

Thanks for the report. I'll handle the SSLCertificateChainFile issue. The SSLMutex I already submitted a pull for https://github.com/kaltura/server/pull/2401 but it was not merged. Will handle that one as well.

As for the current issue, can you please modify the template file instead at /opt/kaltura/app/configurations/apache/kaltura.ssl.conf.template and then:
\# dpkg-reconfigure kaltura-base
\# dpkg-reconfigure kaltura-front
\# dpkg-reconfigure kaltura-batch
Then, if you still have issues, run:
\# kaltlog 
while making the request and see what errors are outputted?

**Comment by jessp01** [comment]
Actually, just made this pull:
https://github.com/kaltura/server/pull/3031

Can you grab the template file from it and test?

Thanks,

**Comment by krischik** [comment]
Sorry to say but that does not work as you now have two `SSLCertificateFile` statements. The correct was to do it is to merge all pem into one file and use that as `SSLCertificateFile`. 

http://www.bensprotips.com/2014/04/apache-sslcertificatechainfile-directive-deprecated-sslcertificatefile/
-----
Also this does not fix the final problem. For that final problem I had to make sure that Apache also listen at port 443. It did that by adding the following to the end of `kaltura.ssl.conf`

```apache
<VirtualHost XXX.XXX.net:443>
        SSLEngine on
        SSLProtocol all -SSLv2
        SSLCipherSuite ALL:!ADH:!EXPORT:!SSLv2:RC4+RSA:+HIGH:+MEDIUM:+LOW

        ErrorLog "/opt/kaltura/log/kaltura_apache_errors_ssl.log"
        CustomLog /opt/kaltura/log/kaltura_apache_access_ssl.log vhost_kalt

        Include "/opt/kaltura/app/configurations/apache/conf.d/enabled.*.conf"
</VirtualHost>
```

**Comment by jessp01** [comment]
Hi Martin,

Actually, should just use SSLCACertificateFile
which is:
#   Certificate Authority (CA):
#   Set the CA certificate verification path where to find CA
#   certificates for client authentication or alternatively one
#   huge file containing all of them (file must be PEM encoded)


Made this pull:
https://github.com/kaltura/server/pull/3036

Can you please try?

Thanks,

May the source be with you,

Jess Portnoy

**Comment by krischik** [comment]
Yes. That works.

**Comment by jessp01** [comment]
Great, thanks for confirming. Will be packaged for 10.18.0.
