### ISSUE TITLE
Dependency Issue: Jupiter install in CentOS Linux release 7.1.1503 (Core)

### ISSUE THREAD

**Issue by GeraldNathan** [kaltura/platform-install-packages#442]
Observations:

1. rpm -ihv http://installrepo.kaltura.org/releases/kaltura-release.noarch.rpm
Installs local.repo (which was disabled as it was pointing to tmp to continue install.

2. rhel7 noarch branch looks like pointing to wrong link.
-  As I had dependency error for nginx- I force installed kaltura-nginx-1.8.0-3.x86_64.rpm first and continued with the install..

Will update if any other observations.

**Comment by jessp01** [comment]
Hi Gerald,

See: https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.20.0/doc/install-kaltura-redhat-based.md#note-on-rhelcentos-7

Noarch is a symlink pointing to latest/noarch but you can just leave it as is and use the default set in kaltura.repo.
Only need to change the x86_64 as per instructions.

For RHEL7, you need to install http://installrepo.kaltura.org/releases/rhel7/RPMS/x86_64/kaltura-nginx-1.8.0-1.x86_64.rpm.

**Comment by GeraldNathan** [comment]
Thanks, Jess.

**Comment by KalturaCommunity** [comment]
Sure, Gerald. All is well? did you install?

May the source be with you,

Jess Portnoy

Kaltura Connect Virtual Summits 2015 - now on VOD! [connect.mediaspace.kaltura.com]
