### ISSUE TITLE
install stalls  with user_consent=1 in bin/contact.rc

### ISSUE THREAD

**Issue by GeraldNathan** [kaltura/platform-install-packages#443]
Completed the all in one deploy with little hurdles :

- First attempt: while  user_consent=1 got stuck in doing a curl to http://installytics.kaltura.org/report

- Second attempt cleared /tmp  and trying with new kaltura.ans (user_consent=0) was having same effect. script picks up the parameter from bin/contact.rc and not from kaltura.ans

- install completed only after making user_consent=0 in bin/contact.rc

**Comment by KalturaCommunity** [comment]
curl http://installytics.kaltura.org/report works fine for me. Are you 
installing from a machine does has no access to www?
even so, it should eventually timeout and the install should continue but 
I'll set a shorter timeout for it so it does not hang too long.

If you are installing from a machine that does have www access, can you 
run the curl command with -I -v and report back the result? this is just 
used for analytics, there is no reason for the installation to fail 
because of it.

May the source be with you,

Jess Portnoy

Kaltura Connect Virtual Summits 2015 - now on VOD! [connect.mediaspace.kaltura.com]

**Comment by GeraldNathan** [comment]
I had executed bash with debug mode and script stopped there.

+ curl -i -X POST -H 'Content-Type: application/json' -d '{"event_type": "install_start", "server_role": "kaltura-config-all.sh", "user_email": "gerald.kaltura@gmail.com", "machine_id": "aa69ded53c8ead0d497da010b9f83db3", "installation_id": "cc7114bb82cbb24bd7b78cb2706b5a62", "timestamp": "1442598195", "kernel_version": "3.10.0-229.14.1.el7.x86_64", "machine_arch": "x86_64","linux_flavor":"Description:' CentOS Linux release 7.1.1503 '(Core)' Codename: 'Core","is_ssl": "false", "service_url": "","install_err_line": "","timezone": "unknown","package_type":"rpm","kaltura_version": "10.19.0","package_revision": "10"}' http://installytics.kaltura.org/report

**Comment by GeraldNathan** [comment]
Sorry didnt answer to you question : Yeah the machine does have access to internet. As you say it could be time out settings.. I didn't wait too long as  I checked the url was accessible from the node.

Thank you,
Gerald

**Comment by KalturaCommunity** [comment]
Can you run this with -v and see why it is taking long to return?
it should happen quite rapidly.

Thanks,

May the source be with you,

Jess Portnoy

Kaltura Connect Virtual Summits 2015 - now on VOD! [connect.mediaspace.kaltura.com]

**Comment by GeraldNathan** [comment]
Hi Jess,
The issue is with the special character (  7.1.1503 '(Core)' Codename: ' ) in description ( not being escaped).

I just changed it test and this request works:
curl -v -i -X POST -H 'Content-Type: application/json' -d '{"event_type": "install_start", "server_role": "kaltura-config-all.sh", "user_email": "gerald.kaltura@gmail.com", "machine_id": "aa69ded53c8ead0d497da010b9f83db3", "installation_id": "cc7114bb82cbb24bd7b78cb2706b5a62", "timestamp": "1442598195", "kernel_version": "3.10.0-229.14.1.el7.x86_64", "machine_arch": "x86_64","linux_flavor": "CentOS Linux release 7.1.1", "Codename": 'Core","is_ssl": "false", "service_url": "","install_err_line": "","timezone": "unknown","package_type":"rpm","kaltura_version": "10.19.0","package_revision": "10"}'" http://installytics.kaltura.org/report

Thanks,
Gerald

**Comment by KalturaCommunity** [comment]
Hi Gerald,

Thanks, I just pushed a fix for it to 10.19.0 [latest] and 10.20.0 
[nightly]. Can you:
# yum clean all
# yum update kaltura-postinst
which should get you to kaltura-postinst-1.0.28-16 and test?



May the source be with you,

Jess Portnoy

Kaltura Connect Virtual Summits 2015 - now on VOD! [connect.mediaspace.kaltura.com]

**Comment by GeraldNathan** [comment]
will reload and update this thread.

**Comment by GeraldNathan** [comment]
Hi Jess,
Cleaned up - and re loaded successfully.
Couldn't replicate any of the issues. Deploys fine.

Happy week end,
Gerald

**Comment by jessp01** [comment]
Thank you, Gerald.
