### ISSUE TITLE
kaltura-base-config.sh fails with long SERVICE_URL

### ISSUE THREAD

**Issue by michaeljem** [kaltura/platform-install-packages#444]
When installing to CentOS 7 the script kaltura-base-config.sh fails with the message:

sed: -e expression #60, char 109: unterminated `s' command

This was caused by a long SERVICE_URL being used (58 characters) which caused the line:

APP_REMOTE_ADDR_HEADER_SALT=`echo $SERVICE_URL|base64`

to include a new line in the variable which then broke the sed.  Changing the line to:

APP_REMOTE_ADDR_HEADER_SALT=`echo $SERVICE_URL|base64 -w0`

fixed the problem.

**Comment by jessp01** [comment]
Correct you are and thank you for reporting it.
Fixed with:
kaltura-postinst-1.0.28-17.noarch.rpm
and:
kaltura-base_10.21.0-1+b3_all.deb
