### ISSUE TITLE
kaltura-sphinx RPM spec refers non-existing kaltura_group and kaltura_user macros

### ISSUE THREAD

**Issue by wzur** [kaltura/platform-install-packages#454]
kaltura-sphinx RPM spec refers non-existing kaltura_group and kaltura_user macros
I guess they are leftovers after renaming these to sphinx_user and sphinx_group

**Comment by jessp01** [comment]
Hello,

They are defined in RPM/SPECS/kaltura-sphinx.spec lines 1 and 2:
%define sphinx_user kaltura
%define sphinx_group kaltura

So, not sure exactly what you are referring to, can you explain?

**Comment by jessp01** [comment]
Closing this one as per what I wrote about, feel free to reopen and clarify if I am missing something...

**Comment by wzur** [comment]
Hi Jess,

When you fixed #455 didn't you notice the names of macros there? They are %{kaltura_group} and %{kaltura_user}

As you commented yourself, the names should be %{sphinx_user} and %{sphinx_group}

**Comment by jessp01** [comment]
Absolutely right && fixed. Thanks,
