### ISSUE TITLE
Media Not Found

### ISSUE THREAD

**Issue by imransheriff** [kaltura/platform-install-packages#459]
Hi guys, I need some help, I did a clean install and did all configs, and testing out! I am having an issue with HLS AND TRMP MEDIA NOT FOUND but it works with HDS/HTTP

Before anyone say do a search and follow steps I have done it, but still same!

Have tried to update kaltura
Have tried updating sql 
Have tried php plagins update and the Luther php code but still same issue with TRMP/HDS please someone shed some light, and yes I am new to katura

**Comment by imransheriff** [comment]
I ment RTMP

**Comment by jessp01** [comment]
Hello,

How are you trying to play HLS and RTMP? i.e, are you using a CDN for that? using the kaltura-nginx VOD module or?

**Comment by imransheriff** [comment]
I use a cdn to live stream HLS Streams mainly

**Comment by imransheriff** [comment]
can you please look at my other toppic it has all details
