### ISSUE TITLE
HDS play back gives a "no media found" ( 10.19.0 CE on CentOS Linux release 7.1.1503 )

### ISSUE THREAD

**Issue by GeraldNathan** [kaltura/platform-install-packages#464]
HDS playback works in centOS 6 ( 10.16)  with similar setting but not in 7 ( 10.19)

Video link:

http://kac.corpus.com/index.php/extwidget/preview/partner_id/101/uiconf_id/23448134/entry_id/0_8snosjuo/embed/dynamic?&flashvars[akamaiHD]=%7B%22loadingPolicy%22%3A%22preInitialize%22%2C%22asyncInit%22%3A%22true%22%7D&flashvars[twoPhaseManifest]=true&flashvars[streamerType]=hdnetworkmanifest

Client machine is unable to get the hds manifest file:

Tried the following:
1. tried to curl from the local machine file is not found.(from nginx)

http://kac.corpus.com:88/hds/p/101/sp/10100/serveFlavor/entryId/0_8snosjuo/v/12/flavorId/0_,o0e4sjzi,t9lila38,uz8zj8o2,shkeltsk,5f3m40l2,/forceproxy/true/name/a.mp4.urlset/manifest.f4m?g=TMPFMHFHBYDG&hdcore=3.1.0&plugin=aasp-3.1.0.43.124

2. Port 88 is open and is available.

3. [root@kac nginx]# grep ip_range /opt/kaltura/app/configurations/local.ini
internal_ip_range =  207.97.147.202

4. nginx error log:
2015/10/08 18:44:54 [error] 44364#44364: *33 ngx_http_vod_process_header: content length 1926064 exceeds the limit 1090 while reading response header from upstream, client: 207.97.147.202, server: kac.corpus.com, request: "GET /hds/p/101/sp/10100/serveFlavor/entryId/0_8snosjuo/v/12/flavorId/0_,o0e4sjzi,t9lila38,uz8zj8o2,shkeltsk,5f3m40l2,/forceproxy/true/name/a.mp4.urlset/manifest.f4m?g=TMPFMHFHBYDG&hdcore=3.1.0&plugin=aasp-3.1.0.43.124 HTTP/1.1", subrequest: "/__child_request__//hds/p/101/sp/10100/serveFlavor/entryId/0_8snosjuo/v/12/flavorId/0_o0e4sjzi/forceproxy/true/name/a.mp4", upstream: "kalapi://192.168.75.21:80", host: "kac.corpus.com:88", referrer: "http://kac.corpus.com/index.php/extwidget/preview/partner_id/101/uiconf_id/23448134/entry_id/0_8snosjuo/embed/dynamic?&flashvars[akamaiHD]=%7B%22loadingPolicy%22%3A%22preInitialize%22%2C%22asyncInit%22%3A%22true%22%7D&flashvars[twoPhaseManifest]=true&flashvars[streamerType]=hdnetworkmanifest"
2015/10/08 18:44:54 [error] 44364#44364: *33 open() "/etc/nginx/html/50x.html" failed (2: No such file or directory), client: 207.97.147.202, server: kac.corpus.com, request: "GET /hds/p/101/sp/10100/serveFlavor/entryId/0_8snosjuo/v/12/flavorId/0_,o0e4sjzi,t9lila38,uz8zj8o2,shkeltsk,5f3m40l2,/forceproxy/true/name/a.mp4.urlset/manifest.f4m?g=TMPFMHFHBYDG&hdcore=3.1.0&plugin=aasp-3.1.0.43.124 HTTP/1.1", host: "kac.corpus.com:88", referrer: "http://kac.corpus.com/index.php/extwidget/preview/partner_id/101/uiconf_id/23448134/entry_id/0_8snosjuo/embed/dynamic?&flashvars[akamaiHD]=%7B%22loadingPolicy%22%3A%22preInitialize%22%2C%22asyncInit%22%3A%22true%22%7D&flashvars[twoPhaseManifest]=true&flashvars[streamerType]=hdnetworkmanifest"

**Comment by jessp01** [comment]
Hi Gerald,

This is does not seem like an installation issue. Please open it on the server repo.
Thanks,
