### ISSUE TITLE
Kaltiran Community Edition 10.19.0 - Live HLS Stream not working

### ISSUE THREAD

**Issue by imransheriff** [kaltura/platform-install-packages#468]
System1: Centos 6.6 / Kalturak CE 10.19.0
System2: Centos 6.6 / Mistserver / Nimble etc (tested demo streams this works fine, no issues what so ever, i add it to the built in test or even any hls/hds player it works fine)

Scenario: I have finally installed kaltura without issue and its working fine, i have also setup another server with cdn to deliver all sorts of out puts. I want to add these links to kaltura and get the player to support this live link and get stats from it, Also on a schedule it plays videos uploaded!

Problem: when i add the url of the hls it dont load, the kaltural player keeps looking and nothing! what i did was goto Uploads >> Live Stream Entry > Sleeted Manual Stream URL'S from drop down, then added the url (http://123.123.123.123:8080/hls/live/index.m3u8) but they player keeps looping, how do i get this started!

Solotions: Please help me get this sorted???

**Comment by imransheriff** [comment]
yes now it says media not found :(

**Comment by imransheriff** [comment]
please refer the attached
![error](https://cloud.githubusercontent.com/assets/12749335/10417288/bb310e28-7053-11e5-9ecf-1cdd3db5e29a.png)

**Comment by imransheriff** [comment]
okay so what i have noticed is if i add the HLS url ((http://123.123.123.123:8080/hls/live/index.m3u8) to the HDS url field it give media not found (i did this to test it out, i know i am not suppose to do that, checking all my options), but if i add only HLS ((http://123.123.123.123:8080/hls/live/index.m3u8) url and save it, the player keep loading with a continues loop

**Comment by imransheriff** [comment]
Output of Sanity

[root@cast ~]# /opt/kaltura/bin/kaltura-sanity.sh
[Space on /] [PASSED, RC: 0] - [.022174380]
[Space on /opt/kaltura/web] [PASSED, RC: 0] - [.093612193]
[Check httpd daemon status] [PASSED, RC: 0] - [.401379564]
Napping 1 seconds to allow the daemon httpd to finish its init after monit restarted it..
Napping 2 seconds to allow the daemon httpd to finish its init after monit restarted it..
Napping 3 seconds to allow the daemon httpd to finish its init after monit restarted it..
Napping 4 seconds to allow the daemon httpd to finish its init after monit restarted it..
Napping 5 seconds to allow the daemon httpd to finish its init after monit restarted it..
Napping 6 seconds to allow the daemon httpd to finish its init after monit restarted it..
Napping 7 seconds to allow the daemon httpd to finish its init after monit restarted it..
Napping 8 seconds to allow the daemon httpd to finish its init after monit restarted it..
[Check httpd daemon is started by Monit] [PASSED, RC: 0] - [12.504808674]
[check daemon httpd init status] [PASSED, RC: 0] - [1.299692517]
[Check kaltura-sphinx daemon status] [PASSED, RC: 0] - [.794280572]
Napping 1 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
Napping 2 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
Napping 3 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
Napping 4 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
Napping 5 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
Napping 6 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
Napping 7 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
Napping 8 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
[Check kaltura-sphinx daemon is started by Monit] [PASSED, RC: 0] - [11.305329330]
[check daemon kaltura-sphinx init status] [PASSED, RC: 0] - [.031642162]
[Check kaltura-batch daemon status] [PASSED, RC: 0] - [.149692772]
Napping 1 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
Napping 2 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
Napping 3 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
Napping 4 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
Napping 5 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
[Check kaltura-batch daemon is started by Monit] [PASSED, RC: 0] - [5.992245870]
[check daemon kaltura-batch init status] [PASSED, RC: 0] - [.005238465]
[Check kaltura-monit daemon status] [PASSED, RC: 0] - [.117905223]
[check daemon kaltura-monit init status] [PASSED, RC: 0] - [.094950110]
[Check memcached daemon status] [PASSED, RC: 0] - [.701500216]
Napping 1 seconds to allow the daemon memcached to finish its init after monit restarted it..
Napping 2 seconds to allow the daemon memcached to finish its init after monit restarted it..
[Check memcached daemon is started by Monit] [PASSED, RC: 0] - [2.896567807]
[check daemon memcached init status] [PASSED, RC: 0] - [.097624299]
[kaltura-html5lib ver in KMC config.ini] [PASSED, RC: 0] - [1.097675962]
[kaltura-kdp3 ver in KDP3 config.ini] [PASSED, RC: 0] - [.500379785]
[kaltura-kmc ver in KMC config.ini] [PASSED, RC: 0] - [.503639334]
[Get KMC SWFs] [PASSED, RC: 0] - [2.495759727]
[check_testme_page] [PASSED, RC: 0] - [3.197656275]
[check_kmc_index_page] [PASSED, RC: 0] - [.295329229]
[check_admin_console_index_page] [PASSED, RC: 0] - [1.899620413]
[check_studio_index_page] [PASSED, RC: 0] - [.197555837]
[check_clipapp_index_page] [PASSED, RC: 0] - [6.204834847]
[Create Partner] [PASSED, RC: 0] - [36.595433435]
[Local dropfolder creation] [PASSED, RC: 0] - [6.191210726]
[Create flavor param] [PASSED, RC: 0] - [4.682062809]
[Delete flavor param] [PASSED, RC: 0] - [2.201188572]
[HTTP notification: ID: 24, URL: http://localhost/1.php] [PASSED, RC: 0] - [4.682062809]
[Mail notification: ID: 25, Subject: Your video is ready to be played!, Mail body: Hello world:)] [PASSED, RC: 0] - [4.682062809]
[Upload content kaltura_logo_animated_blue.flv] [PASSED, RC: 0] - [8.906524550]
Napping 10 seconds to allow entry 0_2a095vfe to digest..
Napping 10 seconds to allow entry 0_2a095vfe to digest..
Napping 10 seconds to allow entry 0_2a095vfe to digest..
Napping 10 seconds to allow entry 0_2a095vfe to digest..
Napping 10 seconds to allow entry 0_2a095vfe to digest..
Napping 10 seconds to allow entry 0_2a095vfe to digest..
Napping 10 seconds to allow entry 0_2a095vfe to digest..
Napping 10 seconds to allow entry 0_2a095vfe to digest..
Napping 10 seconds to allow entry 0_2a095vfe to digest..
[kaltura_logo_animated_blue.flv - 0_2a095vfe status] [FAILED, RC: 1] - [-5.596220848]
Napping 30 seconds to allow mail to be sent out..
[Found an email sending entry for mb-cast.serverlogic.net@kaltura.com[PID is 102] in /var/log/maillog] [PASSED, RC: 0] - [30.492581301]
Testing analytics, be patient..

Please note: if you are running this test on a clustered ENV, it will fail but this does not mean there is an actual problem.
The tech information as to why is available here:
https://github.com/kaltura/platform-install-packages/issues/106#issuecomment-42837404

[DWH cycle] [FAILED, RC: 255] - [10.198259009]
[Upload content kaltura_logo_animated_green.flv] [PASSED, RC: 0] - [39.898593639]
[Upload bulk using CSV] [PASSED, RC: 0] - [28.799356761]
[Upload bulk using XML] [PASSED, RC: 0] - [19.502096265]
[Create player] [PASSED, RC: 0] - [10.404271797]
[Generate thumb] [PASSED, RC: 0] - [8.502956272]
[Delete partner] [PASSED, RC: 0] - [24.000918116]
[Red5 file upload] [SKIPPED as OflaDemo isn't configured]
see: https://github.com/kaltura/platform-install-packages/blob/master/doc/install-kaltura-redhat-based.md#configure-red5-server


Thank you for running Kaltura! To keep Kaltura viable, stable and well tested, please join the community and help by contributing sanity tests that verify overall platform stability: http://bit.ly/kaltura-ci , and by contributing to the project roadmap by solving simple tasks and challenges: http://bit.ly/kaltura-tasks.

You have new mail in /var/spool/mail/root

**Comment by imransheriff** [comment]
From the above i can only see two fails

[kaltura_logo_animated_blue.flv - 0_2a095vfe status] [FAILED, RC: 1] - [-5.596220848]
[DWH cycle] [FAILED, RC: 255] - [10.198259009]

**Comment by jessp01** [comment]
Closing this one as we already have a discussion going on here:
http://forum.kaltura.org/t/kaltiran-community-edition-10-19-0-live-hls-stream-not-working/3623/13
@imransheriff, please update as to the issues you're having there.
