### ISSUE TITLE
MariaDB client with kaltura-server on Debian 8

### ISSUE THREAD

**Issue by JHGitty** [kaltura/platform-install-packages#470]
I want to use ``kaltura-server`` on Debian 8. I have installed ``mariadb-client-core-10.0``.
MariaDB is a fork of MySQL. I really need to use MariaDB.

I cannot install the debian package ``kaltura-server`` because it requires ``mysql-client``. But I use ``mariadb-client-core-10.0``.

So please add the mariadb client to requirements as alternative for mysql-client on the debian package.

How can I bypass this issue? I want to install Kaltura.

Thank you.

**Comment by jessp01** [comment]
Hello,

See https://github.com/kaltura/platform-install-packages/commit/a8486e2f021b2b7c2f29153f0fd3b63cb8bf62b7

The package was pushed to the nightly repo.
To use it, simple edit /etc/apt/sources.list.d/kaltura.list to read:
deb [arch=amd64] http://installrepo.origin.kaltura.org/repo/apt/debian-nightly kajam main

and install as normal.

Let me know if you have any issues.

**Comment by JHGitty** [comment]
You changes ffmpeg to a very high version. Is that right or was that a mistake?

**Comment by KalturaCommunity** [comment]
Not a mistake..

May the source be with you,

Jess Portnoy

Kaltura Connect Virtual Summits 2015 - now on VOD! [connect.mediaspace.kaltura.com]

**Comment by JHGitty** [comment]
Cannot install it.

The package is named "mariadb-client-10.0".

```bash
Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 kaltura-base : Hängt ab von: mysql-client oder
                               mariadb-client soll aber nicht installiert werden
```

I think you should use a star behind "client" :)

**Comment by Huskynarr** [comment]
:+1:

**Comment by KalturaCommunity** [comment]
Hi,

Nope. When specifying deps in the control file, one should not use 
wildcards.

If one needs to specify a specific ver is needed, one needs to do:
Depends: mariadb-client-5.5 (>= $SOME_VERSION)

You should have a package called mariadb-client, see:
https://packages.debian.org/search?keywords=mariadb-client

And also, on my machine:
# aptitude show mariadb-client
Package: mariadb-client
New: yes
State: not installed
Version: 5.5.44-1ubuntu0.14.04.1
Priority: optional
Section: universe/database
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: all
Uncompressed Size: 66.6 k
Depends: mariadb-client-5.5 (>= 5.5.44-1ubuntu0.14.04.1)
Description: MariaDB database client (metapackage depending on the latest 
version)
  This is an empty package that depends on the current "best" version of 
mariadb-client (currently mariadb-client-5.5), as determined by
  the MariaDB maintainers.  Install this package if in doubt about which 
MariaDB version you want, as this is the one considered to be
  in the best shape.
Homepage: http://mariadb.org/


As you can see, the package mariadb-client is a virtual package which, for 
my version of Ubuntu, depends on mariadb-client-5.5, in your case, it may 
depend on a higher version but it should still be pulled.

I don't read German but Google translate says the message APT threw your 
way is:

The following packages have unmet dependencies:
   Kaltura-base: Depends: mysql-client or MariaDB client but is not 
intended to be installed


Lets start by your pasting the output for:
# aptitude show mariadb-client

and also, lets make sure you are able to install that package with:
# aptitude install mariadb-client

and we can take it from there.

May the source be with you,

Jess Portnoy

Kaltura Connect Virtual Summits 2015 - now on VOD! [connect.mediaspace.kaltura.com]

**Comment by JHGitty** [comment]
Ah, thank you! :+1:

**Comment by jessp01** [comment]
Are we good now?

**Comment by JHGitty** [comment]
This issue is fixed (I think). But there is a new issue. #471
