### ISSUE TITLE
Jupiter 10.21 fresh install for centos /bin/chown: invalid user: `kaltura:adm'

### ISSUE THREAD

**Issue by jdubb333** [kaltura/platform-install-packages#474]
[root@oshflkal1 postfix]#  rpm -q kaltura-base
kaltura-base-10.21.0-11.noarch

**Comment by jessp01** [comment]
Hello,

The kaltura user is created at the preinst phase of the kaltura-base RPM.
what's the output for:
\# rpm -q kaltura-base
?

You can see the code creating that user with:
\# rpm -q kaltura-base --scripts

**Comment by jdubb333** [comment]
rpm -q kaltura-base
kaltura-base-10.21.0-11.noarch

**Comment by jessp01** [comment]
What's the output for:
\# id kaltura
\# id adm
?

If the user kaltura does not exist, try running the below code from the shell as root and lets see what it is fail on:
getent group kaltura >/dev/null || groupadd -r kaltura -g7373 2>/dev/null
getent passwd kaltura >/dev/null || useradd -M -r -u7373 -d /opt/kaltura -s /bin/bash -c "Kaltura server" -g kaltura kaltura 2>/dev/null

getent group apache >/dev/null || groupadd -g 48 -r apache
getent passwd apache >/dev/null || \
  useradd -r -u 48 -g apache -s /sbin/nologin \
    -d /var/www -c "Apache" apache
usermod -a -G kaltura apache

usermod -g kaltura kaltura 2>/dev/null || true

**Comment by jdubb333** [comment]
Thank you Kaltura exists just not a member of adm
# id kaltura
uid=7373(kaltura) gid=7373(kaltura) groups=7373(kaltura),48(apache)
# id adm
uid=3(adm) gid=4(adm) groups=4(adm),3(sys)

]#

**Comment by jessp01** [comment]
No need for kaltura to be a member of adm for this to work.
when are you getting this error?

**Comment by jdubb333** [comment]
during the Kaltura install , I have not completed the config steps yet.

I had a previous install and had issues with dwh and internal server error opening kmc (which went away when choosing OK twice).. but starting fresh and I had not seen this error before, so was inquiring , thank you for your time.

**Comment by jessp01** [comment]
No problem. I am closing this issue but if you are able to tell me at exactly which phase you got this, I'll be happy to look into it. In any case, run the post configs, this error should not stop you.
