### ISSUE TITLE
Jupiter fresh install sphinx populate initializing restart did not fix

### ISSUE THREAD

**Issue by jdubb333** [kaltura/platform-install-packages#475]
During  /opt/kaltura/bin/kaltura-config-all.sh
generating UI confs..
Shutting down monit:                                       [FAILED]
Starting monit: checksum: file /opt/kaltura/app/configurations/sphinx/populate/.ini is not regular file
/opt/kaltura/app/configurations/monit/monit.d/enabled.sphinx.populate.rc:13: Cannot compute a checksum for file /opt/kaltura/app/configurations/sphinx/populate/.ini 'restart'
Starting Monit 5.13 daemon with http interface at [*]:2812
                                                           [  OK  ]
Running Batch config...

completed the rest of configuration:
However Monitoring shows kaltura sphinx populate script initializing 
sphinx populate.conf does not exist , 
sphinx populate initializing 

Conf file exists but appears to be missing @servername@:

[root@oshflkal1 populate]# cat oshflkal1.xxx.xxx.com.ini
sphinxServer = 127.0.0.1

 cat populate.conf

sphinxServer =
sphinxPort = @SPHINX_PORT@

cat populate.conf.template

sphinxServer = @SPHINX_SERVER@
sphinxPort = @SPHINX_PORT@

![image](https://cloud.githubusercontent.com/assets/15221223/10645613/a3417a9a-77fc-11e5-8c77-975f31dd418f.png)

How can I fix?
Thank you for your time

**Comment by KalturaCommunity** [comment]
Hello,

This is a bug:)
I just released kaltura-postinst-1.0.28-23 which fixes it.
It will take a while to sync to all CDN edges but you can also take it 
directly with:
# rpm -Uhv 
http://installrepo.origin.kaltura.org/repo/releases/10.21.0/RPMS/noarch/kaltura-postinst-1.0.28-23.noarch.rpm

and then rerun the config script.

Thanks for reporting it,

May the source be with you,

Jess Portnoy

Kaltura Connect Virtual Summits 2015 - now on VOD! [connect.mediaspace.kaltura.com]

**Comment by jdubb333** [comment]
Wow that was fast,! I will give it a spin thank you
we can close

**Comment by jdubb333** [comment]
Same outcome, monitor still says initializing , and conf not found  (did a restart of server as well)

Received this during config_all.sh:

Starting monit: checksum: file /opt/kaltura/app/configurations/sphinx/populate/127.0.0.1.ini is not regular file
/opt/kaltura/app/configurations/monit/monit.d/enabled.sphinx.populate.rc:13: Cannot compute a checksum for file /opt/kaltura/app/configurations/sphinx/populate/127.0.0.1.ini 'restart'
Starting Monit 5.13 daemon with http interface at [*]:2812

Contents of populate looks better:

[root@oshflkal1 populate]# cat populate.conf

sphinxServer = 127.0.0.1
sphinxPort = 9312

Thanks again,

**Comment by KalturaCommunity** [comment]
Hi,

What files do you have under 
/opt/kaltura/app/configurations/sphinx/populate?

It complaining that it cannot find a file called 
/opt/kaltura/app/configurations/sphinx/populate/127.0.0.1.ini

My guess is you DO have a file that instead has `hostname`.ini as name, if 
so, then the fix for it is quite simple, just want to confirm.

Thanks,

May the source be with you,

Jess Portnoy

Kaltura Connect Virtual Summits 2015 - now on VOD! [connect.mediaspace.kaltura.com]

**Comment by jdubb333** [comment]
you are correct:
[root@oshflkal1 populate]# ll /opt/kaltura/app/configurations/sphinx/populate
total 16
-rw-r--r--. 1 root root 25 Oct 21 15:40 oshflkal1.xx.xxxx.com.ini
-rw-r--r--. 1 root root 44 Oct 21 15:39 populate.conf
-rw-r--r--. 1 root root 44 Oct 21 15:39 populate.conf.backup
-rw-r--r--. 1 root root 59 Oct 15 09:31 populate.conf.template
[root@oshflkal1 populate]#

**Comment by KalturaCommunity** [comment]
Great. Fixed with kaltura-postinst-1.0.28-24.
Please confirm,

May the source be with you,

Jess Portnoy

Kaltura Connect Virtual Summits 2015 - now on VOD! [connect.mediaspace.kaltura.com]

**Comment by jdubb333** [comment]
yes it is Fixed, Thank you!

**Comment by jessp01** [comment]
Great && happy Kalturing,

Sent by Outlook<http://taps.io/outlookmobile> for Android



On Wed, Oct 21, 2015 at 1:37 PM -0700, "jdubb333" <notifications@github.com<mailto:notifications@github.com>> wrote:


yes it is Fixed, Thank you!

-
