### ISSUE TITLE
error code: Server:INVALID_KS

### ISSUE THREAD

**Issue by iwaninfor** [kaltura/platform-install-packages#478]
i have succes for installed kaltura, but when i run admin_console/index.php/partner/list. i have error 

An error occurred

(error code: Server:INVALID_KS)

i check in /opt/kaltura/log/kaltura_apache_errors.log, i have error 

File does not exist: /opt/kaltura/app/alpha/web/opt,

can someone help me with this error ?

**Comment by zoharbabin** [comment]
Please review the general troubleshooting procedure here:
https://github.com/kaltura/platform-install-packages/blob/master/doc/kaltura-packages-faq.md#general-troubleshoot-procedure
and post any findings back.

Also - what system are you using, is it a single server or a cluster, and did you experience any problems during the installation?

**Comment by jessp01** [comment]
Hello @iwaninfor,

Seeing how this does not sound like a general bug but more a specific issue, please post to forum.kaltura.org instead and we'll be happy to further assist.
As Zohar said, look at the troubleshooting section, and more specifically, from the server's shell, run:
\# kaltlog
while making the request and look at the output. Please paste it along with info as to what system you're using in the forum post.

Thanks,
