### ISSUE TITLE
Integrating kaltura player

### ISSUE THREAD

**Issue by kjt1212** [kaltura/platform-install-packages#482]
Hi, I am completely new to the video domain. As an intern my task is to integrate the kaltura player in a html page and display a pre-roll vast ad. I am quite at a loss for this one. In order to integrate this player do i need to install the server as well as specified in the step-by-step guide? Please help me get started.

**Comment by jessp01** [comment]
Hello,

For this task, you do not need to install your own server, although, of course, you are welcome to do so:)
You can just open a free trial account on our SaaS and embed a player from there.
To do so, you can either go to corp.kaltura.com and sign up or go to developer.kaltura.org.
You can also see code examples for what you need to do here:
https://developer.kaltura.org/recipes/dynamic_thumbnails

And also on knowledge.kaltura.com.

For more questions, please post at forum.kaltura.org.
