### ISSUE TITLE
Error on install Kaltura from Vagrantfile

### ISSUE THREAD

**Issue by leosuncin** [kaltura/platform-install-packages#484]
Inside `kaltura-install.sh` MySQL root password is set to "vagrant" and when run `vagrant up` throw a error, fixed change to $MYSQL_ROOT_PASSWORD variable from `kaltura-install-config.sh` https://github.com/kaltura/platform-install-packages/pull/483

**Comment by jessp01** [comment]
https://github.com/kaltura/platform-install-packages/pull/483
Was merged, thanks.
