### ISSUE TITLE
Kaltura + Canvas integration. Problem with saving records from web camera.

### ISSUE THREAD

**Issue by ally1** [kaltura/platform-install-packages#485]
Hello,

I have working Canvas LMS and Kaltura.
Red5 server was insalled and integrated with Kltura.
This two instances were installed from next URLs:
https://github.com/instructure/canvas-lms/wiki/Production-Start
https://github.com/kaltura/platform-install-packages/blob/master/doc/install-kaltura-deb-based.md

Canvas and Kaltura located on different servers and works well. 
I integrated Kaltura with Canvas successfully.

I am able to upload audio/video via "Upload Media" option. 
But when I try to use "Record Media" option next click allow,  
https://www.dropbox.com/s/cuemyu6n3pthysm/2015-11-02_18-46.jpg?dl=0 .
Web cam. turn on and begin to record. After a few seconds I click stop the and get:
https://www.dropbox.com/s/ices101kyr0ahwi/2015-11-02_18-49_Nuevo%20anuncio.jpg?dl=0
And this always show connecting and never return back.

It seems like the problem with Red5 streaming media server.
How can I resolve this issue? 

May be someone had experience with similar problem. 
Thanks for the advice.

**Comment by jessp01** [comment]
Hello,

We have received a previous report about a similar issue with Red5 and Krecord and are looking into it.
Can you please confirm that webcam recording from within KMC [which uses a different widget] does work?

Thanks,

**Comment by zoharbabin** [comment]
@ally1 - in addition to the above, can you also provide a link to the page that isn't working for you?

**Comment by ally1** [comment]
Hello,

Thanks for the quick response.
jessp01 you wrote:
>We have received a previous report about a similar issue with Red5 and Krecord and are looking into it.
>Can you please confirm that webcam recording from within KMC [which uses a different widget] does work?

Yes I am able to write the webcam recording directly from KMC. Video saves fine and I can view it earlier. But when I try to do the same via Canvas LMS the process of saving video does not never stop.

zoharbabin you wrote:
> in addition to the above, can you also provide a link to the page that isn't working for you?

I think you did not understand me correctly. Let me try to clarify here.
Steps I did:

- I log into Canvas LMS instance;
- choose course navigate to "Assignments" > "New assignment" > 
here is screenshot: https://www.dropbox.com/s/sd4gc47dy022y6h/2015-11-03_11-16_Edit%20assignment.jpg?dl=0
- click to the "Record Media";
- all next steps described in first message.

Thanks.

**Comment by zoharbabin** [comment]
@ally1 - thanks, I meant if you can share a link to your canvas where we can test it on your installation. feel free to contact me via Skype (z.babin)

**Comment by ally1** [comment]
Hi jessp01,

How can I check, was this issue solved or not? 
Thanks.

**Comment by jessp01** [comment]
Closing this one as we no longer support Red5 or the kRecord Flash widget.
