### ISSUE TITLE
HTML5 Player media not found

### ISSUE THREAD

**Issue by devangbhagdev** [kaltura/platform-install-packages#496]
I installed community edition of kaltura at my server
And configured all the needful things
Also configured S3 storage

Its working with flash player but not with HTML5 Player

I can show controls and show statistics with right click option

But in Statistics I am getting
Media : (Source not found)

Please see (https://cloud.githubusercontent.com/assets/4122298/11557378/6dd06734-99d2-11e5-8264-4ae125ea4986.png)

Please help me
![screenshot from 2015-12-03 15 26 14]

**Comment by jessp01** [comment]
Hello,

I am closing this one in favour of https://forum.kaltura.org/t/html5-player-not-working/3997/5 since we'd rather keep the Github issues section for general bug reports and not specific issues.
Please see my request on the forum thread.
