### ISSUE TITLE
SPHINX_DB_HOST and SPHINX_DB_PORT are not used from the answer file, but still required in kaltura-base-config.sh

### ISSUE THREAD

**Issue by wzur** [kaltura/platform-install-packages#497]
During post installation run of kaltura-base-config.sh, content of both SPHINX_DB_HOST and SPHINX_DB_PORT is overwritten by DB1_HOST and DB1_PORT variables. That makes this variables obsolete, but still required in kaltura-base-config.sh when it checks if variables are present in the answer file.

**Comment by jessp01** [comment]
You are right - corrected && thanks.
Available from 11.3.0 in kaltura-postinst-1.0.30-4.noarch.rpm.
