### ISSUE TITLE
Studio tab shows "Not Found"

### ISSUE THREAD

**Issue by kfr-** [kaltura/platform-install-packages#498]
Not Found
 The requested URL /apps/studio/v2.0.2/index.html was not found on this server.

 ls -lathr /opt/kaltura/apps/studio/v2.0.1/
total 260K
-rw-r--r--.  1 root root  45K Sep 17 09:05 templates.js
-rw-r--r--.  1 root root  512 Sep 17 09:05 studio.template.ini
-rw-r--r--.  1 root root  52K Sep 17 09:05 main.min.js
-rw-r--r--.  1 root root 101K Sep 17 09:05 main.js
-rw-r--r--.  1 root root 2.3K Sep 17 09:05 index.html
drwxr-xr-x.  3 root root 4.0K Dec 10 11:57 ..
drwxr-xr-x.  9 root root 4.0K Dec 10 11:57 __MACOSX
drwxr-xr-x.  3 root root 4.0K Dec 10 11:57 css
drwxr-xr-x.  2 root root 4.0K Dec 10 11:57 fonts
drwxr-xr-x.  2 root root 4.0K Dec 10 11:57 i18n
drwxr-xr-x.  2 root root 4.0K Dec 10 11:57 img
drwxr-xr-x.  3 root root 4.0K Dec 10 11:57 js
drwxr-xr-x.  2 root root 4.0K Dec 10 11:57 lib
drwxr-xr-x.  2 root root 4.0K Dec 10 11:57 vendor
-rw-r--r--   1 root root  520 Dec 10 15:47 studio.ini.backup
-rw-r--r--   1 root root  520 Dec 10 15:47 studio

**Comment by kfr-** [comment]
kaltura-libfaac-1.26-1.x86_64
kaltura-base-11.4.0-4.noarch
kaltura-kdp3wrapper-v37.0-1.noarch
kaltura-flexwrapper-v1.2-1.noarch
kaltura-kdp3-v3.9.9-2.noarch
kaltura-sphinx-2.2.1-17.x86_64
kaltura-pentaho-4.2.1-2.x86_64
kaltura-mencoder-3.4.6-9.x86_64
kaltura-monit-5.13-1.x86_64
kaltura-ffmpeg-2.7.2-2.x86_64
kaltura-segmenter-1.0-2.x86_64
kaltura-nginx-1.8.0-9.x86_64
kaltura-postinst-1.0.30-4.noarch
kaltura-kupload-1.0.0-1.noarch
kaltura-kclip-v1.1.2.1-2.noarch
kaltura-kvpm-v1.0.6-1.noarch
kaltura-clipapp-1.3-2.noarch
kaltura-krecord-1.0.0-1.noarch
kaltura-kdp-v2.7.0-1.noarch
kaltura-widgets-1.0.0-8.noarch
kaltura-front-11.4.0-1.noarch
kaltura-dwh-9.5.0-2.noarch
kaltura-batch-11.4.0-1.noarch
kaltura-libass-0.9.11-2.x86_64
kaltura-x264-0.140-2.20140104.x86_64
kaltura-lame-3.99.5-3.x86_64
kaltura-libopencore-amr-0.1.2-2.x86_64
kaltura-librtmp-2.3-2.x86_64
kaltura-ffmpeg-aux-2.1.3-1.x86_64
kaltura-kmc-v5.39.11-4.noarch
kaltura-kdpwrapper-v11.0-1.noarch
kaltura-kcw-1.0.0-6.noarch
kaltura-html5lib-v2.37.3-1.noarch
kaltura-server-11.4.0-1.noarch
kaltura-release-11.3.0-1.noarch
kaltura-html5-studio-v2.0.1-1.noarch
kaltura-a52dec-0.7.4-11.x86_64
kaltura-sshpass-1.05-1.x86_64
kaltura-libmemcached-1.0.16-2.x86_64

**Comment by kfr-** [comment]
This is a fresh install from today.

**Comment by jessp01** [comment]
Hello,

Thank you for your report. This is fixed with kaltura-html5-studio-v2.0.2-1.
To upgrade:
\# yum clean all
\# yum update kaltura-html5-studio
if running a single server:
\# /opt/kaltura/bin/kaltura-config-all.sh
if running a cluster, on the node where kaltura-html5-studio is installed:
\# kaltura-base-config.sh
\# kaltura-front-config.sh

Note that you can pass the answer file created in the prev install so that you don't need to reinput all the values.

The answer file is always created under /tmp/kaltura_*.ans.
