### ISSUE TITLE
Why the question happen when I install kaltura

### ISSUE THREAD

**Issue by fcxjluo** [kaltura/platform-install-packages#508]
Checking connectivity to needed daemons...
Connectivity test passed:)
Cleaning cache..
Populating DB with data.. please wait..
Output for /opt/kaltura/app/deployment/base/scripts/installPlugins.php being logged into /opt/kaltura/log/installPlugins.log 
Output for /opt/kaltura/app/deployment/base/scripts/insertDefaults.php being logged into /opt/kaltura/log/insertDefaults.log 
Output for /opt/kaltura/app/deployment/base/scripts/insertPermissions.php being logged into /opt/kaltura/log/insertPermissions.log 
Output for /opt/kaltura/app/deployment/base/scripts/insertContent.php being logged into /opt/kaltura/log/insertContent.log 

kaltura-db-config.sh FAILED with: 61582 on line 182

Archving logs to /opt/kaltura/log/log_07_01_16_16_36.tar.gz...
ERROR: we failed on something else..

**Comment by jessp01** [comment]
Hello,

This is not a question, it is a failure in the DB population phase.
Look at /opt/kaltura/log/insertContent.log  to understand what failed. 
Mostly likely, you provided a service URL which cannot be reached.
After looking at the log, if you need further assistance, post to forum.kaltura.org explaining exactly what the failing request was and detailing which version you are trying to install and rather it is deb or RPM.
