### ISSUE TITLE
kaltura-db-config.sh FAILED with: 14060 on line 184

### ISSUE THREAD

**Issue by friedlsa** [kaltura/platform-install-packages#515]
Hello,
I am trying to install Kaltura on a Centos 7 (7.2.1511).
When running the script  kaltura-config-all.sh i get the following error:
`CREATE USER kaltura;
CREATE USER etl;
CREATE DATABASE kaltura;
CREATE DATABASE kaltura_sphinx_log;
CREATE DATABASE kalturadw;
CREATE DATABASE kalturadw_ds;
CREATE DATABASE kalturadw_bisources;
CREATE DATABASE kalturalog;
Checking connectivity to needed daemons...
Connectivity test passed:)
Cleaning cache..
Populating DB with data.. please wait..
Output for /opt/kaltura/app/deployment/base/scripts/installPlugins.php being logged into /opt/kaltura/log/installPlugins.log
Output for /opt/kaltura/app/deployment/base/scripts/insertDefaults.php being logged into /opt/kaltura/log/insertDefaults.log
Output for /opt/kaltura/app/deployment/base/scripts/insertPermissions.php being logged into /opt/kaltura/log/insertPermissions.log
Output for /opt/kaltura/app/deployment/base/scripts/insertContent.php being logged into /opt/kaltura/log/insertContent.log

kaltura-db-config.sh FAILED with: 17044 on line 184

Archving logs to /opt/kaltura/log/log_08_02_16_16_31.tar.gz...`

In the file /opt/kaltura/app/deployment/base/scripts/insertContent.php being logged into /opt/kaltura/log/insertContent.log I get the following content:
`Queuing action [userRole.add]
Queuing action [user.add]
Executing multirequest
service url: [http://mykaltura.mydomain.ch]
curl: http://mykaltura.mydomain.ch/api_v3/service/multirequest
post: {"format":"3","ignoreNull":true,"clientTag":"php5:16-02-08","apiVersion":"3.3.0","0":{"service":"userrole","action":"add","userRole":{"objectType":"KalturaUserRole","name":"System Administrator","systemName":"System Administrator","description":"System Administrator","status":"1","permissionNames":"*","tags":"admin_console"},"ks":"NTkxMWJiZjZiYzFiYTZiM2FjNDkxNjAyMDU4YjQ5NmYxYTI4MjA0OHwtMjstMjsxNDU1MDM1NDgzOzI7MTYwNjc7Ow=="},"1":{"service":"user","action":"add","user":{"objectType":"KalturaUser","id":"samuel.friedli@mydomain.ch","screenName":"samuel.friedli@mydomain.ch","fullName":"Kaltura Administrator","email":"samuel.friedli@mydomain.ch","status":"1","password":"SUcardper16$","isAdmin":"1","roleIds":"{1:result:id}","allowedPartnerIds":"*"},"ks":"NTkxMWJiZjZiYzFiYTZiM2FjNDkxNjAyMDU4YjQ5NmYxYTI4MjA0OHwtMjstMjsxNDU1MDM1NDgzOzI7MTYwNjc7Ow=="},"kalsig":"38e73b3b76f66a2c950b3c629c75ae35"}
PHP Fatal error:  Uncaught exception 'KalturaException' with message 'Internal server error occurred' in /opt/kaltura/app/tests/standAloneClient/exec.php:351
Stack trace:
#0 {main}
  thrown in /opt/kaltura/app/tests/standAloneClient/exec.php on line 351
server: [mykaltura.mydomain.ch], session: [723999916]
result (serialized): a:2:{i:0;O:15:"KalturaUserRole":10:{s:2:"id";i:9;s:4:"name";s:20:"System Administrator";s:10:"systemName";s:20:"System Administrator";s:11:"description";s:20:"System Administrator";s:6:"status";i:1;s:9:"partnerId";i:-2;s:15:"permissionNames";s:5821:"AUDIT_PLUGIN_PERMISSION,FEATURE_MOBILE_FLAVORS,scheduledTask.SYSTEM_ADMIN_MANAGE,ADMIN_USER_ASSIGN_PARNTERS,dropFolder.SYSTEM_ADMIN_DROP_FOLDER_BASE,dropFolder.SYSTEM_ADMIN_DROP_FOLDER_MODIFY,eventNotification.SYSTEM_ADMIN_EVENT_NOTIFICATION_BASE,eventNotification.SYSTEM_ADMIN_EVENT_NOTIFICATION_MODIFY,GLOBAL_PARTNER_UI_CONF_UPDTAE,METADATA_PLUGIN_PERMISSION,PARTNER_-2_GROUP_*_PERMISSION,systemPartner.SYSTEM_ADMIN_PUBLISHER_CONFIG_ACCOUNT_INFO,systemPartner.SYSTEM_ADMIN_PUBLISHER_CONFIG_ADMIN_KMC_USERS,systemPartner.SYSTEM_ADMIN_PUBLISHER_CONFIG_GENERAL_INFORMATION,systemPartner.SYSTEM_ADMIN_PUBLISHER_CONFIG_GROUP_OPTIONS,systemPartner.SYSTEM_ADMIN_PUBLISHER_CONFIG_OPTIONS_MONITOR_USAGE,systemPartner.SYSTEM_ADMIN_PUBLISHER_CONFIG_PACKAGES_SERVICE,systemPartner.SYSTEM_ADMIN_PUBLISHER_CONFIG_PACKAGES_SERVICE_PAID,systemPartner.SYSTEM_ADMIN_PUBLISHER_CONFIG_TECH_DATA,SYSTEM_ADMIN_BASE,SYSTEM_ADMIN_BATCH_CONTROL,SYSTEM_ADMIN_BATCH_CONTROL_FAILED,SYSTEM_ADMIN_BATCH_CONTROL_INPROGRESS,SYSTEM_ADMIN_BATCH_CONTROL_SETUP,SYSTEM_ADMIN_CONTENT_DISTRIBUTION_BASE,SYSTEM_ADMIN_CONTENT_DISTRIBUTION_MODIFY,SYSTEM_ADMIN_DEVELOPERS_TAB,SYSTEM_ADMIN_EMAIL_INGESTION,SYSTEM_ADMIN_ENTRY_INVESTIGATION,SYSTEM_ADMIN_MANAGE_TEMPLATE_PARTNERS,SYSTEM_ADMIN_MP_REDIRECT,SYSTEM_ADMIN_PARTNER_CONFIGURATION_VIEW,SYSTEM_ADMIN_PERMISSIONS_MANAGE,SYSTEM_ADMIN_PUBLISHER_ADD,SYSTEM_ADMIN_PUBLISHER_BASE,SYSTEM_ADMIN_PUBLISHER_BLOCK,SYSTEM_ADMIN_PUBLISHER_CONFIG,SYSTEM_ADMIN_PUBLISHER_KMC_ACCESS,SYSTEM_ADMIN_PUBLISHER_LIST_COMMERCIAL,SYSTEM_ADMIN_PUBLISHER_REMOVE,SYSTEM_ADMIN_PUBLISHER_RESET_USER_PASSWORD,SYSTEM_ADMIN_PUBLISHER_USAGE,SYSTEM_ADMIN_REPORTS_READ,SYSTEM_ADMIN_REPORTS_UPDATE,SYSTEM_ADMIN_STORAGE,SYSTEM_ADMIN_SYSTEM_MONITOR,SYSTEM_ADMIN_USER_MANAGE,SYSTEM_ADMIN_VIRUS_SCAN,SYSTEM_ADMIN_WIDGET,SYSTEM_FILESYNC,SYSTEM_INTERNAL,VIRUSSCAN_PLUGIN_PERMISSION,drm.SYSTEM_ADMIN_DRM_PROFILE_BASE,drm.SYSTEM_ADMIN_DRM_PROFILE_MODIFY,drm.SYSTEM_ADMIN_DRM_POLICY_BASE,drm.SYSTEM_ADMIN_DRM_POLICY_MODIFY,playReady.PLAY_READY_ADMIN,SYSTEM_ADMIN_DELIVERY,SYSTEM_BASE_DELIVERY,eventNotification.SYSTEM_ADMIN_EVENT_NOTIFICATION_INSERT,businessProcessNotification.SYSTEM_ADMIN_ABORT,CONTENT_MANAGE_ASSIGN_USER_GROUP,ACCESS_CONTROL_ADD,ACCESS_CONTROL_BASE,ACCESS_CONTROL_DELETE,ACCESS_CONTROL_UPDATE,ACCOUNT_BASE,ACCOUNT_UPDATE_SETTINGS,adCuePoint.MANAGE,ADMIN_BASE,ADMIN_PERMISSION_ADD,ADMIN_PERMISSION_DELETE,ADMIN_PERMISSION_UPDATE,ADMIN_PUBLISHER_MANAGE,ADMIN_ROLE_ADD,ADMIN_ROLE_DELETE,ADMIN_ROLE_UPDATE,ADMIN_USER_ADD,ADMIN_USER_BULK,ADMIN_USER_DELETE,ADMIN_USER_UPDATE,ADMIN_WHITE_BRANDING,ADVERTISING_BASE,ADVERTISING_UPDATE_SETTINGS,ALWAYS_ALLOWED_ACTIONS,ALWAYS_ALLOWED_FROM_INTERNAL_IP_ACTIONS,ANALYTICS_BASE,ANALYTICS_SEND_DATA,ASPERA_BASE_PERMISSION,ATTACHMENT_MODIFY,AUDIT_TRAIL_ADD,AUDIT_TRAIL_BASE,BASE_USER_SESSION_PERMISSION,BULK_LOG_BASE,BULK_LOG_DELETE,BULK_LOG_DOWNLOAD,BULK_LOG_DOWNLOAD_EMAIL,CAPTION_MODIFY,CAPTION_SEARCH,CONTENT_INGEST_BASE,CONTENT_INGEST_BULK_UPLOAD,CONTENT_INGEST_CLIP_MEDIA,CONTENT_INGEST_EXTERNAL_SEARCH,CONTENT_INGEST_FEED,CONTENT_INGEST_INTO_ORPHAN,CONTENT_INGEST_INTO_READY,CONTENT_INGEST_ORPHAN_AUDIO,CONTENT_INGEST_ORPHAN_VIDEO,CONTENT_INGEST_REFERENCE_MODIFY,CONTENT_INGEST_REMOTE_STORAGE,CONTENT_INGEST_REPLACE,CONTENT_INGEST_UPLOAD,CONTENT_INGEST_WEBCAM,CONTENT_MANAGE_ACCESS_CONTROL,CONTENT_MANAGE_ANNOTATION,CONTENT_MANAGE_ASSIGN_CATEGORIES,CONTENT_MANAGE_BASE,CONTENT_MANAGE_CATEGORY_USERS,CONTENT_MANAGE_CUSTOM_DATA,CONTENT_MANAGE_DELETE,CONTENT_MANAGE_DISTRIBUTION_BASE,CONTENT_MANAGE_DISTRIBUTION_PROFILE_MODIFY,CONTENT_MANAGE_DISTRIBUTION_REMOVE,CONTENT_MANAGE_DISTRIBUTION_SEND,CONTENT_MANAGE_DISTRIBUTION_WHERE,CONTENT_MANAGE_DOWNLOAD,CONTENT_MANAGE_EDIT_CATEGORIES,CONTENT_MANAGE_EMBED_CODE,CONTENT_MANAGE_ENTRY_USERS,CONTENT_MANAGE_EXPORT,CONTENT_MANAGE_METADATA,CONTENT_MANAGE_MIX,CONTENT_MANAGE_RECONVERT,CONTENT_MANAGE_SCHEDULE,CONTENT_MANAGE_SHARE,CONTENT_MANAGE_THUMBNAIL,CONTENT_MANAGE_VIRUS_SCAN,CONTENT_MODERATE_APPROVE_REJECT,CONTENT_MODERATE_BASE,CONTENT_MODERATE_CUSTOM_DATA,CONTENT_MODERATE_METADATA,cuePoint.MANAGE,CUSTOM_DATA_FIELD_ADD,CUSTOM_DATA_FIELD_DELETE,CUSTOM_DATA_FIELD_UPDATE,CUSTOM_DATA_PROFILE_ADD,CUSTOM_DATA_PROFILE_BASE,CUSTOM_DATA_PROFILE_DELETE,CUSTOM_DATA_PROFILE_UPDATE,dropFolder.CONTENT_INGEST_DROP_FOLDER_BASE,dropFolder.CONTENT_INGEST_DROP_FOLDER_DELETE,dropFolder.CONTENT_INGEST_DROP_FOLDER_MATCH,dropFolder.CONTENT_INGEST_DROP_FOLDER_MODIFY,eventNotification.EVENT_NOTIFICATIONS_TEMPLATE_BASE,eventNotification.EVENT_NOTIFICATIONS_TEMPLATE_DELETE,eventNotification.EVENT_NOTIFICATIONS_TEMPLATE_MANAGE,eventNotification.EVENT_NOTIFICATION_BASE,eventNotification.EVENT_NOTIFICATION_DISPATCH,EXTERNAL_MEDIA_BASE,EXTERNAL_MEDIA_DELETE,EXTERNAL_MEDIA_MANAGE,INTEGRATION_BASE,INTEGRATION_UPDATE_SETTINGS,KMC_ACCESS,KMC_READ_ONLY,LIVE_STREAM_ADD,LIVE_STREAM_UPDATE,MANAGE_ADMIN_USERS,PARTNER_AGGREGATION_VIEW,PLAYLIST_ADD,PLAYLIST_BASE,PLAYLIST_DELETE,PLAYLIST_EMBED_CODE,PLAYLIST_UPDATE,SEARCH_SERVICE,SHORT_LINK_BASE,SHORT_LINK_MODIFY,STUDIO_ADD_UICONF,STUDIO_BASE,STUDIO_BRAND_UICONF,STUDIO_DELETE_UICONF,STUDIO_SELECT_CONTENT,STUDIO_UPDATE_UICONF,SYNDICATION_ADD,SYNDICATION_BASE,SYNDICATION_DELETE,SYNDICATION_UPDATE,TRANSCODING_ADD,TRANSCODING_BASE,TRANSCODING_DELETE,TRANSCODING_UPDATE,widevine.WIDEVINE_BASE,WIDGET_ADMIN,WIDGET_SESSION_PERMISSION,LIVE_CHANNEL_ADD,LIVE_CHANNEL_UPDATE,drm.DRM_DEVICE_BASE,MEDIA_SERVER_PARTNER_LEVEL,PUSH_PUBLISH_PERMISSION,LIVE_STREAM_CREATE_SYNC_POINTS,ALWAYS_ALLOWED_PERMISSION_HYBRID_ECDN,PLAYBACK_BASE_PERMISSION,RESPONSE_PROFILE_ADD,RESPONSE_PROFILE_DELETE,RESPONSE_PROFILE_UPDATE,scheduledTask.SCHEDULED_TASK_BASE,SERVER_NODE_BASE,SERVER_NODE_ADD,SERVER_NODE_DELETE,SERVER_NODE_UPDATE,APP_TOKEN_ADD,APP_TOKEN_DELETE,APP_TOKEN_BASE,APP_TOKEN_UPDATE,INTEGRATION_ACTIONS,LIKE_LIST_ADMIN,LIKE_LIST_USER";s:4:"tags";s:13:"admin_console";s:9:"createdAt";i:1454949084;s:9:"updatedAt";i:1454949084;}i:1;a:4:{s:4:"code";s:22:"INTERNAL_SERVERL_ERROR";s:7:"message";s:30:"Internal server error occurred";s:10:"objectType";s:19:"KalturaAPIException";s:4:"args";a:0:{}}}
result (object dump): Array
(
    [0] => KalturaUserRole Object
        (
            [id] => 9
            [name] => System Administrator
            [systemName] => System Administrator
            [description] => System Administrator
            [status] => 1
            [partnerId] => -2
            [permissionNames] => AUDIT_PLUGIN_PERMISSION,FEATURE_MOBILE_FLAVORS,scheduledTask.SYSTEM_ADMIN_MANAGE,ADMIN_USER_ASSIGN_PARNTERS,dropFolder.SYSTEM_ADMIN_DROP_FOLDER_BASE,dropFolder.SYSTEM_ADMIN_DROP_FOLDER_MODIFY,eventNotification.SYSTEM_ADMIN_EVENT_NOTIFICATION_BASE,eventNotification.SYSTEM_ADMIN_EVENT_NOTIFICATION_MODIFY,GLOBAL_PARTNER_UI_CONF_UPDTAE,METADATA_PLUGIN_PERMISSION,PARTNER_-2_GROUP_*_PERMISSION,systemPartner.SYSTEM_ADMIN_PUBLISHER_CONFIG_ACCOUNT_INFO,systemPartner.SYSTEM_ADMIN_PUBLISHER_CONFIG_ADMIN_KMC_USERS,systemPartner.SYSTEM_ADMIN_PUBLISHER_CONFIG_GENERAL_INFORMATION,systemPartner.SYSTEM_ADMIN_PUBLISHER_CONFIG_GROUP_OPTIONS,systemPartner.SYSTEM_ADMIN_PUBLISHER_CONFIG_OPTIONS_MONITOR_USAGE,systemPartner.SYSTEM_ADMIN_PUBLISHER_CONFIG_PACKAGES_SERVICE,systemPartner.SYSTEM_ADMIN_PUBLISHER_CONFIG_PACKAGES_SERVICE_PAID,systemPartner.SYSTEM_ADMIN_PUBLISHER_CONFIG_TECH_DATA,SYSTEM_ADMIN_BASE,SYSTEM_ADMIN_BATCH_CONTROL,SYSTEM_ADMIN_BATCH_CONTROL_FAILED,SYSTEM_ADMIN_BATCH_CONTROL_INPROGRESS,SYSTEM_ADMIN_BATCH_CONTROL_SETUP,SYSTEM_ADMIN_CONTENT_DISTRIBUTION_BASE,SYSTEM_ADMIN_CONTENT_DISTRIBUTION_MODIFY,SYSTEM_ADMIN_DEVELOPERS_TAB,SYSTEM_ADMIN_EMAIL_INGESTION,SYSTEM_ADMIN_ENTRY_INVESTIGATION,SYSTEM_ADMIN_MANAGE_TEMPLATE_PARTNERS,SYSTEM_ADMIN_MP_REDIRECT,SYSTEM_ADMIN_PARTNER_CONFIGURATION_VIEW,SYSTEM_ADMIN_PERMISSIONS_MANAGE,SYSTEM_ADMIN_PUBLISHER_ADD,SYSTEM_ADMIN_PUBLISHER_BASE,SYSTEM_ADMIN_PUBLISHER_BLOCK,SYSTEM_ADMIN_PUBLISHER_CONFIG,SYSTEM_ADMIN_PUBLISHER_KMC_ACCESS,SYSTEM_ADMIN_PUBLISHER_LIST_COMMERCIAL,SYSTEM_ADMIN_PUBLISHER_REMOVE,SYSTEM_ADMIN_PUBLISHER_RESET_USER_PASSWORD,SYSTEM_ADMIN_PUBLISHER_USAGE,SYSTEM_ADMIN_REPORTS_READ,SYSTEM_ADMIN_REPORTS_UPDATE,SYSTEM_ADMIN_STORAGE,SYSTEM_ADMIN_SYSTEM_MONITOR,SYSTEM_ADMIN_USER_MANAGE,SYSTEM_ADMIN_VIRUS_SCAN,SYSTEM_ADMIN_WIDGET,SYSTEM_FILESYNC,SYSTEM_INTERNAL,VIRUSSCAN_PLUGIN_PERMISSION,drm.SYSTEM_ADMIN_DRM_PROFILE_BASE,drm.SYSTEM_ADMIN_DRM_PROFILE_MODIFY,drm.SYSTEM_ADMIN_DRM_POLICY_BASE,drm.SYSTEM_ADMIN_DRM_POLICY_MODIFY,playReady.PLAY_READY_ADMIN,SYSTEM_ADMIN_DELIVERY,SYSTEM_BASE_DELIVERY,eventNotification.SYSTEM_ADMIN_EVENT_NOTIFICATION_INSERT,businessProcessNotification.SYSTEM_ADMIN_ABORT,CONTENT_MANAGE_ASSIGN_USER_GROUP,ACCESS_CONTROL_ADD,ACCESS_CONTROL_BASE,ACCESS_CONTROL_DELETE,ACCESS_CONTROL_UPDATE,ACCOUNT_BASE,ACCOUNT_UPDATE_SETTINGS,adCuePoint.MANAGE,ADMIN_BASE,ADMIN_PERMISSION_ADD,ADMIN_PERMISSION_DELETE,ADMIN_PERMISSION_UPDATE,ADMIN_PUBLISHER_MANAGE,ADMIN_ROLE_ADD,ADMIN_ROLE_DELETE,ADMIN_ROLE_UPDATE,ADMIN_USER_ADD,ADMIN_USER_BULK,ADMIN_USER_DELETE,ADMIN_USER_UPDATE,ADMIN_WHITE_BRANDING,ADVERTISING_BASE,ADVERTISING_UPDATE_SETTINGS,ALWAYS_ALLOWED_ACTIONS,ALWAYS_ALLOWED_FROM_INTERNAL_IP_ACTIONS,ANALYTICS_BASE,ANALYTICS_SEND_DATA,ASPERA_BASE_PERMISSION,ATTACHMENT_MODIFY,AUDIT_TRAIL_ADD,AUDIT_TRAIL_BASE,BASE_USER_SESSION_PERMISSION,BULK_LOG_BASE,BULK_LOG_DELETE,BULK_LOG_DOWNLOAD,BULK_LOG_DOWNLOAD_EMAIL,CAPTION_MODIFY,CAPTION_SEARCH,CONTENT_INGEST_BASE,CONTENT_INGEST_BULK_UPLOAD,CONTENT_INGEST_CLIP_MEDIA,CONTENT_INGEST_EXTERNAL_SEARCH,CONTENT_INGEST_FEED,CONTENT_INGEST_INTO_ORPHAN,CONTENT_INGEST_INTO_READY,CONTENT_INGEST_ORPHAN_AUDIO,CONTENT_INGEST_ORPHAN_VIDEO,CONTENT_INGEST_REFERENCE_MODIFY,CONTENT_INGEST_REMOTE_STORAGE,CONTENT_INGEST_REPLACE,CONTENT_INGEST_UPLOAD,CONTENT_INGEST_WEBCAM,CONTENT_MANAGE_ACCESS_CONTROL,CONTENT_MANAGE_ANNOTATION,CONTENT_MANAGE_ASSIGN_CATEGORIES,CONTENT_MANAGE_BASE,CONTENT_MANAGE_CATEGORY_USERS,CONTENT_MANAGE_CUSTOM_DATA,CONTENT_MANAGE_DELETE,CONTENT_MANAGE_DISTRIBUTION_BASE,CONTENT_MANAGE_DISTRIBUTION_PROFILE_MODIFY,CONTENT_MANAGE_DISTRIBUTION_REMOVE,CONTENT_MANAGE_DISTRIBUTION_SEND,CONTENT_MANAGE_DISTRIBUTION_WHERE,CONTENT_MANAGE_DOWNLOAD,CONTENT_MANAGE_EDIT_CATEGORIES,CONTENT_MANAGE_EMBED_CODE,CONTENT_MANAGE_ENTRY_USERS,CONTENT_MANAGE_EXPORT,CONTENT_MANAGE_METADATA,CONTENT_MANAGE_MIX,CONTENT_MANAGE_RECONVERT,CONTENT_MANAGE_SCHEDULE,CONTENT_MANAGE_SHARE,CONTENT_MANAGE_THUMBNAIL,CONTENT_MANAGE_VIRUS_SCAN,CONTENT_MODERATE_APPROVE_REJECT,CONTENT_MODERATE_BASE,CONTENT_MODERATE_CUSTOM_DATA,CONTENT_MODERATE_METADATA,cuePoint.MANAGE,CUSTOM_DATA_FIELD_ADD,CUSTOM_DATA_FIELD_DELETE,CUSTOM_DATA_FIELD_UPDATE,CUSTOM_DATA_PROFILE_ADD,CUSTOM_DATA_PROFILE_BASE,CUSTOM_DATA_PROFILE_DELETE,CUSTOM_DATA_PROFILE_UPDATE,dropFolder.CONTENT_INGEST_DROP_FOLDER_BASE,dropFolder.CONTENT_INGEST_DROP_FOLDER_DELETE,dropFolder.CONTENT_INGEST_DROP_FOLDER_MATCH,dropFolder.CONTENT_INGEST_DROP_FOLDER_MODIFY,eventNotification.EVENT_NOTIFICATIONS_TEMPLATE_BASE,eventNotification.EVENT_NOTIFICATIONS_TEMPLATE_DELETE,eventNotification.EVENT_NOTIFICATIONS_TEMPLATE_MANAGE,eventNotification.EVENT_NOTIFICATION_BASE,eventNotification.EVENT_NOTIFICATION_DISPATCH,EXTERNAL_MEDIA_BASE,EXTERNAL_MEDIA_DELETE,EXTERNAL_MEDIA_MANAGE,INTEGRATION_BASE,INTEGRATION_UPDATE_SETTINGS,KMC_ACCESS,KMC_READ_ONLY,LIVE_STREAM_ADD,LIVE_STREAM_UPDATE,MANAGE_ADMIN_USERS,PARTNER_AGGREGATION_VIEW,PLAYLIST_ADD,PLAYLIST_BASE,PLAYLIST_DELETE,PLAYLIST_EMBED_CODE,PLAYLIST_UPDATE,SEARCH_SERVICE,SHORT_LINK_BASE,SHORT_LINK_MODIFY,STUDIO_ADD_UICONF,STUDIO_BASE,STUDIO_BRAND_UICONF,STUDIO_DELETE_UICONF,STUDIO_SELECT_CONTENT,STUDIO_UPDATE_UICONF,SYNDICATION_ADD,SYNDICATION_BASE,SYNDICATION_DELETE,SYNDICATION_UPDATE,TRANSCODING_ADD,TRANSCODING_BASE,TRANSCODING_DELETE,TRANSCODING_UPDATE,widevine.WIDEVINE_BASE,WIDGET_ADMIN,WIDGET_SESSION_PERMISSION,LIVE_CHANNEL_ADD,LIVE_CHANNEL_UPDATE,drm.DRM_DEVICE_BASE,MEDIA_SERVER_PARTNER_LEVEL,PUSH_PUBLISH_PERMISSION,LIVE_STREAM_CREATE_SYNC_POINTS,ALWAYS_ALLOWED_PERMISSION_HYBRID_ECDN,PLAYBACK_BASE_PERMISSION,RESPONSE_PROFILE_ADD,RESPONSE_PROFILE_DELETE,RESPONSE_PROFILE_UPDATE,scheduledTask.SCHEDULED_TASK_BASE,SERVER_NODE_BASE,SERVER_NODE_ADD,SERVER_NODE_DELETE,SERVER_NODE_UPDATE,APP_TOKEN_ADD,APP_TOKEN_DELETE,APP_TOKEN_BASE,APP_TOKEN_UPDATE,INTEGRATION_ACTIONS,LIKE_LIST_ADMIN,LIKE_LIST_USER
            [tags] => admin_console
            [createdAt] => 1454949084
            [updatedAt] => 1454949084
            [relatedObjects] => 
        )

    [1] => Array
        (
            [code] => INTERNAL_SERVERL_ERROR
            [message] => Internal server error occurred
            [objectType] => KalturaAPIException
            [args] => Array
                (
                )

        )

)

execution time for [http://mykaltura.mydomain.ch/api_v3/service/multirequest]: [1.0993101596832]
Executing failed for request #2 with error [Internal server error occurred]`

I reinstalled the VM from scratch. The System is up-to-date.
I am kinda lost. Even google seems not to have a solution. Hope someone here can help me.

Best Regards,
Sam

**Comment by salaroglio** [comment]
Hi, i have similar problem, but before thai i had problem with kaltura-sphinx. Did you do some special configuration for that?

**Comment by friedlsa** [comment]
Hi,
I just restarted sphinx.
`service kaltura-sphinx restart`

**Comment by salaroglio** [comment]
Thnx for the answer.

**Comment by jessp01** [comment]
Hello @salaroglio,

Please post at forum.kaltura.org, including the request that failed for you, which you can see in the logs. If it failed at Output for /opt/kaltura/app/deployment/base/scripts/insertContent.php being logged into /opt/kaltura/log/insertContent.log

then look at both /opt/kaltura/log/insertContent.log and /opt/kaltura/log/kaltura_api_v3.log to understand what happened, if somewhere else, in your post, state exactly where and what the logs show.

Usually, a failure at the insertContent stage is due to the fact the SERVICE_URL provided during the config phase is unreachable but there can be other causes as well.

I am closing this issue because we rather use github issues section exclusively for bug reports and not general questions or install failures, please post at the forum.
