### ISSUE TITLE
kaltura-base-config.sh doesn't configure studio.ini on all frontend servers

### ISSUE THREAD

**Issue by wzur** [kaltura/platform-install-packages#516]
Hi there,

kaltura-base-config.sh configures studio.ini from kaltura-html5-studio properly only on the first frontend server, which has kaltura-html5lib installed.

This is due to the fact the script gets value of HTML5_LIB from kaltura-html5lib package version, and the installation instruction said that package should be installed only on one frontend server.

This leads to random problems with Studio in KMC if there are more than one frontend server behind a load balancer like AWS ELB, and when load balancer makes a query for studio.ini to a machine where that file hasn't been configured properly.

Waldemar

**Comment by jessp01** [comment]
Hi @wzur,

You are most correct. See:
https://github.com/kaltura/platform-install-packages/commit/535e200fe2ccb2c1aa8ba50f5ae64950f0bce895#diff-cf521aae9302d8796a8ed92e8d7ebf1eR308

kaltura-postinst-1.0.31-2.noarch.rpm already pushed to the 11.18.0 repo, which will become the stable version on Sun.

Thanks for reporting.

**Comment by wzur** [comment]
Hi @jessp01,

I don't see how this change is going to help. Maybe I'm missing something very obvious, but kaltura-base-config.sh still needs to run `rpm -q kaltura-html5lib` to get the version of the player, and that package is present only on one frontend server, thus leaving all other frontend servers without proper configuration.

**Comment by jessp01** [comment]
HI @wzur,

The fix is to use:
HTML5LIB_VERSION=`yum info kaltura-html5lib|grep Version|awk -F ":" '{print $NF}'
instead of rpm -q kaltura-html5lib.
This way, the retrieval of the latest version is done by querying YUM instead of the RPM DB. This means the html5lib package does not need to be installed on the machine running the script, whereas, when using rpm -q, it does.

Do let me know if I misunderstood your report.

Thanks,

**Comment by wzur** [comment]
Ah - yes - of course. So I just missed _something very obvious_ as I suspected I did. I didn't notice `yum` instead of `rpm`.

Many thanks for a quick fix.

**Comment by jessp01** [comment]
Most welcome and thanks again for reporting it.

May the source be with you,

Jess Portnoy

Kaltura Connect Virtual Summits 2015 - now on VOD! [connect.mediaspace.kaltura.com]

**Comment by wzur** [comment]
Hi @jessp01,

I just noticed both `kaltura-base-config.sh` and `kaltura-front-config.sh` query about `kaltura-html5lib` package and only the latter has been updated to use _yum_ instead of _rpm_.

Do kaltura-base-config.sh need to check the version of that package at all?

Waldemar
