### ISSUE TITLE
debian nginx won't correctly install: config file error "invalid host in upstream"

### ISSUE THREAD

**Issue by fluxcorenz** [kaltura/platform-install-packages#518]
Debian Kaltura nginx 1.8.0-8+b7 fails to correctly install (in iF state in dpkg -l), due to a configuration error:

Reloading nginx configuration: nginx: [emerg] invalid host in upstream "http://xxx.xxx.xxx" in /opt/kaltura/nginx/conf/nginx.conf:17

The issue is that the nginx.conf  stanza

        upstream kalapi {
                server http://xxx.xxx.xxx;
        }

Should not have the protocol in front of the server, i.e. should be

        upstream kalapi {
                server xxx.xxx.xxx;
        }

The template seems to just echo 'server @WWW_HOST@', and that variable in the local.ini doesn't have the protocol specified. Something seems to be injecting the protocol, but I'm not sure what.

I can manually modify the nginx.conf file and the service will start happily, but then any kind of package manipulation will reinstate the templated config file which breaks nginx again.

I am using SSL in the apache config, not sure if that has an effect.

**Comment by jessp01** [comment]
Hello,

Look at: /var/lib/dpkg/info/kaltura-nginx.postinst

WWW_HOST comes from this dialog:

        db_get 'kaltura-nginx/kaltura_service_url'
        db_input critical 'kaltura-nginx/kaltura_service_url' || true
        db_go || true
        db_get 'kaltura-nginx/kaltura_service_url'
        WWW_HOST=$RET

And is then injected later on in the script:
        sed -e "s#@VOD_PACKAGER_HOST@#$VOD_PACKAGER_HOST#g" -e "s#@VOD_PACKAGER_PORT@#$VOD_PACKAGER_PORT#g" -e "s#@LOG_DIR@#/opt/kaltura/log/nginx#" -e "s#@WWW_HOST@#$WWW_HOST#g" /opt/kaltura/nginx/conf/nginx.conf.template > /opt/kaltura/nginx/conf/nginx.conf

The dialog for kaltura_service_url has:
Description: Your Kaltura Service URL:
        Base URL where the Kaltura API will be accessed from - this would be your Load Balancer URL on a cluster or same as your virtual host in an all-in-one Kaltura server.
        Note that currently, only HTTP is supported and make sure to insert the host without the http:// prefix.

So, it does instruct you NOT to include a protocol.

My guess is you once answered it including a protocol and this is cached.
You can verify it easily with:
\# debconf-show "kaltura-nginx"
If indeed you have the proto prefix there, you can fix that with:
\# dpkg-reconfigure kaltura-nginx
which should reprompt you for the values.

**Comment by fluxcorenz** [comment]
I had to dpkg --purge kaltura-nginx to wipe out enough of the config to allow me to reconfigure it, but it looks like you're right - I must have entered the protocol in the URL.

Thanks!
