### ISSUE TITLE
debian 11.7.0-2+b1 odbc libraries missing

### ISSUE THREAD

**Issue by fluxcorenz** [kaltura/platform-install-packages#519]
After an upgrade to 11.7.0-2+b1, kaltlog shows a lot of the following (from multiple error log files):

==> /opt/kaltura/log/batch/dropfolderwatcher-0-2016-02-15.err.log <==
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/kaltura/lib/php/20151012/odbc.so' - /opt/kaltura/lib/php/20151012/odbc.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/kaltura/lib/php/20151012/pdo_odbc.so' - /opt/kaltura/lib/php/20151012/pdo_odbc.so: cannot open shared object file: No such file or directory in Unknown on line 0
MIB search path: /opt/kaltura/.snmp/mibs:/usr/share/snmp/mibs:/usr/share/snmp/mibs/iana:/usr/share/snmp/mibs/ietf:/usr/share/mibs/site:/usr/share/snmp/mibs:/usr/share/mibs/iana:/usr/share/mibs/ietf:/usr/share/mibs/netsnmp
--

They seem to be generated by kaltura-batch, or at least when I stop the kaltura-batch service, I get no further of these errors.

I'm not specifically using any odbc connections anywhere, so these are getting dragged in automatically by something.

The kaltura-php7-odbc package is installed.

**Comment by jessp01** [comment]
Hello,

There isn't anything in kaltura-php7 that requires ODBC as you can see from:
\# aptitude show kaltura-php7
Package: kaltura-php7                    
New: yes
State: not installed
Version: 7.0.0-9
Priority: optional
Section: php
Maintainer: Jess Portnoy <jess.portnoy@kaltura.com>
Architecture: all
Uncompressed Size: 53.2 k
Depends: kaltura-libapache2-mod-php7 (>= 7.0.0-9), kaltura-php7-common (>= 7.0.0-9), kaltura-php7-cli (>= 7.0.0-9), kaltura-php7-mysql,
         kaltura-php7-xsl, kaltura-php7-curl, kaltura-php7-gmp, kaltura-php7-gd, kaltura-php7-mcrypt, kaltura-php7-apcu,
         kaltura-php7-memcache, kaltura-php7-ssh2, kaltura-php7-opcache

I'd start by 
\#grep odbc /opt/kaltura/app/configurations/php/* -r
to see what tried to load odbc with:
extension=odbc.so

There is a package available called kaltura-php7-odbc but it is not required in any way for Kaltura to work.

**Comment by fluxcorenz** [comment]
/opt/kaltura/app/configurations/php/mods-available/pdo_odbc.ini:extension=pdo_odbc.so
/opt/kaltura/app/configurations/php/mods-available/odbc.ini:;extension=odbc.so
/opt/kaltura/app/configurations/php/cli/php.ini:;extension=php_pdo_odbc.dll


I presume I can either disable pdo_odbc.ini or just comment out the pdo_odbc extension? I presume pdo_odbc.so must be including odbc.so as well (since it is commented out in odbc.ini, and the php.ini is commented out as well)

**Comment by jessp01** [comment]
/opt/kaltura/app/configurations/php/mods-available/pdo_odbc.ini:extension=pdo_odbc.so
mods available is not included in the PHP scandir, as can be seen with:
\# /opt/kaltura/bin/php7 -i|grep scan
'--with-config-file-scan-dir=/opt/kaltura/app/configurations/php/conf.d'

only INIs under /opt/kaltura/app/configurations/php/conf.d are parsed.
if you do:
\# ls -al /opt/kaltura/app/configurations/php/conf.d
you'll see that the active extensions are symlinks from ../mods-available/

So, still not sure where it comes from. Did you add additional scandirs?

**Comment by jessp01** [comment]
Closing due to lack of feedback.
