### ISSUE TITLE
Kaltura fresh installation, video not playing [Error getting sources from server]

### ISSUE THREAD

**Issue by rohithmeethal** [kaltura/platform-install-packages#530]
Hi, I have managed to do a fresh kaltura installation on cent os 6.7
I am able to login to control panel, and upload videos, videos are transcoded successfully, But whenever trying to play the media I am getting media not found. Used local embed to try.

You can look into the issue on demo here http://52.0.11.179:80/tiny/k68l0

Apache log for the error 

`[Fri Mar 11 18:54:12 2016] [error] [client 52.0.11.179] PHP Fatal error:  Uncaught exception 'Exception' with message 'Error getting sources from server. Please try again.\nUnknown widget [_99]' in /opt/kaltura/web/html5/html5lib/v2.40/modules/KalturaSupport/Client/KalturaClientHelper.php:65\nStack trace:\n#0 /opt/kaltura/web/html5/html5lib/v2.40/modules/KalturaSupport/Client/KalturaClientHelper.php(53): KalturaClientHelper->generateKS('_99')\n#1 /opt/kaltura/web/html5/html5lib/v2.40/modules/KalturaSupport/Client/KalturaClientHelper.php(16): KalturaClientHelper->getClient()\n#2 /opt/kaltura/web/html5/html5lib/v2.40/modules/KalturaSupport/KalturaCommon.php(111): KalturaClientHelper->__construct(Array)\n#3 /opt/kaltura/web/html5/html5lib/v2.40/includes/Pimple.php(122): {closure}(Object(Pimple))\n#4 /opt/kaltura/web/html5/html5lib/v2.40/includes/Pimple.php(83): {closure}(Object(Pimple))\n#5 /opt/kaltura/web/html5/html5lib/v2.40/modules/KalturaSupport/kalturaIframeClass.php(29): Pimple->offsetGet('client_helper')\n#6 /opt/kaltura/web/html5/html5lib/v2.40/mwEmbedLoader.php(143): kalturaIframeCla in /opt/kaltura/web/html5/html5lib/v2.40/modules/KalturaSupport/Client/KalturaClientHelper.php on line 65`

PS: Used ans file based installation, using IP address instead of domain, followed the commands from the vagrant installation to make sure everything goes fine.

**Comment by KalturaCommunity** [comment]
Hi,

You are using the template partner, i.e partner 99.
This partner is only meant for defining things you want other partners to 
inherit, for example, sample entries.

In order to properly work with Kaltura and playback videos, you need to go 
to Admin Console, i.e: yourhost/admin_console and create a partner by 
going to Publishers->Add new publisher

May the source be with you,

Jess Portnoy

Kaltura Connect Virtual Summits 2015 - now on VOD! [connect.mediaspace.kaltura.com]

**Comment by rohithmeethal** [comment]
Thank you, that did solve the issue for me. [ Ahm.. I should have checked documentation :( , Hope this is mentioned there ]
