### ISSUE TITLE
Kaltura Cluster Red5 Deplyment Issues.

### ISSUE THREAD

**Issue by fera8778** [kaltura/platform-install-packages#537]
/opt/kaltura/bin/kaltura-red5-config.sh /tmp/answ.ans
kaltura-red5-1.0.6-1.x86_64
package kaltura-base is not installed
Exiting as kaltura-base is not installed.
This MAY be because the installation of it was skipped do to SELinux being in 'Enforcing' mode.
Please review: https://github.com/kaltura/platform-install-packages/blob/master/doc/install-kaltura-redhat-based.md#disable-selinux---required-currently-kaltura-cant-run-properly-with-selinux
And re-run:
# yum install kaltura-server

....

And if I install kaltura-server, and run the red5 script it will rewrite my DB and make my front node unusable, please advise. Should the red5 streaming server be deployed on the front node, as the instructions are quite unclear. 

Thank you.

**Comment by jessp01** [comment]
Before answering your question, note that you SHOULD keep a daily backup of your data and there is a script to help you with that called /opt/kaltura/bin/kaltura-export-db.sh.

The Red5 can be installed anywhere but it needs to be install on a machine that has the kaltura-base package installed and configured [you need to run kaltura-base-config.sh after installing].
Installing ONLY kaltura-base will not override any of your data and in any case, ALL config scripts, including kaltura-db-config.sh first check whether data exists or not and prompt you before deleting.

You do not need to install kaltura-server for this, that is a meta package which installs an all in one instance, obviously, you already have Kaltura Server setup so no need for that.

For additional general questions, please post at forum.kaltura.org. We'd like to keep the github's issue section for bug reports exclusively.

Thanks,
