### ISSUE TITLE
noobie questions - how to turn working HTTP kaltura server into SSL / HTTPS

### ISSUE THREAD

**Issue by dannyyeoh** [kaltura/platform-install-packages#541]
Hi all and sorry for this noobie questions - how to turn a working HTTP kaltura server into SSL / HTTPS. We are brand new at working with kaltura.

We have a working kaltura server and database working (working off AWS).
Is there a script besides starting brand new server

/opt/kaltura/bin/kaltura-config-all.sh

that will allow us to just turn it on. We are trying these commands but we thinks it has to be part of an answer file,
SSL Certificate Configuration

Set the following directives in  /etc/httpd/conf.d/zzzkaltura.ssl.conf :
SSLCertificateChainFile
SSLCACertificateFile

To use the monit Monitoring tab in admin console, you will need to also configure the SSL certificate for monit. To use the same certificate as you used for Kaltura they will need to be in PEM format. If it is not see Generate PEM Instructions

Edit:  /opt/kaltura/app/configurations/monit/monit.conf  and add:
SSL ENABLE
PEMFILE /path/to/your/certificate.pem

Finally, run:  /etc/init.d/kaltura-monit restart 

We want to run a script that just turns it on or what is the procedure on a working HTTP server.

Again sorry to ask this noobie question. I have noticed that many of you are past this step.
thanks and I have more later.

danny

**Comment by zoharbabin** [comment]
Have you read this?

https://github.com/kaltura/platform-install-packages/blob/master/doc/kaltura-packages-faq.md#changing-apache-configurations-post-install

**Comment by jessp01** [comment]
@dannyyeoh - I'm closing this one but if you have additional questions, please post at forum.kaltura.org.

**Comment by dannyyeoh** [comment]
zoharbabin  and jessp01 thanks for help I am posting a new question.
