### ISSUE TITLE
kaltura-front-config.sh questions

### ISSUE THREAD

**Issue by dannyyeoh** [kaltura/platform-install-packages#544]
Hi all, Newbie here.
We are trying to setup a kaltura server connected through AWS.

We are trying to get the SSL part of this working website working. From the help we have gotten here (thanks guys by the way) we know that now we have to run kaltura-front-config.sh to change the non SSL to SSL / HTTPS. 

Please is any way to get a .ans file from kaltura-front-config.sh only so that we can change it back if we make a mistake.

Being IT trained we like to take backups but the person who setup the server initially does not have the .ans file that the documentation says is there in the /temp directory.

Please help I am so newbie! thanks danny

**Comment by jessp01** [comment]
Hello Danny,

As the documentation states, each time you run any of the configure scripts [assuming RPM, deb has debconf so no special answer file mechanisms are needed], an answer file is generated under /tmp/kaltura_`date +%d_%m_%H_%M.ans`

You will also get a message saying:
"Kaltura install answer file written to $ANSFILE  -  Please save it!
This answers file can be used to silently-install re-install this machine or deploy other hosts in your cluster."

In addition, there is a full template here:
https://github.com/kaltura/platform-install-packages/blob/Kajam-11.16.0/doc/kaltura.template.ans

I am closing this issue. Again, for general questions, please post at forum.kaltura.org as we'd like to use the github issues section for bug reporting exclusively.
