### ISSUE TITLE
No Configured Batch Services

### ISSUE THREAD

**Issue by leonardobarrientosc** [kaltura/platform-install-packages#552]
Hello, my configured Batch Services is empty, what should i do?

![screen shot 2016-07-10 at 10 40 22 pm](https://cloud.githubusercontent.com/assets/6352011/16718594/72807e5c-46ef-11e6-9286-ba6d83d6d7f0.png)

**Comment by jessp01** [comment]
Hi,

Start by checking the main batch log under /opt/kaltura/log/kaltura_batch.log
You should find errors there and then I can help you further.

We'd like to keep the issues section for specific bug reports and not general troubleshooting discussions.
Please open a thread at forum.kaltura.org with the entries from the log, as well as a full description of your ENV: Linux distro, Kaltura version, is this a cluster or a single machine and any additional relevant info.

Thanks,
