### ISSUE TITLE
Two problems installing

### ISSUE THREAD

**Issue by jsanchez0512** [kaltura/platform-install-packages#555]
I have two problems installing Kaltura:

1. When using a file .ans console displays the following:

`Configuring your Kaltura DB...

Checking MySQL version..
Ver 5.5.47-MariaDB found compatible

CREATE USER kaltura;
CREATE USER etl;
CREATE DATABASE kaltura;
CREATE DATABASE kaltura_sphinx_log;
CREATE DATABASE kalturadw;
CREATE DATABASE kalturadw_ds;
CREATE DATABASE kalturadw_bisources;
CREATE DATABASE kalturalog;
Checking connectivity to needed daemons...
Connectivity test passed:)
ERROR: Couldn't make an API request to http://XXXXXXXXXXXX/api_v3/index.php?service=system&action=ping.
Please check your setup and then run /opt/kaltura/bin/kaltura-db-config.sh again.`

attached content command  curl -I -v http://XXXXXXXXXXXXXXXXXXX.com/api_v3/index.php?service=system&action=ping

`*   Trying 127.0.0.1...
* Connected to XXXXXXXXXXXXXXXXXXX.com (127.0.0.1) port 80 (#0)
> HEAD /api_v3/index.php?service=system HTTP/1.1
> User-Agent: curl/7.29.0
> Host: XXXXXXXXXXXXXXXXXXX.com
> Accept: */*
>
< HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
< Date: Tue, 26 Jul 2016 19:49:32 GMT
Date: Tue, 26 Jul 2016 19:49:32 GMT
< Server: Apache/2.4.6 (Red Hat Enterprise Linux) OpenSSL/1.0.1e-fips PHP/5.4.16
Server: Apache/2.4.6 (Red Hat Enterprise Linux) OpenSSL/1.0.1e-fips PHP/5.4.16
< Content-Type: text/html; charset=iso-8859-1
Content-Type: text/html; charset=iso-8859-1

<
* Connection #0 to host XXXXXXXXXXXXXXXXXXX.com left intact

[1]+  Done                    curl -I -v http://XXXXXXXXXXXXXXXXXXX.com/api_v3/index.php?service=system`

And the command apachectl -t -DDUMP_VHOSTS

`Passing arguments to httpd using apachectl is no longer supported.
You can only start/stop/restart httpd using this script.
If you want to pass extra arguments to httpd, edit the
/etc/sysconfig/httpd config file.
VirtualHost configuration:
*:443                  XXXXXXXXXXXXXXXXXXX.com (/etc/httpd/conf.d/ssl.conf:56)
*:80                   XXXXXXXXXXXXXXXXXXX.com (/etc/httpd/conf.d/zzzkaltura.conf:1)`

2. if I delete the file /base-config.lock basic configuration process starts, but when you reach the time zone the following error message:

`Your time zone [see http://php.net/date.timezone]: America/Bogota
Bad Timezone value, please check valid options at http://php.net/date.timezone`

it should be noted that my time zone has been verified and is found in the above code , however I have also tried other as COT and PDT, America / New_York , have made the area between ' ' and between ' ' and has not I worked.

NOTE: 
I resolved " in theory " one of the issue , but now in the installPlugins.log displays the following error:

( 10143 ) : Fatal Error Zend OPcache can not allocate buffer for interned strings

Thank you very much if you can help me, I apologize for my English is not very good.

**Comment by jessp01** [comment]
This is a dup of https://forum.kaltura.org/t/two-problems-installingf/5311.
Closing.
