### ISSUE TITLE
Vagrant Issue

### ISSUE THREAD

**Issue by fredclown** [kaltura/platform-install-packages#563]
When trying to "vagrant up" the box this is what is happening.

==> default: ##################################################
==> default: kaltura-release
==> default: #####
==> default: ########################################
==> default: #####
==> default: Setting up Install Process
==> default: http://mirror.centos.org/centos/6/SCL/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
==> default: Trying other mirror.
==> default: Error: Cannot retrieve repository metadata (repomd.xml) for repository: scl. Please verify its path and try again

**Comment by jessp01** [comment]
Hello,

See my change here:
https://github.com/kaltura/platform-install-packages/blob/Lynx-12.1.0/vagrant/Vagrantfile#L7

Please edit your local Vagrantfile copy accordingly and retry.

**Comment by jessp01** [comment]
Hello,

See my change here:
https://github.com/kaltura/platform-install-packages/blob/Lynx-12.1.0/vagrant/Vagrantfile#L7

Please edit your local Vagrantfile copy accordingly and retry.
