### ISSUE TITLE
Installation Issue. Error [Get KMC SWFs] [FAILED, RC: 255] - [.354163710]

### ISSUE THREAD

**Issue by itsnando** [kaltura/platform-install-packages#564]
Hello,

I'm trying to install the latest Kaltura on RHEL7 but when I run kaltura-sanity.sh I get an error. I seen other issues similar this but were not yet solved. Could you please help?

[Get KMC SWFs] [FAILED, RC: 255] - [.354163710]
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
[check_testme_page] [FAILED, RC: 1] - [.022218192]
[check_kmc_index_page] [FAILED, RC: 1] - [.014307960]
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
[check_admin_console_index_page] [FAILED, RC: 1] - [.020239808]
[check_studio_index_page] [FAILED, RC: 1] - [.029688039]
[check_clipapp_index_page] [FAILED, RC: 1] - [.873978213]
[Create Partner] [FAILED, RC: 255] - [.440427558]
Partner creation failed. I will skip all tests that require it.

Thanks,
itsnando

**Comment by jessp01** [comment]
Hello,

Please run kaltura-sanity.sh with bash -x, like so:
\# bash -x /opt/kaltura/bin/kaltura-sanity.sh

And look at the full curl command the script executes.
It should be using the SERVICE_URL ENV var defined here:
/etc/kaltura.d/system.ini
if this not properly set, it will fail.

For additional questions and help with troubleshooting problems, please open a thread at forum.kaltura.org.

Thanks,
