### ISSUE TITLE
Missed Legacy Flash Streaming (RTMP)  option

### ISSUE THREAD

**Issue by m925332380** [kaltura/platform-install-packages#568]
I installed current 12.0.0 kaltura-server and in KMC  Missed Legacy Flash Streaming (RTMP)  option. What´s wrong?  I  try enable all features  in  the Kaltura Administration Console, but no effect.
I want to intergat  kaltura and  red5 ,but there  is no rtmp option here.  
please help me  thx!!!!!!!!

**Comment by jessp01** [comment]
Hello,

I answered your question here: https://forum.kaltura.org/t/missed-legacy-flash-streaming-rtmp-option/5604/2.
Closing this one.
