### ISSUE TITLE
kaltura-db-config.sh FAILED with: 1 on line 65

### ISSUE THREAD

**Issue by cassola-enterprises** [kaltura/platform-install-packages#569]
Hi,
I installed kaltura exactly as specified in https://github.com/kaltura/platform-install-packages/blob/Lynx-12.1.0/doc/install-kaltura-redhat-based.md#note-on-rhelcentos-7

This is the output I get running /opt/kaltura/bin/kaltura-config-all.sh:

```
Configuring your Kaltura DB...

Checking MySQL version..
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

kaltura-db-config.sh FAILED with: 1 on line 65

Archving logs to /opt/kaltura/log/log_03_10_16_13_54.tar.gz...

ERROR: we failed on something else..
```

Is this a bug?
Can anybody help please?
I googled already and didn't find anything good.

**Comment by jessp01** [comment]
This means the password you input for the MySQL root user is probably wrong.
The passwd is placed in /etc/kaltura.d/system.ini in the ENV var SUPER_USER_PASSWD.
Does:
\# mysql -hlocalhost -uroot -p$SUPER_USER_PASSWD
let you log into MySQL? I imagine it does not, hence the problem.

Make sure you have the right passwd and the command above works and then rerun the config script.

**Comment by cassola-enterprises** [comment]
I entered your command and was promted for the pasword.
I entered the one I used also in the kaltura config script and it worked perfectly.

**Comment by jessp01** [comment]
You shouldn't be prompted with a password.. the command the script runs is:
\# source /etc/kaltura.d/system.ini
\# mysql -h$DB1_HOST -u$SUPER_USER -p$SUPER_USER_PASSWD

Does this work when run manually from the shell?

I suspect your passwd may contain special characters causing an issue..

**Comment by cassola-enterprises** [comment]
yes it contains a #

**Comment by cassola-enterprises** [comment]
I just entered "mysql -h$DB1_HOST -u$SUPER_USER -p$SUPER_USER_PASSWD" and was promted for the passord.

**Comment by cassola-enterprises** [comment]
what should I run manually?

**Comment by jessp01** [comment]
A '#' in the passwd should still work correctly.

Send me the output of:
bash -x /opt/kaltura/bin/kaltura-db-config.sh <mysql-hostname> <mysql-super-user> <mysql-super-user-passwd> <mysql-port>

to jess.portnoy kaltura com and I'll take a look.

**Comment by jessp01** [comment]
@cassola-enterprises, I tested using a MySQL root passwd that contains '#'.
I pushed a fix for it here:
https://github.com/kaltura/platform-install-packages/commit/f161b39a1e2fa4de655784eaaef5b33854cad06c#diff-6aaba63d1b60c3518624f41cd42efd4fL63

and now it works correctly.
you can either manually patch your existing install or set:
http://installrepo.origin.kaltura.org/releases/nightly/RPMS/
as baseurl in /etc/yum.repos.d/kaltura.repo, run:
```
# yum clean all
# yum update "*kaltura*"
```
and rerun kaltura-config-all.sh

You should be able to complete the install then. The fix will make it to the stable repo next time we switch versions, on Oct 9th.
