### ISSUE TITLE
Sub-process /usr/bin/dpkg returned an error code (1)

### ISSUE THREAD

**Issue by octal-ip** [kaltura/platform-install-packages#574]
I receive the following error when trying to install the kaltura-dwh package in both Debian 8 and Ubuntu 14.04:

> Errors were encountered while processing:
 kaltura-dwh
E: Sub-process /usr/bin/dpkg returned an error code (1)
Failed to perform requested operation on package.  Trying to recover:
Setting up kaltura-dwh (11.3.0-2+b1) ...
dpkg: error processing package kaltura-dwh (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 kaltura-dwh

I've been following the [documented installation process](https://github.com/kaltura/platform-install-packages/blob/master/doc/install-kaltura-deb-based.md) on fresh self hosted installations of either OS, and have tried stepping through the install_kaltura_all_in_1.sh file manually, but have not been able to progress past the kaltura-dwh configuration step without errors.

Output of _dpkg -D73 --configure kaltura-dwh_
> D000001: ensure_diversions: new, (re)loading
D000001: process queue pkg kaltura-dwh:amd64 queue.len 0 progress 1, try 1
D000040: checking dependencies of kaltura-dwh:amd64 (- <none>)
D000040: ok 2 msgs >><<
D000040:     checking Breaks
Setting up kaltura-dwh (11.3.0-2+b1) ...
D000002: fork/exec /var/lib/dpkg/info/kaltura-dwh.postinst ( configure  )
dpkg: error processing package kaltura-dwh (--configure):
 subprocess installed post-installation script returned error exit status 1
D000001: ensure_diversions: same, skipping
Errors were encountered while processing:
 kaltura-dwh

If I run /var/lib/dpkg/info/kaltura-dwh.postinst manually, it seems to terminate with no output. As far as I can tell the script stops executing at line 42 when it checks MySQL for the presence of the kalturadw tables.

Below is the output of _tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"_

> [2016-11-17 08:42:21]failed to connect [1] [0.0037310123443604] mysql:host=localhost;port=3306;dbname=kaltura_sphinx_log;
> PHP Fatal error:  Uncaught exception 'PropelException' with message 'Unable to open PDO connection dsn[mysql:host=localhost;port=3306;dbname=kaltura_sphinx_log;] user[kaltura] password[****] [wrapped: SQLSTATE[28000] [1045] Access denied for user 'kaltura'@'localhost' (using password: YES)]' in /opt/kaltura/app/vendor/propel/Propel.php:649
> Stack trace:
> #0 /opt/kaltura/app/vendor/propel/Propel.php(532): Propel::initConnection(Array, 'sphinx_log_read')
> --
> 2016-11-17 08:44:04 [2031399073] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [] for partner [0] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:65
> Stack trace:
> #0 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(284): KalturaLog::alert('ERROR - Permiss...')
> --
> </HTML>' in /opt/kaltura/app/infra/log/KalturaLog.php:83
> Stack trace:
> #0 /opt/kaltura/app/plugins/drop_folder/batch/DropFolderWatcher/KAsyncDropFolderWatcher.class.php(108): KalturaLog::err('Cannot get drop...')
> --
> </HTML>
> 2016-11-17 11:00:51 [0.000177] [2085297841] [9] [BATCH] [KScheduleHelper->run] ERR: exception 'Exception' with message 'System is not yet ready - ping failed' in /opt/kaltura/app/infra/log/KalturaLog.php:83
> Stack trace:
> #0 /opt/kaltura/app/batch/batches/KScheduleHelper.class.php(42): KalturaLog::err('System is not y...')

Output of _dpkg -l "kaltura-*"_

> Desired=Unknown/Install/Remove/Purge/Hold
> | Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
> |/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
> ||/ Name                                                  Version                         Architecture                    Description
> +++-=====================================================-===============================-===============================-===============================================================================================================
> ii  kaltura-base                                          11.21.0-2                       all                             Kaltura Open Source Video Platform
> ii  kaltura-batch                                         11.21.0-1                       all                             Kaltura Open Source Video Platform - batch server
> ii  kaltura-clipapp                                       1.3-1+b2                        all                             Kaltura Video Presentations Manager
> ii  kaltura-db                                            11.4.0-1                        all                             Kaltura Open Source Video Platform - batch server
> iF  kaltura-dwh                                           11.3.0-2+b1                     amd64                           Kaltura Open Source Video Platform - Analytics
> ii  kaltura-ffmpeg                                        2.7.2-1+b8                      amd64
> ii  kaltura-ffmpeg-aux                                    2.1.3-1                         amd64
> ii  kaltura-front                                         11.21.0-1                       all                             Kaltura Open Source Video Platform - frontend server
> ii  kaltura-html5-studio                                  2.0.6-1                         all                             Kaltura Open Source Video Platform - frontend server
> ii  kaltura-html5lib                                      2.46-1                          all                             Kaltura Open Source Video Platform - HTML5 player
> ii  kaltura-kclip                                         1.1.2.1-1                       all                             Kaltura Video Presentations Manager
> ii  kaltura-kcw                                           2.2.4-1+b3                      all                             Kalture Contribution Wizard
> ii  kaltura-kdp                                           2.7.0-1                         all                             Kaltura Dynamic Player
> ii  kaltura-kdp3                                          3.9.9-1+b3                      amd64                           Kaltura Dynamic Player
> ii  kaltura-kdp3wrapper                                   37-1                            all                             KDP3 Wrapper
> ii  kaltura-kdpwrapper                                    11-1                            all                             KDP Wrapper
> ii  kaltura-kmc                                           5.40.3-1                        all                             Kaltura Management Console
> ii  kaltura-krecord                                       1.7-1                           all                             Kaltura kRecord - used for recording from web cam
> ii  kaltura-kupload                                       1.2.16-1                        all                             Kaltura kupload widget
> un  kaltura-libapache2-mod-php7                           <none>                          <none>                          (no description available)
> ii  kaltura-pentaho                                       4.2.1+b2                        amd64                           Pentaho Open Source Data Integration Community Edition (CE).
> un  kaltura-php7-apcu                                     <none>                          <none>                          (no description available)
> un  kaltura-php7-cli                                      <none>                          <none>                          (no description available)
> un  kaltura-php7-curl                                     <none>                          <none>                          (no description available)
> un  kaltura-php7-gd                                       <none>                          <none>                          (no description available)
> un  kaltura-php7-gmp                                      <none>                          <none>                          (no description available)
> un  kaltura-php7-mcrypt                                   <none>                          <none>                          (no description available)
> un  kaltura-php7-memcache                                 <none>                          <none>                          (no description available)
> un  kaltura-php7-mysql                                    <none>                          <none>                          (no description available)
> un  kaltura-php7-ssh2                                     <none>                          <none>                          (no description available)
> un  kaltura-php7-xsl                                      <none>                          <none>                          (no description available)
> ii  kaltura-postinst                                      1.0.31-1+b3                     all                             Kaltura Open Source Video Platform
> ii  kaltura-sphinx                                        2.2.1-3+b5                      amd64                           Sphinx full-text search server - for Kaltura
> ii  kaltura-widgets                                       10.9.0-1+b4                     all                             Kaltura Open Source Video Platform - widgets meta package

Output of _MySQL -V_

> mysql  Ver 14.14 Distrib 5.5.53, for debian-linux-gnu (x86_64) using readline 6.3

**Comment by jessp01** [comment]
Hello,

Looking at the attached output, it seems your DB is half baked.
I suggest you drop the current DB using:
\# /opt/kaltura/bin/kaltura-drop-db.sh
then run:
\# dpkg-reconfigure kaltura-db
to repopulate it and look for errors outputted to STDOUT/STDERR. The most common reason for errors is the service URL/endpoint provided during the kaltura-base postinst phase is not resolvable in the server. It must be resolvable in order for the deployment to succeed since parts of the deployment are done by making HTTP requests to the API.
and then redeploy the DWH DB with:
\# dpkg-reconfigure kaltura-dwh

**Comment by jessp01** [comment]
I'm closing this issue since for troubleshooting help, we'd rather use forum.kaltura.org. The GitHub issues section should be used for general bug reports exclusively. Should you have follow up questions, please post at forum.kaltura.org.

Thanks,
