### ISSUE TITLE
Centos Installation admin_consol

### ISSUE THREAD

**Issue by siaro30** [kaltura/platform-install-packages#575]
Hi. 
I want to build a katura cluster.
If I try for 3 weeks, an 5-6 clean install but admin_console does not work correctly.
It responds for a minimum of 10 minutes.
and kaltlog is ; 

/opt/kaltura/log/kaltura_admin.log:2016-11-27 12:15:30 [0.000000] [261929374] [1] [%context%] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [KalturaInternalToolsPluginSystemHelperAction] requires permissions [Array
/opt/kaltura/log/kaltura_admin.log:Stack trace:
/opt/kaltura/log/kaltura_admin.log:2016-11-27 12:15:30 [0.001165] [261929374] [2] [%context%] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [VirusScanListAction] requires permissions [Array
/opt/kaltura/log/kaltura_admin.log:Stack trace:
/opt/kaltura/log/kaltura_admin.log:2016-11-27 12:15:30 [0.000205] [261929374] [3] [%context%] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [VirusScanConfigureAction] requires permissions [Array
/opt/kaltura/log/kaltura_admin.log:Stack trace:
/opt/kaltura/log/kaltura_admin.log:2016-11-27 12:15:30 [0.000246] [261929374] [4] [%context%] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [VirusScanSetStatusAction] requires permissions [Array
/opt/kaltura/log/kaltura_admin.log:Stack trace:
/opt/kaltura/log/kaltura_admin.log:2016-11-27 12:15:30 [0.000205] [261929374] [5] [%context%] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [DistributionProfileListAction] requires permissions [Array
/opt/kaltura/log/kaltura_admin.log:Stack trace:
/opt/kaltura/log/kaltura_admin.log:2016-11-27 12:15:30 [0.000201] [261929374] [6] [%context%] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [DistributionProfileConfigureAction] requires permissions [Array
/opt/kaltura/log/kaltura_admin.log:Stack trace:
/opt/kaltura/log/kaltura_admin.log:2016-11-27 12:15:30 [0.000198] [261929374] [7] [%context%] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [DistributionProfileUpdateStatusAction] requires permissions [Array
/opt/kaltura/log/kaltura_admin.log:Stack trace:
/opt/kaltura/log/kaltura_admin.log:2016-11-27 12:15:30 [0.000208] [261929374] [8] [%context%] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [GenericDistributionProvidersListAction] requires permissions [Array
/opt/kaltura/log/kaltura_admin.log:Stack trace:
/opt/kaltura/log/kaltura_admin.log:2016-11-27 12:15:30 [0.000229] [261929374] [9] [%context%] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [GenericDistributionProviderConfigureAction] requires permissions [Array
/opt/kaltura/log/kaltura_admin.log:Stack trace:
/opt/kaltura/log/kaltura_admin.log:2016-11-27 12:15:30 [0.000204] [261929374] [10] [%context%] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [GenericDistributionProviderDeleteAction] requires permissions [Array
/opt/kaltura/log/kaltura_admin.log:Stack trace:
/opt/kaltura/log/kaltura_admin.log:2016-11-27 12:15:30 [0.000197] [261929374] [11] [%context%] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [XsltTesterAction] requires permissions [Array
/opt/kaltura/log/kaltura_admin.log:Stack trace:
/opt/kaltura/log/kaltura_admin.log:2016-11-27 12:15:30 [0.000207] [261929374] [12] [%context%] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [XsltTesterApiAction] requires permissions [Array
/opt/kaltura/log/kaltura_admin.log:Stack trace:
/opt/kaltura/log/kaltura_admin.log:2016-11-27 12:15:30 [0.000200] [261929374] [13] [%context%] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [DropFolderListAction] requires permissions [Array
/opt/kaltura/log/kaltura_admin.log:Stack trace:
/opt/kaltura/log/kaltura_admin.log:2016-11-27 12:15:30 [0.000226] [261929374] [14] [%context%] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [DropFolderConfigureAction] requires permissions [Array
/opt/kaltura/log/kaltura_admin.log:Stack trace:
/opt/kaltura/log/kaltura_admin.log:2016-11-27 12:15:30 [0.000213] [261929374] [15] [%context%] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [DropFolderSetStatusAction] requires permissions [Array
/opt/kaltura/log/kaltura_admin.log:Stack trace:
/opt/kaltura/log/kaltura_admin.log:2016-11-27 12:15:30 [0.000200] [261929374] [16] [%context%] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [EventNotificationTemplatesListAction] requires permissions [Array
/opt/kaltura/log/kaltura_admin.log:Stack trace:
/opt/kaltura/log/kaltura_admin.log:2016-11-27 12:15:30 [0.000199] [261929374] [17] [%context%] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [EventNotificationTemplateConfigureAction] requires permissions [Array
/opt/kaltura/log/kaltura_admin.log:Stack trace:
/opt/kaltura/log/kaltura_admin.log:2016-11-27 12:15:30 [0.000201] [261929374] [18] [%context%] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [EventNotificationTemplateUpdateStatusAction] requires permissions [Array

what can i do.
thanks.

**Comment by jessp01** [comment]
Hello @siaro30,

While these exceptions look fatal, in actuality, they are not. Please describe the actual problem you have when trying to use the Admin Console and we can take it from there. Specifically, what does "It responds for a minimum of 10 minutes." mean?

**Comment by siaro30** [comment]
Hi jessp01 ;
I'm sorry to answer late.
I solved that problem.

I was working with the Freebsd zfs file system and nfs3, and I was getting a bad permission error.
The problem has been solved when using nfs 4.

Now i am having another problem.
I have a akamai dynamic site delivery license. (DSD)

This license , only makes mp4 streaming and js jpeg css  etc possible.
I installed Centos 6 cluster. And I do not know how to integrate with Kaltura to Akamai.

I use the ,  cdn_host="akamai_hostname" in my setup, but the video is still being serving from the origin-server.  

For this reason, the video is not being cached. And all video name is a.mp4


I cant solve this problem.
If you can help me, please.

The .ans file is as follows.

Akamai Hostname is , videocdn.XXXXXX.com
Kaltura Front Hostname is , origin-test.XXXXXX.com


TIME_ZONE="Europe/London"
KALTURA_FULL_VIRTUAL_HOST_NAME="origin-test.XXXXXX.com"
KALTURA_VIRTUAL_HOST_NAME="origin-test.XXXXXX.com"
DB1_HOST="mysql1.XXXXXX.lan"
DB1_PORT="3306"
DB1_PASS="XXXXXXXXX"
DB1_NAME="kaltura"
DB1_USER="kaltura"
SERVICE_URL="http://videocdn.XXXXXX.com"
SPHINX_SERVER1="127.0.0.1"
SPHINX_SERVER2="sphinx2.XXXXXX.lan"
DWH_HOST="dwh.XXXXXXXXX.lan"
DWH_PORT="3306"
ADMIN_CONSOLE_ADMIN_MAIL="xxxxxxxx@xxxxxxx.com"
ADMIN_CONSOLE_PASSWORD="XXXXXXX"
CDN_HOST="videocdn.XXXXXX.com"
KALTURA_VIRTUAL_HOST_PORT="80"
SUPER_USER="root"
SUPER_USER_PASSWD="YYYYYYYYYY"
ENVIRONMENT_NAME="XXXXXXX Video Platform"
DWH_PASS="XXXXXXXXXXxx"
PROTOCOL="http"
RED5_HOST="live.XXXXXX.com"
USER_CONSENT="0"
CONTACT_MAIL="NO"
VOD_PACKAGER_HOST="vd1.XXXXXX.com"
VOD_PACKAGER_PORT="80"
IP_RANGE="0.0.0.0-255.255.255.255"
WWW_HOST="origin-test.XXXXXX.com"
CONFIG_CHOICE="0"
IS_SSL="N"
IS_NGINX_SSL="N"

**Comment by jessp01** [comment]
Hi @siaro30,

In order to integrate with Akamai, you need to go to Admin Console->Publishers->Your partner->Profiles
and create remote storage and delivery profiles, inputting the needed access info.
The remote storage profile is responsible for telling the system where to store the entries and the delivery profile is responsible for telling it how to retrieve the entry for playback.

For additional questions, please post at forum.kaltura.org.

**Comment by siaro30** [comment]
Thanks Jessp
