### ISSUE TITLE
Change Only DB Hostname

### ISSUE THREAD

**Issue by Lotykun** [kaltura/platform-install-packages#577]
I have installed a kaltura platform using a ans file in a Centos server. Version 11.17.0.
Every thing works perfect!!

After a few months increasing visits in our website and due to the volume capactity of our servers.. We have decide to migrate the kaltura DB and the DWH DB to another host prepared to locate DBs.

We have migrated all Databases from Kaltura and all DB from DWH, keeping the same users "kaltura and etl" with the same password and the same privileges.

We just want to edit the hostname of the mysql to redirect to the new location.

We have edit the "system.ini" and "local.ini" files, but in the front of the platform is still showing information about the Old DB. In fact, it is showing information about the new DB (user_login information and state), mixing with old DB information such as all related with the entries.

We would be very pleased if you can show us a tutorial step by step to reconfig the hostname of the DB without create again all tables, or indicating which closed issue solve this problem. We would like to manage this the shortest possible time, because we do not want to stop the platform more than the neccesary.

Thanks

**Comment by jessp01** [comment]
Hello,

You will need to edit /opt/kaltura/app/configurations/db.ini and then reload Apache.
For DWH [analytics] edit /opt/kaltura/dwh/.kettle/kettle.properties.

In general, we'd like to keep the GitHub's issues section for bug reports so please post additional questions on forum.kaltura.org instead.

Thanks,
