### ISSUE TITLE
Trying to get Kaltura Working

### ISSUE THREAD

**Issue by muhamedabada** [kaltura/platform-install-packages#579]
I am installing Kaltura on CentOS release 6.8, and I am getting the below error awhile executing # yum install kaltura-server : 
--> Finished Dependency Resolution
Error: Package: kaltura-ffmpeg-aux-2.1.3-1.x86_64 (Kaltura)
           Requires: libopenjpeg.so.1()(64bit)
Error: Package: 1:kaltura-nginx-1.10.2-5.x86_64 (Kaltura)
           Requires: systemd
Error: Package: librtmp-2.4-2.20131205.gitdc76f0a.el7.nux.x86_64 (Kaltura)
           Requires: libgnutls.so.28(GNUTLS_2_12)(64bit)
Error: Package: php-mcrypt-5.4.35-1.x86_64 (Kaltura)
           Requires: php-api = 20100412
           Available: php-common-5.3.3-47.el6.x86_64 (base)
               php-api = 20090626
           Installing: php-common-5.3.3-48.el6_8.x86_64 (updates)
               php-api = 20090626
Error: Package: kaltura-libmediainfo-0.7.61-3.x86_64 (Kaltura)
           Requires: libzen = 0.4.33
Error: Package: php-pecl-ssh2-0.12-1.x86_64 (Kaltura)
           Requires: php(zend-abi) = 20100525-64
           Available: php-common-5.3.3-47.el6.x86_64 (base)
               php(zend-abi) = 20090626
           Installing: php-common-5.3.3-48.el6_8.x86_64 (updates)
               php(zend-abi) = 20090626
Error: Package: kaltura-mediainfo-0.7.61-3.x86_64 (Kaltura)
           Requires: libzen.so.0()(64bit)
Error: Package: php-pecl-apc-3.1.13-1.x86_64 (Kaltura)
           Requires: php(api) = 20100412-64
           Available: php-common-5.3.3-47.el6.x86_64 (base)
               php(api) = 20090626
           Installing: php-common-5.3.3-48.el6_8.x86_64 (updates)
               php(api) = 20090626
Error: Package: x265-libs-2.0-1.x86_64 (Kaltura)
           Requires: libm.so.6(GLIBC_2.15)(64bit)
Error: Package: 1:kaltura-nginx-1.10.2-5.x86_64 (Kaltura)
           Requires: libpcre.so.1()(64bit)
Error: Package: kaltura-sphinx-2.2.1-20.x86_64 (Kaltura)
           Requires: libmysqlclient.so.18(libmysqlclient_18)(64bit)
Error: Package: php-pecl-apc-3.1.13-1.x86_64 (Kaltura)
           Requires: php(zend-abi) = 20100525-64
           Available: php-common-5.3.3-47.el6.x86_64 (base)
               php(zend-abi) = 20090626
           Installing: php-common-5.3.3-48.el6_8.x86_64 (updates)
               php(zend-abi) = 20090626
Error: Package: kaltura-segmenter-1.0-3.x86_64 (Kaltura)
           Requires: libgmp.so.10()(64bit)
Error: Package: php-pecl-ssh2-0.12-1.x86_64 (Kaltura)
           Requires: php(api) = 20100412-64
           Available: php-common-5.3.3-47.el6.x86_64 (base)
               php(api) = 20090626
           Installing: php-common-5.3.3-48.el6_8.x86_64 (updates)
               php(api) = 20090626
Error: Package: kaltura-libmediainfo-0.7.61-3.x86_64 (Kaltura)
           Requires: libzen.so.0()(64bit)
Error: Package: xvidcore-1.3.2-16.x86_64 (Kaltura)
           Requires: /usr/sbin/ldconfig
Error: Package: xvidcore-1.3.2-16.x86_64 (Kaltura)
           Requires: libm.so.6(GLIBC_2.15)(64bit)
Error: Package: kaltura-ffmpeg-3.2-1.x86_64 (Kaltura)
           Requires: libopenjpeg.so.1()(64bit)
Error: Package: librtmp-2.4-2.20131205.gitdc76f0a.el7.nux.x86_64 (Kaltura)
           Requires: libgnutls.so.28()(64bit)
Error: Package: kaltura-mediainfo-0.7.61-3.x86_64 (Kaltura)
           Requires: libzen = 0.4.33
Error: Package: schroedinger-1.0.11-4.el7.x86_64 (Kaltura)
           Requires: liborc-0.4.so.0()(64bit)
Error: Package: libass-0.10.2-2.el7.x86_64 (Kaltura)
           Requires: libharfbuzz.so.0()(64bit)
Error: Package: kaltura-segmenter-1.0-3.x86_64 (Kaltura)
           Requires: libopenjpeg.so.1()(64bit)
Error: Package: librtmp-2.4-2.20131205.gitdc76f0a.el7.nux.x86_64 (Kaltura)
           Requires: libgnutls.so.28(GNUTLS_1_4)(64bit)
Error: Package: kaltura-sphinx-2.2.1-20.x86_64 (Kaltura)
           Requires: libmysqlclient.so.18()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

Not sure how to overcome this issue, It will be great if you guys can help as its my first time to install Kaltura server.

Regards,

**Comment by GeraldNathan** [comment]
May be you installed Centos  OS image with  i386 ( install with minimal iso of x86_64 ).

**Comment by muhamedabada** [comment]
I tried all the possible Linux Flavors and releases, Finally I managed to get it working with Centos 7 OS Full ISO, I am having issue now with nginx as its failing to start, However Kaltura Admin Console is accessible.

**Comment by jessp01** [comment]
Hello,

More info is needed. So I gather we're currently using CentOS 7, correct? What is the reason the Nginx daemon fails to start, i,e, what is the output of:
\# service kaltura-nginx start
and what is in /opt/kaltura/log/kaltura_nginx_errors.log?

**Comment by jessp01** [comment]
As for your first post, it seems you've been trying to use the CentOS/RHEL 7 repo with CentOS 6. If you still have that ENV, what's the output for:
\# lsb_release -a
and what is in /etc/yum.repos.d/kaltura.repo

**Comment by muhamedabada** [comment]
Looks like a reboot was required, after the reboot Nginx is working fine, but any way below you can find the content of /opt/kaltura/log/kaltura_nginx_errors.log:
2016/12/27 02:13:50 [alert] 18268#18268: mmap(MAP_ANON|MAP_SHARED, 536870912) failed (12: Cannot allocate memory)
2016/12/27 02:14:49 [alert] 18506#18506: mmap(MAP_ANON|MAP_SHARED, 536870912) failed (12: Cannot allocate memory)
2016/12/27 02:30:47 [alert] 21368#21368: mmap(MAP_ANON|MAP_SHARED, 536870912) failed (12: Cannot allocate memory)
2016/12/27 02:32:25 [alert] 21650#21650: mmap(MAP_ANON|MAP_SHARED, 536870912) failed (12: Cannot allocate memory)
2016/12/27 02:34:03 [alert] 21904#21904: mmap(MAP_ANON|MAP_SHARED, 536870912) failed (12: Cannot allocate memory)
2016/12/27 12:14:28 [emerg] 7203#7203: bind() to 0.0.0.0:88 failed (98: Address already in use)
2016/12/27 12:14:28 [emerg] 7203#7203: bind() to 0.0.0.0:1935 failed (98: Address already in use)
2016/12/27 12:14:28 [emerg] 7203#7203: bind() to 0.0.0.0:88 failed (98: Address already in use)
2016/12/27 12:14:28 [emerg] 7203#7203: bind() to 0.0.0.0:1935 failed (98: Address already in use)
2016/12/27 12:14:28 [emerg] 7203#7203: bind() to 0.0.0.0:88 failed (98: Address already in use)
2016/12/27 12:14:28 [emerg] 7203#7203: bind() to 0.0.0.0:1935 failed (98: Address already in use)
2016/12/27 12:14:28 [emerg] 7203#7203: bind() to 0.0.0.0:88 failed (98: Address already in use)
2016/12/27 12:14:28 [emerg] 7203#7203: bind() to 0.0.0.0:1935 failed (98: Address already in use)
2016/12/27 12:14:28 [emerg] 7203#7203: bind() to 0.0.0.0:88 failed (98: Address already in use)
2016/12/27 12:14:28 [emerg] 7203#7203: bind() to 0.0.0.0:1935 failed (98: Address already in use)
2016/12/27 12:14:28 [emerg] 7203#7203: still could not bind()

---------------------------
[root@testkaltura ~]# service kaltura-nginx status
Redirecting to /bin/systemctl status  kaltura-nginx.service
● kaltura-nginx.service - nginx - high performance web server
   Loaded: loaded (/usr/lib/systemd/system/kaltura-nginx.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2016-12-27 12:54:25 EST; 23min ago
     Docs: http://nginx.org/en/docs/
  Process: 1606 ExecStart=/usr/sbin/nginx -c /etc/nginx/nginx.conf (code=exited, status=0/SUCCESS)
  Process: 1047 ExecStartPre=/usr/sbin/nginx -t -c /etc/nginx/nginx.conf (code=exited, status=0/SUCCESS)
 Main PID: 1607 (nginx)
   CGroup: /system.slice/kaltura-nginx.service
           ├─1607 nginx: master process /usr/sbin/nginx -c /etc/nginx/nginx.conf
           ├─1608 nginx: worker process
           └─1609 nginx: cache manager process

Dec 27 12:54:22 testkaltura.localdomain systemd[1]: Starting nginx - high performance web server...
Dec 27 12:54:25 testkaltura.localdomain nginx[1047]: nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
Dec 27 12:54:25 testkaltura.localdomain nginx[1047]: nginx: configuration file /etc/nginx/nginx.conf test is successful
Dec 27 12:54:25 testkaltura.localdomain systemd[1]: Failed to read PID from file /run/nginx.pid: Invalid argument
Dec 27 12:54:25 testkaltura.localdomain systemd[1]: Started nginx - high performance web server.
[root@testkaltura ~]#

Note : "Dec 27 12:54:25 testkaltura.localdomain systemd[1]: Failed to read PID from file /run/nginx.pid: Invalid argument" not sure what is the reason of that.

----------------------------
[root@testkaltura ~]# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.3.1611 (Core)
Release:        7.3.1611
Codename:       Core

----------------------------

Currently Kaltura Admin Console is accessible and Nginx is up and running, But I am not able to reach Admin console from my physical machine only its accessible from inside the VMware.

** During the installation I faced a challenge with libzen-0.4.33-1.el7.x86_64 which is required for Kaltura and its not available in Centos 7 repo only libzen-0.4.34-1.el7.x86_64, I thought of mentioning that for you to review the required package for Kaltura installation in Centos 7.

**Comment by jessp01** [comment]
Hi,

According to your Nginx log, you have two issues:
0. Both 88 and 1935 [TCP] ports have something else listening on them and therefore, Nginx cannot use the ports. You can check what PID and process name occupies these ports with:
       # netstat -plnt |grep "80\|1935"

1. In /etc/nginx/nginx.conf, you should have:
       pid             /var/run/nginx.pid;
but, according to your output the path to the PID file is set to /run/nginx.pid and /run does not exist. 

Now, as for the Admin Console and KMC and all other web interfaces, you should always use a hostname/IP that is resolvable from any client you intend to request them, that includes playback as well, not just administration. If you input a service URL or hostname that is not resolvable from the outside then you will have an issue reaching these interfaces and also an issue with playback. You can correct that by rerunning kaltura-config-all and inputting a different hostname and service URL.

As for libzen, you need to enable the EPEL repo for it, this is explained in the doc here:
https://github.com/kaltura/platform-install-packages/blob/master/doc/install-kaltura-redhat-based.md#note-on-rhelcentos-7:
"Note for RHEL7: depending on what repos you have enabled, you may also need to add the EPEL or CentOS repos to resolve all dependencies."

Since we'd like GitHub's issues section to be used for bug reports exclusively and not for general questions or troubleshooting help, I am closing this issue but feel free to post additional questions on our forum at forum.kaltura.org.
