### ISSUE TITLE
http://www.thoughtpolice.co.uk/vmware/

### ISSUE THREAD

**Issue by grzchr15** [kaltura/platform-install-packages#582]
Seems to be not what is expected
Adware server. Please remove such unverified links

**Comment by jessp01** [comment]
Thanks @grzchr15. Fixed. I'm actually pretty sad about it, this project has been around forever.. guess they shut down due to lack of popularity in light of alternative solutions.. but there is https://www.osboxes.org/vmware-images/ which has a similar range of VM images,
