### ISSUE TITLE
Repo throwing error.

### ISSUE THREAD

**Issue by roopeess** [kaltura/platform-install-packages#585]
Hi,

I am trying to install kaltura-server but my server is not able to connect. Is there any issue going on.

http://installrepo.kaltura.org/releases/latest/RPMS/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://installrepo.origin.kaltura.org/repo/releases/12.11.0/RPMS/x86_64/repodata/repomd.xml: (28, 'connect() timed out!')
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repository: Kaltura. Please verify its path and try again

**Comment by jessp01** [comment]
Hi @roopees,

Both URL fetch the repomd.xml from all machines I tested from.
Is your machine open for communication with the outside world on port 80 TCP? 
Does:
\# wget http://installrepo.kaltura.org/releases/latest/RPMS/x86_64/repodata/repomd.xml
or:
\# curl http://installrepo.kaltura.org/releases/latest/RPMS/x86_64/repodata/repomd.xml
work?

If not, are you able to reach URLs for other domains over HTTP?

**Comment by roopeess** [comment]
Hi jessp01,

I can curl it with response 301 but still wget throws time out. I am able to connect to other URL/Repos from the same machine. There are no proxy. I will once recheck all my networks to confirm it if any firewalls are not acting to make this happen. 

[root@localhost ~]# wget http://installrepo.kaltura.org/releases/latest/RPMS/x86_64/repodata/repomd.xml
--2017-03-09 18:19:56--  http://installrepo.kaltura.org/releases/latest/RPMS/x86_64/repodata/repomd.xml
Resolving installrepo.kaltura.org... 54.192.159.47, 54.192.159.128, 54.192.159.141, ...
Connecting to installrepo.kaltura.org|54.192.159.47|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://installrepo.origin.kaltura.org/repo/releases/12.11.0/RPMS/x86_64/repodata/repomd.xml [following]
--2017-03-09 18:19:56--  http://installrepo.origin.kaltura.org/repo/releases/12.11.0/RPMS/x86_64/repodata/repomd.xml
Resolving installrepo.origin.kaltura.org... 216.200.17.80
Connecting to installrepo.origin.kaltura.org|216.200.17.80|:80... 


^C
[root@localhost ~]# curl http://installrepo.kaltura.org/releases/latest/RPMS/x86_64/repodata/repomd.xml
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://installrepo.origin.kaltura.org/repo/releases/12.11.0/RPMS/x86_64/repodata/repomd.xml">here</a>.</p>
<hr>
<address>Apache/2.2.15 (CentOS) Server at installrepo.origin.kaltura.org Port 80</address>
</body></html>
[root@localhost ~]#

**Comment by jessp01** [comment]
Hello @roopeess,

Can this be closed or do you still have issues?

**Comment by jessp01** [comment]
Closing for lack of response. Feel free to open if you're still having issues.
