### ISSUE TITLE
Not found below setting in centos 7 kaltura based installed

### ISSUE THREAD

**Issue by dipenpatel235** [kaltura/platform-install-packages#591]
Under HTTP Delivery Base URL, type “http://{your amazon cloudfront domain}/kaltura” – replace {your amazon cloudfront domain} with the cloudfront domain you created in the previous section).

**Comment by jessp01** [comment]
Hi @dipenpatel235, sorry but I don't understand what your question/issue is... please explain.

**Comment by dipenpatel235** [comment]
i am doing aws with kalura publisher setting.

so there is given one option to set "HTTP Delivery Base URL" in document.
but that option is not seen on web interface.

**Comment by jessp01** [comment]
Hi @dipenpatel235,

Basically, you need to go to admin console->publishers->your publisher->Profiles

There are two profiles you need to configure:
- Remote Storage
- Delivery Profile

Remote storage is the configuration needed in order for Kaltura to store the media files onto AWS [or any other provider for that matter], delivery profile is the configuration needed in order for Kaltura to serve the files, as a result of a playManifest request by the player, usually.

Please post additional questions at forum.kaltura.org.
