### ISSUE TITLE
libzen dependency error

### ISSUE THREAD

**Issue by sternj** [kaltura/platform-install-packages#596]
Hello,
After going through every step to the letter on CentOS 7 (albeit with Java 8 rather than 7), when running "yum install kaltura-server", this is written after "Finished dependency resolution". I am running the most recent release of CentOS, without PHP installed because when I had it installed it noted a dependency conflict. Yum seems to also be having issues with packages being regarded as their own conflicts, but I am not sure if this is related. 

Error: Package: kaltura-mediainfo-0.7.61-6.x86_64 (Kaltura)
           Requires: libzen = 0.4.35
           Installing: libzen-0.4.34-1.el7.x86_64 (Kaltura)
               libzen = 0.4.34-1.el7
Error: Package: kaltura-libmediainfo-0.7.61-6.x86_64 (Kaltura)
           Requires: libzen = 0.4.35
           Installing: libzen-0.4.34-1.el7.x86_64 (Kaltura)
               libzen = 0.4.34-1.el7
Error: Package: kaltura-mediainfo-0.7.61-6.x86_64 (Kaltura)
           Requires: libzen = 0.4.35
           Available: libzen-0.4.34-1.el7.x86_64 (Kaltura)
               libzen = 0.4.34-1.el7
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by jessp01** [comment]
Hi @sternj,

Please ensure you have the EPEL repo enabled. libzen-0.4.35 is included there.
```
# yum info libzen
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
Repository remi-php56 is listed more than once in the configuration
Installed Packages
Name        : libzen
Arch        : x86_64
Version     : 0.4.35
Release     : 1.el7
Size        : 311 k
Repo        : installed
From repo   : epel
Summary     : Shared library for libmediainfo and medianfo*
URL         : https://github.com/MediaArea/ZenLib
License     : zlib
Description : Files shared library for libmediainfo and medianfo-*.
```
Thanks,
