### ISSUE TITLE
docker install: KMC quickstart guide results in 404

### ISSUE THREAD

**Issue by bnordgren** [kaltura/platform-install-packages#597]
"The requested URL /content/docs/pdf/KMC_Quick_Start_Guide.pdf" was not found on this server.

This resulted from
- New Fedora 26 Atomic image
- New docker install of kaltura
- Typing the IP address of the host every time the configuration script asked for a hostname.

The install script claims to have completed successfully.

**Comment by jessp01** [comment]
Hi @bnordgren,

/opt/kaltura/web//content/docs/pdf/KMC_Quick_Start_Guide.pdf is part of the kaltura-kmc package:

\# rpm -qf /opt/kaltura/web//content/docs/pdf/KMC_Quick_Start_Guide.pdf
kaltura-kmc-v5.42.1-1.noarch

Do you not have it inside you docker container?

**Comment by bnordgren** [comment]
I have a previous version (5.42.0), but that directory (above) does not exist. I just pulled the docker image yesterday.

```
[root@d088cdf34a3e /]# rpm -qa | grep kaltura-kmc
kaltura-kmc-v5.42.0-2.noarch
[root@d088cdf34a3e /]# ls /opt/kaltura/web/content/docs/pdf
ls: cannot access /opt/kaltura/web/content/docs/pdf: No such file or directory
```

**Comment by bnordgren** [comment]
Also just noticed that the "Download CSV/XML Samples" are missing as well.

**Comment by jessp01** [comment]
Hi @bnordgren,

What is the output for:
\# rpm -ql kaltura-kmc|grep "pdf\|csv"
?
All these files should be listed in the output, if they are not present then perhaps you installed the package before mounting /opt/kaltura/web from a remote storage over NFS? If that were the case, they would have been placed on your local FS under /opt/kaltura/web and then, if you were to mount /opt/kaltura/web from a remote FS you would no longer see them.

Anyhow, you can always run:
\# yum reinstall kaltura-kmc

**Comment by bnordgren** [comment]
Well, assuming you meant egrep, the PDF and CSV files are all included in the output of your rpm command. Neither the pdf nor the csv directories are present on the filesystem. The filesystem was pulled from docker hub and nothing has been mounted over it. (i.e., I did no installing of any kind here locally).

```
[root@d088cdf34a3e tmp]# ls /opt/kaltura/web/content/docs/pdf/
ls: cannot access /opt/kaltura/web/content/docs/pdf/: No such file or directory
[root@d088cdf34a3e tmp]# ls /opt/kaltura/web/content/docs/csv/
ls: cannot access /opt/kaltura/web/content/docs/csv/: No such file or directory
[root@d088cdf34a3e tmp]# rpm -ql kaltura-kmc | egrep  'pdf|csv'
/opt/kaltura/app/alpha/web/lib/pdf/KMC3_Quick_Start_Guide(Cassiopea).pdf
/opt/kaltura/app/alpha/web/lib/pdf/KMC3_Quick_Start_Guide(Dragonfly_v1).pdf
/opt/kaltura/app/alpha/web/lib/pdf/KMC3_Quick_Start_Guide.pdf
/opt/kaltura/app/alpha/web/lib/pdf/KMC_Eagle_User_Manual.pdf
/opt/kaltura/app/alpha/web/lib/pdf/KMC_Quick_Start_Guide.pdf
/opt/kaltura/app/alpha/web/lib/pdf/KMC_User_Manual.pdf
/opt/kaltura/web/content/docs/NetHelp/Documents/exportinganalyticstoacsvfile.htm
/opt/kaltura/web/content/docs/NetHelp/Documents/ingestamediafilebundledwithmetadatacsvxmlapi.htm
/opt/kaltura/web/content/docs/csv
/opt/kaltura/web/content/docs/csv/kaltura_batch_upload_andromeda.csv
/opt/kaltura/web/content/docs/csv/kaltura_batch_upload_cassiopeia.csv
/opt/kaltura/web/content/docs/csv/kaltura_batch_upload_eagle.csv
/opt/kaltura/web/content/docs/csv/kaltura_batch_upload_falcon_categories.csv
/opt/kaltura/web/content/docs/csv/kaltura_batch_upload_falcon_category.csv
/opt/kaltura/web/content/docs/csv/kaltura_bulk_upload_falcon_categoryUser.csv
/opt/kaltura/web/content/docs/csv/kaltura_bulk_upload_falcon_user.csv
/opt/kaltura/web/content/docs/falconHelp/NetHelp/Documents/Kaltura_Management_Console_(KMC)_User_Manual.pdf
/opt/kaltura/web/content/docs/pdf
/opt/kaltura/web/content/docs/pdf/KMC3_Quick_Start_Guide(Cassiopea).pdf
/opt/kaltura/web/content/docs/pdf/KMC3_Quick_Start_Guide(Dragonfly_v1).pdf
/opt/kaltura/web/content/docs/pdf/KMC3_Quick_Start_Guide.pdf
/opt/kaltura/web/content/docs/pdf/KMC_Eagle_User_Manual.pdf
/opt/kaltura/web/content/docs/pdf/KMC_Quick_Start_Guide.pdf
/opt/kaltura/web/content/docs/pdf/KMC_User_Manual.pdf
/opt/kaltura/web/flash/kmc/v5.42.0/uiconf/kaltura/kmc/andromeda_sample.csv
/opt/kaltura/web/flash/kmc/v5.42.0/uiconf/kaltura/kmc/sample.csv
```

The yum reinstall completed successfully, and the directories are still not present on the filesystem. Oddly, verifying the kaltura-kmc package produces no output, which I understand means that it succeeded...

```
[root@d088cdf34a3e Kaltura-noarch]# rpm -V kaltura-kmc
[root@d088cdf34a3e Kaltura-noarch]#
```

And to show the mounting situation inside the docker container: 

```[root@d088cdf34a3e Kaltura-noarch]# df
Filesystem           1K-blocks     Used Available Use% Mounted on
overlay              269236224 10875632 258360592   5% /
tmpfs                  2022652       16   2022636   1% /dev
tmpfs                  2022652        0   2022652   0% /sys/fs/cgroup
/dev/mapper/atomicos-docker--root--lv
                     269236224 10875632 258360592   5% /etc/resolv.conf
/dev/mapper/atomicos-docker--root--lv
                     269236224 10875632 258360592   5% /etc/hostname
/dev/mapper/atomicos-docker--root--lv
                     269236224 10875632 258360592   5% /etc/hosts
shm                      65536        0     65536   0% /dev/shm
tmpfs                    65536        0     65536   0% /run
tmpfs                    65536        0     65536   0% /var/log/journal
/dev/mapper/atomicos-root
                       3061760  1517164   1544596  50% /var/log/journal/d088cdf34a3e2228b346b9197ee81969
tmpfs                  2022652  1641420    381232  82% /tmp
tmpfs                  2022652       16   2022636   1% /proc/kcore
tmpfs                  2022652       16   2022636   1% /proc/latency_stats
tmpfs                  2022652       16   2022636   1% /proc/timer_list
tmpfs                  2022652       16   2022636   1% /proc/sched_debug
tmpfs                  2022652        0   2022652   0% /sys/firmware
```

I'm tempted to drop this container and start fresh. However, it appears that the docker build for Mercury 13.0.0 is failing at the moment... May wait until it starts working.

**Comment by bnordgren** [comment]
BTW: You may want to check the docker builds. It appears that the builds for actual releases have been failing, and "latest" is currently Lynx-12.18.0. I'm installing the nightly build now, to see if that makes any difference...

**Comment by bnordgren** [comment]
@jessp01 Same story as above with the nightly build, albeit with a newer version of the kaltura-kmc package:

```
[root@09d41c92f9da /]# ls /opt/kaltura/web/content/docs/csv/
ls: cannot access /opt/kaltura/web/content/docs/csv/: No such file or directory
[root@09d41c92f9da /]# rpm -qa | grep kaltura-kmc
kaltura-kmc-v5.42.3-1.noarch
```

**Comment by jessp01** [comment]
Hi @bnordgren,

Sorry for the delay in response, finally got around to looking into it.
The root cause is that the docker hub centos:6 image has:
```
tsflags=nodocs
```
in /etc/yum.conf

This causes YUM to pass --excludedocs when calling rpm which means rpm will not deploy files marked with %doc in the package spec file.
This commit fixes it by commenting that option out in /etc/yum.conf:
https://github.com/kaltura/platform-install-packages/commit/f741dace97451c01c3ca9ae8679a1b7cd04ef095

As for the docker build failures, see my reply here:
https://github.com/kaltura/platform-install-packages/issues/604

Thanks for reporting both,
