### ISSUE TITLE
kmc1 file has php code in it when it hits the browser

### ISSUE THREAD

**Issue by bnordgren** [kaltura/platform-install-packages#598]
I have a brand new installation of kaltura all-in-one via the docker installation. Docker is running on Fedora 26 atomic, also new.

I have run the setup script, and it completed successfully when I told it to use http instead of https. The admin console seems to work fine as far as I can tell.

The main area of the KMC application page, however, is blank. My browser (Firefox 54) complains of an error in the file "kmc1" (no extension). It appears to be an html file where the php code was left in, and the php code is giving me errors in my browser. I cannot locate a file named "kmc1" (no extension). The upper bar containing the tabs ("Dashboard", "Content", etc.) is present.

I am logged in as the admin user created during the run of the setup script.

**Comment by jessp01** [comment]
Hi @bnordgren,
Please see my reply here:
https://forum.kaltura.org/t/kaltura-media-center-kmc1-file/7251

Let's continue the discussion there, should you have additional questions,
