### ISSUE TITLE
Community Edition installation failing

### ISSUE THREAD

**Issue by NKumarA** [kaltura/platform-install-packages#601]
In the process of Kaltura Community Edition installation on AWS EC2 RedHat 7.3 Serve 64-bit instance found the below error during DB configuration  

Followed the installation instructions based on this page https://serverpilot.io/community/articles/how-to-disable-strict-mode-in-mysql-5-7.html 

Configuring your Kaltura DB...

Checking MySQL version..
Ver 5.5.56-MariaDB found compatible
innodb_log_file_size => 32M
Your MySQL settings are incorrect, do you wish to run /opt/kaltura/bin/kaltura-mysql-settings.sh in order to correct them? [Y/n]
y
**Please adjust your MySQL configuration manually and re-run.
ERROR: we failed on something else..**

We could connect to the MySQL DB which is installed on the same AWS-EC2 RHEL 7 box.
Can you please help, we might be missing some configuration

**Comment by jessp01** [comment]
Hi @NKumarA,

Please input "Y" [uppercased], not "y", anything other than "Y" is evaluated as NO.
That's because this changes crucial MySQL settings and we want to be as explicit as possible when getting the input.

Thanks,

**Comment by NKumarA** [comment]
Hi Jessp
thanks for pointing out the mistake
After correcting the input tables got created but it fails with the below error
Your MySQL settings are incorrect, do you wish to run /opt/kaltura/bin/kaltura-mysql-settings.sh in order to correct them? [Y/n]
Y
package mysql-server is not installed
mariadb-server-5.5.56-2.el7.x86_64
Redirecting to /bin/systemctl restart  mariadb.service
CREATE USER kaltura;
CREATE USER etl;
CREATE DATABASE kaltura;
CREATE DATABASE kaltura_sphinx_log;
CREATE DATABASE kalturadw;
CREATE DATABASE kalturadw_ds;
CREATE DATABASE kalturadw_bisources;
CREATE DATABASE kalturalog;
Checking connectivity to needed daemons...
Connectivity test passed:)
Cleaning cache..
Populating DB with data.. please wait..
Output for /opt/kaltura/app/deployment/base/scripts/installPlugins.php being logged into /opt/kaltura/log/installPlugins.log
Output for /opt/kaltura/app/deployment/base/scripts/insertDefaults.php being logged into /opt/kaltura/log/insertDefaults.log


**kaltura-db-config.sh FAILED with: 255 on line 189

Archving logs to /opt/kaltura/log/log_10_08_17_10_02.tar.gz...
ERROR: we failed on something else..**

I have attached the kaltura-db-config.sh file
below is the 

[kaltura-db-config.zip](https://github.com/kaltura/platform-install-packages/files/1215245/kaltura-db-config.zip)

**Comment by jessp01** [comment]
What's in /opt/kaltura/log/insertDefaults.log?

**Comment by NKumarA** [comment]
Attached is the file log file
We could see fatal timezone issue? Is that causing the issue

[insertDefaults.zip](https://github.com/kaltura/platform-install-packages/files/1215293/insertDefaults.zip)

**Comment by jessp01** [comment]
Your timezone is indeed incorrect.
Here you can find a list of the TZs PHP supports:
http://php.net/manual/en/timezones.php

Correct this and try again.

**Comment by NKumarA** [comment]
@jess 
entering the right zone resolved the issue
thanks for assisting
