### ISSUE TITLE
Unable to login to KMC console of Community Edtion

### ISSUE THREAD

**Issue by NKumarA** [kaltura/platform-install-packages#603]
Installation and configuration of Kaltura Community edition was successfull.
Services that are configured on default port 80 are working fine for example I could able to login to 'Admin console'

But when I click Mangement Console link from index.php page(check KMC-Page screen shot in the attachment) getting error (check Error screen shot in the attachment) with message **"failed Error_Connection_Refused".**
**http://<hostName>.com:7070/lib/js/jquery-1.8.3.min.js** 

I checked our machine there is no service is running on port 7070

Please let me know which service I need to start and how? to access the KMC console.

[Kaltura.zip](https://github.com/kaltura/platform-install-packages/files/1227193/Kaltura.zip)

****Note: 
1. During the configuration i gave custom port as 7070 for CDN service as below
The host will be accessed over http(s). In case your CDN operates on a non-defau                                                                                        lt port, please input CDNHOST:PORT.
<hostName>:7070**

2. Flash player is already installed on our system.**

**Comment by jessp01** [comment]
Hi @NKumarA,

Not sure I understand...  If you inputted a CDN endpoint URL using 7070 as port, obviously, that endpoint needs to exist and be accessible from the server on which you installed Kaltura. 
If you do not work with an external CDN, you can input the same hostname and port as the one Apache is running on that machine. 

I'm closing this issue but should you have additional questions, feel free to post them at forum.kaltura.org
