### ISSUE TITLE
Docker build failing for last several releases

### ISSUE THREAD

**Issue by bnordgren** [kaltura/platform-install-packages#604]
Nightlies sometimes succeed. The error given by the 13.1.0 release: 

```
The command '/bin/sh -c yum install -y kaltura-server' returned a non-zero code: 1
```

See: https://hub.docker.com/r/kaltura/server/builds/bzfv5jydtjner7qpawahqk7/

**Comment by bnordgren** [comment]
Recent failures for the nightlies return this error: 

```
Build failed: The command '/bin/sh -c service postfix start' returned a non-zero code: 1
```

**Comment by jessp01** [comment]
Hi @bnordgren,

Thanks for reporting, much appreciated. Please see this commit which addresses both issues:
https://github.com/kaltura/platform-install-packages/commit/c1df568cea3de43731445c9a1529e20e548e3d80
