### ISSUE TITLE
Apache Configuration + Kaltura installation Guide (Ubuntu 16.04 LTS)

### ISSUE THREAD

**Issue by DPratapSingh** [kaltura/platform-install-packages#605]
Can please some one give a detailed guide for installation of Kaltura single package & Apache configuration as i'm stuck at configuration........
@carise @zoharbabin @jpluijmers @kohend @itaykinnrot @jessp01
@NKumarA

**Comment by DPratapSingh** [comment]
@carise @zoharbabin @jpluijmers @kohend @itaykinnrot @jessp01

**Comment by jessp01** [comment]
Hi @DPratapSingh,

See https://github.com/kaltura/platform-install-packages#documentation-and-guides.
Should you have any questions, please post them at forum.kaltura.org.

**Comment by DPratapSingh** [comment]
can u please give me the detail apache configuration for kaltura....... i'm unable to configure it...
@jessp01
