### ISSUE TITLE
Error processing package kaltura-nginx (–configure) 

### ISSUE THREAD

**Issue by DPratapSingh** [kaltura/platform-install-packages#609]
Hi

I encountered a error while installing kaltura, on Ubuntu 14.04 LTS

Restarting nginx: nginx: [emerg] invalid host in upstream “http://114.79.142.190” in /opt/kaltura/nginx/conf/nginx.conf:17
nginx: configuration file /opt/kaltura/nginx/conf/nginx.conf test failed
invoke-rc.d: initscript kaltura-nginx, action “restart” failed.
dpkg: error processing package kaltura-nginx (–configure):
subprocess installed post-installation script returned error exit status 1
Processing triggers for ureadahead (0.100.0-16) …
Processing triggers for libc-bin (2.19-0ubuntu6.9) …
Errors were encountered while processing:
kaltura-nginx
E: Sub-process /usr/bin/dpkg returned an error code (1)
A package failed to install. Trying to recover:
Setting up kaltura-nginx (1.12-4) …
System start/stop links for /etc/init.d/kaltura-nginx already exist.
Restarting nginx: nginx: [emerg] invalid host in upstream “http://114.79.142.190” in /opt/kaltura/nginx/conf/nginx.conf:17
nginx: configuration file /opt/kaltura/nginx/conf/nginx.conf test failed
invoke-rc.d: initscript kaltura-nginx, action “restart” failed.
dpkg: error processing package kaltura-nginx (–configure):
subprocess installed post-installation script returned error exit status 1
Processing triggers for libc-bin (2.19-0ubuntu6.9) …
Errors were encountered while processing:
kaltura-nginx

**Comment by jessp01** [comment]
As the message reads, you've inputted an invalid hostname. It should be the machine's hostname or IP, without the protocol.
