### ISSUE TITLE
Unable to find ui_conf_id of upload widget

### ISSUE THREAD

**Issue by chaitut715** [kaltura/platform-install-packages#614]
We are trying to integrate Kaltura with sakai.
We need to give upload player widget but couldn't find.
If we create a new player and access it, we are getting /flash/flexwrapper/v1.2/FlexWrapper.swf was not found on this server

We are able to successfully integrate sakai with Kaltura cloud trial version.
Kaltura  contribution wizard widget id of Kaltura cloud is 11601051.

Please help me how to find/create widget.

**Comment by jessp01** [comment]
Hi @chaitut715,

I'm guessing Sakai wants you to input the UI conf ID for KCW [Kaltura Contribution Wizard].
Easiest way to obtain that is by connecting to the 'kaltura' MySQL DB and running this query:
```
mysql> select id from ui_conf where name like '%Kaltrua kcw%'\G
```
You can also search for it using the API by making a request to uiconf.list()

I'm closing this issue as we rather discuss general questions at forum.kaltura.org and keep the GitHub issues section for bug reports. If you have additional questions, please post there.

Thanks,
