### ISSUE TITLE
Kaltura studio asking for login for already loggedin user

### ISSUE THREAD

**Issue by syedwaseemjan** [kaltura/platform-install-packages#615]
I have logged-in successfully in kaltura admin panel but when I click the studio tab I get this
![kaltura-login](https://user-images.githubusercontent.com/10591478/32608319-d32ec26e-c57d-11e7-8308-23a126088abd.png)
Providing credentials still shows the error message. The error most probably started appearing when I run kaltura-config-all to change domain name from http://192.168.90.105 to http://pilot.kaltura.artstor.org. I am not sure may be it was there even before domain name change and I only noticed now. I also changed entries in 

**Delivery_profile entries:**

```
mysql> select id,name,url,host_name from delivery_profile;
+------+------------------------------------------------+------------------------------------------+---------------------------+
| id   | name                                           | url                                      | host_name                 |
+------+------------------------------------------------+------------------------------------------+---------------------------+
| 1001 | Kaltura HLS segmentation                       | http://pilot.kaltura.artstor.org:88/hls  | pilot.kaltura.artstor.org |
| 1002 | Kaltura HDS segmentation                       | http://pilot.kaltura.artstor.org:88/hds  | pilot.kaltura.artstor.org |
| 1003 | Kaltura DASH segmentation                      | http://pilot.kaltura.artstor.org:88/dash | pilot.kaltura.artstor.org |
|  501 | Default HTTP Delivery Profile                  | http://pilot.kaltura.artstor.org:80      | pilot.kaltura.artstor.org |
|  500 | Default HTTP Delivery Profile                  | http://pilot.kaltura.artstor.org:80      | pilot.kaltura.artstor.org |
|  101 | Default HLS Live Delivery Profile              | NULL                                     | NULL                      |
|    1 | Default HD Network Live Delivery Profile       | NULL                                     | NULL                      |
|    2 | Default HDS Live Delivery Profile              | NULL                                     | NULL                      |
|  201 | Default RTMP Live Delivery Profile             | NULL                                     | NULL                      |
| 1004 | Default HLS Live Delivery Profile              | NULL                                     | NULL                      |
| 1005 | Default HLS Network Live Delivery Profile      | NULL                                     | NULL                      |
| 1006 | Default HD Network Live Delivery Profile       | NULL                                     | NULL                      |
| 1007 | Default HDS Live Delivery Profile              | NULL                                     | NULL                      |
| 1008 | Default RTMP Live Delivery Profile             | NULL                                     | NULL                      |
|  301 | Default MPEG-DASH Live Delivery Profile        | NULL                                     | NULL                      |
| 1009 | Default HLS To Multicast Live Delivery Profile | NULL                                     | NULL                      |
+------+------------------------------------------------+------------------------------------------+---------------------------+
16 rows in set (0.00 sec)



```

Library Versions:

[dev@sspilotkaltura ~]$ rpm -qa "kaltura*"
kaltura-libopencore-amr-0.1.2-2.x86_64
kaltura-sshpass-1.05-1.x86_64
kaltura-kdp3wrapper-v37.0-1.noarch
kaltura-kdp3-v3.9.9-2.noarch
kaltura-libmediainfo-0.7.61-7.x86_64
kaltura-segmenter-1.0-2.x86_64
kaltura-kmc-v5.42.3-2.noarch
kaltura-pentaho-4.2.1-2.x86_64
kaltura-libfaac-1.26-1.x86_64
kaltura-libmemcached-1.0.16-2.x86_64
kaltura-kvpm-v1.0.6-1.noarch
kaltura-flexwrapper-v1.2-1.noarch
kaltura-mediainfo-0.7.61-7.x86_64
kaltura-sphinx-2.2.1-21.x86_64
kaltura-postinst-1.0.33-17.noarch
kaltura-batch-13.1.0-1.noarch
kaltura-kupload-v1.2.16-2.noarch
kaltura-dwh-12.14.0-1.noarch
kaltura-release-13.3.0-1.noarch
kaltura-x264-0.140-2.20140104.x86_64
kaltura-a52dec-0.7.4-11.x86_64
kaltura-lame-3.99.5-3.x86_64
kaltura-kclip-v1.1.2.1-2.noarch
kaltura-kdpwrapper-v11.0-1.noarch
kaltura-kcw-1.0.0-6.noarch
kaltura-fdk-acc-0.1.3-1.x86_64
kaltura-mencoder-3.4.6-9.x86_64
kaltura-html5-studio-v2.1.0-1.noarch
kaltura-monit-5.23.0-1.x86_64
kaltura-base-13.1.0-18.noarch
kaltura-ffmpeg-3.2-1.x86_64
kaltura-front-13.1.0-1.noarch
kaltura-clipapp-1.3-2.noarch
kaltura-server-13.1.0-1.noarch
kaltura-libass-0.9.11-2.x86_64
kaltura-libmcrypt-2.5.7-5.x86_64
kaltura-libmcrypt-devel-2.5.7-5.x86_64
kaltura-krecord-1.0.0-1.noarch
kaltura-kdp-v2.7.0-1.noarch
kaltura-widgets-1.0.0-8.noarch
kaltura-librtmp-2.3-3.x86_64
kaltura-html5lib-v2.60-1.noarch
kaltura-ffmpeg-aux-2.1.3-1.x86_64
kaltura-nginx-1.12.0-6.x86_64
kaltura-red5-1.0.6-1.x86_64

This is what we get when our other app try to access and play the files
**Kaltlog**

> 2017-11-09 08:58:06 [0.000385] [192.168.26.118] [1617499704] [28] [API] [KalturaStatement->execute] DEBUG: Sql took - 0.00023603439331055 seconds
> 2017-11-09 08:58:06 [0.000305] [192.168.26.118] [1617499704] [29] [API] [kPermissionManager::isActionPermitted] ERR: exception 'Exception' with message 'Action is not permitted' in /opt/kaltura/app/infra/log/KalturaLog.php:83
> Stack trace:
> #0 /opt/kaltura/app/alpha/apps/kaltura/lib/kPermissionManager.php(806): KalturaLog::err('Action is not p...')
> --
> #7 {main}
> 2017-11-09 08:58:06 [0.000163] [192.168.26.118] [1617499704] [30] [API] [KalturaBaseService->isPermitted] ERR: exception 'Exception' with message 'Action is not permitted' in /opt/kaltura/app/infra/log/KalturaLog.php:83
> Stack trace:
> #0 /opt/kaltura/app/api_v3/lib/KalturaBaseService.php(192): KalturaLog::err('Action is not p...')
> --
> ==> /opt/kaltura/log/kaltura_apache_errors.log <==
> [Thu Nov 09 08:58:09 2017] [error] [client 192.168.90.84] PHP Fatal error:  Uncaught exception 'Exception' with message 'Error getting sources from server. Please try again.\nUnknown widget [_101]' in /nask/web/html5/html5lib/v2.60/modules/KalturaSupport/Client/KalturaClientHelper.php:65\nStack trace:\n#0 /nask/web/html5/html5lib/v2.60/modules/KalturaSupport/Client/KalturaClientHelper.php(53): KalturaClientHelper->generateKS('_101')\n#1 /nask/web/html5/html5lib/v2.60/modules/KalturaSupport/Client/KalturaClientHelper.php(16): KalturaClientHelper->getClient()\n#2 /nask/web/html5/html5lib/v2.60/modules/KalturaSupport/KalturaCommon.php(124): KalturaClientHelper->__construct(Array)\n#3 /nask/web/html5/html5lib/v2.60/includes/Pimple.php(122): {closure}(Object(Pimple))\n#4 /nask/web/html5/html5lib/v2.60/includes/Pimple.php(83): {closure}(Object(Pimple))\n#5 /nask/web/html5/html5lib/v2.60/modules/KalturaSupport/kalturaIframeClass.php(29): Pimple->offsetGet('client_helper')\n#6 /nask/web/html5/html5lib/v2.60/modules/KalturaSupport/kalturaIframe.php(15): kalturaIframeClass->__construct()\n#7 /nask/web/h in /nask/web/html5/html5lib/v2.60/modules/KalturaSupport/Client/KalturaClientHelper.php on line 65, referer: http://192.168.26.118:5555/stor/8adf5a1c-c1c5-46a4-bea0-1140921d1472_kplayer

>

**Comment by jessp01** [comment]
Hi @syedwaseemjan,

First, I suggest you try re-running /opt/kaltura/bin/kaltura-front-config.sh
If that does not solve the issue, please open your browser's dev tools and check for errors under both the "Console" and "Network" tabs and post them.

**Comment by syedwaseemjan** [comment]
**Console**
```
kWidget: Kaltura HTML5 Version: 2.60
mwEmbedLoader.php:14 Error: Using non-production version of kaltura player library. Please see http://knowledge.kaltura.com/production-player-urls
checkEnvironment @ mwEmbedLoader.php:14
setup @ mwEmbedLoader.php:12
(anonymous) @ mwEmbedLoader.php:123
kmc4#studio|universal_studio:1 This page includes a password or credit card input in a non-secure context. A warning has been added to the URL bar. For more information, see https://goo.gl/zmWq3m.
```
**Network**
Everything seems to be fine in Network tab. 
![kaltura-network](https://user-images.githubusercontent.com/10591478/32646977-f9f23b4a-c610-11e7-9c7a-873dbd234644.png)
Also this doesn't appear for Flash Studio tab. It only happens for Universal Studio.

**Comment by syedwaseemjan** [comment]
Finally resolved it. This was something related to mounted NAS drive. I have mounted my /opt/kaltura/web folder in NAS drive previously and rerunning kaltura-config-all was somehow not updating something that was needed to be updated for domain name change. So I 

- Unlinked /opt/kaltura/web.
- Rerun config-all.
- Copied all the folders(except content folder) in web to NAS drive manually.
          `sudo cp -rp /opt/kaltura/web/<folder-name> /nask/web/`
- Created symlink again.
- Executed kaltura-config-all again.
