### ISSUE TITLE
Installation instructions not working

### ISSUE THREAD

**Issue by stgabhas** [kaltura/platform-install-packages#617]
Can the installation instructions for Single Server RH based linux distros be updated please.
I am getting the following error for SSL step by step instruction:

#yum install mariadb-server
Loaded plugins: fastestmirror
Kaltura                                                                                                              | 2.9 kB  00:00:00     
Kaltura-noarch                                                                                                       | 2.9 kB  00:00:00     
base                                                                                                                 | 3.6 kB  00:00:00     
extras                                                                                                               | 3.4 kB  00:00:00     
updates                                                                                                              | 3.4 kB  00:00:00     
Kaltura/7/x86_64/primary_db    FAILED                                          
http://installrepo.kaltura.org/releases/latest/7/RPMS/x86_64/repodata/60e40ae4bcce08c50e1437fbb3b5312217f664584777ef5779571e92652eee3e-primary.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below knowledge base article 

https://access.redhat.com/articles/1320623

If above article doesn't help to resolve this issue please create a bug on https://bugs.centos.org/

Kaltura-noarch/7/primary_db    FAILED                                          
http://installrepo.kaltura.org/releases/latest/7/RPMS/noarch/repodata/31ddacbc87554be31ede0c131c87633457b37e8c007359eca1355d80ed3b798d-primary.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
Loading mirror speeds from cached hostfile
 * base: mirrors.usinternet.com
 * extras: mirrors.usinternet.com
 * updates: mirrors.usinternet.com
Kaltura-noarch/7/primary_db    FAILED                                          
http://installrepo.kaltura.org/releases/latest/7/RPMS/noarch/repodata/31ddacbc87554be31ede0c131c87633457b37e8c007359eca1355d80ed3b798d-primary.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
Kaltura/7/x86_64/primary_db    FAILED                                          
http://installrepo.kaltura.org/releases/latest/7/RPMS/x86_64/repodata/60e40ae4bcce08c50e1437fbb3b5312217f664584777ef5779571e92652eee3e-primary.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
http://installrepo.kaltura.org/releases/latest/7/RPMS/x86_64/repodata/60e40ae4bcce08c50e1437fbb3b5312217f664584777ef5779571e92652eee3e-primary.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.

 One of the configured repositories failed (Kaltura Server),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=Kaltura ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable Kaltura
        or
            subscription-manager repos --disable=Kaltura

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=Kaltura.skip_if_unavailable=true

failure: repodata/60e40ae4bcce08c50e1437fbb3b5312217f664584777ef5779571e92652eee3e-primary.sqlite.bz2 from Kaltura: [Errno 256] No more mirrors to try.
http://installrepo.kaltura.org/releases/latest/7/RPMS/x86_64/repodata/60e40ae4bcce08c50e1437fbb3b5312217f664584777ef5779571e92652eee3e-primary.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found

**Comment by stgabhas** [comment]
Eliminated the error above by adding **.origin** in /etc/yum.repos.d/kaltura.repo

**Comment by jessp01** [comment]
Hi @stgabhas,
It sometimes takes a little while for all the CDN edges to update. I presume we're good now?

**Comment by jessp01** [comment]
Closing for now but please reopen if you're still having issues.
