### ISSUE TITLE
Unable to Upload media using "Record from Webcam"

### ISSUE THREAD

**Issue by sonanchenko** [kaltura/platform-install-packages#625]
Dear Colleagues,

I'm using Kaltura 13.13.
Maybe can be useful: I use http not https in my setup.

STR:
1. Go to KMC
2. Click Upload
3. Choose Record from Webcam

Actual result:
No web cam access
Page haven't asked for any permissions.
Here is what I see in browser error console:
```
Cross-origin plugin content from  must have a visible size larger than 400 x 300 pixels, or it will be blocked. Invisible content is always blocked.
```
Here is what I see in site settings - 
![image](https://user-images.githubusercontent.com/4506681/36314291-042c5be4-133d-11e8-8f6d-3d07225d5052.png)

Other sites can get access to my webcam.

Please check and feel free to ask if any additional information is required.
 
If I places the issue to the incorrect repo, please let me know where to move it

Than you for considering my request.

**Comment by jessp01** [comment]
Hello @sonanchenko,

KMC uses a deprecated Flash widget for the webcam recording. We no longer support or maintain it and it will become completely obsolete once our new KMC [based on Angular and completely Flash free] will be released.

Please see https://github.com/kaltura/webrtc-krecord instead.
This uses the [MediaRecorder API](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder) and should work on Firefox 29 or later, or Chrome 47 or later with Enable experimental Web Platform features enabled from chrome://flags.

You can see a live demo of it here:
https://www.kaltura.org/demos/krecord/index.html
The code is licensed under AGPLv3 and you are welcome to obtain it, modify it to suit your needs and host it on your own server.
