### ISSUE TITLE
n all

### ISSUE THREAD

**Issue by fordentinc** [kaltura/platform-install-packages#627]
- [ ] I've read the [guidelines for Contributing to Kaltura Projects](https://github.com/kaltura/platform-install-packages/blob/master/CONTRIBUTING.md)
- [ ] I've read the [installation guides](https://github.com/kaltura/platform-install-packages#documentation-and-guides) and [troubleshooting FAQ](https://github.com/kaltura/platform-install-packages/blob/master/doc/kaltura-packages-faq.md)
- [ ] This is not a support request or question that should be posted on the [Kaltura forum](https://forum.kaltura.org) 

## Bug report

**Please provide steps to reproduce, including errors from /opt/kaltura/log/kaltura_api_v3.log, /opt/kaltura/log/kaltura_apache_errors*log and /opt/kaltura/log/kaltura_prod.log:**

**Linux distribution name and version:**

**Are you using the RPM or deb packages?**
- [ ] RPM
- [ ] deb

**When using RPM, paste the output for:**
```
# rpm -qa "kaltura-*"
```

**For deb based systems:**
```
# dpkg -l "kaltura-*"
```

**Is this an all in one instance [single server] or a cluster?**
- [ ] All in one
- [ ] Cluster

**If applicable, please provide the MySQL version**

**If you're having an issue with a specific media asset, please provide a link from which it can be downloaded/played:**

**Comment by jessp01** [comment]
Hi @fordentinc,

You seem to have submitted an empty bug report.. Please update.

**Comment by jessp01** [comment]
Closing due to lack of response. If still relevant, reopen and input the required information.

**Comment by fordentinc** [comment]
My self and another Tech Friend of mine tried over 11 times to install this package with absolute no luck. 
The package has promise but as for the database issues and such it always crashed all 11 times on 6 different Linux versions.  We finally Gave up trying as it was taking to much time to get up and operational.

**Comment by jessp01** [comment]
@fordentinc - If you wish to provide the info requested in the bug reporting template, I'll be happy to help you troubleshoot. Without that, there's not much I can do..
