### ISSUE TITLE
Blank KMC after logging into KMC

### ISSUE THREAD

**Issue by pulkitj79** [kaltura/platform-install-packages#628]
- [ ] I've read the [guidelines for Contributing to Kaltura Projects](https://github.com/kaltura/platform-install-packages/blob/master/CONTRIBUTING.md)
- [ ] I've read the [installation guides](https://github.com/kaltura/platform-install-packages#documentation-and-guides) and [troubleshooting FAQ](https://github.com/kaltura/platform-install-packages/blob/master/doc/kaltura-packages-faq.md)
- [ ] This is not a support request or question that should be posted on the [Kaltura forum](https://forum.kaltura.org) 

## Bug report

I am getting the Blank KMC after login. I can see only the links to Dashboard etc. but clicking on them is not working.

**Please provide steps to reproduce, including errors from /opt/kaltura/log/kaltura_api_v3.log, /opt/kaltura/log/kaltura_apache_errors*log and /opt/kaltura/log/kaltura_prod.log:**

**Linux distribution name and version:**

**Are you using the RPM or deb packages?**
- [ ] deb

**When using RPM, paste the output for:**
```
# rpm -qa "kaltura-*"
```

**For deb based systems:**
```
# dpkg -l "kaltura-*"
```

**Is this an all in one instance [single server] or a cluster?**
- [ ] All in one

**If applicable, please provide the MySQL version**

**If you're having an issue with a specific media asset, please provide a link from which it can be downloaded/played:**

**Comment by jessp01** [comment]
Hi @pulkitj79,

Please see https://forum.kaltura.org/t/kaltura-media-center-kmc1-file/7251.
If you have additional questions afterwards, please post on the forum.

We'd rather use this repo's issues section for general bug reports exclusively and the forum for everything else.

Thanks,
