### ISSUE TITLE
/opt/kaltura/bin/kaltura-config-all.sh Problem!!!

### ISSUE THREAD

**Issue by redrajax** [kaltura/platform-install-packages#634]
WHen im using this code /opt/kaltura/bin/kaltura-config-all.sh to configure kaltura  
its calling out that No such file in directory i tried several times to reinstall centus 7 and than installed nginx and only after that i started installing kaltura but the problem is thesame again. Please if u have any suggestions to help me with that

**Comment by jessp01** [comment]
Hi @redrajax,

/opt/kaltura/bin/kaltura-config-all.sh is provided by the `kaltura-postinst` package.
What's the output for:
```sh
# rpm -qa "*kaltura*"
```
?

**Comment by redrajax** [comment]
kaltura-release-13.4.0-4.noarch

**Comment by jessp01** [comment]
If that's the only output then you haven't actually installed any of the required packages yet.
You need to run:
```sh
# yum install kaltura-server
```
which will fetch and install all the needed deps. If that fails, look at the output to understand why.
My first guess would be that you have not set SELinux to permissive mode as the howto says you should.

**Comment by jessp01** [comment]
Closing due to lack of response. Feel free to post at forum.kaltura.org if you have additional questions.
