### ISSUE TITLE
Debian database kaltura access error on installation

### ISSUE THREAD

**Issue by guidtz** [kaltura/platform-install-packages#640]
- [ ] I've read the [guidelines for Contributing to Kaltura Projects](https://github.com/kaltura/platform-install-packages/blob/master/CONTRIBUTING.md)
- [ ] I've read the [installation guides](https://github.com/kaltura/platform-install-packages#documentation-and-guides) and [troubleshooting FAQ](https://github.com/kaltura/platform-install-packages/blob/master/doc/kaltura-packages-faq.md)
- [ ] This is not a support request or question that should be posted on the [Kaltura forum](https://forum.kaltura.org) 

## Bug report

**Please provide steps to reproduce, including errors from /opt/kaltura/log/kaltura_api_v3.log, /opt/kaltura/log/kaltura_apache_errors*log and /opt/kaltura/log/kaltura_prod.log:**

**Linux distribution name and version:**
Debian 8

**Are you using the RPM or deb packages?**
- [ ] deb

**For deb based systems:**
```
# dpkg -l "kaltura-*"
Souhait=inconnU/Installé/suppRimé/Purgé/H=à garder
| État=Non/Installé/fichier-Config/dépaqUeté/échec-conFig/H=semi-installé/W=attend-traitement-déclenchements
|/ Err?=(aucune)/besoin Réinstallation (État,Err: majuscule=mauvais)
||/ Nom            Version      Architecture Description
+++-==============-============-============-==================================
iF  kaltura-base   14.7.0-2     all          Kaltura Open Source Video Platform
un  kaltura-php7-c <aucune>     <aucune>     (aucune description n'est disponib
un  kaltura-php7-c <aucune>     <aucune>     (aucune description n'est disponib
un  kaltura-php7-m <aucune>     <aucune>     (aucune description n'est disponib
un  kaltura-php7-m <aucune>     <aucune>     (aucune description n'est disponib
un  kaltura-php7-m <aucune>     <aucune>     (aucune description n'est disponib
ii  kaltura-postin 1.0.33-3+b9  all          Kaltura Open Source Video Platform
```

**Is this an all in one instance [single server] or a cluster?**
- [ ] All in one

**If applicable, please provide the MySQL version**
mysql-server-5 5.5.60-0+deb

**If you're having an issue with a specific media asset, please provide a link from which it can be downloaded/played:**

With install_kaltura_all_in_1.sh I have error for install process to access to kaltura database : 
`
INFO: testsClient generated successfully
ERROR 1045 (28000): Access denied for user 'kaltura'@'localhost' (using password: YES)
ERROR 1045 (28000): Access denied for user 'kaltura'@'localhost' (using password: YES)
`

If I connect manualy to mysql I have no kaltura user and no kaltura database created.

Thanks for you're help

**Comment by jessp01** [comment]
Hi @guidtz,

Sorry for the delayed response. I actually submitted one 5 days ago but it obviously did not go through for some reason...
In any event, did you invoke `mysql_secure_installation` as per the instructions here? https://github.com/kaltura/platform-install-packages/blob/Naos-14.7.0/doc/install-percona-deb.md#installing-the-mysql-55-percona-deb-package

That document recommends that you install the Percona deb package but using the ` mysql-server-5` package of version 5.5 should work equally well. As stated in the doc:
> The Kaltura Server currently supports all MySQL versions between 5.1 and 5.6.

Thanks,

**Comment by jessp01** [comment]
Closing due to lack of response. @guidtz, please reopen if you're still encountering issues.

**Comment by guidtz** [comment]
yes sorry for the delay. I installed mysql 5.5 from official mysql repos
