### ISSUE TITLE
Does the latest platform-install-packages include the HTML 5 kmc-ng?

### ISSUE THREAD

**Issue by fishfree** [kaltura/platform-install-packages#643]
That's https://github.com/kaltura/kmc-ng.

**Comment by jessp01** [comment]
Hi @fishfree,

Yes. The kaltura-kmcng package was first introduced in 14.1.0 [see https://github.com/kaltura/platform-install-packages/releases/tag/Naos-14.1.0]. Current stable Kaltura CE version is 14.10.0 and includes the latest kaltura-kmcng release - v5.5.2.

**Comment by fishfree** [comment]
@jessp01 Thank you! It's time to upgrade my Kaltura CE now.
