### ISSUE TITLE
How to activate plugins after the installation?

### ISSUE THREAD

**Issue by Patryk57** [kaltura/platform-install-packages#644]
Dear Kaltura community,

I am trying to activate DRM plugins on a new standalone Kaltura installation.
Here are my current software versions:
```
OS: CentOS 7
PHP: 5.6

kaltura-release-13.4.0-4.noarch
kaltura-html5-studio-v2.2.1-1.noarch
kaltura-ffmpeg-4.0.2-1.x86_64
kaltura-kclip-v1.1.2.1-2.noarch
kaltura-flexwrapper-v1.2-1.noarch
kaltura-front-14.13.0-1.noarch
kaltura-server-14.13.0-1.noarch
kaltura-x264-0.140-2.20140104.x86_64
kaltura-libfaac-1.28-1.x86_64
kaltura-kdp3wrapper-v37.0-1.noarch
kaltura-batch-14.13.0-1.noarch
kaltura-libopencore-amr-0.1.3-1.x86_64
kaltura-sshpass-1.05-1.x86_64
kaltura-postinst-1.0.33-58.noarch
kaltura-sphinx-2.2.1-21.x86_64
kaltura-base-14.13.0-15.noarch
kaltura-krecord-1.0.0-1.noarch
kaltura-kdp3-v3.9.9-2.noarch
kaltura-kdp-v2.7.0-1.noarch
kaltura-kmcng-v5.6.3-1.noarch
kaltura-pentaho-4.2.1-2.x86_64
kaltura-lame-3.99.5-3.x86_64
kaltura-a52dec-0.7.4-11.x86_64
kaltura-mediainfo-0.7.61-9.x86_64
kaltura-monit-5.25.2-2.x86_64
kaltura-ffmpeg-aux-2.1.3-2.x86_64
kaltura-nginx-1.14.0-5.x86_64
kaltura-kmcng-analytics-front-v0.1-1.noarch
kaltura-kmc-v5.43.13-16.noarch
kaltura-kcw-1.0.0-6.noarch
kaltura-live-analytics-front-v2.7.3-2.noarch
kaltura-libmediainfo-0.7.61-8.x86_64
kaltura-libvpx-1.7.0-1.x86_64
kaltura-segmenter-1.0-3.x86_64
kaltura-kdpwrapper-v11.0-1.noarch
kaltura-clipapp-1.3-2.noarch
kaltura-html5lib-v2.74.1-1.noarch
kaltura-kupload-v1.2.16-2.noarch
kaltura-widgets-1.0.0-9.noarch
kaltura-dwh-12.14.0-1.noarch
```

These plugins are not activated by default and I am having issue to do it.
Here is my procedure:

> **1.** I edit the plugin ini file
> 
> [root@~]# vi /opt/kaltura/app/configurations/plugins.ini
> And I uncomment the following lines:
> Drm
> Widevine
> WidevineBulkUploadXml
> PlayReady

> 
> **2.** I rerun the batch server installation script
> [root@~]# /opt/kaltura/bin/kaltura-batch-config.sh

But then I have a blank page on the admin console as well as on the KMC.

The only error I get from the logs is the following apache Error log:
`[Tue Feb 12 10:02:42.980694 2019] [:error] [pid 12817] [client 146.220.130.51:50019] PHP Fatal error:  Undefined class constant 'SYSTEM_ADMIN_DRM_PROFILE_BASE' in /opt/kaltura/app/plugins/drm/admin/DrmProfileListAction.php on line 25`

I am missing something but I do not know what...
Do you know how to activate a plugin after the installation?

Many thanks in advance for your help.

Best regards,

Patrick

**Comment by jessp01** [comment]
Hello @Patryk57,

In general, after editing `/opt/kaltura/app/configurations/plugins.ini`, you need to:
```
php $APP_DIR/deployment/base/scripts/installPlugins.php
find $APP_DIR/cache/ -type f -exec rm {} \;
php $APP_DIR/generator/generate.php
find $BASE_DIR/app/cache/ -type d -exec chmod 775 {} \;
find $BASE_DIR/app/cache/ -type f -exec chmod 664 {} \;
chown -R kaltura.apache $BASE_DIR/app/cache/

service httpd restart
service memcached restart
```

If you're using Debian/Ubuntu, the steps are the same as above only the Apache user is `www-data` and the service name is `apache2`, not `httpd`.

That said, I fail to see how enabling these plugins will help you.. DRM is implemented using Widevine which is a proprietary, non-FOSS solution. As such, Kaltura CE is not shipped with what's needed in order for it to work.

For additional questions, please post at forum.kaltura.org instead.
Thanks,
