### ISSUE TITLE
Error during installation (Ubuntu 14.04)

### ISSUE THREAD

**Issue by werkon** [kaltura/platform-install-packages#645]
Hi,
i tried to install kaltura via  ./install_kaltura_all_in_1.sh on AWS Ubuntu 14.04.
Got error:

E: Failed to fetch http://installrepo.kaltura.org/repo/apt/debian/pool/main/k/kaltura-kmc/kaltura-kmc_5.43.13-4_all.deb: 404  Not Found [IP: 54.192.29.131 80]

The following packages will be REMOVED:
  kaltura-clipapp{u} kaltura-flexwrapper{u} kaltura-kclip{u} kaltura-kcw{u}
  kaltura-kdp{u} kaltura-kdp3{u} kaltura-kdp3wrapper{u}
  kaltura-kdpwrapper{u} kaltura-krecord{u} kaltura-kupload{u}

Any idea?
Thanks,
Werner

- [x ] I've read the [guidelines for Contributing to Kaltura Projects](https://github.com/kaltura/platform-install-packages/blob/master/CONTRIBUTING.md)
- [ x] I've read the [installation guides](https://github.com/kaltura/platform-install-packages#documentation-and-guides) and [troubleshooting FAQ](https://github.com/kaltura/platform-install-packages/blob/master/doc/kaltura-packages-faq.md)
- [ ] This is not a support request or question that should be posted on the [Kaltura forum](https://forum.kaltura.org) 

## Bug report

**Please provide steps to reproduce, including errors from /opt/kaltura/log/kaltura_api_v3.log, /opt/kaltura/log/kaltura_apache_errors*log and /opt/kaltura/log/kaltura_prod.log:**

**Linux distribution name and version:**
Ubuntu 14.04

**Are you using the RPM or deb packages?**
- [ ] RPM
- [x ] deb

**When using RPM, paste the output for:**
```
# rpm -qa "kaltura-*"
```

**For deb based systems:**
```
# dpkg -l "kaltura-*"
```

**Is this an all in one instance [single server] or a cluster?**
- [ x] All in one
- [ ] Cluster

**If applicable, please provide the MySQL version**

**If you're having an issue with a specific media asset, please provide a link from which it can be downloaded/played:**

**Comment by jessp01** [comment]
Hello @werkon,

What's the contents of /etc/apt/sources.list.d/kaltura.list?
Also, did you run:
```
# apt-get update
```
?

Lastly, what's the output for:
```
# apt-cache policy kaltura-kmc
```
?
For Ubuntu 14.04, it should be:
```
 kaltura-kmc:
  Installed: 5.43.13-11+b1
  Candidate: 5.43.13-11+b1
  Version table:
 *** 5.43.13-11+b1 0
        500 http://installrepo.origin.kaltura.org/repo/apt/debian/ naos/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by werkon** [comment]
Hi Jess,
1. deb [arch=amd64] http://installrepo.kaltura.org/repo/apt/debian mercury main
2 . apt-get update yes i did
3. :
root@ip-172-31-25-171:~# apt-cache policy kaltura-kmc
kaltura-kmc:
  Installed: (none)
  Candidate: 5.43.13-4
  Version table:
     5.43.13-4 0
        500 http://installrepo.kaltura.org/repo/apt/debian/ mercury/main amd64 Packages

looks different. why?

Thank you,
Werner

**Comment by jessp01** [comment]
Should be:
> deb [arch=amd64] http://installrepo.origin.kaltura.org/repo/apt/debian naos main
Please edit `/etc/apt/sources.list.d/kaltura.list` and then run `apt-get update`

**Comment by werkon** [comment]
Nice, it works. Thanks a lot! Werner
