### ISSUE TITLE
Persistent memory for kaltura docker container

### ISSUE THREAD

**Issue by bolotkalil** [kaltura/platform-install-packages#647]
Hello, Guys.

How do I can make persistent memory for all in one kaltura docker container? in every restart the container I have lose all data in my kaltura container. 

Please help me, suggest any solution.

Many thanks.

**Comment by jessp01** [comment]
Hi @bolotkalil,

The Kaltura container is no different than any other Docker container in that respect. See: https://docs.docker.com/engine/reference/commandline/commit/#commit-a-container-with-new-configurations
