### ISSUE TITLE
installation kaltura on ubuntu 16.04

### ISSUE THREAD

**Issue by sincerbex** [kaltura/platform-install-packages#651]
hi, i have installed kaltura on ubuntu 16.04 server. the installation was successful but I am unable to enter the admin. blank page with An error occurred (error code: API: -1). I installed kaltura with ssl. what can I check to find the problem? thanks for the support. best regards

**Comment by sincerbex** [comment]
hi @jessp01 ,
any suggestions?

**Comment by jessp01** [comment]
@sincerbex, please see my response here: https://forum.kaltura.org/t/kaltura-management-console-error/9824/2
