### ISSUE TITLE
Unmet dependencies kaltura-ffmpeg-aux but it is not installable

### ISSUE THREAD

**Issue by thatcherk1** [kaltura/platform-install-packages#654]
- [x ] I've read the [guidelines for Contributing to Kaltura Projects](https://github.com/kaltura/platform-install-packages/blob/master/CONTRIBUTING.md)
- [x ] I've read the [installation guides](https://github.com/kaltura/platform-install-packages#documentation-and-guides) and [troubleshooting FAQ](https://github.com/kaltura/platform-install-packages/blob/master/doc/kaltura-packages-faq.md)
- [x ] This is not a support request or question that should be posted on the [Kaltura forum](https://forum.kaltura.org) 

## Bug report

**Please provide steps to reproduce, including errors from /opt/kaltura/log/kaltura_api_v3.log, /opt/kaltura/log/kaltura_apache_errors*log and /opt/kaltura/log/kaltura_prod.log:**

**Linux distribution name and version:**
16.04.6

**Are you using the RPM or deb packages?**
- [ ] RPM
- [x ] deb

**For deb based systems:**
```
# dpkg -l "kaltura-*"
```

**Is this an all in one instance [single server] or a cluster?**
- [ x] All in one
- [ ] Cluster

**If applicable, please provide the MySQL version**
5.5

**If you're having an issue with a specific media asset, please provide a link from which it can be downloaded/played:**

I'm installing all-in-one on ESXi VM Ubuntu 16.04.6
Following the guide for 16.0.4. MySQL 5.5 as directed from the install guide.

Fresh install, following guide exactly. When I run this: `./install_kaltura_all_in_1.sh`
It stops partway through here: `kaltura-front` : Depends: kaltura-ffmpeg-aux but it is not installable
E: Unable to correct problems, you have held broken packages.`

my output from 'dpkg -l "kaltura-*" '

Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  kaltura-base   15.0.0-2     all          Kaltura Open Source Video Platfor
ii  kaltura-clipap 1.3-1+b2     all          Kaltura Video Presentations Manag
ii  kaltura-flexwr 1.2-1+b1     all          Kaltura Video Presentations Manag
ii  kaltura-html5- 0.2          all          Kaltura Open Source Video Platfor
ii  kaltura-html5- 2.2.1-1      all          Kaltura Open Source Video Platfor
ii  kaltura-html5- 3.3.0-1      all          Kaltura Open Source Video Platfor
ii  kaltura-html5l 2.76-1       all          Kaltura Open Source Video Platfor
ii  kaltura-kclip  1.1.2.1-1    all          Kaltura Video Presentations Manag
ii  kaltura-kcw    2.2.4-1+b6   all          Kalture Contribution Wizard
ii  kaltura-kdp    2.7.0-1+b1   all          Kaltura Dynamic Player
ii  kaltura-kdp3   3.9.9-1+b4   amd64        Kaltura Dynamic Player
ii  kaltura-kdp3wr 37-1+b3      all          KDP3 Wrapper
ii  kaltura-kdpwra 11-1+b2      all          KDP Wrapper
ii  kaltura-kmc    5.43.13-11+b all          Kaltura Management Console
ii  kaltura-kmcng  5.9.1        all          Kaltura Management Console
ii  kaltura-krecor 1.7-1+b1     all          Kaltura kRecord - used for record
ii  kaltura-kuploa 1.2.16-1+b2  all          Kaltura kupload widget
un  kaltura-libapa <none>       <none>       (no description available)
un  kaltura-php7-c <none>       <none>       (no description available)
un  kaltura-php7-c <none>       <none>       (no description available)
un  kaltura-php7-m <none>       <none>       (no description available)
un  kaltura-php7-m <none>       <none>       (no description available)
un  kaltura-php7-m <none>       <none>       (no description available)
ii  kaltura-postin 1.0.33-3+b11 all          Kaltura Open Source Video Platfor
ii  kaltura-widget 14.1.0-1     all          Kaltura Open Source Video Platfor

**Comment by jessp01** [comment]
Hi @thatcherk1,

Please see https://forum.kaltura.org/t/package-issues-with-ubuntu-16-04/9929/2.

Cheers,
