### ISSUE TITLE
Why kmc_analytics_version keeping v0.3, while "kaltura/analytics-front-end" is upgrade to 1.4.1 ?

### ISSUE THREAD

**Issue by tyyly** [kaltura/platform-install-packages#657]
Hi,

I am installing Kaltura CE as personal interest. I am not sure if I am asking question right way.
Why kmc_analytics_version keeping v0.3, while "kaltura/analytics-front-end" is already upgraded to 1.4.1 ?

Regards,
Yuri

**Comment by jessp01** [comment]
Hi @tyyly,

Please see my response here:
https://forum.kaltura.org/t/how-can-i-upgrade-analytics-front-end-module-to-v1-5-1/10116

THanks
