### ISSUE TITLE
how to install kultura server or package in ubuntu 16.04 deb

### ISSUE THREAD

**Issue by designerprasan007** [kaltura/platform-install-packages#663]
- [ ] I've read the [guidelines for Contributing to Kaltura Projects](https://github.com/kaltura/platform-install-packages/blob/master/CONTRIBUTING.md)
- [ ] I've read the [installation guides](https://github.com/kaltura/platform-install-packages#documentation-and-guides) and [troubleshooting FAQ](https://github.com/kaltura/platform-install-packages/blob/master/doc/kaltura-packages-faq.md)
- [ ] This is not a support request or question that should be posted on the [Kaltura forum](https://forum.kaltura.org) 

## Bug report

**Please provide steps to reproduce, including errors from /opt/kaltura/log/kaltura_api_v3.log, /opt/kaltura/log/kaltura_apache_errors*log and /opt/kaltura/log/kaltura_prod.log:**

**Linux distribution name and version:**

**Are you using the RPM or deb packages?**
- [ ] RPM
- [ ] deb

**When using RPM, paste the output for:**
```
# rpm -qa "kaltura-*"
```

**For deb based systems:**
```
# dpkg -l "kaltura-*"
```

**Is this an all in one instance [single server] or a cluster?**
- [ ] All in one
- [ ] Cluster

**If applicable, please provide the MySQL version**

**If you're having an issue with a specific media asset, please provide a link from which it can be downloaded/played:**

hi. i'm trying to installl kultura-service in my ubuntu 16.04 system, so whenever i run command of apt install kultura-service(as given in [https://www.youtube.com/watch?v=aGH3ucn42lY](url) ) getting error of an E: Unable to locate package Kaltura-server, and when i run apt install kaltura-nginx (as given in [https://github.com/kaltura/nginx-vod-module](url)  getting error of  E: Unable to locate package kultura-nginx ) . please guide me to correct way to install the kultura. thank you

**Comment by Alexdrr** [comment]
better choose [centos 7](https://github.com/kaltura/platform-install-packages/blob/Orion-15.17.0/doc/install-kaltura-redhat-based.md), there are no installation problems.
for ubuntu 16.04 is not a valid repository key.

**Comment by jessp01** [comment]
Hello,

Deployment instructions for Ubuntu 16.04 (Xenial) are available here:
https://github.com/kaltura/platform-install-packages/blob/Orion-15.18.0/doc/install-kaltura-xenial.md
and it is a fully supported distribution. If you encounter issues, post at forum.kaltura.org
