### ISSUE TITLE
Error installation kaltura-server in Cent OS 7

### ISSUE THREAD

**Issue by maity** [kaltura/platform-install-packages#667]
- [ Y] I've read the [guidelines for Contributing to Kaltura Projects](https://github.com/kaltura/platform-install-packages/blob/master/CONTRIBUTING.md)
- [ Y] I've read the [installation guides](https://github.com/kaltura/platform-install-packages#documentation-and-guides) and [troubleshooting FAQ](https://github.com/kaltura/platform-install-packages/blob/master/doc/kaltura-packages-faq.md)
- [ Y] This is not a support request or question that should be posted on the [Kaltura forum](https://forum.kaltura.org) 

## Bug report

**Please provide steps to reproduce, including errors from /opt/kaltura/log/kaltura_api_v3.log, /opt/kaltura/log/kaltura_apache_errors*log and /opt/kaltura/log/kaltura_prod.log:**

**Linux distribution name and version:**

**Are you using the RPM or deb packages?**
- [ Y] RPM

**Is this an all in one instance [single server] or a cluster?**
- [ Y] All in one

Was trying kaltura-server in a CentOS-7 VM in Azure following this guide - "install-kaltura-redhat-based.md"

While "yum install kaltura-server" --- it gave a error and finnaly did not install (could not even find /opt/kaltura)

---> Package libXxf86misc.x86_64 0:1.0.3-7.1.el7 will be installed
--> Finished Dependency Resolution
Error: Package: kaltura-libmediainfo-0.7.61-8.x86_64 (Kaltura)
           Requires: libzen = 0.4.37
           Available: libzen-0.4.36-1.el7.x86_64 (Kaltura)
               libzen = 0.4.36-1.el7
           Available: libzen-0.4.37-1.el7.x86_64 (Kaltura)
               libzen = 0.4.37-1.el7
           Installing: libzen-0.4.38-1.el7.x86_64 (epel)
               libzen = 0.4.38-1.el7
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

Please suggest !!!

**Comment by jessp01** [comment]
Hello @maity ,

EPEL released a new version of the `libzen` package (0.4.38-1). We will address this in the next release.
For now, in order to install the current version, you could simply install http://installrepo.origin.kaltura.org/releases/15.20.0/7/RPMS/x86_64/libzen-0.4.37-1.el7.x86_64.rpm manually and then proceed with the regular deployment flow.

Thank you for reporting.

**Comment by maity** [comment]
Solved the problem ... thank you !!!
