### ISSUE TITLE
2 different fresh install = same issues

### ISSUE THREAD

**Issue by pacomedina** [kaltura/platform-install-packages#669]
Hello,

After a fresh install, using Docker and another on Centos 7, I still have the same error.

When I navigate to “Administration”, I have this message : 
Current status: 1 KMC user in use, -2 additional available.

And after login, the KMC overview will show a “Page not found” under the admin menu.

Too different servers, one ubuntu using Docker, another using Centos 7. No errors during install.

Regards,

**Comment by jessp01** [comment]
Hello,

I just answered your question here: https://forum.kaltura.org/t/2-different-fresh-install-same-issues/10518/3
If you have additional questions, let's continue the discussion there.
