### ISSUE TITLE
Error: Couldn't connect to Sphinx with mysql -h while using Docker installation

### ISSUE THREAD

**Issue by akash-accedo** [kaltura/platform-install-packages#673]
- [x] I've read the [guidelines for Contributing to Kaltura Projects](https://github.com/kaltura/platform-install-packages/blob/master/CONTRIBUTING.md)
- [x] I've read the [installation guides](https://github.com/kaltura/platform-install-packages#documentation-and-guides) and [troubleshooting FAQ](https://github.com/kaltura/platform-install-packages/blob/master/doc/kaltura-packages-faq.md)
- [ ] This is not a support request or question that should be posted on the [Kaltura forum](https://forum.kaltura.org) 

## Bug report
I am getting the following error when executing `install.sh` file to set up Kaltura on Amazon Linux 2.

`ERROR: Couldn't connect to Sphinx with mysql -hec2-13-251-124-42.ap-southeast-1.compute.amazonaws.com -P9312.`

**Machine** - Amazon Linux 2
**Installation process** - Single All in One docker installation: https://github.com/kaltura/platform-install-packages/blob/Propus-16.5.0/doc/install-docker.md
**Method** - Unattended

**Comment by jessp01** [comment]
Hello,

Is the `kaltura-sphinx` daemon running?
What's the output for:
```
# /etc/init.d/kaltura-sphinx status`
# netstat -plntu|grep 9312
```
?

**Comment by akash-accedo** [comment]
Hey @jessp01 ,

The problem has been solved, I misconfigured sphinx host URL. 

Thank you for support.
