### ISSUE TITLE
Ubuntu 20.04 fresh server kaltura-db fails with subprocess error

### ISSUE THREAD

**Issue by horvan** [kaltura/platform-install-packages#676]
- [x] I've read the [guidelines for Contributing to Kaltura Projects](https://github.com/kaltura/platform-install-packages/blob/master/CONTRIBUTING.md)
- [x] I've read the [installation guides](https://github.com/kaltura/platform-install-packages#documentation-and-guides) and [troubleshooting FAQ](https://github.com/kaltura/platform-install-packages/blob/master/doc/kaltura-packages-faq.md)
- [x] This is not a support request or question that should be posted on the [Kaltura forum](https://forum.kaltura.org) 

See: https://drive.google.com/file/d/15cvajJsgkpp3cDKM3i28b8n7fdEI1VUj/view?usp=sharing for a video of the install process. 

## Bug report

** Installing caltura fails, bercause kaltura-db deb fails to correct percona users and databaseses
** Ubuntu **
root@vmd22910:~# neofetch
            .-/+oossssoo+/-.               root@x
        `:+ssssssssssssssssss+:`           ------------------------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 20.04.1 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: KVM/QEMU (Standard PC (i440FX + PIIX, 1996) pc-i440fx-2.11) 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.4.0-42-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 36 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 1058 (dpkg) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.0.17 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Terminal: /dev/pts/0 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   CPU: Intel Xeon E5-2630 v4 (4) @ 2.199GHz 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   GPU: 00:02.0 Vendor 1234 Device 1111 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Memory: 256MiB / 11981MiB 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/                            
  +sssssssssdmydMMMMMMMMddddyssssssss+                             
   /ssssssssssshdmNNNNmyNMMMMhssssss/
    .ossssssssssssssssssdMMMNysssso.
      -+sssssssssssssssssyyyssss+-
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.

root@vmd22910:~# 

**Are you using the RPM or deb packages?**
- [ ] RPM
- [x ] deb

** When using RPM, paste the output for:**
```
# rpm -qa "kaltura-*"
```

**For deb based systems:**
```
# dpkg -l "kaltura-*"

bassh``
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                        Version             Architecture Description
+++-===========================-===================-============-=========================================================
ii  kaltura-base                16.5.0-2+b1         all          Kaltura Open Source Video Platform
ii  kaltura-clipapp             1.3-1               all          Kaltura Video Presentations Manager
iF  kaltura-db                  15.10.0-1+b1        all          Kaltura Open Source Video Platform - batch server
ii  kaltura-ffmpeg              4.0.2-3+b1          amd64        
ii  kaltura-ffmpeg-aux          3.4.6-1+b1          amd64        
ii  kaltura-flexwrapper         1.2-1+b1            all          Kaltura Video Presentations Manager
ii  kaltura-front               16.5.0-1            all          Kaltura Open Source Video Platform - frontend server
ii  kaltura-html5-analytics     0.3                 all          Kaltura Open Source Video Platform - frontend server
ii  kaltura-html5-studio        2.2.1-1+b1          all          Kaltura Open Source Video Platform - frontend server
ii  kaltura-html5-studio3       3.5.0-1+b1          all          Kaltura Open Source Video Platform - frontend server
ii  kaltura-html5lib            2.83-1              all          Kaltura Open Source Video Platform - HTML5 player
ii  kaltura-html5lib3           0.54.0-1            all          Kaltura Open Source Video Platform - HTML5 player
ii  kaltura-kclip               1.1.2.1-1           all          Kaltura Video Presentations Manager
ii  kaltura-kcw                 2.2.4-1+b6          all          Kalture Contribution Wizard
ii  kaltura-kdp                 2.7.0-1+b1          all          Kaltura Dynamic Player
ii  kaltura-kdp3                3.9.9-1+b4          amd64        Kaltura Dynamic Player
ii  kaltura-kdp3wrapper         37-1+b3             all          KDP3 Wrapper
ii  kaltura-kdpwrapper          11-1+b2             all          KDP Wrapper
ii  kaltura-kmc                 5.43.13-7           all          Kaltura Management Console
ii  kaltura-kmcng               5.19-3+really5.17-1 all          Kaltura Management Console
ii  kaltura-krecord             1.7-1+b1            all          Kaltura kRecord - used for recording from web cam
ii  kaltura-kupload             1.2.16-1+b2         all          Kaltura kupload widget
un  kaltura-libapache2-mod-php7 <none>              <none>       (no description available)
un  kaltura-php7-apcu           <none>              <none>       (no description available)
un  kaltura-php7-cli            <none>              <none>       (no description available)
un  kaltura-php7-curl           <none>              <none>       (no description available)
un  kaltura-php7-gd             <none>              <none>       (no description available)
un  kaltura-php7-gmp            <none>              <none>       (no description available)
un  kaltura-php7-memcache       <none>              <none>       (no description available)
un  kaltura-php7-mysql          <none>              <none>       (no description available)
un  kaltura-php7-ssh2           <none>              <none>       (no description available)
un  kaltura-php7-xsl            <none>              <none>       (no description available)
ii  kaltura-playkit-bundler     1.2.0-1+b2          all          Kaltura Open Source Video Platform - frontend server
ii  kaltura-postinst            1.0.33-3+b14        all          Kaltura Open Source Video Platform
ii  kaltura-sphinx              2.2.1-4+b5          amd64        Sphinx full-text search server - for Kaltura
ii  kaltura-widgets             14.1.0-1+b1         all          Kaltura Open Source Video Platform - widgets meta package"
```
``
**Is this an all in one instance [single server] or a cluster?**
- [ x] All in one
- [ ] Cluster

**If applicable, please provide the MySQL version**

percona 5.5  install script from repo is used

**If you're having an issue with a specific media asset, please provide a link from which it can be downloaded/played:**

**Comment by jessp01** [comment]
Hello @horvan ,

Did you run `mysql_secure_install` prior to installing the `kaltura-db` package?
If not, please do. If you have, what's the output for:
```
mysql> select user,host,password from mysql.user;
```

(You should mask the actual password hashes when posting).

Please also attach the output from the logs.

Thanks,

**Comment by horvan** [comment]
I don't know if the script does it. Guess it doesn't. Maybe thats because the error occours. Did not do it manually, because I would not to interrupt the script. See the video above. You'll notice I used the all in one install script directly from the documentation page. When you do that you can't run mysql secure manually, But the script fails because of the subprocess error. So the install script for ubuntu 20.04 is unusable currenly. That's what tis issue is about.

**Comment by jessp01** [comment]
Hello @horvan ,

For 16.04, we referred people to the Percona repo for the deb package and the need to run `mysql_secure_installation` was documented here:
https://github.com/kaltura/platform-install-packages/blob/Propus-16.6.0/doc/install-percona-deb.md

Since Percona does not provide packages for 20.04, we now include one in our own repo. I added the invocation of `mysql_secure_installation` in the 20.04 install script.
For now, please run it manually and then reconfigure the `kaltura-db` package.

Thanks,

**Comment by jessp01** [comment]
Hello @horvan ,

Any updates?

Thanks,
