### ISSUE TITLE
Failed to fetch files on Ubuntu 16 install

### ISSUE THREAD

**Issue by EnergyComms** [kaltura/platform-install-packages#677]
- [x ] I've read the [guidelines for Contributing to Kaltura Projects](https://github.com/kaltura/platform-install-packages/blob/master/CONTRIBUTING.md)
- [x ] I've read the [installation guides](https://github.com/kaltura/platform-install-packages#documentation-and-guides) and [troubleshooting FAQ](https://github.com/kaltura/platform-install-packages/blob/master/doc/kaltura-packages-faq.md)
- [ x] This is not a support request or question that should be posted on the [Kaltura forum](https://forum.kaltura.org) 

## Bug report

**Please provide steps to reproduce, including errors from /opt/kaltura/log/kaltura_api_v3.log, /opt/kaltura/log/kaltura_apache_errors*log and /opt/kaltura/log/kaltura_prod.log:**

running this after following all steps from the Ubuntu 16 installation instructions:
./install_kaltura_all_in_1.sh

The following NEW packages will be installed:
  kaltura-clipapp kaltura-flexwrapper kaltura-html5-analytics kaltura-html5-studio kaltura-html5-studio3 kaltura-html5lib kaltura-kclip kaltura-kcw kaltura-kdp kaltura-kdp3 kaltura-kdp3wrapper kaltura-kdpwrapper kaltura-kmc
  kaltura-kmcng kaltura-krecord kaltura-kupload kaltura-widgets
0 upgraded, 17 newly installed, 0 to remove and 4 not upgraded.
Need to get 7,436 kB/408 MB of archives.
After this operation, 696 MB of additional disk space will be used.
Err:1 http://installrepo.kaltura.org/repo/apt/xenial propus/main amd64 kaltura-clipapp all 1.3-1+b2
  404  Not Found [IP: 52.84.137.122 80]
Err:2 http://installrepo.kaltura.org/repo/apt/xenial propus/main amd64 kaltura-flexwrapper all 1.2-1+b1
  404  Not Found [IP: 52.84.137.122 80]
Err:3 http://installrepo.kaltura.org/repo/apt/xenial propus/main amd64 kaltura-html5-analytics all 0.3
  404  Not Found [IP: 52.84.137.122 80]
Err:4 http://installrepo.kaltura.org/repo/apt/xenial propus/main amd64 kaltura-html5-studio all 2.2.1-1
  404  Not Found [IP: 52.84.137.122 80]
Err:5 http://installrepo.kaltura.org/repo/apt/xenial propus/main amd64 kaltura-html5-studio3 all 3.5.0-1
  404  Not Found [IP: 52.84.137.122 80]
Err:6 http://installrepo.kaltura.org/repo/apt/xenial propus/main amd64 kaltura-kclip all 1.1.2.1-1
  404  Not Found [IP: 52.84.137.122 80]
Err:7 http://installrepo.kaltura.org/repo/apt/xenial propus/main amd64 kaltura-kdp all 2.7.0-1+b1
  404  Not Found [IP: 52.84.137.122 80]
Err:8 http://installrepo.kaltura.org/repo/apt/xenial propus/main amd64 kaltura-kdp3wrapper all 37-1+b3
  404  Not Found [IP: 52.84.137.122 80]
Err:9 http://installrepo.kaltura.org/repo/apt/xenial propus/main amd64 kaltura-kdpwrapper all 11-1+b2
  404  Not Found [IP: 52.84.137.122 80]
Err:10 http://installrepo.kaltura.org/repo/apt/xenial propus/main amd64 kaltura-kmcng all 5.19-3+really5.17-1
  404  Not Found [IP: 52.84.137.122 80]
Err:11 http://installrepo.kaltura.org/repo/apt/xenial propus/main amd64 kaltura-kupload all 1.2.16-1+b2
  404  Not Found [IP: 52.84.137.122 80]
Err:12 http://installrepo.kaltura.org/repo/apt/xenial propus/main amd64 kaltura-widgets all 14.1.0-1
  404  Not Found [IP: 52.84.137.122 80]
E: Failed to fetch http://installrepo.kaltura.org/repo/apt/xenial/pool/main/k/kaltura-clipapp/kaltura-clipapp_1.3-1+b2_all.deb  404  Not Found [IP: 52.84.137.122 80]

E: Failed to fetch http://installrepo.kaltura.org/repo/apt/xenial/pool/main/k/kaltura-flexwrapper/kaltura-flexwrapper_1.2-1+b1_all.deb  404  Not Found [IP: 52.84.137.122 80]

E: Failed to fetch http://installrepo.kaltura.org/repo/apt/xenial/pool/main/k/kaltura-html5-analytics/kaltura-html5-analytics_0.3_all.deb  404  Not Found [IP: 52.84.137.122 80]

E: Failed to fetch http://installrepo.kaltura.org/repo/apt/xenial/pool/main/k/kaltura-html5-studio/kaltura-html5-studio_2.2.1-1_all.deb  404  Not Found [IP: 52.84.137.122 80]

E: Failed to fetch http://installrepo.kaltura.org/repo/apt/xenial/pool/main/k/kaltura-html5-studio3/kaltura-html5-studio3_3.5.0-1_all.deb  404  Not Found [IP: 52.84.137.122 80]

E: Failed to fetch http://installrepo.kaltura.org/repo/apt/xenial/pool/main/k/kaltura-kclip/kaltura-kclip_1.1.2.1-1_all.deb  404  Not Found [IP: 52.84.137.122 80]

E: Failed to fetch http://installrepo.kaltura.org/repo/apt/xenial/pool/main/k/kaltura-kdp/kaltura-kdp_2.7.0-1+b1_all.deb  404  Not Found [IP: 52.84.137.122 80]

E: Failed to fetch http://installrepo.kaltura.org/repo/apt/xenial/pool/main/k/kaltura-kdp3wrapper/kaltura-kdp3wrapper_37-1+b3_all.deb  404  Not Found [IP: 52.84.137.122 80]

E: Failed to fetch http://installrepo.kaltura.org/repo/apt/xenial/pool/main/k/kaltura-kdpwrapper/kaltura-kdpwrapper_11-1+b2_all.deb  404  Not Found [IP: 52.84.137.122 80]

E: Failed to fetch http://installrepo.kaltura.org/repo/apt/xenial/pool/main/k/kaltura-kmcng/kaltura-kmcng_5.19-3+really5.17-1_all.deb  404  Not Found [IP: 52.84.137.122 80]

E: Failed to fetch http://installrepo.kaltura.org/repo/apt/xenial/pool/main/k/kaltura-kupload/kaltura-kupload_1.2.16-1+b2_all.deb  404  Not Found [IP: 52.84.137.122 80]

E: Failed to fetch http://installrepo.kaltura.org/repo/apt/xenial/pool/main/k/kaltura-widgets/kaltura-widgets_14.1.0-1_all.deb  404  Not Found [IP: 52.84.137.122 80]

**Linux distribution name and version:**
Ubuntu 16.04.6 (LTS) x64
**Are you using the RPM or deb packages?**
- [ ] RPM
- [ x] deb

**When using RPM, paste the output for:**
```
# rpm -qa "kaltura-*"
```

**For deb based systems:**
```
# dpkg -l "kaltura-*"
```
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                                  Version                         Architecture                    Description
+++-=====================================================-===============================-===============================-===============================================================================================================
ii  kaltura-base                                          16.5.0-2                        all                             Kaltura Open Source Video Platform
un  kaltura-php7-cli                                      <none>                          <none>                          (no description available)
un  kaltura-php7-curl                                     <none>                          <none>                          (no description available)
un  kaltura-php7-memcache                                 <none>                          <none>                          (no description available)
un  kaltura-php7-mysql                                    <none>                          <none>                          (no description available)
ii  kaltura-postinst                                      1.0.33-3+b13                    all                             Kaltura Open Source Video Platform
**Is this an all in one instance [single server] or a cluster?**
- [ x] All in one
- [ ] Cluster

**If applicable, please provide the MySQL version**

**If you're having an issue with a specific media asset, please provide a link from which it can be downloaded/played:**

**Comment by jessp01** [comment]
Hello @EnergyComms,

There was an issue with the CDN. It will update shortly. For now, please change all instances of `installrepo.kaltura.org` to `installrepo.origin.kaltura.org` and retry.

Thanks for reporting,

**Comment by EnergyComms** [comment]
Working now, thanks

**Comment by jessp01** [comment]
Appreciate the confirmation.

Cheers,
