### ISSUE TITLE
Documentation Request - For all-in-one can you note if all of the installation Q&A hostnames are allowed to be the same?

### ISSUE THREAD

**Issue by HeneryH** [kaltura/platform-install-packages#694]
## Documentation Request 
During an All-in-One installation the installer asks for various hostnames including for example the CDN Hostname, VOD hostname and the Service URL.  Can you note in the All-in-One instructions if it is OK to have these all the same?

**Comment by jessp01** [comment]
Hello @HeneryH ,

Yes, for an all in one instance, you may use the same hostname whenever prompted, providing that:
- The hostname is resolvable both from within and outside the instance (that is, the machines from which you intend to make requests; i.e: to load the different web interfaces, interact with the API, etc)
- All needed daemons/services are in fact running on this one host

Should you have additional questions, please post them on forum.kaltura.org.

Cheers,
